//*******************************************************************************
//*	cursive.jhf		Cursive
//*	formated for use with Arduino Processing 
//*	by Mark Sproul
//*******************************************************************************
//*	Jan 22,	2009	<MLS>	Formated Hershey Cursive for Arduino
//*******************************************************************************
//#include	"HersheyCursive.h"


prog_char	gCursive_00[]	PROGMEM	=	"Cursive";
prog_char	gCursive_20[]	PROGMEM	=	" 1JZ";
prog_char	gCursive_21[]	PROGMEM	=	" 9MWRFRT RRYQZR[SZRY";
prog_char	gCursive_22[]	PROGMEM	=	" 6JZNFNM RVFVM";
prog_char	gCursive_23[]	PROGMEM	=	"12H]SBLb RYBRb RLOZO RKUYU";
prog_char	gCursive_24[]	PROGMEM	=	"27H\\PBP_ RTBT_ RYIWGTFPFMGKIKKLMMNOOUQWRXSYUYXWZT[P[MZKX";
prog_char	gCursive_25[]	PROGMEM	=	"32F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT";
prog_char	gCursive_26[]	PROGMEM	=	"35E_\\O\\N[MZMYNXPVUTXRZP[L[JZIYHWHUISJRQNRMSKSIRGPFNGMIMKNNPQUXWZY[[[\\Z\\Y";
prog_char	gCursive_27[]	PROGMEM	=	" 3PTRMRQ";
prog_char	gCursive_28[]	PROGMEM	=	"11KYVBTDRGPKOPOTPYR]T`Vb";
prog_char	gCursive_29[]	PROGMEM	=	"11KYNBPDRGTKUPUTTYR]P`Nb";
prog_char	gCursive_2A[]	PROGMEM	=	" 9JZRLRX RMOWU RWOMU";
prog_char	gCursive_2B[]	PROGMEM	=	" 6E_RIR[ RIR[R";
prog_char	gCursive_2C[]	PROGMEM	=	" 8NVSWRXQWRVSWSYQ[";
prog_char	gCursive_2D[]	PROGMEM	=	" 3E_IR[R";
prog_char	gCursive_2E[]	PROGMEM	=	" 6NVRVQWRXSWRV";
prog_char	gCursive_2F[]	PROGMEM	=	" 3G][BIb";

prog_char	gCursive_30[]	PROGMEM	=	"18H\\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF";
prog_char	gCursive_31[]	PROGMEM	=	" 5H\\NJPISFS[";
prog_char	gCursive_32[]	PROGMEM	=	"15H\\LKLJMHNGPFTFVGWHXJXLWNUQK[Y[";
prog_char	gCursive_33[]	PROGMEM	=	"16H\\MFXFRNUNWOXPYSYUXXVZS[P[MZLYKW";
prog_char	gCursive_34[]	PROGMEM	=	" 7H\\UFKTZT RUFU[";
prog_char	gCursive_35[]	PROGMEM	=	"18H\\WFMFLOMNPMSMVNXPYSYUXXVZS[P[MZLYKW";
prog_char	gCursive_36[]	PROGMEM	=	"24H\\XIWGTFRFOGMJLOLTMXOZR[S[VZXXYUYTXQVOSNRNOOMQLT";
prog_char	gCursive_37[]	PROGMEM	=	" 6H\\YFO[ RKFYF";
prog_char	gCursive_38[]	PROGMEM	=	"30H\\PFMGLILKMMONSOVPXRYTYWXYWZT[P[MZLYKWKTLRNPQOUNWMXKXIWGTFPF";
prog_char	gCursive_39[]	PROGMEM	=	"24H\\XMWPURRSQSNRLPKMKLLINGQFRFUGWIXMXRWWUZR[P[MZLX";
prog_char	gCursive_3A[]	PROGMEM	=	"12NVROQPRQSPRO RRVQWRXSWRV";
prog_char	gCursive_3B[]	PROGMEM	=	"14NVROQPRQSPRO RSWRXQWRVSWSYQ[";
prog_char	gCursive_3C[]	PROGMEM	=	" 4F^ZIJRZ[";
prog_char	gCursive_3D[]	PROGMEM	=	" 6E_IO[O RIU[U";
prog_char	gCursive_3E[]	PROGMEM	=	" 4F^JIZRJ[";
prog_char	gCursive_3F[]	PROGMEM	=	"21I[LKLJMHNGPFTFVGWHXJXLWNVORQRT RRYQZR[SZRY";

prog_char	gCursive_40[]	PROGMEM	=	"56E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
prog_char	gCursive_41[]	PROGMEM	=	"20G[G[IZLWOSSLVFV[UXSUQSNQLQKRKTLVNXQZT[Y[";
prog_char	gCursive_42[]	PROGMEM	=	"41F]SHTITLSPRSQUOXMZK[J[IZIWJRKOLMNJPHRGUFXFZG[I[KZMYNWOTP RSPTPWQXRYTYWXYWZU[R[PZOX";
prog_char	gCursive_43[]	PROGMEM	=	"24H\\TLTMUNWNYMZKZIYGWFTFQGOIMLLNKRKVLYMZO[Q[TZVXWV";
prog_char	gCursive_44[]	PROGMEM	=	"35G^TFRGQIPMOSNVMXKZI[G[FZFXGWIWKXMZP[S[VZXXZT[O[KZHYGWFTFRHRJSMUPWRZT\\U";
prog_char	gCursive_45[]	PROGMEM	=	"28H\\VJVKWLYLZKZIYGVFRFOGNINLONPOSPPPMQLRKTKWLYMZP[S[VZXXYV";
prog_char	gCursive_46[]	PROGMEM	=	"28H\\RLPLNKMINGQFTFXG[G]F RXGVNTTRXPZN[L[JZIXIVJULUNV RQPZP";
prog_char	gCursive_47[]	PROGMEM	=	"29G^G[IZMVPQQNRJRGQFPFOGNINLONQOUOXNYMZKZQYVXXVZS[O[LZJXIVIT";
prog_char	gCursive_48[]	PROGMEM	=	"38F^MMKLJJJIKGMFNFPGQIQKPONULYJ[H[GZGX RMRVOXN[L]J^H^G]F\\FZHXLVRUWUZV[W[YZZY\\V";
prog_char	gCursive_49[]	PROGMEM	=	"25IZWVUTSQROQLQIRGSFUFVGWIWLVQTVSXQZO[M[KZJXJVKUMUOV";
prog_char	gCursive_4A[]	PROGMEM	=	"25JYT^R[PVOPOJPGRFTFUGVJVMURR[PaOdNfLgKfKdLaN^P\\SZWX";
prog_char	gCursive_4B[]	PROGMEM	=	"39F^MMKLJJJIKGMFNFPGQIQKPONULYJ[H[GZGX R^I^G]F\\FZGXIVLTNROPO RROSQSXTZU[V[XZYY[V";
prog_char	gCursive_4C[]	PROGMEM	=	"29I\\MRORSQVOXMYKYHXFVFUGTISNRSQVPXNZL[J[IZIXJWLWNXQZT[V[YZ[X";
prog_char	gCursive_4D[]	PROGMEM	=	"45@aEMCLBJBICGEFFFHGIIIKHPGTE[ RGTJLLHMGOFPFRGSISKRPQTO[ RQTTLVHWGYFZF\\G]I]K\\PZWZZ[[\\[^Z_YaV";
prog_char	gCursive_4E[]	PROGMEM	=	"32E]JMHLGJGIHGJFKFMGNINKMPLTJ[ RLTOLQHRGTFVFXGYIYKXPVWVZW[X[ZZ[Y]V";
prog_char	gCursive_4F[]	PROGMEM	=	"29H]TFQGOIMLLNKRKVLYMZO[Q[TZVXXUYSZOZKYHXGVFTFRHRKSNUQWSZU\\V";

prog_char	gCursive_50[]	PROGMEM	=	"31F_SHTITLSPRSQUOXMZK[J[IZIWJRKOLMNJPHRGUFZF\\G]H^J^M]O\\PZQWQUPTO";
prog_char	gCursive_51[]	PROGMEM	=	"32H^ULTNSOQPOPNNNLOIQGTFWFYGZIZMYPWSSWPYNZK[I[HZHXIWKWMXPZS[V[YZ[X";
prog_char	gCursive_52[]	PROGMEM	=	"38F_SHTITLSPRSQUOXMZK[J[IZIWJRKOLMNJPHRGUFYF[G\\H]J]M\\O[PYQVQSPTQUSUXVZX[ZZ[Y]V";
prog_char	gCursive_53[]	PROGMEM	=	"28H\\H[JZLXOTQQSMTJTGSFRFQGPIPKQMSOVQXSYUYWXYWZT[P[MZKXJVJT";
prog_char	gCursive_54[]	PROGMEM	=	"25H[RLPLNKMINGQFTFXG[G]F RXGVNTTRXPZN[L[JZIXIVJULUNV";
prog_char	gCursive_55[]	PROGMEM	=	"33E]JMHLGJGIHGJFKFMGNINKMOLRKVKXLZN[P[RZSYUUXMZF RXMWQVWVZW[X[ZZ[Y]V";
prog_char	gCursive_56[]	PROGMEM	=	"32F]KMILHJHIIGKFLFNGOIOKNOMRLVLYM[O[QZTWVTXPYMZIZGYFXFWGVIVKWNYP[Q";
prog_char	gCursive_57[]	PROGMEM	=	"25C_HMFLEJEIFGHFIFKGLILLK[ RUFK[ RUFS[ RaF_G\\JYNVTS[";
prog_char	gCursive_58[]	PROGMEM	=	"36F^NLLLKKKILGNFPFRGSISLQUQXRZT[V[XZYXYVXUVU R]I]G\\FZFXGVITLPUNXLZJ[H[GZGX";
prog_char	gCursive_59[]	PROGMEM	=	"38F]KMILHJHIIGKFLFNGOIOKNOMRLVLXMZN[P[RZTXVUWSYM R[FYMVWT]RbPfNgMfMdNaP^S[VY[V";
prog_char	gCursive_5A[]	PROGMEM	=	"40H]ULTNSOQPOPNNNLOIQGTFWFYGZIZMYPWTTWPZN[K[JZJXKWNWPXQYR[R^QaPcNfLgKfKdLaN^Q[TYZV";
prog_char	gCursive_5B[]	PROGMEM	=	"12KYOBOb RPBPb ROBVB RObVb";
prog_char	gCursive_5C[]	PROGMEM	=	" 3KYKFY^";
prog_char	gCursive_5D[]	PROGMEM	=	"12KYTBTb RUBUb RNBUB RNbUb";
prog_char	gCursive_5E[]	PROGMEM	=	" 6JZRDJR RRDZR";
prog_char	gCursive_5F[]	PROGMEM	=	" 3G[Gb[b";

prog_char	gCursive_60[]	PROGMEM	=	" 8NVSKQMQORPSORNQO";
prog_char	gCursive_61[]	PROGMEM	=	"22L\\UUTSRRPRNSMTLVLXMZO[Q[SZTXVRUWUZV[W[YZZY\\V";
prog_char	gCursive_62[]	PROGMEM	=	"23M[MVOSRNSLTITGSFQGPIOMNTNZO[P[RZTXUUURVVWWYW[V";
prog_char	gCursive_63[]	PROGMEM	=	"14MXTTTSSRQROSNTMVMXNZP[S[VYXV";
prog_char	gCursive_64[]	PROGMEM	=	"24L\\UUTSRRPRNSMTLVLXMZO[Q[SZTXZF RVRUWUZV[W[YZZY\\V";
prog_char	gCursive_65[]	PROGMEM	=	"17NXOYQXRWSUSSRRQROSNUNXOZQ[S[UZVYXV";
prog_char	gCursive_66[]	PROGMEM	=	"24OWOVSQUNVLWIWGVFTGSIQQNZKaJdJfKgMfNcOZP[R[TZUYWV";
prog_char	gCursive_67[]	PROGMEM	=	"28L[UUTSRRPRNSMTLVLXMZO[Q[SZTY RVRTYPdOfMgLfLdMaP^S\\U[XY[V";
prog_char	gCursive_68[]	PROGMEM	=	"29M\\MVOSRNSLTITGSFQGPIOMNSM[ RM[NXOVQSSRURVSVUUXUZV[W[YZZY\\V";
prog_char	gCursive_69[]	PROGMEM	=	"16PWSMSNTNTMSM RPVRRPXPZQ[R[TZUYWV";
prog_char	gCursive_6A[]	PROGMEM	=	"20PWSMSNTNTMSM RPVRRLdKfIgHfHdIaL^O\\Q[TYWV";
prog_char	gCursive_6B[]	PROGMEM	=	"33M[MVOSRNSLTITGSFQGPIOMNSM[ RM[NXOVQSSRURVSVUTVQV RQVSWTZU[V[XZYY[V";
prog_char	gCursive_6C[]	PROGMEM	=	"18OWOVQSTNULVIVGUFSGRIQMPTPZQ[R[TZUYWV";
prog_char	gCursive_6D[]	PROGMEM	=	"33E^EVGSIRJSJTIXH[ RIXJVLSNRPRQSQTPXO[ RPXQVSSURWRXSXUWXWZX[Y[[Z\\Y^V";
prog_char	gCursive_6E[]	PROGMEM	=	"23J\\JVLSNROSOTNXM[ RNXOVQSSRURVSVUUXUZV[W[YZZY\\V";
prog_char	gCursive_6F[]	PROGMEM	=	"23LZRRPRNSMTLVLXMZO[Q[SZTYUWUUTSRRQSQURWTXWXYWZV";

prog_char	gCursive_70[]	PROGMEM	=	"24KZKVMSNQMUGg RMUNSPRRRTSUUUWTYSZQ[ RMZO[R[UZWYZV";
prog_char	gCursive_71[]	PROGMEM	=	"27L[UUTSRRPRNSMTLVLXMZO[Q[SZ RVRUUSZPaOdOfPgRfScS\\U[XY[V";
prog_char	gCursive_72[]	PROGMEM	=	"15MZMVOSPQPSSSTTTVSYSZT[U[WZXYZV";
prog_char	gCursive_73[]	PROGMEM	=	"16NYNVPSQQQSSVTXTZR[ RNZP[T[VZWYYV";
prog_char	gCursive_74[]	PROGMEM	=	"16OXOVQSSO RVFPXPZQ[S[UZVYXV RPNWN";
prog_char	gCursive_75[]	PROGMEM	=	"19L[LVNRLXLZM[O[QZSXUU RVRTXTZU[V[XZYY[V";
prog_char	gCursive_76[]	PROGMEM	=	"17L[LVNRMWMZN[O[RZTXUUUR RURVVWWYW[V";
prog_char	gCursive_77[]	PROGMEM	=	"25I^LRJTIWIYJ[L[NZPX RRRPXPZQ[S[UZWXXUXR RXRYVZW\\W^V";
prog_char	gCursive_78[]	PROGMEM	=	"20JZJVLSNRPRQSQZR[U[XYZV RWSVRTRSSOZN[L[KZ";
prog_char	gCursive_79[]	PROGMEM	=	"23L[LVNRLXLZM[O[QZSXUU RVRPdOfMgLfLdMaP^S\\U[XY[V";
prog_char	gCursive_7A[]	PROGMEM	=	"23LZLVNSPRRRTTTVSXQZN[P\\Q^QaPdOfMgLfLdMaP^S\\WYZV";
prog_char	gCursive_7B[]	PROGMEM	=	"40KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
prog_char	gCursive_7C[]	PROGMEM	=	" 3NVRBRb";
prog_char	gCursive_7D[]	PROGMEM	=	"40KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
prog_char	gCursive_7E[]	PROGMEM	=	"24F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
prog_char	gCursive_7F[]	PROGMEM	=	"35JZJFJ[K[KFLFL[M[MFNFN[O[OFPFP[Q[QFRFR[S[SFTFT[U[UFVFV[W[WFXFX[Y[YFZFZ[";



PGM_P gHershyCursiveFontTable[]	PROGMEM =	   // change "string_table" name to suit
{

	gCursive_00,
	gCursive_20,
	gCursive_21,
	gCursive_22,
	gCursive_23,
	gCursive_24,
	gCursive_25,
	gCursive_26,
	gCursive_27,
	gCursive_28,
	gCursive_29,
	gCursive_2A,
	gCursive_2B,
	gCursive_2C,
	gCursive_2D,
	gCursive_2E,
	gCursive_2F,

	gCursive_30,
	gCursive_31,
	gCursive_32,
	gCursive_33,
	gCursive_34,
	gCursive_35,
	gCursive_36,
	gCursive_37,
	gCursive_38,
	gCursive_39,
	gCursive_3A,
	gCursive_3B,
	gCursive_3C,
	gCursive_3D,
	gCursive_3E,
	gCursive_3F,

	gCursive_40,
	gCursive_41,
	gCursive_42,
	gCursive_43,
	gCursive_44,
	gCursive_45,
	gCursive_46,
	gCursive_47,
	gCursive_48,
	gCursive_49,
	gCursive_4A,
	gCursive_4B,
	gCursive_4C,
	gCursive_4D,
	gCursive_4E,
	gCursive_4F,

	gCursive_50,
	gCursive_51,
	gCursive_52,
	gCursive_53,
	gCursive_54,
	gCursive_55,
	gCursive_56,
	gCursive_57,
	gCursive_58,
	gCursive_59,
	gCursive_5A,
	gCursive_5B,
	gCursive_5C,
	gCursive_5D,
	gCursive_5E,
	gCursive_5F,

	gCursive_60,
	gCursive_61,
	gCursive_62,
	gCursive_63,
	gCursive_64,
	gCursive_65,
	gCursive_66,
	gCursive_67,
	gCursive_68,
	gCursive_69,
	gCursive_6A,
	gCursive_6B,
	gCursive_6C,
	gCursive_6D,
	gCursive_6E,
	gCursive_6F,

	gCursive_70,
	gCursive_71,
	gCursive_72,
	gCursive_73,
	gCursive_74,
	gCursive_75,
	gCursive_76,
	gCursive_77,
	gCursive_78,
	gCursive_79,
	gCursive_7A,
	gCursive_7B,
	gCursive_7C,
	gCursive_7D,
	gCursive_7E,
	gCursive_7F

};
