//*******************************************************************************
//*	timesrb.jhf		Times Roman Bold
//*	formated for use with Arduino Processing 
//*	by Mark Sproul
//*******************************************************************************
//*	Jan 24,	2009	<MLS>	Formated Hershey Times Roman Bold for Arduino
//*******************************************************************************
//#include	"HersheyTimesRomanBold.h"

prog_char	gTimesRomanBold_00[]	PROGMEM	=	"Times Roman Bold";

prog_char	gTimesRomanBold_20[]	PROGMEM	=	" 1JZ";
prog_char	gTimesRomanBold_21[]	PROGMEM	=	"34MXRFQGQIRQ RRFRTST RRFSFST RSFTGTISQ RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY";
prog_char	gTimesRomanBold_22[]	PROGMEM	=	"22I[NFMGMM RNGMM RNFOGMM RWFVGVM RWGVM RWFXGVM";
prog_char	gTimesRomanBold_23[]	PROGMEM	=	"12H]SBLb RYBRb RLOZO RKUYU";
prog_char	gTimesRomanBold_24[]	PROGMEM	=	"56H\\PBP_ RTBT_ RXKXJWJWLYLYJXHWGTFPFMGKIKLLNOPURWSXUXXWZ RLLMNOOUQWRXT RMGLILKMMONUPXRYTYWXYWZT[P[MZLYKWKUMUMWLWLV";
prog_char	gTimesRomanBold_25[]	PROGMEM	=	"32F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT";
prog_char	gTimesRomanBold_26[]	PROGMEM	=	"74E_[O[NZNZP\\P\\N[MZMYNXPVUTXRZP[L[JZIXIUJSPORMSKSIRGPFNGMIMLNOPRTWWZY[[[\\Y\\X RKZJXJUKSLR RRMSI RSKRG RNGMK RNNPQTVWYYZ RN[LZKXKULSPO RMINMQQUVXYZZ[Z\\Y";
prog_char	gTimesRomanBold_27[]	PROGMEM	=	"11NWSFRGRM RSGRM RSFTGRM";
prog_char	gTimesRomanBold_28[]	PROGMEM	=	"27KYUBSDQGOKNPNTOYQ]S`Ub RQHPKOOOUPYQ\\ RSDRFQIPOPUQ[R^S`";
prog_char	gTimesRomanBold_29[]	PROGMEM	=	"27KYOBQDSGUKVPVTUYS]Q`Ob RSHTKUOUUTYS\\ RQDRFSITOTUS[R^Q`";
prog_char	gTimesRomanBold_2A[]	PROGMEM	=	"39JZRFQGSQRR RRFRR RRFSGQQRR RMINIVOWO RMIWO RMIMJWNWO RWIVINOMO RWIMO RWIWJMNMO";
prog_char	gTimesRomanBold_2B[]	PROGMEM	=	"16F_RIRZSZ RRISISZ RJQ[Q[R RJQJR[R";
prog_char	gTimesRomanBold_2C[]	PROGMEM	=	"24MXTZS[R[QZQYRXSXTYT\\S^Q_ RRYRZSZSYRY RS[T\\ RTZS^";
prog_char	gTimesRomanBold_2D[]	PROGMEM	=	" 3E_IR[R";
prog_char	gTimesRomanBold_2E[]	PROGMEM	=	"16MXRXQYQZR[S[TZTYSXRX RRYRZSZSYRY";
prog_char	gTimesRomanBold_2F[]	PROGMEM	=	" 8G^[BIbJb R[B\\BJb";

prog_char	gTimesRomanBold_30[]	PROGMEM	=	"50H\\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF RNHMJLNLSMWNY RVYWWXSXNWJVH RQFOGNIMNMSNXOZQ[ RS[UZVXWSWNVIUGSF";
prog_char	gTimesRomanBold_31[]	PROGMEM	=	"28H\\QHQ[ RRHRZ RSFS[ RSFPINJ RM[W[ RQZO[ RQYP[ RSYT[ RSZU[";
prog_char	gTimesRomanBold_32[]	PROGMEM	=	"62H\\LJLKMKMJLJ RLIMINJNKMLLLKKKJLHMGPFTFWGXHYJYLXNUPPRNSLUKXK[ RWHXJXLWN RTFVGWJWLVNTPPR RKYLXNXSYWYYX RNXSZWZXY RNXS[W[XZYXYV";
prog_char	gTimesRomanBold_33[]	PROGMEM	=	"76H\\LJLKMKMJLJ RLIMINJNKMLLLKKKJLHMGPFTFWGXIXLWNTO RVGWIWLVN RSFUGVIVLUNSO RQOTOVPXRYTYWXYWZT[P[MZLYKWKVLUMUNVNWMXLX RWRXTXWWY RSOUPVQWTWWVZT[ RLVLWMWMVLV";
prog_char	gTimesRomanBold_34[]	PROGMEM	=	"28H\\SIS[ RTHTZ RUFU[ RUFJUZU RP[X[ RSZQ[ RSYR[ RUYV[ RUZW[";
prog_char	gTimesRomanBold_35[]	PROGMEM	=	"55H\\MFKPMNPMSMVNXPYSYUXXVZS[P[MZLYKWKVLUMUNVNWMXLX RWPXRXVWX RSMUNVOWRWVVYUZS[ RLVLWMWMVLV RMFWF RMGUG RMHQHUGWF";
prog_char	gTimesRomanBold_36[]	PROGMEM	=	"69H\\VIVJWJWIVI RWHVHUIUJVKWKXJXIWGUFRFOGMILKKOKULXNZQ[S[VZXXYUYTXQVOSNQNOONPMR RNIMKLOLUMXNY RWXXVXSWQ RRFPGOHNJMNMUNXOZQ[ RS[UZVYWVWSVPUOSN";
prog_char	gTimesRomanBold_37[]	PROGMEM	=	"43H\\KFKL RYFYIXLTQSSRWR[ RSRRTQWQ[ RXLSQQTPWP[R[ RKJLHNFPFUIWIXHYF RMHNGPGRH RKJLINHPHUI";
prog_char	gTimesRomanBold_38[]	PROGMEM	=	"79H\\PFMGLILLMNPOTOWNXLXIWGTFPF RNGMIMLNN RVNWLWIVG RPFOGNINLONPO RTOUNVLVIUGTF RPOMPLQKSKWLYMZP[T[WZXYYWYSXQWPTO RMQLSLWMY RWYXWXSWQ RPONPMSMWNZP[ RT[VZWWWSVPTO";
prog_char	gTimesRomanBold_39[]	PROGMEM	=	"69H\\MWMXNXNWMW RWOVQURSSQSNRLPKMKLLINGQFSFVGXIYLYRXVWXUZR[O[MZLXLWMVNVOWOXNYMY RMPLNLKMI RVHWIXLXRWVVX RQSORNQMNMKNHOGQF RSFUGVIWLWSVWUYTZR[";
prog_char	gTimesRomanBold_3A[]	PROGMEM	=	"32MXRMQNQORPSPTOTNSMRM RRNROSOSNRN RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY";
prog_char	gTimesRomanBold_3B[]	PROGMEM	=	"40MXRMQNQORPSPTOTNSMRM RRNROSOSNRN RTZS[R[QZQYRXSXTYT\\S^Q_ RRYRZSZSYRY RS[T\\ RTZS^";
prog_char	gTimesRomanBold_3C[]	PROGMEM	=	" 4F^ZIJRZ[";
prog_char	gTimesRomanBold_3D[]	PROGMEM	=	"16F_JM[M[N RJMJN[N RJU[U[V RJUJV[V";
prog_char	gTimesRomanBold_3E[]	PROGMEM	=	" 4F^JIZRJ[";
prog_char	gTimesRomanBold_3F[]	PROGMEM	=	"52I\\MKMJNJNLLLLJMHNGPFTFWGXHYJYLXNWOSQ RWHXIXMWN RTFVGWIWMVOUP RRQRTSTSQRQ RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY";

prog_char	gTimesRomanBold_40[]	PROGMEM	=	"56E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
prog_char	gTimesRomanBold_41[]	PROGMEM	=	"36H\\RFKZ RQIW[ RRIX[ RRFY[ RMUVU RI[O[ RT[[[ RKZJ[ RKZM[ RWZU[ RWYV[ RXYZ[";
prog_char	gTimesRomanBold_42[]	PROGMEM	=	"78G]LFL[ RMGMZ RNFN[ RIFUFXGYHZJZLYNXOUP RXHYJYLXN RUFWGXIXMWOUP RNPUPXQYRZTZWYYXZU[I[ RXRYTYWXY RUPWQXSXXWZU[ RJFLG RKFLH ROFNH RPFNG RLZJ[ RLYK[ RNYO[ RNZP[";
prog_char	gTimesRomanBold_43[]	PROGMEM	=	"37G\\XIYFYLXIVGTFQFNGLIKKJNJSKVLXNZQ[T[VZXXYV RMILKKNKSLVMX RQFOGMJLNLSMWOZQ[";
prog_char	gTimesRomanBold_44[]	PROGMEM	=	"62G]LFL[ RMGMZ RNFN[ RIFSFVGXIYKZNZSYVXXVZS[I[ RWIXKYNYSXVWX RSFUGWJXNXSWWUZS[ RJFLG RKFLH ROFNH RPFNG RLZJ[ RLYK[ RNYO[ RNZP[";
prog_char	gTimesRomanBold_45[]	PROGMEM	=	"83G\\LFL[ RMGMZ RNFN[ RIFYFYL RNPTP RTLTT RI[Y[YU RJFLG RKFLH ROFNH RPFNG RTFYG RVFYH RWFYI RXFYL RTLSPTT RTNRPTR RTOPPTQ RLZJ[ RLYK[ RNYO[ RNZP[ RT[YZ RV[YY RW[YX RX[YU";
prog_char	gTimesRomanBold_46[]	PROGMEM	=	"70G[LFL[ RMGMZ RNFN[ RIFYFYL RNPTP RTLTT RI[Q[ RJFLG RKFLH ROFNH RPFNG RTFYG RVFYH RWFYI RXFYL RTLSPTT RTNRPTR RTOPPTQ RLZJ[ RLYK[ RNYO[ RNZP[";
prog_char	gTimesRomanBold_47[]	PROGMEM	=	"60G^XIYFYLXIVGTFQFNGLIKKJNJSKVLXNZQ[T[VZXZY[YS RMILKKNKSLVMX RQFOGMJLNLSMWOZQ[ RXTXY RWSWYVZ RTS\\S RUSWT RVSWU RZSYU R[SYT";
prog_char	gTimesRomanBold_48[]	PROGMEM	=	"81F^KFK[ RLGLZ RMFM[ RWFW[ RXGXZ RYFY[ RHFPF RTF\\F RMPWP RH[P[ RT[\\[ RIFKG RJFKH RNFMH ROFMG RUFWG RVFWH RZFYH R[FYG RKZI[ RKYJ[ RMYN[ RMZO[ RWZU[ RWYV[ RYYZ[ RYZ[[";
prog_char	gTimesRomanBold_49[]	PROGMEM	=	"39LXQFQ[ RRGRZ RSFS[ RNFVF RN[V[ ROFQG RPFQH RTFSH RUFSG RQZO[ RQYP[ RSYT[ RSZU[";
prog_char	gTimesRomanBold_4A[]	PROGMEM	=	"45JZSFSWRZQ[ RTGTWSZ RUFUWTZQ[O[MZLXLVMUNUOVOWNXMX RMVMWNWNVMV RPFXF RQFSG RRFSH RVFUH RWFUG";
prog_char	gTimesRomanBold_4B[]	PROGMEM	=	"69F\\KFK[ RLGLZ RMFM[ RXGMR RPPW[ RQPX[ RQNY[ RHFPF RUF[F RH[P[ RT[[[ RIFKG RJFKH RNFMH ROFMG RWFXG RZFXG RKZI[ RKYJ[ RMYN[ RMZO[ RWYU[ RWYZ[";
prog_char	gTimesRomanBold_4C[]	PROGMEM	=	"52I[NFN[ ROGOZ RPFP[ RKFSF RK[Z[ZU RLFNG RMFNH RQFPH RRFPG RNZL[ RNYM[ RPYQ[ RPZR[ RU[ZZ RW[ZY RX[ZX RY[ZU";
prog_char	gTimesRomanBold_4D[]	PROGMEM	=	"63E_JFJZ RJFQ[ RKFQX RLFRX RXFQ[ RXFX[ RYGYZ RZFZ[ RGFLF RXF]F RG[M[ RU[][ RHFJG R[FZH R\\FZG RJZH[ RJZL[ RXZV[ RXYW[ RZY[[ RZZ\\[";
prog_char	gTimesRomanBold_4E[]	PROGMEM	=	"39F^KFKZ RKFY[ RLFXX RMFYX RYGY[ RHFMF RVF\\F RH[N[ RIFKG RWFYG R[FYG RKZI[ RKZM[";
prog_char	gTimesRomanBold_4F[]	PROGMEM	=	"54G]QFNGLIKKJOJRKVLXNZQ[S[VZXXYVZRZOYKXIVGSFQF RMILKKNKSLVMX RWXXVYSYNXKWI RQFOGMJLNLSMWOZQ[ RS[UZWWXSXNWJUGSF";

prog_char	gTimesRomanBold_50[]	PROGMEM	=	"59G]LFL[ RMGMZ RNFN[ RIFUFXGYHZJZMYOXPUQNQ RXHYJYMXO RUFWGXIXNWPUQ RI[Q[ RJFLG RKFLH ROFNH RPFNG RLZJ[ RLYK[ RNYO[ RNZP[";
prog_char	gTimesRomanBold_51[]	PROGMEM	=	"77G]QFNGLIKKJOJRKVLXNZQ[S[VZXXYVZRZOYKXIVGSFQF RMILKKNKSLVMX RWXXVYSYNXKWI RQFOGMJLNLSMWOZQ[ RS[UZWWXSXNWJUGSF RNXOVQURUTVUXV^W`Y`Z^Z\\ RV\\W^X_Y_ RUXW]X^Y^Z]";
prog_char	gTimesRomanBold_52[]	PROGMEM	=	"80G]LFL[ RMGMZ RNFN[ RIFUFXGYHZJZLYNXOUPNP RXHYJYLXN RUFWGXIXMWOUP RRPTQUSWYX[Z[[Y[W RWWXYYZZZ RTQURXXYYZY[X RI[Q[ RJFLG RKFLH ROFNH RPFNG RLZJ[ RLYK[ RNYO[ RNZP[";
prog_char	gTimesRomanBold_53[]	PROGMEM	=	"44H\\XIYFYLXIVGSFPFMGKIKLLNOPURWSXUXXWZ RLLMNOOUQWRXT RMGLILKMMONUPXRYTYWXYWZT[Q[NZLXKUK[LX";
prog_char	gTimesRomanBold_54[]	PROGMEM	=	"57H\\JFJL RQFQ[ RRGRZ RSFS[ RZFZL RJFZF RN[V[ RKFJL RLFJI RMFJH ROFJG RUFZG RWFZH RXFZI RYFZL RQZO[ RQYP[ RSYT[ RSZU[";
prog_char	gTimesRomanBold_55[]	PROGMEM	=	"45F^KFKULXNZQ[S[VZXXYUYG RLGLVMX RMFMVNYOZQ[ RHFPF RVF\\F RIFKG RJFKH RNFMH ROFMG RWFYG R[FYG";
prog_char	gTimesRomanBold_56[]	PROGMEM	=	"34H\\KFR[ RLFRXR[ RMFSX RYGR[ RIFPF RUF[F RJFLH RNFMH ROFMG RWFYG RZFYG";
prog_char	gTimesRomanBold_57[]	PROGMEM	=	"55F^JFN[ RKFNVN[ RLFOV RRFOVN[ RRFV[ RSFVVV[ RTFWV RZGWVV[ RGFOF RRFTF RWF]F RHFKG RIFKH RMFLH RNFLG RXFZG R\\FZG";
prog_char	gTimesRomanBold_58[]	PROGMEM	=	"54H\\KFW[ RLFX[ RMFY[ RXGLZ RIFPF RUF[F RI[O[ RT[[[ RJFMH RNFMH ROFMG RVFXG RZFXG RLZJ[ RLZN[ RWZU[ RWYV[ RWYZ[";
prog_char	gTimesRomanBold_59[]	PROGMEM	=	"48G]JFQQQ[ RKFRQRZ RLFSQS[ RYGSQ RHFOF RVF\\F RN[V[ RIFKG RNFLG RWFYG R[FYG RQZO[ RQYP[ RSYT[ RSZU[";
prog_char	gTimesRomanBold_5A[]	PROGMEM	=	"41H\\YFKFKL RWFK[ RXFL[ RYFM[ RK[Y[YU RLFKL RMFKI RNFKH RPFKG RT[YZ RV[YY RW[YX RX[YU";
prog_char	gTimesRomanBold_5B[]	PROGMEM	=	"12KYOBOb RPBPb ROBVB RObVb";
prog_char	gTimesRomanBold_5C[]	PROGMEM	=	" 3KYKFY^";
prog_char	gTimesRomanBold_5D[]	PROGMEM	=	"12KYTBTb RUBUb RNBUB RNbUb";
prog_char	gTimesRomanBold_5E[]	PROGMEM	=	" 8G]JTROZT RJTRPZT";
prog_char	gTimesRomanBold_5F[]	PROGMEM	=	" 3H\\Hb\\b";

prog_char	gTimesRomanBold_60[]	PROGMEM	=	" 7LXPFUL RPFOGUL";
prog_char	gTimesRomanBold_61[]	PROGMEM	=	"54I]NPNOOOOQMQMONNPMTMVNWOXQXXYZZ[ RVOWQWXXZ RTMUNVPVXWZZ[[[ RVRUSPTMULWLXMZP[S[UZVX RNUMWMXNZ RUSQTOUNWNXOZP[";
prog_char	gTimesRomanBold_62[]	PROGMEM	=	"47G\\LFL[MZOZ RMGMY RIFNFNZ RNPONQMSMVNXPYSYUXXVZS[Q[OZNX RWPXRXVWX RSMUNVOWRWVVYUZS[ RJFLG RKFLH";
prog_char	gTimesRomanBold_63[]	PROGMEM	=	"34H[WQWPVPVRXRXPVNTMQMNNLPKSKULXNZQ[S[VZXX RMPLRLVMX RQMONNOMRMVNYOZQ[";
prog_char	gTimesRomanBold_64[]	PROGMEM	=	"52H]VFV[[[ RWGWZ RSFXFX[ RVPUNSMQMNNLPKSKULXNZQ[S[UZVX RMPLRLVMX RQMONNOMRMVNYOZQ[ RTFVG RUFVH RXYY[ RXZZ[";
prog_char	gTimesRomanBold_65[]	PROGMEM	=	"41H[MSXSXQWOVNSMQMNNLPKSKULXNZQ[S[VZXX RWRWQVO RMPLRLVMX RVSVPUNSM RQMONNOMRMVNYOZQ[";
prog_char	gTimesRomanBold_66[]	PROGMEM	=	"40KYWHWGVGVIXIXGWFTFRGQHPKP[ RRHQKQZ RTFSGRIR[ RMMVM RM[U[ RPZN[ RPYO[ RRYS[ RRZT[";
prog_char	gTimesRomanBold_67[]	PROGMEM	=	"89I\\XNYOZNYMXMVNUO RQMONNOMQMSNUOVQWSWUVVUWSWQVOUNSMQM ROONQNSOU RUUVSVQUO RQMPNOPOTPVQW RSWTVUTUPTNSM RNUMVLXLYM[N\\Q]U]X^Y_ RN[Q\\U\\X] RLYMZP[U[X\\Y^Y_XaUbObLaK_K^L\\O[ RObMaL_L^M\\O[";
prog_char	gTimesRomanBold_68[]	PROGMEM	=	"65G^LFL[ RMGMZ RIFNFN[ RNQOOPNRMUMWNXOYRY[ RWOXRXZ RUMVNWQW[ RI[Q[ RT[\\[ RJFLG RKFLH RLZJ[ RLYK[ RNYO[ RNZP[ RWZU[ RWYV[ RYYZ[ RYZ[[";
prog_char	gTimesRomanBold_69[]	PROGMEM	=	"43LXQFQHSHSFQF RRFRH RQGSG RQMQ[ RRNRZ RNMSMS[ RN[V[ ROMQN RPMQO RQZO[ RQYP[ RSYT[ RSZU[";
prog_char	gTimesRomanBold_6A[]	PROGMEM	=	"41KXRFRHTHTFRF RSFSH RRGTG RRMR^QaPb RSNS]R` ROMTMT]S`RaPbMbLaL_N_NaMaM` RPMRN RQMRO";
prog_char	gTimesRomanBold_6B[]	PROGMEM	=	"61G]LFL[ RMGMZ RIFNFN[ RWNNW RRSY[ RRTX[ RQTW[ RTM[M RI[Q[ RT[[[ RJFLG RKFLH RUMWN RZMWN RLZJ[ RLYK[ RNYO[ RNZP[ RWYU[ RVYZ[";
prog_char	gTimesRomanBold_6C[]	PROGMEM	=	"31LXQFQ[ RRGRZ RNFSFS[ RN[V[ ROFQG RPFQH RQZO[ RQYP[ RSYT[ RSZU[";
prog_char	gTimesRomanBold_6D[]	PROGMEM	=	"99AcFMF[ RGNGZ RCMHMH[ RHQIOJNLMOMQNROSRS[ RQORRRZ ROMPNQQQ[ RSQTOUNWMZM\\N]O^R^[ R\\O]R]Z RZM[N\\Q\\[ RC[K[ RN[V[ RY[a[ RDMFN REMFO RFZD[ RFYE[ RHYI[ RHZJ[ RQZO[ RQYP[ RSYT[ RSZU[ R\\ZZ[ R\\Y[[ R^Y_[ R^Z`[";
prog_char	gTimesRomanBold_6E[]	PROGMEM	=	"65G^LML[ RMNMZ RIMNMN[ RNQOOPNRMUMWNXOYRY[ RWOXRXZ RUMVNWQW[ RI[Q[ RT[\\[ RJMLN RKMLO RLZJ[ RLYK[ RNYO[ RNZP[ RWZU[ RWYV[ RYYZ[ RYZ[[";
prog_char	gTimesRomanBold_6F[]	PROGMEM	=	"46H\\QMNNLPKSKULXNZQ[S[VZXXYUYSXPVNSMQM RMPLRLVMX RWXXVXRWP RQMONNOMRMVNYOZQ[ RS[UZVYWVWRVOUNSM";

prog_char	gTimesRomanBold_70[]	PROGMEM	=	"60G\\LMLb RMNMa RIMNMNb RNPONQMSMVNXPYSYUXXVZS[Q[OZNX RWPXRXVWX RSMUNVOWRWVVYUZS[ RIbQb RJMLN RKMLO RLaJb RL`Kb RN`Ob RNaPb";
prog_char	gTimesRomanBold_71[]	PROGMEM	=	"55H\\VNVb RWOWa RUNWNXMXb RVPUNSMQMNNLPKSKULXNZQ[S[UZVX RMPLRLVMX RQMONNOMRMVNYOZQ[ RSb[b RVaTb RV`Ub RX`Yb RXaZb";
prog_char	gTimesRomanBold_72[]	PROGMEM	=	"43IZNMN[ RONOZ RKMPMP[ RWOWNVNVPXPXNWMUMSNQPPS RK[S[ RLMNN RMMNO RNZL[ RNYM[ RPYQ[ RPZR[";
prog_char	gTimesRomanBold_73[]	PROGMEM	=	"43J[WOXMXQWOVNTMPMNNMOMQNSPTUUWVXY RNNMQ RNRPSUTWU RXVWZ RMONQPRUSWTXVXYWZU[Q[OZNYMWM[NY";
prog_char	gTimesRomanBold_74[]	PROGMEM	=	"22KZPHPVQYRZT[V[XZYX RQHQWRY RPHRFRWSZT[ RMMVM";
prog_char	gTimesRomanBold_75[]	PROGMEM	=	"43G^LMLVMYNZP[S[UZVYWW RMNMWNY RIMNMNWOZP[ RWMW[\\[ RXNXZ RTMYMY[ RJMLN RKMLO RYYZ[ RYZ[[";
prog_char	gTimesRomanBold_76[]	PROGMEM	=	"31I[LMR[ RMMRY RNMSY RXNSYR[ RJMQM RTMZM RKMNO RPMNN RVMXN RYMXN";
prog_char	gTimesRomanBold_77[]	PROGMEM	=	"45F^JMN[ RKMNX RLMOX RRMOXN[ RRMV[ RSMVX RRMTMWX RZNWXV[ RGMOM RWM]M RHMKN RNMLN RXMZN R\\MZN";
prog_char	gTimesRomanBold_78[]	PROGMEM	=	"48H\\LMV[ RMMW[ RNMX[ RWNMZ RJMQM RTMZM RJ[P[ RS[Z[ RKMMN RPMNN RUMWN RYMWN RMZK[ RMZO[ RVZT[ RWZY[";
prog_char	gTimesRomanBold_79[]	PROGMEM	=	"40H[LMR[ RMMRY RNMSY RXNSYP_NaLbJbIaI_K_KaJaJ` RJMQM RTMZM RKMNO RPMNN RVMXN RYMXN";
prog_char	gTimesRomanBold_7A[]	PROGMEM	=	"41I[VML[ RWMM[ RXMN[ RXMLMLQ RL[X[XW RMMLQ RNMLP ROMLO RQMLN RS[XZ RU[XY RV[XX RW[XW";
prog_char	gTimesRomanBold_7B[]	PROGMEM	=	"40KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
prog_char	gTimesRomanBold_7C[]	PROGMEM	=	" 3NVRBRb";
prog_char	gTimesRomanBold_7D[]	PROGMEM	=	"40KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
prog_char	gTimesRomanBold_7E[]	PROGMEM	=	"24F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
prog_char	gTimesRomanBold_7F[]	PROGMEM	=	"35JZJFJ[K[KFLFL[M[MFNFN[O[OFPFP[Q[QFRFR[S[SFTFT[U[UFVFV[W[WFXFX[Y[YFZFZ[";


PGM_P gHershyTimesRomanBoldFontTable[]	PROGMEM =
{

	gTimesRomanBold_00,
	gTimesRomanBold_20,
	gTimesRomanBold_21,
	gTimesRomanBold_22,
	gTimesRomanBold_23,
	gTimesRomanBold_24,
	gTimesRomanBold_25,
	gTimesRomanBold_26,
	gTimesRomanBold_27,
	gTimesRomanBold_28,
	gTimesRomanBold_29,
	gTimesRomanBold_2A,
	gTimesRomanBold_2B,
	gTimesRomanBold_2C,
	gTimesRomanBold_2D,
	gTimesRomanBold_2E,
	gTimesRomanBold_2F,

	gTimesRomanBold_30,
	gTimesRomanBold_31,
	gTimesRomanBold_32,
	gTimesRomanBold_33,
	gTimesRomanBold_34,
	gTimesRomanBold_35,
	gTimesRomanBold_36,
	gTimesRomanBold_37,
	gTimesRomanBold_38,
	gTimesRomanBold_39,
	gTimesRomanBold_3A,
	gTimesRomanBold_3B,
	gTimesRomanBold_3C,
	gTimesRomanBold_3D,
	gTimesRomanBold_3E,
	gTimesRomanBold_3F,

	gTimesRomanBold_40,
	gTimesRomanBold_41,
	gTimesRomanBold_42,
	gTimesRomanBold_43,
	gTimesRomanBold_44,
	gTimesRomanBold_45,
	gTimesRomanBold_46,
	gTimesRomanBold_47,
	gTimesRomanBold_48,
	gTimesRomanBold_49,
	gTimesRomanBold_4A,
	gTimesRomanBold_4B,
	gTimesRomanBold_4C,
	gTimesRomanBold_4D,
	gTimesRomanBold_4E,
	gTimesRomanBold_4F,

	gTimesRomanBold_50,
	gTimesRomanBold_51,
	gTimesRomanBold_52,
	gTimesRomanBold_53,
	gTimesRomanBold_54,
	gTimesRomanBold_55,
	gTimesRomanBold_56,
	gTimesRomanBold_57,
	gTimesRomanBold_58,
	gTimesRomanBold_59,
	gTimesRomanBold_5A,
	gTimesRomanBold_5B,
	gTimesRomanBold_5C,
	gTimesRomanBold_5D,
	gTimesRomanBold_5E,
	gTimesRomanBold_5F,

	gTimesRomanBold_60,
	gTimesRomanBold_61,
	gTimesRomanBold_62,
	gTimesRomanBold_63,
	gTimesRomanBold_64,
	gTimesRomanBold_65,
	gTimesRomanBold_66,
	gTimesRomanBold_67,
	gTimesRomanBold_68,
	gTimesRomanBold_69,
	gTimesRomanBold_6A,
	gTimesRomanBold_6B,
	gTimesRomanBold_6C,
	gTimesRomanBold_6D,
	gTimesRomanBold_6E,
	gTimesRomanBold_6F,

	gTimesRomanBold_70,
	gTimesRomanBold_71,
	gTimesRomanBold_72,
	gTimesRomanBold_73,
	gTimesRomanBold_74,
	gTimesRomanBold_75,
	gTimesRomanBold_76,
	gTimesRomanBold_77,
	gTimesRomanBold_78,
	gTimesRomanBold_79,
	gTimesRomanBold_7A,
	gTimesRomanBold_7B,
	gTimesRomanBold_7C,
	gTimesRomanBold_7D,
	gTimesRomanBold_7E,
	gTimesRomanBold_7F

};
