//*******************************************************************************
//*	music.jhf		Music
//*	formated for use with Arduino Processing 
//*	by Mark Sproul
//*******************************************************************************
//*	Jan 24,	2009	<MLS>	Formated Hershey Music for Arduino
//*******************************************************************************
//#include	"HersheyMusic.h"



prog_char	gMusic_00[]	PROGMEM	=	"Music";


prog_char	gMusic_20[]	PROGMEM	=	" 1JZ";
prog_char	gMusic_21[]	PROGMEM	=	"15MWRFQHRTSHRF RRHRN RRYQZR[SZRY";
prog_char	gMusic_22[]	PROGMEM	=	"18JZMPQRTTVVWYW[V]U^ RMQST RMRPSTUVWWY";
prog_char	gMusic_23[]	PROGMEM	=	"18JZWKVMTOPQMR RSPMS RUFVGWIWKVNTPQRMT";
prog_char	gMusic_24[]	PROGMEM	=	"36H\\SMONLPKRKTLVNWQWUVXTYRYPXNVMSM RXNSM RVMQNLP RONKR RLVQW RNWSVXT RUVYR";
prog_char	gMusic_25[]	PROGMEM	=	"36H\\SMONLPKRKTLVNWQWUVXTYRYPXNVMSM RXNSM RVMQNLP RONKR RLVQW RNWSVXT RUVYR";
prog_char	gMusic_26[]	PROGMEM	=	"34J[SMPNNPMRMTNVPWRWUVWTXRXPWNUMSM ROPUM RNRVN RMTWO RNUXP ROVWR RPWVT";
prog_char	gMusic_27[]	PROGMEM	=	"18JZOGO^ RUFU] RMNWL RMOWM RMWWU RMXWV";
prog_char	gMusic_28[]	PROGMEM	=	"18JZNFNX RVLV^ RNNVL RNOVM RNWVU RNXVV";
prog_char	gMusic_29[]	PROGMEM	=	"25JZNBNW RNNQLTLVMWOWQVSSUQVNW RNNQMTMVN RUMVOVQUSSU";
prog_char	gMusic_2A[]	PROGMEM	=	"18E_HIHL R\\I\\L RHI\\I RHJ\\J RHK\\K RHL\\L";
prog_char	gMusic_2B[]	PROGMEM	=	"18JZMNMQ RWNWQ RMNWN RMOWO RMPWP RMQWQ";
prog_char	gMusic_2C[]	PROGMEM	=	"49JZMLWX RMLONQOTOVNWMWKUKUMTO RONTO RQOWM RVKVN RULWL RWXUVSUPUNVMWMYOYOWPU RUVPU RSUMW RNVNY RMXOX";
prog_char	gMusic_2D[]	PROGMEM	=	"26JZPOOMOKMKMMNNPOSOUNWL RNKNN RMLOL RMMSO RPOUN RWLWY";
prog_char	gMusic_2E[]	PROGMEM	=	"36JZQCVMRTRU RULQS RTITKPRRUUY RW\\UYSXQXOYN[N]O_Ra RW\\UZSYOYO]P_Ra RSXPZN]";
prog_char	gMusic_2F[]	PROGMEM	=	"03EfNSOUQVSVUUVSVQUOSNQNOONPMSMVNYP[S\\V\\Y[[Y\\W]T]P\\MZJXIUHRHOIMJKLIOHSHXI]KaMcPeTfYf]e`cba RKLJNIRIXJ\\L`NbQdUeYe]d_cba RPOTO ROPUP RNQVQ RNRVR RNSVS ROTUT RPUTU RaLaNcNcLaL RbLbN RaMcM RaVaXcXcVaV RbVbX RaWcW";

prog_char	gMusic_30[]	PROGMEM	=	"40H\\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF RQFOGNHMJLOLRMWNYOZQ[ RS[UZVYWWXRXOWJVHUGSF";
prog_char	gMusic_31[]	PROGMEM	=	"11H\\NJPISFS[ RRGR[ RN[W[";
prog_char	gMusic_32[]	PROGMEM	=	"45H\\LJMKLLKKKJLHMGPFTFWGXHYJYLXNUPPRNSLUKXK[ RTFVGWHXJXLWNTPPR RKYLXNXSZVZXYYX RNXS[W[XZYXYV";
prog_char	gMusic_33[]	PROGMEM	=	"47H\\LJMKLLKKKJLHMGPFTFWGXIXLWNTOQO RTFVGWIWLVNTO RTOVPXRYTYWXYWZT[P[MZLYKWKVLUMVLW RWQXTXWWYVZT[";
prog_char	gMusic_34[]	PROGMEM	=	"13H\\THT[ RUFU[ RUFJUZU RQ[X[";
prog_char	gMusic_35[]	PROGMEM	=	"39H\\MFKP RKPMNPMSMVNXPYSYUXXVZS[P[MZLYKWKVLUMVLW RSMUNWPXSXUWXUZS[ RMFWF RMGRGWF";
prog_char	gMusic_36[]	PROGMEM	=	"48H\\WIVJWKXJXIWGUFRFOGMILKKOKULXNZQ[S[VZXXYUYTXQVOSNRNOOMQLT RRFPGNIMKLOLUMXOZQ[ RS[UZWXXUXTWQUOSN";
prog_char	gMusic_37[]	PROGMEM	=	"31H\\KFKL RKJLHNFPFUIWIXHYF RLHNGPGUI RYFYIXLTQSSRVR[ RXLSQRSQVQ[";
prog_char	gMusic_38[]	PROGMEM	=	"63H\\PFMGLILLMNPOTOWNXLXIWGTFPF RPFNGMIMLNNPO RTOVNWLWIVGTF RPOMPLQKSKWLYMZP[T[WZXYYWYSXQWPTO RPONPMQLSLWMYNZP[ RT[VZWYXWXSWQVPTO";
prog_char	gMusic_39[]	PROGMEM	=	"48H\\XMWPURRSQSNRLPKMKLLINGQFSFVGXIYLYRXVWXUZR[O[MZLXLWMVNWMX RQSORMPLMLLMIOGQF RSFUGWIXLXRWVVXTZR[";
prog_char	gMusic_3A[]	PROGMEM	=	"12MWRMQNROSNRM RRYQZR[SZRY";
prog_char	gMusic_3B[]	PROGMEM	=	"86A^GfHfIeIdHcGcFdFfGhIiKiNhPfQdR`RUQ;Q4R/S-U,V,X-Y/Y3X6W8U;P?JCHEFHEJDNDREVGYJ[N\\R\\V[XZZW[T[PZMYKWITHPHMIKKJNJRKUMW RGdGeHeHdGd RU;Q?LCIFGIFKENERFVGXJ[ RR\\U[WZYWZTZPYMXKVITH";
prog_char	gMusic_3C[]	PROGMEM	=	"03EfNSOUQVSVUUVSVQUOSNQNOONPMSMVNYP[S\\V\\Y[[Y\\W]T]P\\MZJXIUHRHOIMJKLIOHSHXI]KaMcPeTfYf]e`cba RKLJNIRIXJ\\L`NbQdUeYe]d_cba RPOTO ROPUP RNQVQ RNRVR RNSVS ROTUT RPUTU RaLaNcNcLaL RbLbN RaMcM RaVaXcXcVaV RbVbX RaWcW";
prog_char	gMusic_3D[]	PROGMEM	=	"89IjNQOOQNSNUOVQVSUUSVQVOUNTMQMNNKPISHWH[I^K`NaRaW`[_]]`ZcVfQiMk RWHZI]K_N`R`W_[^]\\`YcTgQi RPOTO ROPUP RNQVQ RNRVR RNSVS ROTUT RPUTU ReLeNgNgLeL RfLfN ReMgM ReVeXgXgVeV RfVfX ReWgW";
prog_char	gMusic_3E[]	PROGMEM	=	"30D`H@Hd RM@Md RW@Wd R\\@\\d RMMWK RMNWL RMOWM RMWWU RMXWV RMYWW";
prog_char	gMusic_3F[]	PROGMEM	=	"85D`H>Hf RI>If RM>Mf RQBSBSDQDQAR?T>W>Y?[A\\D\\I[LYNWOUOSNRLQNOQNROSQVRXSVUUWUYV[X\\[\\`[cYeWfTfReQcQ`S`SbQb RRBRD RQCSC RY?ZA[D[IZLYN RRLRNPQNRPSRVRX RYVZX[[[`ZcYe RR`Rb RQaSa";

prog_char	gMusic_40[]	PROGMEM	=	"18JZMNMQ RWNWQ RMNWN RMOWO RMPWP RMQWQ";
prog_char	gMusic_41[]	PROGMEM	=	"18H\\UFH[ RUFV[ RTHU[ RLUUU RF[L[ RR[X[";
prog_char	gMusic_42[]	PROGMEM	=	"41F^OFI[ RPFJ[ RLFWFZG[I[KZNYOVP RWFYGZIZKYNXOVP RMPVPXQYSYUXXVZR[F[ RVPWQXSXUWXUZR[";
prog_char	gMusic_43[]	PROGMEM	=	"34H]ZH[H\\F[L[JZHYGWFTFQGOIMLLOKSKVLYMZP[S[UZWXXV RTFRGPINLMOLSLVMYNZP[";
prog_char	gMusic_44[]	PROGMEM	=	"30F]OFI[ RPFJ[ RLFUFXGYHZKZOYSWWUYSZO[F[ RUFWGXHYKYOXSVWTYRZO[";
prog_char	gMusic_45[]	PROGMEM	=	"22F]OFI[ RPFJ[ RTLRT RLF[FZLZF RMPSP RF[U[WVT[";
prog_char	gMusic_46[]	PROGMEM	=	"20F\\OFI[ RPFJ[ RTLRT RLF[FZLZF RMPSP RF[M[";
prog_char	gMusic_47[]	PROGMEM	=	"42H^ZH[H\\F[L[JZHYGWFTFQGOIMLLOKSKVLYMZP[R[UZWXYT RTFRGPINLMOLSLVMYNZP[ RR[TZVXXT RUT\\T";
prog_char	gMusic_48[]	PROGMEM	=	"27E_NFH[ ROFI[ R[FU[ R\\FV[ RKFRF RXF_F RLPXP RE[L[ RR[Y[";
prog_char	gMusic_49[]	PROGMEM	=	"12LYUFO[ RVFP[ RRFYF RL[S[";
prog_char	gMusic_4A[]	PROGMEM	=	"21I[XFSWRYQZO[M[KZJXJVKULVKW RWFRWQYO[ RTF[F";
prog_char	gMusic_4B[]	PROGMEM	=	"27F]OFI[ RPFJ[ R]FLS RSOW[ RROV[ RLFSF RYF_F RF[M[ RS[Y[";
prog_char	gMusic_4C[]	PROGMEM	=	"14H\\QFK[ RRFL[ RNFUF RH[W[YUV[";
prog_char	gMusic_4D[]	PROGMEM	=	"30E`NFH[ RNFO[ ROFPY R\\FO[ R\\FV[ R]FW[ RKFOF R\\F`F RE[K[ RS[Z[";
prog_char	gMusic_4E[]	PROGMEM	=	"21F_OFI[ ROFVX ROIV[ R\\FV[ RLFOF RYF_F RF[L[";
prog_char	gMusic_4F[]	PROGMEM	=	"42G]SFPGNILLKOJSJVKYLZN[Q[TZVXXUYRZNZKYHXGVFSF RSFQGOIMLLOKSKVLYN[ RQ[SZUXWUXRYNYKXHVF";

prog_char	gMusic_50[]	PROGMEM	=	"27F]OFI[ RPFJ[ RLFXF[G\\I\\K[NYPUQMQ RXFZG[I[KZNXPUQ RF[M[";
prog_char	gMusic_51[]	PROGMEM	=	"61G]SFPGNILLKOJSJVKYLZN[Q[TZVXXUYRZNZKYHXGVFSF RSFQGOIMLLOKSKVLYN[ RQ[SZUXWUXRYNYKXHVF RLYLXMVOUPURVSXS_T`V`W^W] RSXT^U_V_W^";
prog_char	gMusic_52[]	PROGMEM	=	"42F^OFI[ RPFJ[ RLFWFZG[I[KZNYOVPMP RWFYGZIZKYNXOVP RRPTQURVZW[Y[ZYZX RURWYXZYZZY RF[M[";
prog_char	gMusic_53[]	PROGMEM	=	"35G^ZH[H\\F[L[JZHYGVFRFOGMIMKNMONVRXT RMKOMVQWRXTXWWYVZS[O[LZKYJWJUI[JYKY";
prog_char	gMusic_54[]	PROGMEM	=	"16H]UFO[ RVFP[ ROFLLNF]F\\L\\F RL[S[";
prog_char	gMusic_55[]	PROGMEM	=	"25F_NFKQJUJXKZN[R[UZWXXU\\F ROFLQKUKXLZN[ RKFRF RYF_F";
prog_char	gMusic_56[]	PROGMEM	=	"15H\\NFO[ ROFPY R\\FO[ RLFRF RXF^F";
prog_char	gMusic_57[]	PROGMEM	=	"24E_MFK[ RNFLY RUFK[ RUFS[ RVFTY R]FS[ RJFQF RZF`F";
prog_char	gMusic_58[]	PROGMEM	=	"21G]NFU[ ROFV[ R\\FH[ RLFRF RXF^F RF[L[ RR[X[";
prog_char	gMusic_59[]	PROGMEM	=	"20H]NFRPO[ ROFSPP[ R]FSP RLFRF RYF_F RL[S[";
prog_char	gMusic_5A[]	PROGMEM	=	"16G][FH[ R\\FI[ ROFLLNF\\F RH[V[XUU[";
prog_char	gMusic_5B[]	PROGMEM	=	"12KYOBOb RPBPb ROBVB RObVb";
prog_char	gMusic_5C[]	PROGMEM	=	" 3KYKFY^";
prog_char	gMusic_5D[]	PROGMEM	=	"12KYTBTb RUBUb RNBUB RNbUb";
prog_char	gMusic_5E[]	PROGMEM	=	" 7LXTFOL RTFUGOL";
prog_char	gMusic_5F[]	PROGMEM	=	" 3E_IR[R";

prog_char	gMusic_60[]	PROGMEM	=	" 7LXPFUL RPFOGUL";
prog_char	gMusic_61[]	PROGMEM	=	"39H]XMVTUXUZV[Y[[Y\\W RYMWTVXVZW[ RVTVQUNSMQMNNLQKTKWLYMZO[Q[SZUWVT RQMONMQLTLXMZ";
prog_char	gMusic_62[]	PROGMEM	=	"36H[PFLSLVMYNZ RQFMS RMSNPPNRMTMVNWOXQXTWWUZR[P[NZMWMS RVNWPWTVWTZR[ RMFQF";
prog_char	gMusic_63[]	PROGMEM	=	"25I[WPWQXQXPWNUMRMONMQLTLWMYNZP[R[UZWW RRMPNNQMTMXNZ";
prog_char	gMusic_64[]	PROGMEM	=	"42H]ZFVTUXUZV[Y[[Y\\W R[FWTVXVZW[ RVTVQUNSMQMNNLQKTKWLYMZO[Q[SZUWVT RQMONMQLTLXMZ RWF[F";
prog_char	gMusic_65[]	PROGMEM	=	"26I[MVQUTTWRXPWNUMRMONMQLTLWMYNZP[R[UZWX RRMPNNQMTMXNZ";
prog_char	gMusic_66[]	PROGMEM	=	"35KZZGYHZI[H[GZFXFVGUHTJSMP[O_Na RXFVHUJTNRWQ[P^O`NaLbJbIaI`J_K`Ja ROMYM";
prog_char	gMusic_67[]	PROGMEM	=	"43H\\YMU[T^RaObLbJaI`I_J^K_J` RXMT[S^QaOb RVTVQUNSMQMNNLQKTKWLYMZO[Q[SZUWVT RQMONMQLTLXMZ";
prog_char	gMusic_68[]	PROGMEM	=	"31H]PFJ[ RQFK[ RMTOPQNSMUMWNXOXQVWVZW[ RUMWOWQUWUZV[Y[[Y\\W RMFQF";
prog_char	gMusic_69[]	PROGMEM	=	"26LYUFTGUHVGUF RMQNOPMSMTNTQRWRZS[ RRMSNSQQWQZR[U[WYXW";
prog_char	gMusic_6A[]	PROGMEM	=	"32LYVFUGVHWGVF RNQOOQMTMUNUQR[Q^P`OaMbKbJaJ`K_L`Ka RSMTNTQQ[P^O`Mb";
prog_char	gMusic_6B[]	PROGMEM	=	"34H\\PFJ[ RQFK[ RXNWOXPYOYNXMWMUNQROSMS ROSQTSZT[ ROSPTRZS[U[WZYW RMFQF";
prog_char	gMusic_6C[]	PROGMEM	=	"18MYUFQTPXPZQ[T[VYWW RVFRTQXQZR[ RRFVF";
prog_char	gMusic_6D[]	PROGMEM	=	"52AbBQCOEMHMINIPHTF[ RGMHNHPGTE[ RHTJPLNNMPMRNSOSQP[ RPMRORQO[ RRTTPVNXMZM\\N]O]Q[W[Z\\[ RZM\\O\\QZWZZ[[^[`YaW";
prog_char	gMusic_6E[]	PROGMEM	=	"37F]GQHOJMMMNNNPMTK[ RLMMNMPLTJ[ RMTOPQNSMUMWNXOXQVWVZW[ RUMWOWQUWUZV[Y[[Y\\W";
prog_char	gMusic_6F[]	PROGMEM	=	"32I[RMONMQLTLWMYNZP[R[UZWWXTXQWOVNTMRM RRMPNNQMTMXNZ RR[TZVWWTWPVN";

prog_char	gMusic_70[]	PROGMEM	=	"42G\\HQIOKMNMONOPNTJb RMMNNNPMTIb RNTOQQNSMUMWNXOYQYTXWVZS[Q[OZNWNT RWNXPXTWWUZS[ RFbMb";
prog_char	gMusic_71[]	PROGMEM	=	"33H\\XMRb RYMSb RVTVQUNSMQMNNLQKTKWLYMZO[Q[SZUWVT RQMONMQLTLXMZ RObVb";
prog_char	gMusic_72[]	PROGMEM	=	"26IZJQKOMMPMQNQPPTN[ ROMPNPPOTM[ RPTRPTNVMXMYNYOXPWOXN";
prog_char	gMusic_73[]	PROGMEM	=	"28J[XOXPYPYOXNUMRMONNONQORVVWW RNPOQVUWVWYVZS[P[MZLYLXMXMY";
prog_char	gMusic_74[]	PROGMEM	=	"18KYTFPTOXOZP[S[UYVW RUFQTPXPZQ[ RNMWM";
prog_char	gMusic_75[]	PROGMEM	=	"37F]GQHOJMMMNNNQLWLYN[ RLMMNMQKWKYLZN[P[RZTXVT RXMVTUXUZV[Y[[Y\\W RYMWTVXVZW[";
prog_char	gMusic_76[]	PROGMEM	=	"26H\\IQJOLMOMPNPQNWNYP[ RNMONOQMWMYNZP[Q[TZVXXUYQYMXMYO";
prog_char	gMusic_77[]	PROGMEM	=	"41C`DQEOGMJMKNKQIWIYK[ RIMJNJQHWHYIZK[M[OZQXRV RTMRVRYSZU[W[YZ[X\\V]R]M\\M]O RUMSVSYU[";
prog_char	gMusic_78[]	PROGMEM	=	"42H\\KQMNOMRMSOSR RQMRORRQVPXNZL[K[JZJYKXLYKZ RQVQYR[U[WZYW RYNXOYPZOZNYMXMVNTPSRRVRYS[";
prog_char	gMusic_79[]	PROGMEM	=	"41G\\HQIOKMNMONOQMWMYO[ RMMNNNQLWLYMZO[Q[SZUXWT RZMV[U^SaPbMbKaJ`J_K^L_K` RYMU[T^RaPb";
prog_char	gMusic_7A[]	PROGMEM	=	"31H\\YMXOVQNWLYK[ RLQMOOMRMVO RMOONRNVOXO RLYNYRZUZWY RNYR[U[WYXW";
prog_char	gMusic_7B[]	PROGMEM	=	"40KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
prog_char	gMusic_7C[]	PROGMEM	=	" 3NVRBRb";
prog_char	gMusic_7D[]	PROGMEM	=	"40KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
prog_char	gMusic_7E[]	PROGMEM	=	"24F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
prog_char	gMusic_7F[]	PROGMEM	=	"35JZJFJ[K[KFLFL[M[MFNFN[O[OFPFP[Q[QFRFR[S[SFTFT[U[UFVFV[W[WFXFX[Y[YFZFZ[";


PGM_P gHershyMusicFontTable[]	PROGMEM =	   // change "string_table" name to suit
{

	gMusic_00,
	gMusic_20,
	gMusic_21,
	gMusic_22,
	gMusic_23,
	gMusic_24,
	gMusic_25,
	gMusic_26,
	gMusic_27,
	gMusic_28,
	gMusic_29,
	gMusic_2A,
	gMusic_2B,
	gMusic_2C,
	gMusic_2D,
	gMusic_2E,
	gMusic_2F,

	gMusic_30,
	gMusic_31,
	gMusic_32,
	gMusic_33,
	gMusic_34,
	gMusic_35,
	gMusic_36,
	gMusic_37,
	gMusic_38,
	gMusic_39,
	gMusic_3A,
	gMusic_3B,
	gMusic_3C,
	gMusic_3D,
	gMusic_3E,
	gMusic_3F,

	gMusic_40,
	gMusic_41,
	gMusic_42,
	gMusic_43,
	gMusic_44,
	gMusic_45,
	gMusic_46,
	gMusic_47,
	gMusic_48,
	gMusic_49,
	gMusic_4A,
	gMusic_4B,
	gMusic_4C,
	gMusic_4D,
	gMusic_4E,
	gMusic_4F,

	gMusic_50,
	gMusic_51,
	gMusic_52,
	gMusic_53,
	gMusic_54,
	gMusic_55,
	gMusic_56,
	gMusic_57,
	gMusic_58,
	gMusic_59,
	gMusic_5A,
	gMusic_5B,
	gMusic_5C,
	gMusic_5D,
	gMusic_5E,
	gMusic_5F,

	gMusic_60,
	gMusic_61,
	gMusic_62,
	gMusic_63,
	gMusic_64,
	gMusic_65,
	gMusic_66,
	gMusic_67,
	gMusic_68,
	gMusic_69,
	gMusic_6A,
	gMusic_6B,
	gMusic_6C,
	gMusic_6D,
	gMusic_6E,
	gMusic_6F,

	gMusic_70,
	gMusic_71,
	gMusic_72,
	gMusic_73,
	gMusic_74,
	gMusic_75,
	gMusic_76,
	gMusic_77,
	gMusic_78,
	gMusic_79,
	gMusic_7A,
	gMusic_7B,
	gMusic_7C,
	gMusic_7D,
	gMusic_7E,
	gMusic_7F

};
