//*******************************************************************************
//*	timesib.jhf		Times Italic Bold
//*	formated for use with Arduino Processing 
//*	by Mark Sproul
//*******************************************************************************
//*	Jan 24,	2009	<MLS>	Formated Hershey Times Italic Boldfor Arduino
//*******************************************************************************
//#include	"HersheyTimesItalicBold.h"

prog_char	gTimesItalicBold_00[]	PROGMEM	=	"Times Italic Bold";

prog_char	gTimesItalicBold_20[]	PROGMEM	=	" 1JZ";
prog_char	gTimesItalicBold_21[]	PROGMEM	=	"34MXVFUFTGRT RVGUGRT RVGVHRT RVFWGWHRT RPXOYOZP[Q[RZRYQXPX RPYPZQZQYPY";
prog_char	gTimesItalicBold_22[]	PROGMEM	=	"12I[PFNM RQFNM RYFWM RZFWM";
prog_char	gTimesItalicBold_23[]	PROGMEM	=	"12H]SBLb RYBRb RLOZO RKUYU";
prog_char	gTimesItalicBold_24[]	PROGMEM	=	"52H]TBL_ RYBQ_ RZKZJYJYL[L[JZHYGVFRFOGMIMLNNPPVSWUWXVZ RNLONVRWT ROGNINKOMUPWRXTXWWYVZS[O[LZKYJWJULULWKWKV";
prog_char	gTimesItalicBold_25[]	PROGMEM	=	"32F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT";
prog_char	gTimesItalicBold_26[]	PROGMEM	=	"72E_\\O\\N[N[P]P]N\\M[MYNWPRXPZN[K[HZGXGVHTISKRPPROTMUKUITGRFPGOIOLPRQURWTZV[X[YYYX RL[HZ RIZHXHVITJSLR RPPQSTYVZ RK[JZIXIVJTKSMRRO ROLPOQRSVUYWZXZYY";
prog_char	gTimesItalicBold_27[]	PROGMEM	=	" 6NWUFSM RVFSM";
prog_char	gTimesItalicBold_28[]	PROGMEM	=	"32JZZBXCUERHPKNOMSMXN\\O_Qb RSHQKOONTN\\ RZBWDTGRJQLPOOSN\\ RNTO]P`Qb";
prog_char	gTimesItalicBold_29[]	PROGMEM	=	"32JZSBUEVHWLWQVUTYR\\O_LaJb RVHVPUUSYQ\\ RSBTDUGVP RVHUQTUSXRZP]M`Jb";
prog_char	gTimesItalicBold_2A[]	PROGMEM	=	"39J[TFSGUQTR RTFTR RTFUGSQTR ROIPIXOYO ROIYO ROIOJYNYO RYIXIPOOO RYIOO RYIYJONOO";
prog_char	gTimesItalicBold_2B[]	PROGMEM	=	"16F_RIRZSZ RRISISZ RJQ[Q[R RJQJR[R";
prog_char	gTimesItalicBold_2C[]	PROGMEM	=	"22MXQ[P[OZOYPXQXRYR[Q]P^N_ RPYPZQZQYPY RQ[Q\\P^";
prog_char	gTimesItalicBold_2D[]	PROGMEM	=	" 3E_IR[R";
prog_char	gTimesItalicBold_2E[]	PROGMEM	=	"16MXPXOYOZP[Q[RZRYQXPX RPYPZQZQYPY";
prog_char	gTimesItalicBold_2F[]	PROGMEM	=	" 8G^[BIbJb R[B\\BJb";

prog_char	gTimesItalicBold_30[]	PROGMEM	=	"58H]TFQGOIMLLOKSKVLYMZO[Q[TZVXXUYRZNZKYHXGVFTF RQHOJNLMOLSLWMY RTYVWWUXRYNYJXH RTFRGPJOLNOMSMXNZO[ RQ[SZUWVUWRXNXIWGVF";
prog_char	gTimesItalicBold_31[]	PROGMEM	=	"20H]TJO[Q[ RWFUJP[ RWFQ[ RWFTIQKOL RTJRKOL";
prog_char	gTimesItalicBold_32[]	PROGMEM	=	"52H]OKOJPJPLNLNJOHPGSFVFYGZIZKYMWOMUKWI[ RXGYIYKXMVOSQ RVFWGXIXKWMUOMU RJYKXMXRYWYXX RMXRZWZ RMXR[U[WZXXXW";
prog_char	gTimesItalicBold_33[]	PROGMEM	=	"64H]OKOJPJPLNLNJOHPGSFVFYGZIZKYMXNVOSP RXGYIYKXMWN RVFWGXIXKWMUOSP RQPSPVQWRXTXWWYUZR[O[LZKYJWJULULWKWKV RVRWTWWVY RSPUQVSVWUYTZR[";
prog_char	gTimesItalicBold_34[]	PROGMEM	=	"15H]WJR[T[ RZFXJS[ RZFT[ RZFJUZU";
prog_char	gTimesItalicBold_35[]	PROGMEM	=	"49H]QFLP RQF[F RQGYG RPHUHYG[F RLPMOPNSNVOWPXRXUWXUZQ[N[LZKYJWJULULWKWKV RVPWRWUVXTZ RSNUOVQVUUXSZQ[";
prog_char	gTimesItalicBold_36[]	PROGMEM	=	"61H]YJYIXIXKZKZIYGWFTFQGOIMLLOKSKVLYMZO[R[UZWXXVXSWQVPTOQOOPNQMS RPINLMOLSLWMY RVXWVWSVQ RTFRGPJOLNOMSMXNZO[ RR[TZUYVVVRUPTO";
prog_char	gTimesItalicBold_37[]	PROGMEM	=	"39H]NFLL R[FZIXLTQRTQWP[ RRSPWO[ RXLRRPUOWN[P[ RMIPFRFWI ROGRGWI RMIOHRHWIYIZH[F";
prog_char	gTimesItalicBold_38[]	PROGMEM	=	"04H]SFPGOHNJNMOOQPTPWOYNZLZIYGWFSF RUFPG RPHOJONPO ROORP RSPWO RXNYLYIXG RYGUF RSFQHPJPNQP RTPVOWNXLXHWF RQPMQKSJUJXKZN[R[VZWYXWXTWRVQTP RRPMQ RNQLSKUKXLZ RKZP[VZ RVYWWWTVR RVQSP RQPOQMSLULXMZN[ RR[TZUYVWVSUQTP";
prog_char	gTimesItalicBold_39[]	PROGMEM	=	"61H]XNWPVQTRQROQNPMNMKNIPGSFVFXGYHZKZNYRXUVXTZQ[N[LZKXKVMVMXLXLW ROPNNNKOI RXHYJYNXRWUUX RQRPQOOOKPHQGSF RVFWGXIXNWRVUUWSZQ[";
prog_char	gTimesItalicBold_3A[]	PROGMEM	=	"32MXSMRNROSPTPUOUNTMSM RSNSOTOTNSN RPXOYOZP[Q[RZRYQXPX RPYPZQZQYPY";
prog_char	gTimesItalicBold_3B[]	PROGMEM	=	"38MXSMRNROSPTPUOUNTMSM RSNSOTOTNSN RQ[P[OZOYPXQXRYR[Q]P^N_ RPYPZQZQYPY RQ[Q\\P^";
prog_char	gTimesItalicBold_3C[]	PROGMEM	=	" 4F^ZIJRZ[";
prog_char	gTimesItalicBold_3D[]	PROGMEM	=	"16F_JM[M[N RJMJN[N RJU[U[V RJUJV[V";
prog_char	gTimesItalicBold_3E[]	PROGMEM	=	" 4F^JIZRJ[";
prog_char	gTimesItalicBold_3F[]	PROGMEM	=	"59H]OKOJPJPLNLNJOHPGSFWFZG[I[KZMYNWOSPQQQSSTTT RUFZG RYGZIZKYMXNVO RWFXGYIYKXMWNSPRQRSST RPXOYOZP[Q[RZRYQXPX RPYPZQZQYPY";

prog_char	gTimesItalicBold_40[]	PROGMEM	=	"56E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
prog_char	gTimesItalicBold_41[]	PROGMEM	=	"38H\\UFIZ RSJT[ RTHUZ RUFUHVYV[ RLUTU RF[L[ RQ[X[ RIZG[ RIZK[ RTZR[ RTYS[ RVYW[";
prog_char	gTimesItalicBold_42[]	PROGMEM	=	"78F^OFI[ RPFJ[ RQFK[ RLFWFZG[I[KZNYOVP RYGZIZKYNXO RWFXGYIYKXNVP RNPVPXQYSYUXXVZR[F[ RWQXSXUWXUZ RVPWRWUVXTZR[ RMFPG RNFOH RRFPH RSFPG RJZG[ RJYH[ RKYL[ RJZM[";
prog_char	gTimesItalicBold_43[]	PROGMEM	=	"41H]ZH[H\\F[L[JZHYGWFTFQGOIMLLOKSKVLYMZP[S[UZWXXV RQHOJNLMOLSLWMY RTFRGPJOLNOMSMXNZP[";
prog_char	gTimesItalicBold_44[]	PROGMEM	=	"63F]OFI[ RPFJ[ RQFK[ RLFUFXGYHZKZOYSWWUYSZO[F[ RWGXHYKYOXSVWTY RUFWHXKXOWSUWRZO[ RMFPG RNFOH RRFPH RSFPG RJZG[ RJYH[ RKYL[ RJZM[";
prog_char	gTimesItalicBold_45[]	PROGMEM	=	"80F]OFI[ RPFJ[ RQFK[ RULST RLF[FZL RNPTP RF[U[WV RMFPG RNFOH RRFPH RSFPG RWFZG RXFZH RYFZI RZFZL RULSPST RTNRPSR RTOQPSQ RJZG[ RJYH[ RKYL[ RJZM[ RP[UZ RR[UY RUYWV";
prog_char	gTimesItalicBold_46[]	PROGMEM	=	"70F\\OFI[ RPFJ[ RQFK[ RULST RLF[FZL RNPTP RF[N[ RMFPG RNFOH RRFPH RSFPG RWFZG RXFZH RYFZI RZFZL RULSPST RTNRPSR RTOQPSQ RJZG[ RJYH[ RKYL[ RJZM[";
prog_char	gTimesItalicBold_47[]	PROGMEM	=	"65H^ZH[H\\F[L[JZHYGWFTFQGOIMLLOKSKVLYMZP[R[UZWXYT RQHOJNLMOLSLWMY RVXWWXT RTFRGPJOLNOMSMXNZP[ RR[TZVWWT RTT\\T RUTWU RVTWW RZTXV R[TXU";
prog_char	gTimesItalicBold_48[]	PROGMEM	=	"81E_NFH[ ROFI[ RPFJ[ RZFT[ R[FU[ R\\FV[ RKFSF RWF_F RLPXP RE[M[ RQ[Y[ RLFOG RMFNH RQFOH RRFOG RXF[G RYFZH R]F[H R^F[G RIZF[ RIYG[ RJYK[ RIZL[ RUZR[ RUYS[ RVYW[ RUZX[";
prog_char	gTimesItalicBold_49[]	PROGMEM	=	"39KYTFN[ RUFO[ RVFP[ RQFYF RK[S[ RRFUG RSFTH RWFUH RXFUG ROZL[ ROYM[ RPYQ[ ROZR[";
prog_char	gTimesItalicBold_4A[]	PROGMEM	=	"47I\\WFRWQYO[ RXFTSSVRX RYFUSSXQZO[M[KZJXJVKULUMVMWLXKX RKVKWLWLVKV RTF\\F RUFXG RVFWH RZFXH R[FXG";
prog_char	gTimesItalicBold_4B[]	PROGMEM	=	"72F]OFI[ RPFJ[ RQFK[ R\\GMR RQOU[ RROV[ RSNWZ RLFTF RYF_F RF[N[ RR[Y[ RMFPG RNFOH RRFPH RSFPG RZF\\G R^F\\G RJZG[ RJYH[ RKYL[ RJZM[ RUZS[ RUYT[ RVYX[";
prog_char	gTimesItalicBold_4C[]	PROGMEM	=	"49H\\QFK[ RRFL[ RSFM[ RNFVF RH[W[YU ROFRG RPFQH RTFRH RUFRG RLZI[ RLYJ[ RMYN[ RLZO[ RR[WZ RT[XX RV[YU";
prog_char	gTimesItalicBold_4D[]	PROGMEM	=	"68D`MFGZ RMGNYN[ RNFOY ROFPX R[FPXN[ R[FU[ R\\FV[ R]FW[ RJFOF R[F`F RD[J[ RR[Z[ RKFMG RLFMH R^F\\H R_F\\G RGZE[ RGZI[ RVZS[ RVYT[ RWYX[ RVZY[";
prog_char	gTimesItalicBold_4E[]	PROGMEM	=	"43F_OFIZ ROFV[ RPFVX RQFWX R\\GWXV[ RLFQF RYF_F RF[L[ RMFPG RNFPH RZF\\G R^F\\G RIZG[ RIZK[";
prog_char	gTimesItalicBold_4F[]	PROGMEM	=	"56G]SFPGNILLKOJSJVKYLZN[Q[TZVXXUYRZNZKYHXGVFSF ROIMLLOKSKWLY RUXWUXRYNYJXH RSFQGOJNLMOLSLXMZN[ RQ[SZUWVUWRXNXIWGVF";

prog_char	gTimesItalicBold_50[]	PROGMEM	=	"60F]OFI[ RPFJ[ RQFK[ RLFXF[G\\I\\K[NYPUQMQ RZG[I[KZNXP RXFYGZIZKYNWPUQ RF[N[ RMFPG RNFOH RRFPH RSFPG RJZG[ RJYH[ RKYL[ RJZM[";
prog_char	gTimesItalicBold_51[]	PROGMEM	=	"78G]SFPGNILLKOJSJVKYLZN[Q[TZVXXUYRZNZKYHXGVFSF ROIMLLOKSKWLY RUXWUXRYNYJXH RSFQGOJNLMOLSLXMZN[ RQ[SZUWVUWRXNXIWGVF RLXMVOUPURVSXT]U^V^W] RT^U_V_ RSXS_T`V`W]W\\";
prog_char	gTimesItalicBold_52[]	PROGMEM	=	"78F^OFI[ RPFJ[ RQFK[ RLFWFZG[I[KZNYOVPNP RYGZIZKYNXO RWFXGYIYKXNVP RRPTQURWXXYYYZX RWYXZYZ RURVZW[Y[ZXZW RF[N[ RMFPG RNFOH RRFPH RSFPG RJZG[ RJYH[ RKYL[ RJZM[";
prog_char	gTimesItalicBold_53[]	PROGMEM	=	"44G^ZH[H\\F[L[JZHYGVFRFOGMIMLNNPPVSWUWXVZ RNLONVRWT ROGNINKOMUPWRXTXWWYVZS[O[LZKYJWJUI[JYKY";
prog_char	gTimesItalicBold_54[]	PROGMEM	=	"54G]TFN[ RUFO[ RVFP[ RMFKL R]F\\L RMF]F RK[S[ RNFKL RPFLI RRFMG RYF\\G RZF\\H R[F\\I R\\F\\L ROZL[ ROYM[ RPYQ[ ROZR[";
prog_char	gTimesItalicBold_55[]	PROGMEM	=	"48F_NFKQJUJXKZN[R[UZWXXU\\G ROFLQKUKYLZ RPFMQLULYN[ RKFSF RYF_F RLFOG RMFNH RQFOH RRFOG RZF\\G R^F\\G";
prog_char	gTimesItalicBold_56[]	PROGMEM	=	"35H\\NFNHOYO[ ROGPX RPFQW R[GO[ RLFSF RXF^F RMFNH RQFPH RRFOG RYF[G R]F[G";
prog_char	gTimesItalicBold_57[]	PROGMEM	=	"57E_MFMHKYK[ RNGLX ROFMW RUFMWK[ RUFUHSYS[ RVGTX RWFUW R]GUWS[ RJFRF RUFWF RZF`F RKFNG RLFMH RPFNI RQFNG R[F]G R_F]G";
prog_char	gTimesItalicBold_58[]	PROGMEM	=	"54G]NFT[ ROFU[ RPFV[ R[GIZ RLFSF RXF^F RF[L[ RQ[X[ RMFOH RQFPH RRFPG RYF[G R]F[G RIZG[ RIZK[ RTZR[ RTYS[ RUYW[";
prog_char	gTimesItalicBold_59[]	PROGMEM	=	"51G]MFQPN[ RNFRPO[ ROFSPP[ R\\GSP RKFRF RYF_F RK[S[ RLFNG RPFOH RQFNG RZF\\G R^F\\G ROZL[ ROYM[ RPYQ[ ROZR[";
prog_char	gTimesItalicBold_5A[]	PROGMEM	=	"35G]ZFH[ R[FI[ R\\FJ[ R\\FNFLL RH[V[XU ROFLL RPFMI RRFNG RR[VZ RT[WX RU[XU";
prog_char	gTimesItalicBold_5B[]	PROGMEM	=	"12KYOBOb RPBPb ROBVB RObVb";
prog_char	gTimesItalicBold_5C[]	PROGMEM	=	" 3KYKFY^";
prog_char	gTimesItalicBold_5D[]	PROGMEM	=	"12KYTBTb RUBUb RNBUB RNbUb";
prog_char	gTimesItalicBold_5E[]	PROGMEM	=	" 8G]JTROZT RJTRPZT";
prog_char	gTimesItalicBold_5F[]	PROGMEM	=	" 3H\\Hb\\b";

prog_char	gTimesItalicBold_60[]	PROGMEM	=	" 7LXPFUL RPFOGUL";
prog_char	gTimesItalicBold_61[]	PROGMEM	=	"50G]WMUTUXVZW[Y[[Y\\W RXMVTVZ RWMYMWTVX RUTUQTNRMPMMNKQJTJVKYLZN[P[RZSYTWUT RNNLQKTKWLY RPMNOMQLTLWMZN[";
prog_char	gTimesItalicBold_62[]	PROGMEM	=	"52I\\PFNMMSMWNYOZQ[S[VZXWYTYRXOWNUMSMQNPOOQNT RQFOMNQNWOZ RVYWWXTXQWO RMFRFPMNT RS[UYVWWTWQVNUM RNFQG ROFPH";
prog_char	gTimesItalicBold_63[]	PROGMEM	=	"34I[WQWPVPVRXRXPWNUMRMONMQLTLVMYNZP[R[UZWW ROONQMTMWNY RRMPOOQNTNWOZP[";
prog_char	gTimesItalicBold_64[]	PROGMEM	=	"58G]YFVQUUUXVZW[Y[[Y\\W RZFWQVUVZ RVF[FWTVX RUTUQTNRMPMMNKQJTJVKYLZN[P[RZSYTWUT RMOLQKTKWLY RPMNOMQLTLWMZN[ RWFZG RXFYH";
prog_char	gTimesItalicBold_65[]	PROGMEM	=	"33I[MVQUTTWRXPWNUMRMONMQLTLVMYNZP[R[UZWX ROONQMTMWNY RRMPOOQNTNWOZP[";
prog_char	gTimesItalicBold_66[]	PROGMEM	=	"45JZZHZGYGYI[I[GZFXFVGTISKRNQRO[N^M`Kb RTJSMRRP[O^ RXFVHUJTMSRQZP]O_MaKbIbHaH_J_JaIaI` RNMYM";
prog_char	gTimesItalicBold_67[]	PROGMEM	=	"57H]XMT[S^QaOb RYMU[S_ RXMZMV[T_RaObLbJaI`I^K^K`J`J_ RVTVQUNSMQMNNLQKTKVLYMZO[Q[SZTYUWVT RNOMQLTLWMY RQMOONQMTMWNZO[";
prog_char	gTimesItalicBold_68[]	PROGMEM	=	"41G]OFI[K[ RPFJ[ RLFQFK[ RMTOPQNSMUMWNXPXSVX RWNWRVVVZ RWPUUUXVZW[Y[[Y\\W RMFPG RNFOH";
prog_char	gTimesItalicBold_69[]	PROGMEM	=	"35KXSFSHUHUFSF RTFTH RSGUG RLQMOOMQMRNSPSSQX RRNRRQVQZ RRPPUPXQZR[T[VYWW";
prog_char	gTimesItalicBold_6A[]	PROGMEM	=	"45KXUFUHWHWFUF RVFVH RUGWG RMQNOPMRMSNTPTSRZQ]P_NaLbJbIaI_K_KaJaJ` RSNSSQZP]O_ RSPRTP[O^N`Lb";
prog_char	gTimesItalicBold_6B[]	PROGMEM	=	"49G]OFI[K[ RPFJ[ RLFQFK[ RYOYNXNXPZPZNYMWMUNQROS RMSOSQTRUTYUZWZ RQUSYTZ ROSPTRZS[U[WZYW RMFPG RNFOH";
prog_char	gTimesItalicBold_6C[]	PROGMEM	=	"26LXTFQQPUPXQZR[T[VYWW RUFRQQUQZ RQFVFRTQX RRFUG RSFTH";
prog_char	gTimesItalicBold_6D[]	PROGMEM	=	"61@cAQBODMFMGNHPHSF[ RGNGSE[ RGPFTD[F[ RHSJPLNNMPMRNSPSSQ[ RRNRSP[ RRPQTO[Q[ RSSUPWNYM[M]N^P^S\\X R]N]R\\V\\Z R]P[U[X\\Z][_[aYbW";
prog_char	gTimesItalicBold_6E[]	PROGMEM	=	"42F^GQHOJMLMMNNPNSL[ RMNMSK[ RMPLTJ[L[ RNSPPRNTMVMXNYPYSWX RXNXRWVWZ RXPVUVXWZX[Z[\\Y]W";
prog_char	gTimesItalicBold_6F[]	PROGMEM	=	"46H\\QMNNLQKTKVLYMZP[S[VZXWYTYRXOWNTMQM RNOMQLTLWMY RVYWWXTXQWO RQMOONQMTMWNZP[ RS[UYVWWTWQVNTM";

prog_char	gTimesItalicBold_70[]	PROGMEM	=	"66G]HQIOKMMMNNOPOSNWKb RNNNSMWJb RNPMTIb ROTPQQORNTMVMXNYOZRZTYWWZT[R[PZOWOT RXOYQYTXWWY RVMWNXQXTWWVYT[ RFbNb RJaGb RJ`Hb RK`Lb RJaMb";
prog_char	gTimesItalicBold_71[]	PROGMEM	=	"57G\\WMQb RXMRb RWMYMSb RUTUQTNRMPMMNKQJTJVKYLZN[P[RZSYTWUT RMOLQKTKWLY RPMNOMQLTLWMZN[ RNbVb RRaOb RR`Pb RS`Tb RRaUb";
prog_char	gTimesItalicBold_72[]	PROGMEM	=	"30I[JQKOMMOMPNQPQTO[ RPNPTN[ RPPOTM[O[ RYOYNXNXPZPZNYMWMUNSPQT";
prog_char	gTimesItalicBold_73[]	PROGMEM	=	"47J[XPXOWOWQYQYOXNUMRMONNONQOSQTTUVVWX RONNQ RORQSTTVU RWVVZ RNOOQQRTSVTWVWXVZS[P[MZLYLWNWNYMYMX";
prog_char	gTimesItalicBold_74[]	PROGMEM	=	"23KYTFQQPUPXQZR[T[VYWW RUFRQQUQZ RTFVFRTQX RNMXM";
prog_char	gTimesItalicBold_75[]	PROGMEM	=	"42F^GQHOJMLMMNNPNSLX RMNMRLVLZ RMPKUKXLZN[P[RZTXVU RXMVUVXWZX[Z[\\Y]W RYMWUWZ RXMZMXTWX";
prog_char	gTimesItalicBold_76[]	PROGMEM	=	"29H\\IQJOLMNMONPPPSNX RONORNVNZ ROPMUMXNZP[R[TZVXXUYQYMXMXNYP";
prog_char	gTimesItalicBold_77[]	PROGMEM	=	"48CaDQEOGMIMJNKPKSIX RJNJRIVIZ RJPHUHXIZK[M[OZQXRU RTMRURXSZU[W[YZ[X]U^Q^M]M]N^P RUMSUSZ RTMVMTTSX";
prog_char	gTimesItalicBold_78[]	PROGMEM	=	"51G]JQLNNMPMRNSPSR RPMQNQRPVOXMZK[I[HZHXJXJZIZIY RRORRQVQY RZOZNYNYP[P[NZMXMVNTPSRRVRZS[ RPVPXQZS[U[WZYW";
prog_char	gTimesItalicBold_79[]	PROGMEM	=	"49G]HQIOKMMMNNOPOSMX RNNNRMVMZ RNPLULXMZO[Q[SZUXWT RYMU[T^RaPb RZMV[T_ RYM[MW[U_SaPbMbKaJ`J^L^L`K`K_";
prog_char	gTimesItalicBold_7A[]	PROGMEM	=	"39H\\YMXOVQNWLYK[ RXOOOMPLR RVORNONNO RVORMOMMOLR RLYUYWXXV RNYRZUZVY RNYR[U[WYXV";
prog_char	gTimesItalicBold_7B[]	PROGMEM	=	"40KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
prog_char	gTimesItalicBold_7C[]	PROGMEM	=	" 3NVRBRb";
prog_char	gTimesItalicBold_7D[]	PROGMEM	=	"40KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
prog_char	gTimesItalicBold_7E[]	PROGMEM	=	"24F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
prog_char	gTimesItalicBold_7F[]	PROGMEM	=	"35JZJFJ[K[KFLFL[M[MFNFN[O[OFPFP[Q[QFRFR[S[SFTFT[U[UFVFV[W[WFXFX[Y[YFZFZ[";


PGM_P gHershyTimesItalicBoldFontTable[]	PROGMEM =
{

	gTimesItalicBold_00,
	gTimesItalicBold_20,
	gTimesItalicBold_21,
	gTimesItalicBold_22,
	gTimesItalicBold_23,
	gTimesItalicBold_24,
	gTimesItalicBold_25,
	gTimesItalicBold_26,
	gTimesItalicBold_27,
	gTimesItalicBold_28,
	gTimesItalicBold_29,
	gTimesItalicBold_2A,
	gTimesItalicBold_2B,
	gTimesItalicBold_2C,
	gTimesItalicBold_2D,
	gTimesItalicBold_2E,
	gTimesItalicBold_2F,

	gTimesItalicBold_30,
	gTimesItalicBold_31,
	gTimesItalicBold_32,
	gTimesItalicBold_33,
	gTimesItalicBold_34,
	gTimesItalicBold_35,
	gTimesItalicBold_36,
	gTimesItalicBold_37,
	gTimesItalicBold_38,
	gTimesItalicBold_39,
	gTimesItalicBold_3A,
	gTimesItalicBold_3B,
	gTimesItalicBold_3C,
	gTimesItalicBold_3D,
	gTimesItalicBold_3E,
	gTimesItalicBold_3F,

	gTimesItalicBold_40,
	gTimesItalicBold_41,
	gTimesItalicBold_42,
	gTimesItalicBold_43,
	gTimesItalicBold_44,
	gTimesItalicBold_45,
	gTimesItalicBold_46,
	gTimesItalicBold_47,
	gTimesItalicBold_48,
	gTimesItalicBold_49,
	gTimesItalicBold_4A,
	gTimesItalicBold_4B,
	gTimesItalicBold_4C,
	gTimesItalicBold_4D,
	gTimesItalicBold_4E,
	gTimesItalicBold_4F,

	gTimesItalicBold_50,
	gTimesItalicBold_51,
	gTimesItalicBold_52,
	gTimesItalicBold_53,
	gTimesItalicBold_54,
	gTimesItalicBold_55,
	gTimesItalicBold_56,
	gTimesItalicBold_57,
	gTimesItalicBold_58,
	gTimesItalicBold_59,
	gTimesItalicBold_5A,
	gTimesItalicBold_5B,
	gTimesItalicBold_5C,
	gTimesItalicBold_5D,
	gTimesItalicBold_5E,
	gTimesItalicBold_5F,

	gTimesItalicBold_60,
	gTimesItalicBold_61,
	gTimesItalicBold_62,
	gTimesItalicBold_63,
	gTimesItalicBold_64,
	gTimesItalicBold_65,
	gTimesItalicBold_66,
	gTimesItalicBold_67,
	gTimesItalicBold_68,
	gTimesItalicBold_69,
	gTimesItalicBold_6A,
	gTimesItalicBold_6B,
	gTimesItalicBold_6C,
	gTimesItalicBold_6D,
	gTimesItalicBold_6E,
	gTimesItalicBold_6F,

	gTimesItalicBold_70,
	gTimesItalicBold_71,
	gTimesItalicBold_72,
	gTimesItalicBold_73,
	gTimesItalicBold_74,
	gTimesItalicBold_75,
	gTimesItalicBold_76,
	gTimesItalicBold_77,
	gTimesItalicBold_78,
	gTimesItalicBold_79,
	gTimesItalicBold_7A,
	gTimesItalicBold_7B,
	gTimesItalicBold_7C,
	gTimesItalicBold_7D,
	gTimesItalicBold_7E,
	gTimesItalicBold_7F

};
