//*******************************************************************************
//*	timesr.jhf		Times Roman
//*	formated for use with Arduino Processing 
//*	by Mark Sproul
//*******************************************************************************
//*	Jan 24,	2009	<MLS>	Formated Hershey Times Roman for Arduino
//*******************************************************************************
//#include	"HersheyTimesRoman.h"

prog_char	gTimesRoman_00[]	PROGMEM	=	"Times Roman";

prog_char	gTimesRoman_20[]	PROGMEM	=	" 1JZ";
prog_char	gTimesRoman_21[]	PROGMEM	=	"15MWRFQHRTSHRF RRHRN RRYQZR[SZRY";
prog_char	gTimesRoman_22[]	PROGMEM	=	"22I[NFMGMM RNGMM RNFOGMM RWFVGVM RWGVM RWFXGVM";
prog_char	gTimesRoman_23[]	PROGMEM	=	"12H]SBLb RYBRb RLOZO RKUYU";
prog_char	gTimesRoman_24[]	PROGMEM	=	"42H\\PBP_ RTBT_ RXIWJXKYJYIWGTFPFMGKIKKLMMNOOUQWRYT RKKMMONUPWQXRYTYXWZT[P[MZKXKWLVMWLX";
prog_char	gTimesRoman_25[]	PROGMEM	=	"32F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT";
prog_char	gTimesRoman_26[]	PROGMEM	=	"49F_[NZO[P\\O\\N[MZMYNXPVUTXRZP[M[JZIXIUJSPORMSKSIRGPFNGMIMKNNPQUXWZZ[[[\\Z\\Y RM[KZJXJUKSMQ RMKNMVXXZZ[";
prog_char	gTimesRoman_27[]	PROGMEM	=	" 6NVRFQM RSFQM";
prog_char	gTimesRoman_28[]	PROGMEM	=	"20KYVBTDRGPKOPOTPYR]T`Vb RTDRHQKPPPTQYR\\T`";
prog_char	gTimesRoman_29[]	PROGMEM	=	"20KYNBPDRGTKUPUTTYR]P`Nb RPDRHSKTPTTSYR\\P`";
prog_char	gTimesRoman_2A[]	PROGMEM	=	" 9JZRLRX RMOWU RWOMU";
prog_char	gTimesRoman_2B[]	PROGMEM	=	" 6E_RIR[ RIR[R";
prog_char	gTimesRoman_2C[]	PROGMEM	=	" 8NVSWRXQWRVSWSYQ[";
prog_char	gTimesRoman_2D[]	PROGMEM	=	" 3E_IR[R";
prog_char	gTimesRoman_2E[]	PROGMEM	=	" 6NVRVQWRXSWRV";
prog_char	gTimesRoman_2F[]	PROGMEM	=	" 3G][BIb";

prog_char	gTimesRoman_30[]	PROGMEM	=	"40H\\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF RQFOGNHMJLOLRMWNYOZQ[ RS[UZVYWWXRXOWJVHUGSF";
prog_char	gTimesRoman_31[]	PROGMEM	=	"11H\\NJPISFS[ RRGR[ RN[W[";
prog_char	gTimesRoman_32[]	PROGMEM	=	"45H\\LJMKLLKKKJLHMGPFTFWGXHYJYLXNUPPRNSLUKXK[ RTFVGWHXJXLWNTPPR RKYLXNXSZVZXYYX RNXS[W[XZYXYV";
prog_char	gTimesRoman_33[]	PROGMEM	=	"47H\\LJMKLLKKKJLHMGPFTFWGXIXLWNTOQO RTFVGWIWLVNTO RTOVPXRYTYWXYWZT[P[MZLYKWKVLUMVLW RWQXTXWWYVZT[";
prog_char	gTimesRoman_34[]	PROGMEM	=	"13H\\THT[ RUFU[ RUFJUZU RQ[X[";
prog_char	gTimesRoman_35[]	PROGMEM	=	"39H\\MFKP RKPMNPMSMVNXPYSYUXXVZS[P[MZLYKWKVLUMVLW RSMUNWPXSXUWXUZS[ RMFWF RMGRGWF";
prog_char	gTimesRoman_36[]	PROGMEM	=	"48H\\WIVJWKXJXIWGUFRFOGMILKKOKULXNZQ[S[VZXXYUYTXQVOSNRNOOMQLT RRFPGNIMKLOLUMXOZQ[ RS[UZWXXUXTWQUOSN";
prog_char	gTimesRoman_37[]	PROGMEM	=	"31H\\KFKL RKJLHNFPFUIWIXHYF RLHNGPGUI RYFYIXLTQSSRVR[ RXLSQRSQVQ[";
prog_char	gTimesRoman_38[]	PROGMEM	=	"63H\\PFMGLILLMNPOTOWNXLXIWGTFPF RPFNGMIMLNNPO RTOVNWLWIVGTF RPOMPLQKSKWLYMZP[T[WZXYYWYSXQWPTO RPONPMQLSLWMYNZP[ RT[VZWYXWXSWQVPTO";
prog_char	gTimesRoman_39[]	PROGMEM	=	"48H\\XMWPURRSQSNRLPKMKLLINGQFSFVGXIYLYRXVWXUZR[O[MZLXLWMVNWMX RQSORMPLMLLMIOGQF RSFUGWIXLXRWVVXTZR[";
prog_char	gTimesRoman_3A[]	PROGMEM	=	"12NVROQPRQSPRO RRVQWRXSWRV";
prog_char	gTimesRoman_3B[]	PROGMEM	=	"14NVROQPRQSPRO RSWRXQWRVSWSYQ[";
prog_char	gTimesRoman_3C[]	PROGMEM	=	" 4F^ZIJRZ[";
prog_char	gTimesRoman_3D[]	PROGMEM	=	" 6E_IO[O RIU[U";
prog_char	gTimesRoman_3E[]	PROGMEM	=	" 4F^JIZRJ[";
prog_char	gTimesRoman_3F[]	PROGMEM	=	"32I[MJNKMLLKLJMHNGPFSFVGWHXJXLWNVORQRT RSFUGVHWJWLVNTP RRYQZR[SZRY";

prog_char	gTimesRoman_40[]	PROGMEM	=	"56E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
prog_char	gTimesRoman_41[]	PROGMEM	=	"18H\\RFK[ RRFY[ RRIX[ RMUVU RI[O[ RU[[[";
prog_char	gTimesRoman_42[]	PROGMEM	=	"45G]LFL[ RMFM[ RIFUFXGYHZJZLYNXOUP RUFWGXHYJYLXNWOUP RMPUPXQYRZTZWYYXZU[I[ RUPWQXRYTYWXYWZU[";
prog_char	gTimesRoman_43[]	PROGMEM	=	"32G\\XIYLYFXIVGSFQFNGLIKKJNJSKVLXNZQ[S[VZXXYV RQFOGMILKKNKSLVMXOZQ[";
prog_char	gTimesRoman_44[]	PROGMEM	=	"30G]LFL[ RMFM[ RIFSFVGXIYKZNZSYVXXVZS[I[ RSFUGWIXKYNYSXVWXUZS[";
prog_char	gTimesRoman_45[]	PROGMEM	=	"22G\\LFL[ RMFM[ RSLST RIFYFYLXF RMPSP RI[Y[YUX[";
prog_char	gTimesRoman_46[]	PROGMEM	=	"20G[LFL[ RMFM[ RSLST RIFYFYLXF RMPSP RI[P[";
prog_char	gTimesRoman_47[]	PROGMEM	=	"40G^XIYLYFXIVGSFQFNGLIKKJNJSKVLXNZQ[S[VZXX RQFOGMILKKNKSLVMXOZQ[ RXSX[ RYSY[ RUS\\S";
prog_char	gTimesRoman_48[]	PROGMEM	=	"27F^KFK[ RLFL[ RXFX[ RYFY[ RHFOF RUF\\F RLPXP RH[O[ RU[\\[";
prog_char	gTimesRoman_49[]	PROGMEM	=	"12MXRFR[ RSFS[ ROFVF RO[V[";
prog_char	gTimesRoman_4A[]	PROGMEM	=	"20KZUFUWTZR[P[NZMXMVNUOVNW RTFTWSZR[ RQFXF";
prog_char	gTimesRoman_4B[]	PROGMEM	=	"27F\\KFK[ RLFL[ RYFLS RQOY[ RPOX[ RHFOF RUF[F RH[O[ RU[[[";
prog_char	gTimesRoman_4C[]	PROGMEM	=	"14I[NFN[ ROFO[ RKFRF RK[Z[ZUY[";
prog_char	gTimesRoman_4D[]	PROGMEM	=	"30F_KFK[ RLFRX RKFR[ RYFR[ RYFY[ RZFZ[ RHFLF RYF]F RH[N[ RV[][";
prog_char	gTimesRoman_4E[]	PROGMEM	=	"21G^LFL[ RMFYY RMHY[ RYFY[ RIFMF RVF\\F RI[O[";
prog_char	gTimesRoman_4F[]	PROGMEM	=	"44G]QFNGLIKKJOJRKVLXNZQ[S[VZXXYVZRZOYKXIVGSFQF RQFOGMILKKOKRLVMXOZQ[ RS[UZWXXVYRYOXKWIUGSF";

prog_char	gTimesRoman_50[]	PROGMEM	=	"29G]LFL[ RMFM[ RIFUFXGYHZJZMYOXPUQMQ RUFWGXHYJYMXOWPUQ RI[P[";
prog_char	gTimesRoman_51[]	PROGMEM	=	"64G]QFNGLIKKJOJRKVLXNZQ[S[VZXXYVZRZOYKXIVGSFQF RQFOGMILKKOKRLVMXOZQ[ RS[UZWXXVYRYOXKWIUGSF RNYNXOVQURUTVUXV_W`Y`Z^Z] RUXV\\W^X_Y_Z^";
prog_char	gTimesRoman_52[]	PROGMEM	=	"45G]LFL[ RMFM[ RIFUFXGYHZJZLYNXOUPMP RUFWGXHYJYLXNWOUP RI[P[ RRPTQURXYYZZZ[Y RTQUSWZX[Z[[Y[X";
prog_char	gTimesRoman_53[]	PROGMEM	=	"34H\\XIYFYLXIVGSFPFMGKIKKLMMNOOUQWRYT RKKMMONUPWQXRYTYXWZT[Q[NZLXKUK[LX";
prog_char	gTimesRoman_54[]	PROGMEM	=	"16I\\RFR[ RSFS[ RLFKLKFZFZLYF RO[V[";
prog_char	gTimesRoman_55[]	PROGMEM	=	"23F^KFKULXNZQ[S[VZXXYUYF RLFLUMXOZQ[ RHFOF RVF\\F";
prog_char	gTimesRoman_56[]	PROGMEM	=	"15H\\KFR[ RLFRX RYFR[ RIFOF RUF[F";
prog_char	gTimesRoman_57[]	PROGMEM	=	"24F^JFN[ RKFNV RRFN[ RRFV[ RSFVV RZFV[ RGFNF RWF]F";
prog_char	gTimesRoman_58[]	PROGMEM	=	"21H\\KFX[ RLFY[ RYFK[ RIFOF RUF[F RI[O[ RU[[[";
prog_char	gTimesRoman_59[]	PROGMEM	=	"20H]KFRQR[ RLFSQS[ RZFSQ RIFOF RVF\\F RO[V[";
prog_char	gTimesRoman_5A[]	PROGMEM	=	"16H\\XFK[ RYFL[ RLFKLKFYF RK[Y[YUX[";
prog_char	gTimesRoman_5B[]	PROGMEM	=	"12KYOBOb RPBPb ROBVB RObVb";
prog_char	gTimesRoman_5C[]	PROGMEM	=	" 3KYKFY^";
prog_char	gTimesRoman_5D[]	PROGMEM	=	"12KYTBTb RUBUb RNBUB RNbUb";
prog_char	gTimesRoman_5E[]	PROGMEM	=	" 8G]JTROZT RJTRPZT";
prog_char	gTimesRoman_5F[]	PROGMEM	=	" 3H\\Hb\\b";

prog_char	gTimesRoman_60[]	PROGMEM	=	" 7LXPFUL RPFOGUL";
prog_char	gTimesRoman_61[]	PROGMEM	=	"39I]NONPMPMONNPMTMVNWOXQXXYZZ[ RWOWXXZZ[[[ RWQVRPSMTLVLXMZP[S[UZWX RPSNTMVMXNZP[";
prog_char	gTimesRoman_62[]	PROGMEM	=	"33G\\LFL[ RMFM[ RMPONQMSMVNXPYSYUXXVZS[Q[OZMX RSMUNWPXSXUWXUZS[ RIFMF";
prog_char	gTimesRoman_63[]	PROGMEM	=	"28H[WPVQWRXQXPVNTMQMNNLPKSKULXNZQ[S[VZXX RQMONMPLSLUMXOZQ[";
prog_char	gTimesRoman_64[]	PROGMEM	=	"36H]WFW[ RXFX[ RWPUNSMQMNNLPKSKULXNZQ[S[UZWX RQMONMPLSLUMXOZQ[ RTFXF RW[[[";
prog_char	gTimesRoman_65[]	PROGMEM	=	"31H[LSXSXQWOVNTMQMNNLPKSKULXNZQ[S[VZXX RWSWPVN RQMONMPLSLUMXOZQ[";
prog_char	gTimesRoman_66[]	PROGMEM	=	"22KXUGTHUIVHVGUFSFQGPIP[ RSFRGQIQ[ RMMUM RM[T[";
prog_char	gTimesRoman_67[]	PROGMEM	=	"60I\\QMONNOMQMSNUOVQWSWUVVUWSWQVOUNSMQM RONNPNTOV RUVVTVPUN RVOWNYMYNWN RNUMVLXLYM[P\\U\\X]Y^ RLYMZP[U[X\\Y^Y_XaUbObLaK_K^L\\O[";
prog_char	gTimesRoman_68[]	PROGMEM	=	"28G]LFL[ RMFM[ RMPONRMTMWNXPX[ RTMVNWPW[ RIFMF RI[P[ RT[[[";
prog_char	gTimesRoman_69[]	PROGMEM	=	"18MXRFQGRHSGRF RRMR[ RSMS[ ROMSM RO[V[";
prog_char	gTimesRoman_6A[]	PROGMEM	=	"25MXSFRGSHTGSF RTMT_SaQbObNaN`O_P`Oa RSMS_RaQb RPMTM";
prog_char	gTimesRoman_6B[]	PROGMEM	=	"27G\\LFL[ RMFM[ RWMMW RRSX[ RQSW[ RIFMF RTMZM RI[P[ RT[Z[";
prog_char	gTimesRoman_6C[]	PROGMEM	=	"12MXRFR[ RSFS[ ROFSF RO[V[";
prog_char	gTimesRoman_6D[]	PROGMEM	=	"44BcGMG[ RHMH[ RHPJNMMOMRNSPS[ ROMQNRPR[ RSPUNXMZM]N^P^[ RZM\\N]P][ RDMHM RD[K[ RO[V[ RZ[a[";
prog_char	gTimesRoman_6E[]	PROGMEM	=	"28G]LML[ RMMM[ RMPONRMTMWNXPX[ RTMVNWPW[ RIMMM RI[P[ RT[[[";
prog_char	gTimesRoman_6F[]	PROGMEM	=	"36H\\QMNNLPKSKULXNZQ[S[VZXXYUYSXPVNSMQM RQMONMPLSLUMXOZQ[ RS[UZWXXUXSWPUNSM";

prog_char	gTimesRoman_70[]	PROGMEM	=	"36G\\LMLb RMMMb RMPONQMSMVNXPYSYUXXVZS[Q[OZMX RSMUNWPXSXUWXUZS[ RIMMM RIbPb";
prog_char	gTimesRoman_71[]	PROGMEM	=	"33H\\WMWb RXMXb RWPUNSMQMNNLPKSKULXNZQ[S[UZWX RQMONMPLSLUMXOZQ[ RTb[b";
prog_char	gTimesRoman_72[]	PROGMEM	=	"23IZNMN[ ROMO[ ROSPPRNTMWMXNXOWPVOWN RKMOM RK[R[";
prog_char	gTimesRoman_73[]	PROGMEM	=	"32J[WOXMXQWOVNTMPMNNMOMQNRPSUUWVXW RMPNQPRUTWUXVXYWZU[Q[OZNYMWM[NY";
prog_char	gTimesRoman_74[]	PROGMEM	=	"16KZPFPWQZS[U[WZXX RQFQWRZS[ RMMUM";
prog_char	gTimesRoman_75[]	PROGMEM	=	"28G]LMLXMZP[R[UZWX RMMMXNZP[ RWMW[ RXMX[ RIMMM RTMXM RW[[[";
prog_char	gTimesRoman_76[]	PROGMEM	=	"15I[LMR[ RMMRY RXMR[ RJMPM RTMZM";
prog_char	gTimesRoman_77[]	PROGMEM	=	"24F^JMN[ RKMNX RRMN[ RRMV[ RSMVX RZMV[ RGMNM RWM]M";
prog_char	gTimesRoman_78[]	PROGMEM	=	"21H\\LMW[ RMMX[ RXML[ RJMPM RTMZM RJ[P[ RT[Z[";
prog_char	gTimesRoman_79[]	PROGMEM	=	"22H[LMR[ RMMRY RXMR[P_NaLbKbJaK`La RJMPM RTMZM";
prog_char	gTimesRoman_7A[]	PROGMEM	=	"16I[WML[ RXMM[ RMMLQLMXM RL[X[XWW[";
prog_char	gTimesRoman_7B[]	PROGMEM	=	"40KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
prog_char	gTimesRoman_7C[]	PROGMEM	=	" 3NVRBRb";
prog_char	gTimesRoman_7D[]	PROGMEM	=	"40KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
prog_char	gTimesRoman_7E[]	PROGMEM	=	"24F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
prog_char	gTimesRoman_7F[]	PROGMEM	=	"35JZJFJ[K[KFLFL[M[MFNFN[O[OFPFP[Q[QFRFR[S[SFTFT[U[UFVFV[W[WFXFX[Y[YFZFZ[";


PGM_P gHershyTimesRomanFontTable[]	PROGMEM =
{

	gTimesRoman_00,
	gTimesRoman_20,
	gTimesRoman_21,
	gTimesRoman_22,
	gTimesRoman_23,
	gTimesRoman_24,
	gTimesRoman_25,
	gTimesRoman_26,
	gTimesRoman_27,
	gTimesRoman_28,
	gTimesRoman_29,
	gTimesRoman_2A,
	gTimesRoman_2B,
	gTimesRoman_2C,
	gTimesRoman_2D,
	gTimesRoman_2E,
	gTimesRoman_2F,

	gTimesRoman_30,
	gTimesRoman_31,
	gTimesRoman_32,
	gTimesRoman_33,
	gTimesRoman_34,
	gTimesRoman_35,
	gTimesRoman_36,
	gTimesRoman_37,
	gTimesRoman_38,
	gTimesRoman_39,
	gTimesRoman_3A,
	gTimesRoman_3B,
	gTimesRoman_3C,
	gTimesRoman_3D,
	gTimesRoman_3E,
	gTimesRoman_3F,

	gTimesRoman_40,
	gTimesRoman_41,
	gTimesRoman_42,
	gTimesRoman_43,
	gTimesRoman_44,
	gTimesRoman_45,
	gTimesRoman_46,
	gTimesRoman_47,
	gTimesRoman_48,
	gTimesRoman_49,
	gTimesRoman_4A,
	gTimesRoman_4B,
	gTimesRoman_4C,
	gTimesRoman_4D,
	gTimesRoman_4E,
	gTimesRoman_4F,

	gTimesRoman_50,
	gTimesRoman_51,
	gTimesRoman_52,
	gTimesRoman_53,
	gTimesRoman_54,
	gTimesRoman_55,
	gTimesRoman_56,
	gTimesRoman_57,
	gTimesRoman_58,
	gTimesRoman_59,
	gTimesRoman_5A,
	gTimesRoman_5B,
	gTimesRoman_5C,
	gTimesRoman_5D,
	gTimesRoman_5E,
	gTimesRoman_5F,

	gTimesRoman_60,
	gTimesRoman_61,
	gTimesRoman_62,
	gTimesRoman_63,
	gTimesRoman_64,
	gTimesRoman_65,
	gTimesRoman_66,
	gTimesRoman_67,
	gTimesRoman_68,
	gTimesRoman_69,
	gTimesRoman_6A,
	gTimesRoman_6B,
	gTimesRoman_6C,
	gTimesRoman_6D,
	gTimesRoman_6E,
	gTimesRoman_6F,

	gTimesRoman_70,
	gTimesRoman_71,
	gTimesRoman_72,
	gTimesRoman_73,
	gTimesRoman_74,
	gTimesRoman_75,
	gTimesRoman_76,
	gTimesRoman_77,
	gTimesRoman_78,
	gTimesRoman_79,
	gTimesRoman_7A,
	gTimesRoman_7B,
	gTimesRoman_7C,
	gTimesRoman_7D,
	gTimesRoman_7E,
	gTimesRoman_7F

};
