//*******************************************************************************
//*	cursive.jhf		Cursive
//*	formated for use with Arduino Processing 
//*	by Mark Sproul
//*******************************************************************************
//*	Feb 18,	2009	<MLS> Formated Hershey Gothic Italian for Arduino
//*******************************************************************************
//#include	"HersheyGothicItalian.h"


prog_char	gGothicItilian_00[]	PROGMEM	=	"Gothic Italian";

prog_char	gGothicItilian_20[]	PROGMEM	=	" 1JZ";
prog_char	gGothicItilian_21[]	PROGMEM	=	"30LXRFQGOHQIRT RRISHRGQHRIRT RRFSGUHSIRT RRXPZR[TZRX RRYQZSZRY";
prog_char	gGothicItilian_22[]	PROGMEM	=	"22I[NFMGMM RNGMM RNFOGMM RWFVGVM RWGVM RWFXGVM";
prog_char	gGothicItilian_23[]	PROGMEM	=	"12H]SBLb RYBRb RLOZO RKUYU";
prog_char	gGothicItilian_24[]	PROGMEM	=	"60H\\PBP_ RTBT_ RTFVGWIWKYJXHWGTFPFMGKIKLLNOPURWSXUXXWZ RXJWH RLLMNOOUQWRXT RMYLW RMGLILKMMONUPXRYTYWXYWZT[P[MZLYKWMVMXNZP[";
prog_char	gGothicItilian_25[]	PROGMEM	=	"32F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT";
prog_char	gGothicItilian_26[]	PROGMEM	=	"62E_YNZO[O\\N RXOYP[P RXPYQZQ[P\\N RYNST RRUL[HVNP ROOSKOFJLPRTXVZX[Z[[Z\\X RLZIV RRKOG RKLPQTWVYXZ[Z RMZIU RRLNG RKKQQUWVXXY[Y\\X";
prog_char	gGothicItilian_27[]	PROGMEM	=	"11NWSFRGRM RSGRM RSFTGRM";
prog_char	gGothicItilian_28[]	PROGMEM	=	"27KYUBSDQGOKNPNTOYQ]S`Ub RQHPKOOOUPYQ\\ RSDRFQIPOPUQ[R^S`";
prog_char	gGothicItilian_29[]	PROGMEM	=	"27KYOBQDSGUKVPVTUYS]Q`Ob RSHTKUOUUTYS\\ RQDRFSITOTUS[R^Q`";
prog_char	gGothicItilian_2A[]	PROGMEM	=	"39JZRFQGSQRR RRFRR RRFSGQQRR RMINIVOWO RMIWO RMIMJWNWO RWIVINOMO RWIMO RWIWJMNMO";
prog_char	gGothicItilian_2B[]	PROGMEM	=	"16F_RIRZSZ RRISISZ RJQ[Q[R RJQJR[R";
prog_char	gGothicItilian_2C[]	PROGMEM	=	"14LXR^R\\PZRXSZS\\R^P_ RRYQZR[RY";
prog_char	gGothicItilian_2D[]	PROGMEM	=	" 3E_IR[R";
prog_char	gGothicItilian_2E[]	PROGMEM	=	"11LXRXPZR[TZRX RRYQZSZRY";
prog_char	gGothicItilian_2F[]	PROGMEM	=	" 8G^[BIbJb R[B\\BJb";

prog_char	gGothicItilian_30[]	PROGMEM	=	"42H\\LHLXJY RMIMXPZ RNHNXPYQZ RLHNHSGUF RSGTHVIVY RTGWIWX RUFVGXHZHXIXY RJYLYNZO[QZVYXY";
prog_char	gGothicItilian_31[]	PROGMEM	=	"27H\\OHPIQKQXOY RQIPHQGRIRYTZ ROHRFSHSXUYVY ROYPYRZS[TZVY";
prog_char	gGothicItilian_32[]	PROGMEM	=	"48H\\LHNHPGQFSGVHXH RPHRG RLHNIPIRHSG RVHVP RWIWO RXHXPQPNQLSKVK[ RK[OYSXVXZY RNZQYVYYZ RK[PZUZX[ZY";
prog_char	gGothicItilian_33[]	PROGMEM	=	"57H\\LHMHOGPFRGVHXH ROHQG RLHNIPIRG RVHVO RWIWN RXHXOVOSPQQ RQPSQVRXRXY RWSWX RVRVY RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY";
prog_char	gGothicItilian_34[]	PROGMEM	=	"41H\\UFKPKUTU RVUZU[V[TZU RLPLT RMNMU RTGTXRY RUJVHUGUYWZ RUFWHVJVXXYYY RRYSYUZV[WZYY";
prog_char	gGothicItilian_35[]	PROGMEM	=	"53H\\LFLO RLFXF RMGVG RLHUHWGXF RVLUMSNOOLO RSNTNVOVY RUMWNWX RVLWMYNZNXOXY RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY";
prog_char	gGothicItilian_36[]	PROGMEM	=	"59H\\LHLXJY RMIMXPZ RNHNXPYQZ RLHNHRGTFUGWHXH RSGUH RRGTIVIXH RNPOPSOUNVM RSOTOVPVY RUNWPWX RVMWNYOZOXPXY RJYLYNZO[QZVYXY";
prog_char	gGothicItilian_37[]	PROGMEM	=	"38H\\KHMFPGUGZF RLGOHTHWG RKHOIRIVHZF RZFYHWKSOQRPUPXQ[ RRQQTQWRZ RUMSPRSRVSYQ[";
prog_char	gGothicItilian_38[]	PROGMEM	=	"71H\\LILO RMJMN RNINO RLINISHUGVF RSHTHVIVO RUGWHWN RVFWGYHZHXIXO RLONOVRXR RXOVONRLR RLRLXJY RMSMXPZ RNRNXPYQZ RVRVY RWSWX RXRXY RJYLYNZO[QZVYXY";
prog_char	gGothicItilian_39[]	PROGMEM	=	"60H\\LHLQJR RMIMROS RNHNQPRQR RLHNHSGUF RSGTHVIVY RTGWIWX RUFVGXHZHXIXY RJRKRMSNTOSQRUQVQ RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY";
prog_char	gGothicItilian_3A[]	PROGMEM	=	"22LXRMPORPTORM RRNQOSORN RRXPZR[TZRX RRYQZSZRY";
prog_char	gGothicItilian_3B[]	PROGMEM	=	"25LXRMPORPTORM RRNQOSORN RR^R\\PZRXSZS\\R^P_ RRYQZR[RY";
prog_char	gGothicItilian_3C[]	PROGMEM	=	" 4F^ZIJRZ[";
prog_char	gGothicItilian_3D[]	PROGMEM	=	"16F_JM[M[N RJMJN[N RJU[U[V RJUJV[V";
prog_char	gGothicItilian_3E[]	PROGMEM	=	" 4F^JIZRJ[";
prog_char	gGothicItilian_3F[]	PROGMEM	=	"51I[LJMHNGQFSFVGWHXJXLWNUPSQ RMJNH RVHWIWMVN RLJNKNIOGQF RSFUGVIVMUOSQ RRQRTSQQQRT RRXPZR[TZRX RRYQZSZRY";

prog_char	gGothicItilian_40[]	PROGMEM	=	"56E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
prog_char	gGothicItilian_41[]	PROGMEM	=	"52E_NHLIJKIMHPHSIUKV RJLIOISJU RNHLJKLJOJRKVKXJZH[ RVHXHXYVY RYHYY RZGZZ RHFKGQHVHZG\\F RJPXP RH[KZQYVYZZ\\[";
prog_char	gGothicItilian_42[]	PROGMEM	=	"65E_LGLZ RMGMZ RPFNGNZP[ RHJJHLGPFUFXGZIZKYM RXHYIYKXM RUFWGXIXKWL RQUOTNRNPONPMSLVLYM[O\\Q\\T[WYYWZT[P[LZJYHW RZO[Q[UZW RVLYNZQZUYXWZ";
prog_char	gGothicItilian_43[]	PROGMEM	=	"60E_\\F[HZJXHVGSFQFNGLHJJILHOHRIUJWLYNZQ[S[VZXYZW[Y\\[ R[HZMZT[Y RZKYJ RZNYKXIVG RJKINISJV RNGLIKKJNJSKVLXNZ RYWZV RVZXXYVZS";
prog_char	gGothicItilian_44[]	PROGMEM	=	"46E_KGKZ RLGLZ RNFMGMZN[ RHKIIKGNFSFVGXHZJ[L\\O\\R[UZWXYVZS[N[KZIXHV RZK[N[SZV RVGXIYKZNZSYVXXVZ";
prog_char	gGothicItilian_45[]	PROGMEM	=	"86E_\\F[HZJXHVGSFQFNGLHJJILHOHRIUJWLYNZQ[S[VZXYZW[Y\\[ R[HZMZT[Y RZKYJ RZMXIVG RJKINISJV RNGLIKKJNJSKVLXNZ RYWZV RVZXXYVZS RJPKONOUQXQZP RPPRQURWRYQ RMORRUSWSYRZP RZMYLXLWMXNYM";
prog_char	gGothicItilian_46[]	PROGMEM	=	"69E_JHJZ RMGKHKY ROFMGLILYNY RHJJHLGOFSFVGXHYI\\F R\\F[HZLZO[S\\U RZIYK RVGXIYLZO RLPMOOOTPWPYO RQPTQVQXP RNOTRVRXQYOYLXKWKVLWMXL RH[JZNYSYYZ\\[";
prog_char	gGothicItilian_47[]	PROGMEM	=	"90E_\\F[HZJXHVGSFQFNGLHJJILHOHRIUJWLYNZQ[T[VZXYYXZV[Y\\[ R[HZMZT[Y RZKYJ RZNYKXIVG RJKINISJV RNGLIKKJNJSKVLXNZ RXXYVYR RVZWYXVXQ RKSLRMSLTKTJS RJPKNMMOMRNUPWQ RKOMNONROTP RJPLOOOUQYQZP";
prog_char	gGothicItilian_48[]	PROGMEM	=	"50E_JGJZH[ RKHKZ RNHLHLZ RHFJGNHSHYG\\F RLPMNOLRKVKYL[N\\Q\\T[UYV RZN[P[SZU RVKXLYMZOZSYVYXZZ\\[ RH[LZPZU[";
prog_char	gGothicItilian_49[]	PROGMEM	=	"23E_QIQY RRJRX RSISY RHFLHPITIXH\\F RH[KZOYUYYZ\\[";
prog_char	gGothicItilian_4A[]	PROGMEM	=	"42E_TIVIVXUZS[ RWIWXVY RXHXY RHFLHPITIXH\\F RIOHQHUIXKZN[S[VZXYZW\\T RIUJXKY RHSJUKXLZN[";
prog_char	gGothicItilian_4B[]	PROGMEM	=	"70E_JGJZH[ RKHKZ RNHLHLZ RHFJGNHSHYG\\F RLPMNOLRKUKXLYMYOXPSRQSPTPUQVRUQT RWLXMXOWP RUKWMWOVPSR RSRVRYSZUZWYX RWSYUYW RSRVSXUYXZZ[[\\[ RH[LZPZU[";
prog_char	gGothicItilian_4C[]	PROGMEM	=	"45E_JGJZ RKHKY RNHLHLYNY R\\KZNYPXSXUYW[X RZOYRYUZW R\\K[MZQZT[X\\[ RHFJGNHSHYG\\F RH[JZNYSYYZ\\[";
prog_char	gGothicItilian_4D[]	PROGMEM	=	"68E_QIQY RRJRX RSISY RNYLWJVIUHRHMIJKHMGPFTFWGYH[J\\M\\R[UZVXWVY RJUIRIMJJ RLWKUJRJLKIMG RZJ[M[RZU RWGYIZLZRYUXW RHFLHPITIXH\\F RH[KZOYUYYZ\\[";
prog_char	gGothicItilian_4E[]	PROGMEM	=	"48E_JHJZH[ RLHKIKZ ROFMGLILZ RHJJHLGOFSFVGXHZJ[L\\O\\S[UYV RZK[N[RZU RVGXIYKZNZRYVYXZZ[[\\[ RH[LZPZU[";
prog_char	gGothicItilian_4F[]	PROGMEM	=	"54E_QFNGLHJJILHOHRIUJWLYNZQ[S[VZXYZW[U\\R\\O[LZJXHVGSFQF RJKINISJV RNGLIKKJNJSKVLXNZ RZV[S[NZK RVZXXYVZSZNYKXIVG";

prog_char	gGothicItilian_50[]	PROGMEM	=	"51E_JIJZ RMHKJKY RQFOGMILKLYNY RHKJINGQFTFWGYH[J\\M\\O[RYTVURUOTMRLO RZJ[L[PZR RWGYIZLZPYSVU RH[JZNYSYYZ\\[";
prog_char	gGothicItilian_51[]	PROGMEM	=	"74E_QFNGLHJJILHOHRIUJWLYNZQ[S[VZXYZW[U\\R\\O[LZJXHVGSFQF RJKINISJV RNGLIKKJNJSKVLXNZ RZV[S[NZK RVZXXYVZSZNYKXIVG RJSKUNVTW[W\\X\\Z[[[Z\\Y RPWRW RKUNWQXSXTW";
prog_char	gGothicItilian_52[]	PROGMEM	=	"69E_JIJZH[ RKIKZ RLHLZ RHKJILHNGQFUFYG[I\\K\\N[PZQ RYHZI[K[NZP RUFWGYIZKZOYQ RXRUSRSPRPPROUOXPZR\\U\\W[XZX RXQYR[V[WZT RTOVPXRYTZX[Z\\[ RH[LZPZU[";
prog_char	gGothicItilian_53[]	PROGMEM	=	"94E_TFZG\\F[H[JYHWGTFPFMGJJIMIOJRLTOURUTTUSVQVP R[GZH[J RJPKRLSOTRTTS RKIJKJNKPMRPSRSTRVPWOXO RLQMQNPPNRMUMWNYPZRZUYXWZ RPMRLULXMZO[R[UZW RIWJYIZ RNPNOOMPLRKUKXL[O\\R\\T[WYYWZT[P[MZKYIWIYH[JZP[";
prog_char	gGothicItilian_54[]	PROGMEM	=	"66E_QHMHKIJJILHOHSIVJXKYMZP[S[VZXYZW[U\\R\\N[KYIWH RUHTITKULVKUJ RISJVLXNYQZTZWY RJJINIQJTLWNXQYTYWXYW[T\\R RHFKI RKHLG RIGJGKFMGQHWHZG\\F";
prog_char	gGothicItilian_55[]	PROGMEM	=	"51E_LHJJILHOHRIUJWLYNZQ[U[XZZY RKJJLIOISJV RKILJLKKMJPJSKVLXNZ RVHXHXXWZU[ RYHYXXY RZGZY\\[ RHFKGQHVHZG\\F";
prog_char	gGothicItilian_56[]	PROGMEM	=	"31E_HFR[ RIGJHQWRY RJGKHRWSX R\\FR[ RWNUS RYLUQTTTV RHFJGOHUHZG\\F";
prog_char	gGothicItilian_57[]	PROGMEM	=	"67E_LHJJILHOHRIUJWLYNZQ[S[VZXYZW[U\\R\\O[LZJXH RJLIOIRJUKW RJJKKKLJOJRKVLXNZ RYWZU[R[OZL RVZXXYVZRZOYLYKZJ RQIQ[ RRJRZ RSIS[ RHFLHPITIXH\\F";
prog_char	gGothicItilian_58[]	PROGMEM	=	"41E_HFXYYZ RIGKHZZ RLH\\[ R\\FSP RQRJZ RPSMULW RQRMTLUKWKY RHFLHPITIXH\\F RH[JZNYSYYZ\\[";
prog_char	gGothicItilian_59[]	PROGMEM	=	"47E_XHXZ RYHYY RZGZY RKHIJHMHPISKUMVPWSWVVXU RLUOVUV RHPIRKTNUTUVV RHFLHPITIXH\\F RHWJYLZP[T[XZ\\X";
prog_char	gGothicItilian_5A[]	PROGMEM	=	"73E_HFIGKHNHSFVFYGZIZKYM RXGYIYKXM RVFWGXIXL RXNTOROPNPLRKTKXL RTKVLWMVNTO RYM[O\\R\\T[WYYWZT[P[MZKYIWHTHRIOJNLMNMPNPPOQNPOO RXMZO[Q[UZW RXNYOZQZUYXWZ";
prog_char	gGothicItilian_5B[]	PROGMEM	=	"12KYOBOb RPBPb ROBVB RObVb";
prog_char	gGothicItilian_5C[]	PROGMEM	=	" 3KYKFY^";
prog_char	gGothicItilian_5D[]	PROGMEM	=	"12KYTBTb RUBUb RNBUB RNbUb";
prog_char	gGothicItilian_5E[]	PROGMEM	=	" 8G]JTROZT RJTRPZT";
prog_char	gGothicItilian_5F[]	PROGMEM	=	" 3E_Eb_b";

prog_char	gGothicItilian_60[]	PROGMEM	=	" 7LXPFUL RPFOGUL";
prog_char	gGothicItilian_61[]	PROGMEM	=	"42J[PQMTMXP[TY RNTNXPZ ROROWRZ RRSMNNMONNO RONSNUMWOWXXY RUNVOVXUYVZWYVX RSNUPUXTYV[XY";
prog_char	gGothicItilian_62[]	PROGMEM	=	"31IZNHLFMJMXP[UYWX RNHNXPZ RNHPFOJOWRZ ROOTMWPWX RTNVPVX RRNUQUY";
prog_char	gGothicItilian_63[]	PROGMEM	=	"23KWNPNYP[RY ROPOYPZ RPOPXQYRY RNPTMVOTPRN RSNUO";
prog_char	gGothicItilian_64[]	PROGMEM	=	"32JZRMMPMXP[RZUYWY RNPNXPZ ROOOWRZ RPIPFQIWPWY RPIVPVX RPIMIPJUPUY";
prog_char	gGothicItilian_65[]	PROGMEM	=	"25KXNPNYP[RY ROPOYPZ RPOPXQYRY RNPTMWQPU RSNVQ RRNUR";
prog_char	gGothicItilian_66[]	PROGMEM	=	"32KWOIOXNYP[ RPIPXOYPZQYPX RQHQXRYP[ ROIUFWHUISG RTGVH RLMOM RQMUM";
prog_char	gGothicItilian_67[]	PROGMEM	=	"41J[MPMXP[UY RNPNXPZ ROOOWRZ RMPOOTMWPW]V_U`SaQaO`MaObQa RTNVPV]U_ RPaNa RRNUQU^T`Sa";
prog_char	gGothicItilian_68[]	PROGMEM	=	"42I[NHLFMJMXLYN[ RNHNXMYNZOYNX RNHPFOJOXPYN[ ROORNTMWPWYT]T`UbVbT` RTNVPVYU[ RRNUQUZT]";
prog_char	gGothicItilian_69[]	PROGMEM	=	"37MWRFPHRJTHRF RRGQHRISHRG RRMPOQPQXPYR[ RRPSORNQORPRXQYRZSYRX RRMTOSPSXTYR[";
prog_char	gGothicItilian_6A[]	PROGMEM	=	"37MWRFPHRJTHRF RRGQHRISHRG RRMPOQPQYT] RRPSORNQORPRYS[ RRMTOSPSZT]T`RbPaPbRb";
prog_char	gGothicItilian_6B[]	PROGMEM	=	"51IZNHLFMJMXLYN[ RNHNXMYNZOYNX RNHPFOJOXPYN[ ROPRNTMVPSROU RSNUP RRNTQ RRSSTTYV[XY RSSTUUYVZ RSRTSVXWYXY";
prog_char	gGothicItilian_6C[]	PROGMEM	=	"21MWRHPFQJQXPYR[ RRHRXQYRZSYRX RRHTFSJSXTYR[";
prog_char	gGothicItilian_6D[]	PROGMEM	=	"66E_GOHOIPIXHYJ[ RINJOJXIYJZKYJX RGOIMKOKXLYJ[ RKONNPMSOSXTYR[ RPNRORXQYRZSYRX RNNQPQXPYR[ RSOVNXM[O[X\\YZ[ RXNZOZXYYZZ[YZX RVNYPYXXYZ[";
prog_char	gGothicItilian_6E[]	PROGMEM	=	"44I[KOLOMPMXLYN[ RMNNONXMYNZOYNX RKOMMOOOXPYN[ ROORNTMWOWXXYV[ RTNVOVXUYVZWYVX RRNUPUXTYV[";
prog_char	gGothicItilian_6F[]	PROGMEM	=	"28JZMPMXP[UYWX RNPNXPZ ROOOWRZ RMPOOTMWPWX RTNVPVX RRNUQUY";

prog_char	gGothicItilian_70[]	PROGMEM	=	"47IZLMMOMXKYMYM_LbN` RNON` RLMNNOOOXQYRZ RNYOYQZ ROZP[UYWX ROZO_PbN` ROORNTMWPWX RTNVPVX RRNUQUY";
prog_char	gGothicItilian_71[]	PROGMEM	=	"31J[MPMXP[UY RNPNXPZ ROOOWRZ RMPOOTMWPW_XbV` RTNVPV` RRNUQU_TbV`";
prog_char	gGothicItilian_72[]	PROGMEM	=	"31KXMONOOPOXNYP[ RONPOPXOYPZQYPX RMOOMQOQXRYP[ RQOUMWOUPSN RTNVO";
prog_char	gGothicItilian_73[]	PROGMEM	=	"41JZMPMSOUURWTWX RNPNSOT ROOOSPT RUSVTVX RTSUTUY RMPSMVNTOQN RRNUN RWXQ[MYOXSZ ROYQZ";
prog_char	gGothicItilian_74[]	PROGMEM	=	"27MWRHPFQJQXPYR[ RRHRXQYRZSYRX RRHTFSJSXTYR[ RNMQM RSMVM";
prog_char	gGothicItilian_75[]	PROGMEM	=	"40I[KOLOMPMYP[UY RMNNONYPZ RKOMMOOOXRZ RVMXOWPWXXYYY RVPWOVNUOVPVYWZ RVMTOUPUYW[YY";
prog_char	gGothicItilian_76[]	PROGMEM	=	"36I[LMMOMXQ[SYWW RMNNONXQZ RLMNNOOOWRYSY RVMXOWPWW RVPWOVNUOVPVW RVMTOUPUX";
prog_char	gGothicItilian_77[]	PROGMEM	=	"59E_HMIOIXM[OYQX RINJOJXMZ RHMJNKOKWNYOY RRMPOQPQXU[WY[W RRPSORNQORPRXUZ RRMTOSPSWVYWY RZM\\O[P[W RZP[OZNYOZPZW RZMXOYPYX";
prog_char	gGothicItilian_78[]	PROGMEM	=	"39I[LONPUZV[XY RMNOOUYWZ RLONMONVXXY RXMVMVOXOXMVOSS RQUNYL[N[NYLYL[ RNTQT RSTVT";
prog_char	gGothicItilian_79[]	PROGMEM	=	"49I[KOLOMPMYP[UY RMNNONYPZ RKOMMOOOXRZ RVMXOWPW]V_U`SaQaO`MaObQa RVPWOVNUOVPV^U_ RPaNa RVMTOUPU^T`Sa";
prog_char	gGothicItilian_7A[]	PROGMEM	=	"43L[RNOPOORNTMWOWSRU RTNVOVS RRNUPUSTT RRUWWW]V_U`SaQaO`MaObQa RVWV^U_ RPaNa RTVUWU^T`Sa";
prog_char	gGothicItilian_7B[]	PROGMEM	=	"40KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
prog_char	gGothicItilian_7C[]	PROGMEM	=	" 3NVRBRb";
prog_char	gGothicItilian_7D[]	PROGMEM	=	"40KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
prog_char	gGothicItilian_7E[]	PROGMEM	=	"24F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
prog_char	gGothicItilian_7F[]	PROGMEM	=	"35JZJFJ[K[KFLFL[M[MFNFN[O[OFPFP[Q[QFRFR[S[SFTFT[U[UFVFV[W[WFXFX[Y[YFZFZ[";




PGM_P gHershyGothicItalianFontTable[]	PROGMEM =	   // change "string_table" name to suit
{

	gGothicItilian_00,
	gGothicItilian_20,
	gGothicItilian_21,
	gGothicItilian_22,
	gGothicItilian_23,
	gGothicItilian_24,
	gGothicItilian_25,
	gGothicItilian_26,
	gGothicItilian_27,
	gGothicItilian_28,
	gGothicItilian_29,
	gGothicItilian_2A,
	gGothicItilian_2B,
	gGothicItilian_2C,
	gGothicItilian_2D,
	gGothicItilian_2E,
	gGothicItilian_2F,

	gGothicItilian_30,
	gGothicItilian_31,
	gGothicItilian_32,
	gGothicItilian_33,
	gGothicItilian_34,
	gGothicItilian_35,
	gGothicItilian_36,
	gGothicItilian_37,
	gGothicItilian_38,
	gGothicItilian_39,
	gGothicItilian_3A,
	gGothicItilian_3B,
	gGothicItilian_3C,
	gGothicItilian_3D,
	gGothicItilian_3E,
	gGothicItilian_3F,

	gGothicItilian_40,
	gGothicItilian_41,
	gGothicItilian_42,
	gGothicItilian_43,
	gGothicItilian_44,
	gGothicItilian_45,
	gGothicItilian_46,
	gGothicItilian_47,
	gGothicItilian_48,
	gGothicItilian_49,
	gGothicItilian_4A,
	gGothicItilian_4B,
	gGothicItilian_4C,
	gGothicItilian_4D,
	gGothicItilian_4E,
	gGothicItilian_4F,

	gGothicItilian_50,
	gGothicItilian_51,
	gGothicItilian_52,
	gGothicItilian_53,
	gGothicItilian_54,
	gGothicItilian_55,
	gGothicItilian_56,
	gGothicItilian_57,
	gGothicItilian_58,
	gGothicItilian_59,
	gGothicItilian_5A,
	gGothicItilian_5B,
	gGothicItilian_5C,
	gGothicItilian_5D,
	gGothicItilian_5E,
	gGothicItilian_5F,

	gGothicItilian_60,
	gGothicItilian_61,
	gGothicItilian_62,
	gGothicItilian_63,
	gGothicItilian_64,
	gGothicItilian_65,
	gGothicItilian_66,
	gGothicItilian_67,
	gGothicItilian_68,
	gGothicItilian_69,
	gGothicItilian_6A,
	gGothicItilian_6B,
	gGothicItilian_6C,
	gGothicItilian_6D,
	gGothicItilian_6E,
	gGothicItilian_6F,

	gGothicItilian_70,
	gGothicItilian_71,
	gGothicItilian_72,
	gGothicItilian_73,
	gGothicItilian_74,
	gGothicItilian_75,
	gGothicItilian_76,
	gGothicItilian_77,
	gGothicItilian_78,
	gGothicItilian_79,
	gGothicItilian_7A,
	gGothicItilian_7B,
	gGothicItilian_7C,
	gGothicItilian_7D,
	gGothicItilian_7E,
	gGothicItilian_7F

};
