//*******************************************************************************
//*	greek.jhf		Greek
//*	formated for use with Arduino Processing 
//*	by Mark Sproul
//*******************************************************************************
//*	Feb 20,	2009	<MLS> Formated Hershey Script Complex for Arduino
//*******************************************************************************
//#include	"HersheyScriptComplex.h"


prog_char	gScriptComplex_00[]	PROGMEM	=	"Script Complex";


prog_char	gScriptComplex_20[]	PROGMEM	=	" 1JZ";
prog_char	gScriptComplex_21[]	PROGMEM	=	"17MXUFTGRS RUGRS RUFVGRS RPYOZP[QZPY";
prog_char	gScriptComplex_22[]	PROGMEM	=	"12I[PFNM RQFNM RYFWM RZFWM";
prog_char	gScriptComplex_23[]	PROGMEM	=	"12H]SFLb RYFRb RLQZQ RKWYW";
prog_char	gScriptComplex_24[]	PROGMEM	=	"41H]TBL_ RYBQ_ RZJYKZL[K[JZHYGVFRFOGMIMKNMONVRXT RMKOMVQWRXTXWWYVZS[O[LZKYJWJVKULVKW";
prog_char	gScriptComplex_25[]	PROGMEM	=	"32F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT";
prog_char	gScriptComplex_26[]	PROGMEM	=	"55E_\\N[O\\P]O]N\\M[MYNWPRXPZN[K[HZGXGVHTISKRPPROTMUKUITGRFPGOIOLPRQUSXUZW[Y[ZYZX RK[IZHXHVITJSPP ROLPQQTSWUYWZYZZY";
prog_char	gScriptComplex_27[]	PROGMEM	=	" 8MXUHTGUFVGVHUJSL";
prog_char	gScriptComplex_28[]	PROGMEM	=	"20KZZBVESHQKOONTNXO]P`Qb RVESIQMPPOUOZP_Qb";
prog_char	gScriptComplex_29[]	PROGMEM	=	"20JYSBTDUGVLVPUUSYQ\\N_Jb RSBTEUJUOTTSWQ[N_";
prog_char	gScriptComplex_2A[]	PROGMEM	=	" 9J[TFTR ROIYO RYIOO";
prog_char	gScriptComplex_2B[]	PROGMEM	=	" 6E_RIR[ RIR[R";
prog_char	gScriptComplex_2C[]	PROGMEM	=	" 8MXP[OZPYQZQ[P]N_";
prog_char	gScriptComplex_2D[]	PROGMEM	=	" 3E_IR[R";
prog_char	gScriptComplex_2E[]	PROGMEM	=	" 6MXPYOZP[QZPY";
prog_char	gScriptComplex_2F[]	PROGMEM	=	" 3G]_BEb";

prog_char	gScriptComplex_30[]	PROGMEM	=	"42H]TFQGOIMLLOKSKVLYMZO[Q[TZVXXUYRZNZKYHXGVFTF RTFRGPINLMOLSLVMYO[ RQ[SZUXWUXRYNYKXHVF";
prog_char	gScriptComplex_31[]	PROGMEM	=	"15H]TJO[ RVFP[ RVFSIPKNL RUIQKNL";
prog_char	gScriptComplex_32[]	PROGMEM	=	"42H]OJPKOLNKNJOHPGSFVFYGZIZKYMWOTQPSMUKWI[ RVFXGYIYKXMVOPS RJYKXMXRZUZWYXW RMXR[U[WZXW";
prog_char	gScriptComplex_33[]	PROGMEM	=	"50H]OJPKOLNKNJOHPGSFVFYGZIZKYMVOSP RVFXGYIYKXMVO RQPSPVQWRXTXWWYVZS[O[LZKYJWJVKULVKW RSPUQVRWTWWVYUZS[";
prog_char	gScriptComplex_34[]	PROGMEM	=	"10H]XGR[ RYFS[ RYFJUZU";
prog_char	gScriptComplex_35[]	PROGMEM	=	"39H]QFLP RQF[F RQGVG[F RLPMOPNSNVOWPXRXUWXUZR[O[LZKYJWJVKULVKW RSNUOVPWRWUVXTZR[";
prog_char	gScriptComplex_36[]	PROGMEM	=	"46H]YIXJYKZJZIYGWFTFQGOIMLLOKSKWLYMZO[R[UZWXXVXSWQVPTOQOOPMRLT RTFRGPINLMOLSLXMZ RR[TZVXWVWRVP";
prog_char	gScriptComplex_37[]	PROGMEM	=	"30H]NFLL R[FZIXLSRQUPWO[ RXLRRPUOWN[ RMIPFRFWI RNHPGRGWIYIZH[F";
prog_char	gScriptComplex_38[]	PROGMEM	=	"63H]SFPGOHNJNMOOQPTPXOYNZLZIYGVFSF RSFQGPHOJOMPOQP RTPWOXNYLYIXGVF RQPMQKSJUJXKZN[R[VZWYXWXTWRVQTP RQPNQLSKUKXLZN[ RR[UZVYWWWSVQ";
prog_char	gScriptComplex_39[]	PROGMEM	=	"46H]YMXOVQTRQROQNPMNMKNIPGSFVFXGYHZJZNYRXUVXTZQ[N[LZKXKWLVMWLX ROQNONKOIQGSF RXGYIYNXRWUUXSZQ[";
prog_char	gScriptComplex_3A[]	PROGMEM	=	"11MXSMRNSOTNSM RPYOZP[QZ";
prog_char	gScriptComplex_3B[]	PROGMEM	=	"14MXSMRNSOTNSM RP[OZPYQZQ[P]N_";
prog_char	gScriptComplex_3C[]	PROGMEM	=	" 4F^ZIJRZ[";
prog_char	gScriptComplex_3D[]	PROGMEM	=	" 6E_IO[O RIU[U";
prog_char	gScriptComplex_3E[]	PROGMEM	=	" 4F^JIZRJ[";
prog_char	gScriptComplex_3F[]	PROGMEM	=	"34H]OJPKOLNKNJOHPGSFWFZG[I[KZMYNSPQQQSRTTT RWFYGZIZKYMXNVO RPYOZP[QZPY";

prog_char	gScriptComplex_40[]	PROGMEM	=	"56E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
prog_char	gScriptComplex_41[]	PROGMEM	=	"38E\\XFVHTKQPOSLWIZG[E[DZDXEWFXEY RXFWJUTT[ RXFU[ RT[TYSVRTPRNQLQKRKTLWOZR[V[XZ";
prog_char	gScriptComplex_42[]	PROGMEM	=	"70F^UGTHSJQOOUNWLZJ[ RTHSKQSPVOXMZJ[H[GZGXHWIXHY ROLNNMOKOJNJLKJMHOGRFXFZG[I[KZMXNTORO RXFYGZIZKYMXN RTOWPXQYSYVXYWZU[S[RZRXSU RTOVPWQXSXVWYU[";
prog_char	gScriptComplex_43[]	PROGMEM	=	"41H]KHJJJLKNNOQOUNWMYKZIZGYFWFTGQJOMMQLULXMZP[R[UZWXXVXTWRURSSRU RWFUGRJPMNQMUMXNZP[";
prog_char	gScriptComplex_44[]	PROGMEM	=	"43F]UGTHSJQOOUNWLZJ[ RTHSKQSPVOXMZJ[H[GZGXHWJWLXNZP[S[UZWXYTZOZLYIWGUFPFMGKIJKJMKNMNNMOK";
prog_char	gScriptComplex_45[]	PROGMEM	=	"49I\\WIVJVLWMYMZKZIYGWFTFRGQHPJPLQNSO RTFRHQJQMSO RSOQONPLRKTKWLYMZO[R[UZWXXVXTWRURSSRU RQOOPMRLTLXMZ";
prog_char	gScriptComplex_46[]	PROGMEM	=	"46G\\WHVJTORUQWOZM[ RQLPNNOLOKMKKLINGQF[FXGWHVKTSSVRXPZM[K[IZHYHXIWJXIY RSFWGXG ROSPRRQVQXPZMXT";
prog_char	gScriptComplex_47[]	PROGMEM	=	"53G]JIIKIMJOLPOPROTNWKXHXGWFVFTGRIQKPNPQQSSTUTWSYQZO RWFUGSIRKQNQRST RZOYSWWUYSZO[L[JZIXIWJVKWJX RYSWVUXRZO[";
prog_char	gScriptComplex_48[]	PROGMEM	=	"55F^LLKKKILGOFRFOQMWLYKZI[G[FZFXGWHXGY RRFOONRLWKYI[ RJTKSMRVOXN[L]J^H^G]F\\FZGXJWLURTVTYV[W[YZ[X R\\FZHXLVRUVUYV[";
prog_char	gScriptComplex_49[]	PROGMEM	=	"33IYWHUKSPQUPWNZL[ RYLWNTOQOONNLNJOHQGUFYFWHVJTPRVQXOZL[J[IZIXJWKXJY";
prog_char	gScriptComplex_4A[]	PROGMEM	=	"34IZYFWHUKSPPYN] RYMWOTPQPOONMNKOIQGUFYFWIVKSTQXPZN]M^K_J^J\\KZMXOWRVVU";
prog_char	gScriptComplex_4B[]	PROGMEM	=	"59F^LLKKKIMGPFRFOQMWLYKZI[G[FZFXGWHXGY RRFOONRLWKYI[ RZGWKUMSNPO R]G\\H]I^H^G]F\\FZGWLVMTNPO RPOSPTRUYV[ RPORPSRTYV[W[YZ[X";
prog_char	gScriptComplex_4C[]	PROGMEM	=	"40I[MILKLMMOOPRPUOWNZK[H[GZFYFWGVHTKPUOWMZK[ RVHTLRSQVPXNZK[I[HZHXIWKWMXPZR[U[WZYX";
prog_char	gScriptComplex_4D[]	PROGMEM	=	"49D`RFNOKUIXGZE[C[BZBXCWDXCY RRFPMOQNVNZP[ RRFQJPOOVOZP[ R[FWORXP[ R[FYMXQWVWZY[Z[\\Z^X R[FZJYOXVXZY[";
prog_char	gScriptComplex_4E[]	PROGMEM	=	"38G^RFQJOPMULWJZH[F[EZEXFWGXFY RRFRKSVT[ RRFSKTVT[ R`G_H`IaHaG`F^F\\GZJYLWQUWT[";
prog_char	gScriptComplex_4F[]	PROGMEM	=	"34H]SFQGOIMLLNKRKVLYMZO[Q[TZVXXUYSZOZKYHXGWGUHSJQNPSPV RQGOJMNLRLVMYO[";

prog_char	gScriptComplex_50[]	PROGMEM	=	"53F]UGTHSJQOOUNWLZJ[ RTHSKQSPVOXMZJ[H[GZGXHWIXHY ROLNNMOKOJNJLKJMHOGRFVFYGZH[J[MZOYPVQTQRP RVFXGYHZJZMYOXPVQ";
prog_char	gScriptComplex_51[]	PROGMEM	=	"43H]UJULTNSOQPOPNNNLOIQGTFWFYGZIZMYPWSSWPYNZK[I[HZHXIWKWMXPZS[V[XZZX RWFXGYIYMXPVSSVOYK[";
prog_char	gScriptComplex_52[]	PROGMEM	=	"65F^UGTHSJQOOUNWLZJ[ RTHSKQSPVOXMZJ[H[GZGXHWIXHY ROLNNMOKOJNJLKJMHOGRFWFZG[I[KZMYNVORO RWFYGZIZKYMXNVO RROUPVRWYX[ RROTPURVYX[Y[[Z]X";
prog_char	gScriptComplex_53[]	PROGMEM	=	"36H\\NIMKMMNOPPSPVOXN[K\\H\\G[FZFXGWHVJUMSTRWPZN[ RVJUNTUSXQZN[K[IZHXHWIVJWIX";
prog_char	gScriptComplex_54[]	PROGMEM	=	"38I[YHXJVOTUSWQZO[ RSLRNPONOMMMKNIPGSF\\FZGYHXKVSUVTXRZO[M[KZJYJXKWLXKY RUFYGZG";
prog_char	gScriptComplex_55[]	PROGMEM	=	"39G]HJJGLFMFOHOKNNKVKYL[ RMFNHNKKSJVJYL[N[PZSWUTVR RZFVRUVUYW[X[ZZ\\X R[FWRVVVYW[";
prog_char	gScriptComplex_56[]	PROGMEM	=	"36G\\HJJGLFMFOHOKNOLVLYM[ RMFNHNKLRKVKYM[N[QZTWVTXPYMZIZGYFXFWGVIVLWNYP[Q]Q";
prog_char	gScriptComplex_57[]	PROGMEM	=	"41F]ILHLGKGIHGJFNFMHLLKUJ[ RLLLUK[ RVFTHRLOUMYK[ RVFUHTLSUR[ RTLTUS[ R`F^G\\IZLWUUYS[";
prog_char	gScriptComplex_58[]	PROGMEM	=	"52H\\PKOLMLLKLIMGOFQFSGTITLSPQUOXMZJ[H[GZGXHWIXHY RQFRGSISLRPPUNXLZJ[ R]G\\H]I^H^G]F[FYGWIULSPRURXSZT[U[WZYX";
prog_char	gScriptComplex_59[]	PROGMEM	=	"42G]JJLGNFOFQGQIOOORPT ROFPGPINONRPTRTUSWQYNZL R\\FZLWTUX R]F[LYQWUUXSZP[L[JZIXIWJVKWJX";
prog_char	gScriptComplex_5A[]	PROGMEM	=	"44G\\ZHYJWOVRUTSWQYOZL[ RSLRNPONOMMMKNIPGSF]F[GZHYKXOVUTXQZL[H[GZGXHWJWLXOZQ[T[WZYX RVFZG[G";
prog_char	gScriptComplex_5B[]	PROGMEM	=	"12KYOBOb RPBPb ROBVB RObVb";
prog_char	gScriptComplex_5C[]	PROGMEM	=	" 3KYKFY^";
prog_char	gScriptComplex_5D[]	PROGMEM	=	"12KYTBTb RUBUb RNBUB RNbUb";
prog_char	gScriptComplex_5E[]	PROGMEM	=	"11JZPLRITL RMORJWO RRJR[";
prog_char	gScriptComplex_5F[]	PROGMEM	=	" 3JZJ]Z]";

prog_char	gScriptComplex_60[]	PROGMEM	=	" 8MXVFTHSJSKTLUKTJ";
prog_char	gScriptComplex_61[]	PROGMEM	=	"33K[UUTSRRPRNSMTLVLXMZO[Q[SZTX RPRNTMVMYO[ RVRTXTZV[XZYY[V RWRUXUZV[";
prog_char	gScriptComplex_62[]	PROGMEM	=	"23LZLVNSPO RSFMXMZO[P[RZTXUUURVVWWXWZV RTFNXNZO[";
prog_char	gScriptComplex_63[]	PROGMEM	=	"22LXTSSTTTTSSRQROSNTMVMXNZP[S[VYXV RQROTNVNYP[";
prog_char	gScriptComplex_64[]	PROGMEM	=	"33K[UUTSRRPRNSMTLVLXMZO[Q[SZTX RPRNTMVMYO[ RZFTXTZV[XZYY[V R[FUXUZV[";
prog_char	gScriptComplex_65[]	PROGMEM	=	"23LXOYQXRWSUSSRRQROSNTMVMXNZP[S[VYXV RQROTNVNYP[";
prog_char	gScriptComplex_66[]	PROGMEM	=	"27OXRRUOWLXIXGWFUGTIKdKfLgNfOcPZQ[S[UZVYXV RTISNRRO[M`Kd";
prog_char	gScriptComplex_67[]	PROGMEM	=	"38K[UUTSRRPRNSMTLVLXMZO[Q[SZTX RPRNTMVMYO[ RVRPd RWRT[R`PdOfMgLfLdMaO_R]V[YY[V";
prog_char	gScriptComplex_68[]	PROGMEM	=	"30L[LVNSPO RSFL[ RTFM[ ROUQSSRTRVSVUUXUZV[ RTRUSUUTXTZV[XZYY[V";
prog_char	gScriptComplex_69[]	PROGMEM	=	"19NVSLRMSNTMSL RQROXOZQ[SZTYVV RRRPXPZQ[";
prog_char	gScriptComplex_6A[]	PROGMEM	=	"24NVSLRMSNTMSL RQRKd RRRO[M`KdJfHgGfGdHaJ_M]Q[TYVV";
prog_char	gScriptComplex_6B[]	PROGMEM	=	"31LZLVNSPO RSFL[ RTFM[ RURUSVSURTRRTOU ROURVSZT[ ROUQVRZT[U[XYZV";
prog_char	gScriptComplex_6C[]	PROGMEM	=	"17NVNVPSRO RUFOXOZQ[SZTYVV RVFPXPZQ[";
prog_char	gScriptComplex_6D[]	PROGMEM	=	"45E^EVGSIRKSKUI[ RIRJSJUH[ RKUMSORPRRSRUP[ RPRQSQUO[ RRUTSVRWRYSYUXXXZY[ RWRXSXUWXWZY[[Z\\Y^V";
prog_char	gScriptComplex_6E[]	PROGMEM	=	"32I[IVKSMROSOUM[ RMRNSNUL[ ROUQSSRTRVSVUUXUZV[ RTRUSUUTXTZV[XZYY[V";
prog_char	gScriptComplex_6F[]	PROGMEM	=	"29KYRRPRNSMTLVLXMZO[Q[SZTYUWUUTSRRQSQURWTXVXXWYV RPRNTMVMYO[";

prog_char	gScriptComplex_70[]	PROGMEM	=	"30L[LVNSPO RQLHg RRLIg ROUQSSRTRVSVUUXUZV[ RTRUSUUTXTZV[XZYY[V";
prog_char	gScriptComplex_71[]	PROGMEM	=	"35K[UUTSRRPRNSMTLVLXMZO[Q[SZ RPRNTMVMYO[ RVRPdPfQgSfTcT[V[YY[V RWRT[R`Pd";
prog_char	gScriptComplex_72[]	PROGMEM	=	"24LZLVNSPRRSRUP[ RPRQSQUO[ RRUTSVRWRVU RVRVUWWXWZV";
prog_char	gScriptComplex_73[]	PROGMEM	=	"22NZNVPSQQQSTUUWUYTZR[ RQSSUTWTYR[ RNZP[U[XYZV";
prog_char	gScriptComplex_74[]	PROGMEM	=	"20NVNVPSRO RUFOXOZQ[SZTYVV RVFPXPZQ[ RPNVN";
prog_char	gScriptComplex_75[]	PROGMEM	=	"27K[NRLXLZN[O[QZSXUU RORMXMZN[ RVRTXTZV[XZYY[V RWRUXUZV[";
prog_char	gScriptComplex_76[]	PROGMEM	=	"23KZNRMTLWLZN[O[RZTXUUUR RORNTMWMZN[ RURVVWWXWZV";
prog_char	gScriptComplex_77[]	PROGMEM	=	"36H]LRJTIWIZK[L[NZPX RMRKTJWJZK[ RRRPXPZR[S[UZWXXUXR RSRQXQZR[ RXRYVZW[W]V";
prog_char	gScriptComplex_78[]	PROGMEM	=	"42JZJVLSNRPRQSQUPXOZM[L[KZKYLYKZ RWSVTWTWSVRURSSRUQXQZR[U[XYZV RQSRU RSSQU RPXQZ RQXOZ";
prog_char	gScriptComplex_79[]	PROGMEM	=	"32K[NRLXLZN[O[QZSXUU RORMXMZN[ RVRPd RWRT[R`PdOfMgLfLdMaO_R]V[YY[V";
prog_char	gScriptComplex_7A[]	PROGMEM	=	"38LYLVNSPRRRTSTVSXPZN[ RRRSSSVRXPZ RN[P\\Q^QaPdNfLgKfKdLaO^R\\VYYV RN[O\\P^PaOdNf";
prog_char	gScriptComplex_7B[]	PROGMEM	=	"40KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
prog_char	gScriptComplex_7C[]	PROGMEM	=	" 3NVRBRb";
prog_char	gScriptComplex_7D[]	PROGMEM	=	"40KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
prog_char	gScriptComplex_7E[]	PROGMEM	=	"24F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
prog_char	gScriptComplex_7F[]	PROGMEM	=	"14KZSFQGPIPKQMSNUNWMXKXIWGUFSF";


PGM_P gHershyScriptComplexFontTable[]	PROGMEM =	   // change "string_table" name to suit
{

	gScriptComplex_00,
	gScriptComplex_20,
	gScriptComplex_21,
	gScriptComplex_22,
	gScriptComplex_23,
	gScriptComplex_24,
	gScriptComplex_25,
	gScriptComplex_26,
	gScriptComplex_27,
	gScriptComplex_28,
	gScriptComplex_29,
	gScriptComplex_2A,
	gScriptComplex_2B,
	gScriptComplex_2C,
	gScriptComplex_2D,
	gScriptComplex_2E,
	gScriptComplex_2F,

	gScriptComplex_30,
	gScriptComplex_31,
	gScriptComplex_32,
	gScriptComplex_33,
	gScriptComplex_34,
	gScriptComplex_35,
	gScriptComplex_36,
	gScriptComplex_37,
	gScriptComplex_38,
	gScriptComplex_39,
	gScriptComplex_3A,
	gScriptComplex_3B,
	gScriptComplex_3C,
	gScriptComplex_3D,
	gScriptComplex_3E,
	gScriptComplex_3F,

	gScriptComplex_40,
	gScriptComplex_41,
	gScriptComplex_42,
	gScriptComplex_43,
	gScriptComplex_44,
	gScriptComplex_45,
	gScriptComplex_46,
	gScriptComplex_47,
	gScriptComplex_48,
	gScriptComplex_49,
	gScriptComplex_4A,
	gScriptComplex_4B,
	gScriptComplex_4C,
	gScriptComplex_4D,
	gScriptComplex_4E,
	gScriptComplex_4F,

	gScriptComplex_50,
	gScriptComplex_51,
	gScriptComplex_52,
	gScriptComplex_53,
	gScriptComplex_54,
	gScriptComplex_55,
	gScriptComplex_56,
	gScriptComplex_57,
	gScriptComplex_58,
	gScriptComplex_59,
	gScriptComplex_5A,
	gScriptComplex_5B,
	gScriptComplex_5C,
	gScriptComplex_5D,
	gScriptComplex_5E,
	gScriptComplex_5F,

	gScriptComplex_60,
	gScriptComplex_61,
	gScriptComplex_62,
	gScriptComplex_63,
	gScriptComplex_64,
	gScriptComplex_65,
	gScriptComplex_66,
	gScriptComplex_67,
	gScriptComplex_68,
	gScriptComplex_69,
	gScriptComplex_6A,
	gScriptComplex_6B,
	gScriptComplex_6C,
	gScriptComplex_6D,
	gScriptComplex_6E,
	gScriptComplex_6F,

	gScriptComplex_70,
	gScriptComplex_71,
	gScriptComplex_72,
	gScriptComplex_73,
	gScriptComplex_74,
	gScriptComplex_75,
	gScriptComplex_76,
	gScriptComplex_77,
	gScriptComplex_78,
	gScriptComplex_79,
	gScriptComplex_7A,
	gScriptComplex_7B,
	gScriptComplex_7C,
	gScriptComplex_7D,
	gScriptComplex_7E,
	gScriptComplex_7F

};
