//*******************************************************************************
//*	cyrillic.jhf		Cyrillic
//*	formated for use with Arduino Processing 
//*	by Mark Sproul
//*******************************************************************************
//*	Jan 30,	2009	<MLS> Formated Hershey Cyrillic for Arduino
//*******************************************************************************
//#include	"HersheyCyrillic.h"


prog_char	gCyrillic_00[]	PROGMEM	=	"Cyrillic";

prog_char	gCyrillic_20[]	PROGMEM	=	" 1JZ";
prog_char	gCyrillic_21[]	PROGMEM	=	"15MWRFQHRTSHRF RRHRN RRYQZR[SZRY";
prog_char	gCyrillic_22[]	PROGMEM	=	"12JZNFMM ROFMM RVFUM RWFUM";
prog_char	gCyrillic_23[]	PROGMEM	=	"12H]SBLb RYBRb RLOZO RKUYU";
prog_char	gCyrillic_24[]	PROGMEM	=	"41CaHFH[ RIFI[ REFLF RIPPPSQTRUTUWTYSZP[E[ RPPRQSRTTTWSYRZP[ R[F[[ R\\F\\[ RXF_F RX[_[";
prog_char	gCyrillic_25[]	PROGMEM	=	"23G]LML[ RMMM[ RWMW[ RXMX[ RIMPM RTM[M RI[[[[`Z[";
prog_char	gCyrillic_26[]	PROGMEM	=	"37E_JMJ[ RKMK[ RGMNM RKTOTRUSWSXRZO[G[ ROTQURWRXQZO[ RYMY[ RZMZ[ RVM]M RV[][";
prog_char	gCyrillic_27[]	PROGMEM	=	" 6NVRFQM RSFQM";
prog_char	gCyrillic_28[]	PROGMEM	=	"24KYUBSDQGOKNPNTOYQ]S`UbVb RUBVBTDRGPKOPOTPYR]T`Vb";
prog_char	gCyrillic_29[]	PROGMEM	=	"24KYNBPDRGTKUPUTTYR]P`NbOb RNBOBQDSGUKVPVTUYS]Q`Ob";
prog_char	gCyrillic_2A[]	PROGMEM	=	" 9JZRLRX RMOWU RWOMU";
prog_char	gCyrillic_2B[]	PROGMEM	=	" 6E_RIR[ RIR[R";
prog_char	gCyrillic_2C[]	PROGMEM	=	" 8NVSWRXQWRVSWSYQ[";
prog_char	gCyrillic_2D[]	PROGMEM	=	" 3E_IR[R";
prog_char	gCyrillic_2E[]	PROGMEM	=	" 6NVRVQWRXSWRV";
prog_char	gCyrillic_2F[]	PROGMEM	=	" 3G][BIb";

prog_char	gCyrillic_30[]	PROGMEM	=	"40H\\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF RQFOGNHMJLOLRMWNYOZQ[ RS[UZVYWWXRXOWJVHUGSF";
prog_char	gCyrillic_31[]	PROGMEM	=	"11H\\NJPISFS[ RRGR[ RN[W[";
prog_char	gCyrillic_32[]	PROGMEM	=	"45H\\LJMKLLKKKJLHMGPFTFWGXHYJYLXNUPPRNSLUKXK[ RTFVGWHXJXLWNTPPR RKYLXNXSZVZXYYX RNXS[W[XZYXYV";
prog_char	gCyrillic_33[]	PROGMEM	=	"47H\\LJMKLLKKKJLHMGPFTFWGXIXLWNTOQO RTFVGWIWLVNTO RTOVPXRYTYWXYWZT[P[MZLYKWKVLUMVLW RWQXTXWWYVZT[";
prog_char	gCyrillic_34[]	PROGMEM	=	"13H\\THT[ RUFU[ RUFJUZU RQ[X[";
prog_char	gCyrillic_35[]	PROGMEM	=	"39H\\MFKP RKPMNPMSMVNXPYSYUXXVZS[P[MZLYKWKVLUMVLW RSMUNWPXSXUWXUZS[ RMFWF RMGRGWF";
prog_char	gCyrillic_36[]	PROGMEM	=	"48H\\WIVJWKXJXIWGUFRFOGMILKKOKULXNZQ[S[VZXXYUYTXQVOSNRNOOMQLT RRFPGNIMKLOLUMXOZQ[ RS[UZWXXUXTWQUOSN";
prog_char	gCyrillic_37[]	PROGMEM	=	"31H\\KFKL RKJLHNFPFUIWIXHYF RLHNGPGUI RYFYIXLTQSSRVR[ RXLSQRSQVQ[";
prog_char	gCyrillic_38[]	PROGMEM	=	"63H\\PFMGLILLMNPOTOWNXLXIWGTFPF RPFNGMIMLNNPO RTOVNWLWIVGTF RPOMPLQKSKWLYMZP[T[WZXYYWYSXQWPTO RPONPMQLSLWMYNZP[ RT[VZWYXWXSWQVPTO";
prog_char	gCyrillic_39[]	PROGMEM	=	"48H\\XMWPURRSQSNRLPKMKLLINGQFSFVGXIYLYRXVWXUZR[O[MZLXLWMVNWMX RQSORMPLMLLMIOGQF RSFUGWIXLXRWVVXTZR[";
prog_char	gCyrillic_3A[]	PROGMEM	=	"12NVROQPRQSPRO RRVQWRXSWRV";
prog_char	gCyrillic_3B[]	PROGMEM	=	"14NVROQPRQSPRO RSWRXQWRVSWSYQ[";
prog_char	gCyrillic_3C[]	PROGMEM	=	" 4F^ZIJRZ[";
prog_char	gCyrillic_3D[]	PROGMEM	=	" 6E_IO[O RIU[U";
prog_char	gCyrillic_3E[]	PROGMEM	=	" 4F^JIZRJ[";
prog_char	gCyrillic_3F[]	PROGMEM	=	"32I[MJNKMLLKLJMHNGPFSFVGWHXJXLWNVORQRT RSFUGVHWJWLVNTP RRYQZR[SZRY";

prog_char	gCyrillic_40[]	PROGMEM	=	"56E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
prog_char	gCyrillic_41[]	PROGMEM	=	"18H\\RFK[ RRFY[ RRIX[ RMUVU RI[O[ RU[[[";
prog_char	gCyrillic_42[]	PROGMEM	=	"31G]LFL[ RMFM[ RIFYFYLXF RMPUPXQYRZTZWYYXZU[I[ RUPWQXRYTYWXYWZU[";
prog_char	gCyrillic_43[]	PROGMEM	=	"39H]LIKFKLLINGQFSFVGXIYKZNZSYVXXVZS[P[MZLYKWKVLUMVLW RSFUGWIXKYNYSXVWXUZS[ RPPYP";
prog_char	gCyrillic_44[]	PROGMEM	=	"31F^NFNLMTLXKZJ[ RXFX[ RYFY[ RKF\\F RG[\\[ RG[Gb RH[Gb R[[\\b R\\[\\b";
prog_char	gCyrillic_45[]	PROGMEM	=	"27F^KFK[ RLFL[ RXFX[ RYFY[ RHFOF RUF\\F RXHLY RH[O[ RU[\\[";
prog_char	gCyrillic_46[]	PROGMEM	=	"48F_RFR[ RSFS[ ROFVF RPILJJLIOIRJULWPXUXYW[U\\R\\O[LYJUIPI RPIMJKLJOJRKUMWPX RUXXWZU[R[OZLXJUI RO[V[";
prog_char	gCyrillic_47[]	PROGMEM	=	"14I[NFN[ ROFO[ RKFZFZLYF RK[R[";
prog_char	gCyrillic_48[]	PROGMEM	=	"71CbRFR[ RSFS[ ROFVF RGGHHGIFHFGGFHFIGJIKMLONPWPYOZM[I\\G]F^F_G_H^I]H^G RNPLQKSJXIZH[ RNPMQLSKXJZI[G[FZEX RWPYQZS[X\\Z][ RWPXQYSZX[Z\\[^[_Z`X RO[V[";
prog_char	gCyrillic_49[]	PROGMEM	=	"27F^KFK[ RLFL[ RXFX[ RYFY[ RHFOF RUF\\F RXHLY RH[O[ RU[\\[";
prog_char	gCyrillic_4A[]	PROGMEM	=	"28F]KFKQLSOTRTUSWQ RLFLQMSOT RWFW[ RXFX[ RHFOF RTF[F RT[[[";
prog_char	gCyrillic_4B[]	PROGMEM	=	"43F^KFK[ RLFL[ RHFOF RLPSPUOVMWIXGYFZF[G[HZIYHZG RSPUQVSWXXZY[ RSPTQUSVXWZX[Z[[Z\\X RH[O[";
prog_char	gCyrillic_4C[]	PROGMEM	=	"25E^MFMLLTKXJZI[H[GZGYHXIYHZ RXFX[ RYFY[ RJF\\F RU[\\[";
prog_char	gCyrillic_4D[]	PROGMEM	=	"30F_KFK[ RLFRX RKFR[ RYFR[ RYFY[ RZFZ[ RHFLF RYF]F RH[N[ RV[][";
prog_char	gCyrillic_4E[]	PROGMEM	=	"27F^KFK[ RLFL[ RXFX[ RYFY[ RHFOF RUF\\F RLPXP RH[O[ RU[\\[";
prog_char	gCyrillic_4F[]	PROGMEM	=	"44G]QFNGLIKKJOJRKVLXNZQ[S[VZXXYVZRZOYKXIVGSFQF RQFOGMILKKOKRLVMXOZQ[ RS[UZWXXVYRYOXKWIUGSF";

prog_char	gCyrillic_50[]	PROGMEM	=	"21F^KFK[ RLFL[ RXFX[ RYFY[ RHF\\F RH[O[ RU[\\[";
prog_char	gCyrillic_51[]	PROGMEM	=	"30BcGFG[ RHFH[ RRFR[ RSFS[ R]F][ R^F^[ RDFKF ROFVF RZFaF RD[a[";
prog_char	gCyrillic_52[]	PROGMEM	=	"29G]LFL[ RMFM[ RIFUFXGYHZJZMYOXPUQMQ RUFWGXHYJYMXOWPUQ RI[P[";
prog_char	gCyrillic_53[]	PROGMEM	=	"32G\\XIYLYFXIVGSFQFNGLIKKJNJSKVLXNZQ[S[VZXXYV RQFOGMILKKNKSLVMXOZQ[";
prog_char	gCyrillic_54[]	PROGMEM	=	"16I\\RFR[ RSFS[ RLFKLKFZFZLYF RO[V[";
prog_char	gCyrillic_55[]	PROGMEM	=	"59CbHFH[ RIFI[ REFLF RE[L[ RVFSGQIPKOOORPVQXSZV[X[[Z]X^V_R_O^K]I[GXFVF RVFTGRIQKPOPRQVRXTZV[ RX[ZZ\\X]V^R^O]K\\IZGXF RIPOP";
prog_char	gCyrillic_56[]	PROGMEM	=	"45G]LFL[ RMFM[ RIFUFXGYHZJZLYNXOUP RUFWGXHYJYLXNWOUP RMPUPXQYRZTZWYYXZU[I[ RUPWQXRYTYWXYWZU[";
prog_char	gCyrillic_57[]	PROGMEM	=	"36BcGFG[ RHFH[ RRFR[ RSFS[ R]F][ R^F^[ RDFKF ROFVF RZFaF RD[a[ R`[ab Ra[ab";
prog_char	gCyrillic_58[]	PROGMEM	=	"21H\\KFX[ RLFY[ RYFK[ RIFOF RUF[F RI[O[ RU[[[";
prog_char	gCyrillic_59[]	PROGMEM	=	"24H]KFRV RLFSV RZFSVQYPZN[M[LZLYMXNYMZ RIFOF RVF\\F";
prog_char	gCyrillic_5A[]	PROGMEM	=	"45H\\LIKFKLLINGPFTFWGXIXLWNTOQO RTFVGWIWLVNTO RTOVPXRYTYWXYWZT[O[MZLYKWKVLUMVLW RWQXTXWWYVZT[";
prog_char	gCyrillic_5B[]	PROGMEM	=	"22G\\LFL[ RMFM[ RSLST RIFYFYLXF RMPSP RI[Y[YUX[";
prog_char	gCyrillic_5C[]	PROGMEM	=	" 3KYKFY^";
prog_char	gCyrillic_5D[]	PROGMEM	=	"31F`PFP[ RQFQ[ RIFHLHFTF RQPXP[Q\\R]T]W\\Y[ZX[M[ RXPZQ[R\\T\\W[YZZX[";
prog_char	gCyrillic_5E[]	PROGMEM	=	"45G]WFW[ RXFX[ R[FOFLGKHJJJLKNLOOPWP ROFMGLHKJKLLNMOOP RRPPQORLYKZJZIY RPQOSMZL[J[IYIX RT[[[";
prog_char	gCyrillic_5F[]	PROGMEM	=	"29H]MFM[ RNFN[ RJFQF RNPUPXQYRZTZWYYXZU[J[ RUPWQXRYTYWXYWZU[";

prog_char	gCyrillic_60[]	PROGMEM	=	"27F^KFK[ RLFL[ RXFX[ RYFY[ RHFOF RUF\\F RH[\\[ R[[\\b R\\[\\b";
prog_char	gCyrillic_61[]	PROGMEM	=	"39I]NONPMPMONNPMTMVNWOXQXXYZZ[ RWOWXXZZ[[[ RWQVRPSMTLVLXMZP[S[UZWX RPSNTMVMXNZP[";
prog_char	gCyrillic_62[]	PROGMEM	=	"48H\\XFWGQINKLNKQKULXNZQ[S[VZXXYUYSXPVNSMQMNNLPKS RXFWHUIQJNLLN RQMONMPLSLUMXOZQ[ RS[UZWXXUXSWPUNSM";
prog_char	gCyrillic_63[]	PROGMEM	=	"39H]LIKFKLLINGQFSFVGXIYKZNZSYVXXVZS[P[MZLYKWKVLUMVLW RSFUGWIXKYNYSXVWXUZS[ RPPYP";
prog_char	gCyrillic_64[]	PROGMEM	=	"22F]NMNQMWLZK[ RWMW[ RXMX[ RKM[M RI[H`H[[[[`Z[";
prog_char	gCyrillic_65[]	PROGMEM	=	"37G]LML[ RMMM[ RWMW[ RXMX[ RIMPM RTM[M RI[P[ RT[[[ RWNMZ ROGOFNFNGOIQJSJUIVG";
prog_char	gCyrillic_66[]	PROGMEM	=	"52H]RFRb RSFSb ROFSF RRPQNPMNMLNKQKWLZN[P[QZRX RNMMNLQLWMZN[ RWMXNYQYWXZW[ RSPTNUMWMYNZQZWYZW[U[TZSX RObVb";
prog_char	gCyrillic_67[]	PROGMEM	=	"14HZMMM[ RNMN[ RJMXMXRWM RJ[Q[";
prog_char	gCyrillic_68[]	PROGMEM	=	"59E`RMR[ RSMS[ ROMVM RJNIOHNIMJMKNMRNSPTUTWSXRZN[M\\M]N\\O[N RPTNUMVKZJ[ RPTNVLZK[I[HZGX RUTWUXVZZ[[ RUTWVYZZ[\\[]Z^X RO[V[";
prog_char	gCyrillic_69[]	PROGMEM	=	"27G]LML[ RMMM[ RWMW[ RXMX[ RIMPM RTM[M RI[P[ RT[[[ RWNMZ";
prog_char	gCyrillic_6A[]	PROGMEM	=	"28G]LMLTMVPWRWUVWT RMMMTNVPW RWMW[ RXMX[ RIMPM RTM[M RT[[[";
prog_char	gCyrillic_6B[]	PROGMEM	=	"38H\\MMM[ RNMN[ RJMQM RNTPTSSTRVNWMXMYNXOWN RPTSUTVVZW[ RPTRUSVUZV[X[YZZX RJ[Q[";
prog_char	gCyrillic_6C[]	PROGMEM	=	"22G]NMNQMWLZK[J[IZJYKZ RWMW[ RXMX[ RKM[M RT[[[";
prog_char	gCyrillic_6D[]	PROGMEM	=	"30G^LML[ RLMR[ RMMRY RXMR[ RXMX[ RYMY[ RIMMM RXM\\M RI[O[ RU[\\[";
prog_char	gCyrillic_6E[]	PROGMEM	=	"27G]LML[ RMMM[ RWMW[ RXMX[ RIMPM RTM[M RMTWT RI[P[ RT[[[";
prog_char	gCyrillic_6F[]	PROGMEM	=	"36H\\QMNNLPKSKULXNZQ[S[VZXXYUYSXPVNSMQM RQMONMPLSLUMXOZQ[ RS[UZWXXUXSWPUNSM";

prog_char	gCyrillic_70[]	PROGMEM	=	"21G]LML[ RMMM[ RWMW[ RXMX[ RIM[M RI[P[ RT[[[";
prog_char	gCyrillic_71[]	PROGMEM	=	"30CbHMH[ RIMI[ RRMR[ RSMS[ R\\M\\[ R]M][ REMLM ROMVM RYM`M RE[`[";
prog_char	gCyrillic_72[]	PROGMEM	=	"36G\\LMLb RMMMb RMPONQMSMVNXPYSYUXXVZS[Q[OZMX RSMUNWPXSXUWXUZS[ RIMMM RIbPb";
prog_char	gCyrillic_73[]	PROGMEM	=	"28H[WPVQWRXQXPVNTMQMNNLPKSKULXNZQ[S[VZXX RQMONMPLSLUMXOZQ[";
prog_char	gCyrillic_74[]	PROGMEM	=	"16I\\RMR[ RSMS[ RMMLRLMYMYRXM RO[V[";
prog_char	gCyrillic_75[]	PROGMEM	=	"51DaIMI[ RJMJ[ RFMMM RF[M[ RVMSNQPPSPUQXSZV[X[[Z]X^U^S]P[NXMVM RVMTNRPQSQURXTZV[ RX[ZZ\\X]U]S\\PZNXM RJTPT";
prog_char	gCyrillic_76[]	PROGMEM	=	"37H\\MMM[ RNMN[ RJMUMXNYPYQXSUT RUMWNXPXQWSUT RNTUTXUYWYXXZU[J[ RUTWUXWXXWZU[";
prog_char	gCyrillic_77[]	PROGMEM	=	"32CbHMH[ RIMI[ RRMR[ RSMS[ R\\M\\[ R]M][ REMLM ROMVM RYM`M RE[`[``_[";
prog_char	gCyrillic_78[]	PROGMEM	=	"21H\\LMW[ RMMX[ RXML[ RJMPM RTMZM RJ[P[ RT[Z[";
prog_char	gCyrillic_79[]	PROGMEM	=	"22I[LMR[ RMMRY RXMR[P_NaLbKbJaK`La RJMPM RTMZM";
prog_char	gCyrillic_7A[]	PROGMEM	=	"42I[MOLMLQMONNPMTMWNXPXQWSTT RTMVNWPWQVSTT RQTTTWUXWXXWZT[P[MZLXLWMVNWMX RTTVUWWWXVZT[";
prog_char	gCyrillic_7B[]	PROGMEM	=	"31H[LSXSXQWOVNTMQMNNLPKSKULXNZQ[S[VZXX RWSWPVN RQMONMPLSLUMXOZQ[";
prog_char	gCyrillic_7C[]	PROGMEM	=	"27H]QMQ[ RRMR[ RLMKRKMUM RRTVTYUZWZXYZV[N[ RVTXUYWYXXZV[";
prog_char	gCyrillic_7D[]	PROGMEM	=	"40G\\VMV[ RWMW[ RZMOMLNKPKQLSOTVT ROMMNLPLQMSOT RTTQUPVNZM[ RTTRUQVOZN[L[KZJX RS[Z[";
prog_char	gCyrillic_7E[]	PROGMEM	=	"25J[OMO[ RPMP[ RLMSM RPTTTWUXWXXWZT[L[ RTTVUWWWXVZT[";
prog_char	gCyrillic_7F[]	PROGMEM	=	"24F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";



PGM_P gHershyCyrillicFontTable[]	PROGMEM =
{

	gCyrillic_00,
	gCyrillic_20,
	gCyrillic_21,
	gCyrillic_22,
	gCyrillic_23,
	gCyrillic_24,
	gCyrillic_25,
	gCyrillic_26,
	gCyrillic_27,
	gCyrillic_28,
	gCyrillic_29,
	gCyrillic_2A,
	gCyrillic_2B,
	gCyrillic_2C,
	gCyrillic_2D,
	gCyrillic_2E,
	gCyrillic_2F,

	gCyrillic_30,
	gCyrillic_31,
	gCyrillic_32,
	gCyrillic_33,
	gCyrillic_34,
	gCyrillic_35,
	gCyrillic_36,
	gCyrillic_37,
	gCyrillic_38,
	gCyrillic_39,
	gCyrillic_3A,
	gCyrillic_3B,
	gCyrillic_3C,
	gCyrillic_3D,
	gCyrillic_3E,
	gCyrillic_3F,

	gCyrillic_40,
	gCyrillic_41,
	gCyrillic_42,
	gCyrillic_43,
	gCyrillic_44,
	gCyrillic_45,
	gCyrillic_46,
	gCyrillic_47,
	gCyrillic_48,
	gCyrillic_49,
	gCyrillic_4A,
	gCyrillic_4B,
	gCyrillic_4C,
	gCyrillic_4D,
	gCyrillic_4E,
	gCyrillic_4F,

	gCyrillic_50,
	gCyrillic_51,
	gCyrillic_52,
	gCyrillic_53,
	gCyrillic_54,
	gCyrillic_55,
	gCyrillic_56,
	gCyrillic_57,
	gCyrillic_58,
	gCyrillic_59,
	gCyrillic_5A,
	gCyrillic_5B,
	gCyrillic_5C,
	gCyrillic_5D,
	gCyrillic_5E,
	gCyrillic_5F,

	gCyrillic_60,
	gCyrillic_61,
	gCyrillic_62,
	gCyrillic_63,
	gCyrillic_64,
	gCyrillic_65,
	gCyrillic_66,
	gCyrillic_67,
	gCyrillic_68,
	gCyrillic_69,
	gCyrillic_6A,
	gCyrillic_6B,
	gCyrillic_6C,
	gCyrillic_6D,
	gCyrillic_6E,
	gCyrillic_6F,

	gCyrillic_70,
	gCyrillic_71,
	gCyrillic_72,
	gCyrillic_73,
	gCyrillic_74,
	gCyrillic_75,
	gCyrillic_76,
	gCyrillic_77,
	gCyrillic_78,
	gCyrillic_79,
	gCyrillic_7A,
	gCyrillic_7B,
	gCyrillic_7C,
	gCyrillic_7D,
	gCyrillic_7E,
	gCyrillic_7F

};
