//*******************************************************************************
//*	rowmand.jhf		Rowmand
//*	formated for use with Arduino Processing 
//*	by Mark Sproul
//*******************************************************************************
//*	Jan 24,	2009	<MLS>	Formated Hershey RowmanDuplex for Arduino
//*******************************************************************************
//#include	"HersheyRowmanDuplex.h"



prog_char	gRowmanDuplex_00[]	PROGMEM	=	"Rowman Duplex";


prog_char	gRowmanDuplex_20[]	PROGMEM	=	" 1JZ";
prog_char	gRowmanDuplex_21[]	PROGMEM	=	"24MXRFRTST RRFSFST RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY";
prog_char	gRowmanDuplex_22[]	PROGMEM	=	"22I[NFMGMM RNGMM RNFOGMM RWFVGVM RWGVM RWFXGVM";
prog_char	gRowmanDuplex_23[]	PROGMEM	=	"12H]SFLb RYFRb RLQZQ RKWYW";
prog_char	gRowmanDuplex_24[]	PROGMEM	=	"51I\\RBR_S_ RRBSBS_ RWIYIWGTFQFNGLILKMMNNVRWSXUXWWYTZQZOYNX RWIVHTGQGNHMIMKNMVQXSYUYWXYWZT[Q[NZLXNX RXXUZ";
prog_char	gRowmanDuplex_25[]	PROGMEM	=	"32F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT";
prog_char	gRowmanDuplex_26[]	PROGMEM	=	"71F_\\MZMXNWPUVTXSYQZMZKYJWJUKSLRQOSMTKTISGQFPFNGMIMKNNPQUWXZZ[\\[ R\\M\\NZNXO RYNXPVVUXSZQ[M[KZJYIWIUJSLQQNRMSKSIRG RSHQGPGNH ROGNINKONQQVWXYZZ\\Z\\[";
prog_char	gRowmanDuplex_27[]	PROGMEM	=	"24MXTHSIRIQHQGRFSFTGTJSLQM RRGRHSHSGRG RSITJ RTHSL";
prog_char	gRowmanDuplex_28[]	PROGMEM	=	"24KYUBSDQGOKNPNTOYQ]S`UbVb RUBVBTDRGPKOPOTPYR]T`Vb";
prog_char	gRowmanDuplex_29[]	PROGMEM	=	"24KYNBPDRGTKUPUTTYR]P`NbOb RNBOBQDSGUKVPVTUYS]Q`Ob";
prog_char	gRowmanDuplex_2A[]	PROGMEM	=	"39JZRFQGSQRR RRFRR RRFSGQQRR RMINIVOWO RMIWO RMIMJWNWO RWIVINOMO RWIMO RWIWJMNMO";
prog_char	gRowmanDuplex_2B[]	PROGMEM	=	"16F_RIRZSZ RRISISZ RJQ[Q[R RJQJR[R";
prog_char	gRowmanDuplex_2C[]	PROGMEM	=	"24MXTZS[R[QZQYRXSXTYT\\S^Q_ RRYRZSZSYRY RS[T\\ RTZS^";
prog_char	gRowmanDuplex_2D[]	PROGMEM	=	" 8F_JQ[Q[R RJQJR[R";
prog_char	gRowmanDuplex_2E[]	PROGMEM	=	"16MXRXQYQZR[S[TZTYSXRX RRYRZSZSYRY";
prog_char	gRowmanDuplex_2F[]	PROGMEM	=	" 8G^[BIbJb R[B\\BJb";

prog_char	gRowmanDuplex_30[]	PROGMEM	=	"42H\\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF ROGMJLOLRMWOZ RNYQZSZVY RUZWWXRXOWJUG RVHSGQGNH";
prog_char	gRowmanDuplex_31[]	PROGMEM	=	"12H\\NJPISFS[ RNJNKPJRHR[S[";
prog_char	gRowmanDuplex_32[]	PROGMEM	=	"34H\\LKLJMHNGPFTFVGWHXJXLWNUQL[ RLKMKMJNHPGTGVHWJWLVNTQK[ RLZYZY[ RK[Y[";
prog_char	gRowmanDuplex_33[]	PROGMEM	=	"48H\\MFXFQO RMFMGWG RWFPO RQNSNVOXQYTYUXXVZS[P[MZLYKWLW RPOSOVPXS RTOWQXTXUWXTZ RXVVYSZPZMYLW ROZLX";
prog_char	gRowmanDuplex_34[]	PROGMEM	=	"18H\\UIU[V[ RVFV[ RVFKVZV RUILV RLUZUZV";
prog_char	gRowmanDuplex_35[]	PROGMEM	=	"53H\\MFLO RNGMN RMFWFWG RNGWG RMNPMSMVNXPYSYUXXVZS[P[MZLYKWLW RLOMOONSNVOXR RTNWPXSXUWXTZ RXVVYSZPZMYLW ROZLX";
prog_char	gRowmanDuplex_36[]	PROGMEM	=	"62H\\VGWIXIWGTFRFOGMJLOLTMXOZR[S[VZXXYUYTXQVOSNRNOOMQ RWHTGRGOH RPGNJMOMTNXQZ RMVOYRZSZVYXV RTZWXXUXTWQTO RXSVPSOROOPMS RQONQMT";
prog_char	gRowmanDuplex_37[]	PROGMEM	=	"12H\\KFYFO[ RKFKGXG RXFN[O[";
prog_char	gRowmanDuplex_38[]	PROGMEM	=	"68H\\PFMGLILKMMNNPOTPVQWRXTXWWYTZPZMYLWLTMRNQPPTOVNWMXKXIWGTFPF RNGMIMKNMPNTOVPXRYTYWXYWZT[P[MZLYKWKTLRNPPOTNVMWKWIVG RWHTGPGMH RLXOZ RUZXX";
prog_char	gRowmanDuplex_39[]	PROGMEM	=	"62H\\WPURRSQSNRLPKMKLLINGQFRFUGWIXMXRWWUZR[P[MZLXMXNZ RWMVPSR RWNUQRRQRNQLN RPRMPLMLLMIPG RLKNHQGRGUHWK RSGVIWMWRVWTZ RUYRZPZMY";
prog_char	gRowmanDuplex_3A[]	PROGMEM	=	"32MXRMQNQORPSPTOTNSMRM RRNROSOSNRN RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY";
prog_char	gRowmanDuplex_3B[]	PROGMEM	=	"40MXRMQNQORPSPTOTNSMRM RRNROSOSNRN RTZS[R[QZQYRXSXTYT\\S^Q_ RRYRZSZSYRY RS[T\\ RTZS^";
prog_char	gRowmanDuplex_3C[]	PROGMEM	=	" 4F^ZIJRZ[";
prog_char	gRowmanDuplex_3D[]	PROGMEM	=	"16F_JM[M[N RJMJN[N RJU[U[V RJUJV[V";
prog_char	gRowmanDuplex_3E[]	PROGMEM	=	" 4F^JIZRJ[";
prog_char	gRowmanDuplex_3F[]	PROGMEM	=	"58I\\LKLJMHNGQFTFWGXHYJYLXNWOUPRQ RLKMKMJNHQGTGWHXJXLWNUORP RMIPG RUGXI RXMTP RRPRTSTSP RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY";

prog_char	gRowmanDuplex_40[]	PROGMEM	=	"56E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
prog_char	gRowmanDuplex_41[]	PROGMEM	=	"20H\\RFJ[ RRIK[J[ RRIY[Z[ RRFZ[ RMUWU RLVXV";
prog_char	gRowmanDuplex_42[]	PROGMEM	=	"44H\\LFL[ RMGMZ RLFTFWGXHYJYMXOWPTQ RMGTGWHXJXMWOTP RMPTPWQXRYTYWXYWZT[L[ RMQTQWRXTXWWYTZMZ";
prog_char	gRowmanDuplex_43[]	PROGMEM	=	"38H]ZKYIWGUFQFOGMILKKNKSLVMXOZQ[U[WZYXZV RZKYKXIWHUGQGOHMKLNLSMVOYQZUZWYXXYVZV";
prog_char	gRowmanDuplex_44[]	PROGMEM	=	"32H]LFL[ RMGMZ RLFSFVGXIYKZNZSYVXXVZS[L[ RMGSGVHWIXKYNYSXVWXVYSZMZ";
prog_char	gRowmanDuplex_45[]	PROGMEM	=	"27I\\MFM[ RNGNZ RMFYF RNGYGYF RNPTPTQ RNQTQ RNZYZY[ RM[Y[";
prog_char	gRowmanDuplex_46[]	PROGMEM	=	"21I[MFM[ RNGN[M[ RMFYF RNGYGYF RNPTPTQ RNQTQ";
prog_char	gRowmanDuplex_47[]	PROGMEM	=	"44H]ZKYIWGUFQFOGMILKKNKSLVMXOZQ[U[WZYXZVZRUR RZKYKXIWHUGQGOHNIMKLNLSMVNXOYQZUZWYXXYVYSUSUR";
prog_char	gRowmanDuplex_48[]	PROGMEM	=	"22G]KFK[ RKFLFL[K[ RYFXFX[Y[ RYFY[ RLPXP RLQXQ";
prog_char	gRowmanDuplex_49[]	PROGMEM	=	" 8NWRFR[S[ RRFSFS[";
prog_char	gRowmanDuplex_4A[]	PROGMEM	=	"20J[VFVVUYSZQZOYNVMV RVFWFWVVYUZS[Q[OZNYMV";
prog_char	gRowmanDuplex_4B[]	PROGMEM	=	"22H]LFL[M[ RLFMFM[ RZFYFMR RZFMS RPOY[Z[ RQOZ[";
prog_char	gRowmanDuplex_4C[]	PROGMEM	=	"14IZMFM[ RMFNFNZ RNZYZY[ RM[Y[";
prog_char	gRowmanDuplex_4D[]	PROGMEM	=	"26F^JFJ[ RKKK[J[ RKKR[ RJFRX RZFRX RYKR[ RYKY[Z[ RZFZ[";
prog_char	gRowmanDuplex_4E[]	PROGMEM	=	"20G]KFK[ RLIL[K[ RLIY[ RKFXX RXFXX RXFYFY[";
prog_char	gRowmanDuplex_4F[]	PROGMEM	=	"40G]PFNGLIKKJNJSKVLXNZP[T[VZXXYVZSZNYKXIVGTFPF RQGNHLKKNKSLVNYQZSZVYXVYSYNXKVHSGQG";

prog_char	gRowmanDuplex_50[]	PROGMEM	=	"27H\\LFL[ RMGM[L[ RLFUFWGXHYJYMXOWPUQMQ RMGUGWHXJXMWOUPMP";
prog_char	gRowmanDuplex_51[]	PROGMEM	=	"48G]PFNGLIKKJNJSKVLXNZP[T[VZXXYVZSZNYKXIVGTFPF RQGNHLKKNKSLVNYQZSZVYXVYSYNXKVHSGQG RSXX]Y] RSXTXY]";
prog_char	gRowmanDuplex_52[]	PROGMEM	=	"34H\\LFL[ RMGM[L[ RLFTFWGXHYJYMXOWPTQMQ RMGTGWHXJXMWOTPMP RRQX[Y[ RSQY[";
prog_char	gRowmanDuplex_53[]	PROGMEM	=	"43H\\YIWGTFPFMGKIKKLMMNOOTQVRWSXUXXWYTZPZNYMXKX RYIWIVHTGPGMHLILKMMONTPVQXSYUYXWZT[P[MZKX";
prog_char	gRowmanDuplex_54[]	PROGMEM	=	"15J[RGR[ RSGS[R[ RLFYFYG RLFLGYG";
prog_char	gRowmanDuplex_55[]	PROGMEM	=	"24G]KFKULXNZQ[S[VZXXYUYF RKFLFLUMXNYQZSZVYWXXUXFYF";
prog_char	gRowmanDuplex_56[]	PROGMEM	=	"14H\\JFR[ RJFKFRX RZFYFRX RZFR[";
prog_char	gRowmanDuplex_57[]	PROGMEM	=	"26E_GFM[ RGFHFMX RRFMX RRIM[ RRIW[ RRFWX R]F\\FWX R]FW[";
prog_char	gRowmanDuplex_58[]	PROGMEM	=	"16H\\KFX[Y[ RKFLFY[ RYFXFK[ RYFL[K[";
prog_char	gRowmanDuplex_59[]	PROGMEM	=	"17I\\KFRPR[S[ RKFLFSP RZFYFRP RZFSPS[";
prog_char	gRowmanDuplex_5A[]	PROGMEM	=	"20H\\XFK[ RYFL[ RKFYF RKFKGXG RLZYZY[ RK[Y[";
prog_char	gRowmanDuplex_5B[]	PROGMEM	=	"12KYOBOb RPBPb ROBVB RObVb";
prog_char	gRowmanDuplex_5C[]	PROGMEM	=	" 3KYKFY^";
prog_char	gRowmanDuplex_5D[]	PROGMEM	=	"12KYTBTb RUBUb RNBUB RNbUb";
prog_char	gRowmanDuplex_5E[]	PROGMEM	=	"11JZPLRITL RMORJWO RRJR[";
prog_char	gRowmanDuplex_5F[]	PROGMEM	=	" 3JZJ]Z]";

prog_char	gRowmanDuplex_60[]	PROGMEM	=	"24MXTFRGQIQLRMSMTLTKSJRJQK RRKRLSLSKRK RRGQK RQIRJ";
prog_char	gRowmanDuplex_61[]	PROGMEM	=	"36H\\WMW[X[ RWMXMX[ RWPUNSMPMNNLPKSKULXNZP[S[UZWX RWPSNPNNOMPLSLUMXNYPZSZWX";
prog_char	gRowmanDuplex_62[]	PROGMEM	=	"36H\\LFL[M[ RLFMFM[ RMPONQMTMVNXPYSYUXXVZT[Q[OZMX RMPQNTNVOWPXSXUWXVYTZQZMX";
prog_char	gRowmanDuplex_63[]	PROGMEM	=	"32I[XPVNTMQMONMPLSLUMXOZQ[T[VZXX RXPWQVOTNQNOONPMSMUNXOYQZTZVYWWXX";
prog_char	gRowmanDuplex_64[]	PROGMEM	=	"36H\\WFW[X[ RWFXFX[ RWPUNSMPMNNLPKSKULXNZP[S[UZWX RWPSNPNNOMPLSLUMXNYPZSZWX";
prog_char	gRowmanDuplex_65[]	PROGMEM	=	"36I[MTXTXQWOVNTMQMONMPLSLUMXOZQ[T[VZXX RMSWSWQVOTNQNOONPMSMUNXOYQZTZVYWWXX";
prog_char	gRowmanDuplex_66[]	PROGMEM	=	"24LZWFUFSGRJR[S[ RWFWGUGSH RTGSJS[ ROMVMVN ROMONVN";
prog_char	gRowmanDuplex_67[]	PROGMEM	=	"48H\\XMWMW\\V_U`SaQaO`N_L_ RXMX\\W_UaSbPbNaL_ RWPUNSMPMNNLPKSKULXNZP[S[UZWX RWPSNPNNOMPLSLUMXNYPZSZWX";
prog_char	gRowmanDuplex_68[]	PROGMEM	=	"25H\\LFL[M[ RLFMFM[ RMQPNRMUMWNXQX[ RMQPORNTNVOWQW[X[";
prog_char	gRowmanDuplex_69[]	PROGMEM	=	"24NWRFQGQHRISITHTGSFRF RRGRHSHSGRG RRMR[S[ RRMSMS[";
prog_char	gRowmanDuplex_6A[]	PROGMEM	=	"24NWRFQGQHRISITHTGSFRF RRGRHSHSGRG RRMRbSb RRMSMSb";
prog_char	gRowmanDuplex_6B[]	PROGMEM	=	"22H[LFL[M[ RLFMFM[ RXMWMMW RXMMX RPTV[X[ RQSX[";
prog_char	gRowmanDuplex_6C[]	PROGMEM	=	" 8NWRFR[S[ RRFSFS[";
prog_char	gRowmanDuplex_6D[]	PROGMEM	=	"42CbGMG[H[ RGMHMH[ RHQKNMMPMRNSQS[ RHQKOMNONQORQR[S[ RSQVNXM[M]N^Q^[ RSQVOXNZN\\O]Q][^[";
prog_char	gRowmanDuplex_6E[]	PROGMEM	=	"25H\\LML[M[ RLMMMM[ RMQPNRMUMWNXQX[ RMQPORNTNVOWQW[X[";
prog_char	gRowmanDuplex_6F[]	PROGMEM	=	"36I\\QMONMPLSLUMXOZQ[T[VZXXYUYSXPVNTMQM RQNOONPMSMUNXOYQZTZVYWXXUXSWPVOTNQN";

prog_char	gRowmanDuplex_70[]	PROGMEM	=	"36H\\LMLbMb RLMMMMb RMPONQMTMVNXPYSYUXXVZT[Q[OZMX RMPQNTNVOWPXSXUWXVYTZQZMX";
prog_char	gRowmanDuplex_71[]	PROGMEM	=	"36H\\WMWbXb RWMXMXb RWPUNSMPMNNLPKSKULXNZP[S[UZWX RWPSNPNNOMPLSLUMXNYPZSZWX";
prog_char	gRowmanDuplex_72[]	PROGMEM	=	"21KYOMO[P[ ROMPMP[ RPSQPSNUMXM RPSQQSOUNXNXM";
prog_char	gRowmanDuplex_73[]	PROGMEM	=	"50J[XPWNTMQMNNMPNRPSUUWV RVUWWWXVZ RWYTZQZNY ROZNXMX RXPWPVN RWOTNQNNO RONNPOR RNQPRUTWUXWXXWZT[Q[NZMX";
prog_char	gRowmanDuplex_74[]	PROGMEM	=	"16MXRFR[S[ RRFSFS[ ROMVMVN ROMONVN";
prog_char	gRowmanDuplex_75[]	PROGMEM	=	"25H\\LMLWMZO[R[TZWW RLMMMMWNYPZRZTYWW RWMW[X[ RWMXMX[";
prog_char	gRowmanDuplex_76[]	PROGMEM	=	"14JZLMR[ RLMMMRY RXMWMRY RXMR[";
prog_char	gRowmanDuplex_77[]	PROGMEM	=	"26F^IMN[ RIMJMNX RRMNX RRPN[ RRPV[ RRMVX R[MZMVX R[MV[";
prog_char	gRowmanDuplex_78[]	PROGMEM	=	"16I[LMW[X[ RLMMMX[ RXMWML[ RXMM[L[";
prog_char	gRowmanDuplex_79[]	PROGMEM	=	"17JZLMR[ RLMMMRY RXMWMRYNb RXMR[ObNb";
prog_char	gRowmanDuplex_7A[]	PROGMEM	=	"20I[VNL[ RXMNZ RLMXM RLMLNVN RNZXZX[ RL[X[";
prog_char	gRowmanDuplex_7B[]	PROGMEM	=	"40KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
prog_char	gRowmanDuplex_7C[]	PROGMEM	=	" 3NVRBRb";
prog_char	gRowmanDuplex_7D[]	PROGMEM	=	"40KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
prog_char	gRowmanDuplex_7E[]	PROGMEM	=	"24F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
prog_char	gRowmanDuplex_7F[]	PROGMEM	=	"30KYQFOGNINKOMQNSNUMVKVIUGSFQF RQFNIOMSNVKUGQF RSFOGNKQNUMVISF";


PGM_P gHershyRowmanDuplexFontTable[]	PROGMEM =	   // change "string_table" name to suit
{

	gRowmanDuplex_00,
	gRowmanDuplex_20,
	gRowmanDuplex_21,
	gRowmanDuplex_22,
	gRowmanDuplex_23,
	gRowmanDuplex_24,
	gRowmanDuplex_25,
	gRowmanDuplex_26,
	gRowmanDuplex_27,
	gRowmanDuplex_28,
	gRowmanDuplex_29,
	gRowmanDuplex_2A,
	gRowmanDuplex_2B,
	gRowmanDuplex_2C,
	gRowmanDuplex_2D,
	gRowmanDuplex_2E,
	gRowmanDuplex_2F,

	gRowmanDuplex_30,
	gRowmanDuplex_31,
	gRowmanDuplex_32,
	gRowmanDuplex_33,
	gRowmanDuplex_34,
	gRowmanDuplex_35,
	gRowmanDuplex_36,
	gRowmanDuplex_37,
	gRowmanDuplex_38,
	gRowmanDuplex_39,
	gRowmanDuplex_3A,
	gRowmanDuplex_3B,
	gRowmanDuplex_3C,
	gRowmanDuplex_3D,
	gRowmanDuplex_3E,
	gRowmanDuplex_3F,

	gRowmanDuplex_40,
	gRowmanDuplex_41,
	gRowmanDuplex_42,
	gRowmanDuplex_43,
	gRowmanDuplex_44,
	gRowmanDuplex_45,
	gRowmanDuplex_46,
	gRowmanDuplex_47,
	gRowmanDuplex_48,
	gRowmanDuplex_49,
	gRowmanDuplex_4A,
	gRowmanDuplex_4B,
	gRowmanDuplex_4C,
	gRowmanDuplex_4D,
	gRowmanDuplex_4E,
	gRowmanDuplex_4F,

	gRowmanDuplex_50,
	gRowmanDuplex_51,
	gRowmanDuplex_52,
	gRowmanDuplex_53,
	gRowmanDuplex_54,
	gRowmanDuplex_55,
	gRowmanDuplex_56,
	gRowmanDuplex_57,
	gRowmanDuplex_58,
	gRowmanDuplex_59,
	gRowmanDuplex_5A,
	gRowmanDuplex_5B,
	gRowmanDuplex_5C,
	gRowmanDuplex_5D,
	gRowmanDuplex_5E,
	gRowmanDuplex_5F,

	gRowmanDuplex_60,
	gRowmanDuplex_61,
	gRowmanDuplex_62,
	gRowmanDuplex_63,
	gRowmanDuplex_64,
	gRowmanDuplex_65,
	gRowmanDuplex_66,
	gRowmanDuplex_67,
	gRowmanDuplex_68,
	gRowmanDuplex_69,
	gRowmanDuplex_6A,
	gRowmanDuplex_6B,
	gRowmanDuplex_6C,
	gRowmanDuplex_6D,
	gRowmanDuplex_6E,
	gRowmanDuplex_6F,

	gRowmanDuplex_70,
	gRowmanDuplex_71,
	gRowmanDuplex_72,
	gRowmanDuplex_73,
	gRowmanDuplex_74,
	gRowmanDuplex_75,
	gRowmanDuplex_76,
	gRowmanDuplex_77,
	gRowmanDuplex_78,
	gRowmanDuplex_79,
	gRowmanDuplex_7A,
	gRowmanDuplex_7B,
	gRowmanDuplex_7C,
	gRowmanDuplex_7D,
	gRowmanDuplex_7E,
	gRowmanDuplex_7F

};
