//*******************************************************************************
//*	Gothic German Font
//*	formated for use with Arduino Processing 
//*	by Mark Sproul
//*******************************************************************************
//*	Feb 28,	2009	<MLS> Formated Hershey Gothic gbt for Arduino
//*******************************************************************************
//#include	"HersheyGothgbt.h"

prog_char	gGothgbt_00[]	PROGMEM	=	"Gothic gbt";

prog_char	gGothgbt_20[]	PROGMEM	=	" 1JZ";
prog_char	gGothgbt_21[]	PROGMEM	=	"30LXRFQGOHQIRT RRISHRGQHRIRT RRFSGUHSIRT RRXPZR[TZRX RRYQZSZRY";
prog_char	gGothgbt_22[]	PROGMEM	=	"22I[NFMGMM RNGMM RNFOGMM RWFVGVM RWGVM RWFXGVM";
prog_char	gGothgbt_23[]	PROGMEM	=	"12H]SFLb RYFRb RLQZQ RKWYW";
prog_char	gGothgbt_24[]	PROGMEM	=	"60H\\PBP_ RTBT_ RTFVGWIWKYJXHWGTFPFMGKIKLLNOPURWSXUXXWZ RXJWH RLLMNOOUQWRXT RMYLW RMGLILKMMONUPXRYTYWXYWZT[P[MZLYKWMVMXNZP[";
prog_char	gGothgbt_25[]	PROGMEM	=	"32F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT";
prog_char	gGothgbt_26[]	PROGMEM	=	"62E_YNZO[O\\N RXOYP[P RXPYQZQ[P\\N RYNST RRUL[HVNP ROOSKOFJLPRTXVZX[Z[[Z\\X RLZIV RRKOG RKLPQTWVYXZ[Z RMZIU RRLNG RKKQQUWVXXY[Y\\X";
prog_char	gGothgbt_27[]	PROGMEM	=	"14LXRLRJPHRFSHSJRLPM RRGQHRIRG";
prog_char	gGothgbt_28[]	PROGMEM	=	"27KYUBSDQGOKNPNTOYQ]S`Ub RQHPKOOOUPYQ\\ RSDRFQIPOPUQ[R^S`";
prog_char	gGothgbt_29[]	PROGMEM	=	"27KYOBQDSGUKVPVTUYS]Q`Ob RSHTKUOUUTYS\\ RQDRFSITOTUS[R^Q`";
prog_char	gGothgbt_2A[]	PROGMEM	=	"39JZRFQGSQRR RRFRR RRFSGQQRR RMINIVOWO RMIWO RMIMJWNWO RWIVINOMO RWIMO RWIWJMNMO";
prog_char	gGothgbt_2B[]	PROGMEM	=	"16F_RIRZSZ RRISISZ RJQ[Q[R RJQJR[R";
prog_char	gGothgbt_2C[]	PROGMEM	=	"14LXR^R\\PZRXSZS\\R^P_ RRYQZR[RY";
prog_char	gGothgbt_2D[]	PROGMEM	=	" 8F_JQ[Q[R RJQJR[R";
prog_char	gGothgbt_2E[]	PROGMEM	=	"11LXRXPZR[TZRX RRYQZSZRY";
prog_char	gGothgbt_2F[]	PROGMEM	=	" 8G^[BIbJb R[B\\BJb";

prog_char	gGothgbt_30[]	PROGMEM	=	"42H\\LHLXJY RMIMXPZ RNHNXPYQZ RLHNHSGUF RSGTHVIVY RTGWIWX RUFVGXHZHXIXY RJYLYNZO[QZVYXY";
prog_char	gGothgbt_31[]	PROGMEM	=	"27H\\OHPIQKQXOY RQIPHQGRIRYTZ ROHRFSHSXUYVY ROYPYRZS[TZVY";
prog_char	gGothgbt_32[]	PROGMEM	=	"48H\\LHNHPGQFSGVHXH RPHRG RLHNIPIRHSG RVHVP RWIWO RXHXPQPNQLSKVK[ RK[OYSXVXZY RNZQYVYYZ RK[PZUZX[ZY";
prog_char	gGothgbt_33[]	PROGMEM	=	"57H\\LHMHOGPFRGVHXH ROHQG RLHNIPIRG RVHVO RWIWN RXHXOVOSPQQ RQPSQVRXRXY RWSWX RVRVY RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY";
prog_char	gGothgbt_34[]	PROGMEM	=	"41H\\UFKPKUTU RVUZU[V[TZU RLPLT RMNMU RTGTXRY RUJVHUGUYWZ RUFWHVJVXXYYY RRYSYUZV[WZYY";
prog_char	gGothgbt_35[]	PROGMEM	=	"53H\\LFLO RLFXF RMGVG RLHUHWGXF RVLUMSNOOLO RSNTNVOVY RUMWNWX RVLWMYNZNXOXY RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY";
prog_char	gGothgbt_36[]	PROGMEM	=	"59H\\LHLXJY RMIMXPZ RNHNXPYQZ RLHNHRGTFUGWHXH RSGUH RRGTIVIXH RNPOPSOUNVM RSOTOVPVY RUNWPWX RVMWNYOZOXPXY RJYLYNZO[QZVYXY";
prog_char	gGothgbt_37[]	PROGMEM	=	"38H\\KHMFPGUGZF RLGOHTHWG RKHOIRIVHZF RZFYHWKSOQRPUPXQ[ RRQQTQWRZ RUMSPRSRVSYQ[";
prog_char	gGothgbt_38[]	PROGMEM	=	"71H\\LILO RMJMN RNINO RLINISHUGVF RSHTHVIVO RUGWHWN RVFWGYHZHXIXO RLONOVRXR RXOVONRLR RLRLXJY RMSMXPZ RNRNXPYQZ RVRVY RWSWX RXRXY RJYLYNZO[QZVYXY";
prog_char	gGothgbt_39[]	PROGMEM	=	"60H\\LHLQJR RMIMROS RNHNQPRQR RLHNHSGUF RSGTHVIVY RTGWIWX RUFVGXHZHXIXY RJRKRMSNTOSQRUQVQ RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY";
prog_char	gGothgbt_3A[]	PROGMEM	=	"22LXRMPORPTORM RRNQOSORN RRXPZR[TZRX RRYQZSZRY";
prog_char	gGothgbt_3B[]	PROGMEM	=	"25LXRMPORPTORM RRNQOSORN RR^R\\PZRXSZS\\R^P_ RRYQZR[RY";
prog_char	gGothgbt_3C[]	PROGMEM	=	" 4F^ZIJRZ[";
prog_char	gGothgbt_3D[]	PROGMEM	=	"16F_JM[M[N RJMJN[N RJU[U[V RJUJV[V";
prog_char	gGothgbt_3E[]	PROGMEM	=	" 4F^JIZRJ[";
prog_char	gGothgbt_3F[]	PROGMEM	=	"51I[LJMHNGQFSFVGWHXJXLWNUPSQ RMJNH RVHWIWMVN RLJNKNIOGQF RSFUGVIVMUOSQ RRQRTSQQQRT RRXPZR[TZRX RRYQZSZRY";

prog_char	gGothgbt_40[]	PROGMEM	=	"56E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
prog_char	gGothgbt_41[]	PROGMEM	=	"60G]LINGPFRFSGZW[X]X RQGRHYXZZ[YYX RNGPGQHXXYZZ[[[]X RLMMLOKPKQL RPLPM RMLOLPN RG[IYKXNXPY RJYNYOZ RG[JZMZN[PY RRJLX RNSVS";
prog_char	gGothgbt_42[]	PROGMEM	=	"10F^HHJFMFOGQF RKGNG RHHJGLHOHQF RMKLLKNKOIOHPHRIQKQKW RLMLU RIPLP RMKMTLVKW RRIQJPLPU RQKQS RRIRRQTPU RRIXFZG[I[KYMUO RXGZIZK RVGXHYIYLWN RWNZP[R[X RYPZRZW RWNXOYQYX RJ[MYPXTXWY RLZOYTYVZ RJ[NZSZU[WYYX[X RUOUX RURYR RUUYU";
prog_char	gGothgbt_43[]	PROGMEM	=	"69E]NGLHJJILHOHSIVJXMZP[S[VZXYZW[U RJKINISKWNYQZTZWY RNGLIKKJNJRKUNXQYTYWXYW[U RPJPV RQJQT RRIRSQUPV RPJRIUFWGYGZF RTGVHXH RSHUIWIYHZF RWIWX";
prog_char	gGothgbt_44[]	PROGMEM	=	"72G^IFWFYGZIZX RKGWGYIYW RIFJGLHWHXIXX ROKNLMNMOKOJPJRKQMQMV RNMNT RKPNP ROKOSNUMV RI[LYOXSXVY RKZNYSYUZ RI[MZRZT[VYXXZX RRHRX RRMTNVNXM RRSTRVRXS";
prog_char	gGothgbt_45[]	PROGMEM	=	"94G]IHKFMFOGQF RLGNG RIHKGMHOHQF RNKMLLNLOJOIPIRJQLQLW RMMMU RJPMP RNKNTMVLW RQMRJSHTGVFXF[G RTHVGXGZH RRJSIUHWHYI[G RQURRSPTOVOXP RTPVPWQ RRRSQUQVRXP RK[NYRXWX[Y RMZPYWYZZ RK[OZVZY[[Y RQMQX";
prog_char	gGothgbt_46[]	PROGMEM	=	"91F]JHLFOFQGSF RMGPG RJHLGNHQHSF RPKOLNNNOLOKPKRLQNQNV ROMOT RLPOP RPKPSOUNV RSJSYRZQZMXKXIYG[ RTJTX RTPXP RPZOZMYJY RUIUOXO RXQUQUWTYP[N[LZJZG[ RSJUIXFZG\\G]F RWGYH[H RVHXIZI\\H]F RXIXW";
prog_char	gGothgbt_47[]	PROGMEM	=	"87E^NGLHJJILHOHRIUJWLYNZQ[U[XZZX[V[SZQYPWOUO RJKINISJV RNGLIKKJNJSKVLXNZ RYXZWZSYQ RU[WZXYYWYSXQWPUO RPJPW RQJQU RRIRTQVPW RPJRIUFWGYGZF RTGVHXH RSHUIWIYHZF RYHUOU[ RUSYS RUVYV";
prog_char	gGothgbt_48[]	PROGMEM	=	"12F^HHJFMFOGQF RKGNG RHHJGLHOHQF RMKLLKNKOIOHPHRIQKQKW RLMLU RIPLP RMKMTLVKW RJ[MYPXSXUY RLZOYRYTZ RJ[NZQZS[UY RRIQJPLPU RQKQS RRIRRQTPU RRITGVFXFZG RWGXGYH RTGVGXIZG RUOWNYLZM[P[TZXX[ RXMYNZPZUYX RWNXNYPYUX[ RUOUY RURYR RUUYU";
prog_char	gGothgbt_49[]	PROGMEM	=	"67I\\LHNFQFTGVF ROGSG RLHNGQHTHVF RSKRLQNQOOONPNROQQQQV RRMRT ROPRP RSKSSRUQV RYHWJVMVXUZSZOXMXKYI[ RWKWW RRZQZOYLY RYHXJXVWXUZS[P[NZKZI[";
prog_char	gGothgbt_4A[]	PROGMEM	=	"65H\\LHNFQFTGVF ROGSG RLHNGQHTHVF RSKRLQNQOOONPNROQQQQV RRMRT ROPRP RSKSSRUQV RYHWJVMVXUZ RWKWW RYHXJXVWXUZR[O[LZJXJVKULUMVLWKW RJVMV";
prog_char	gGothgbt_4B[]	PROGMEM	=	"15F^HHJFMFOGQF RKGNG RHHJGLHOHQF RMKLLKNKOIOHPHRIQKQKW RLMLU RIPLP RMKMTLVKW RJ[MYPXSXUY RLZNYRYTZ RJ[NZQZS[UY RRIQJPLPU RQKQS RRIRRQTPU RRITGVFXFZG RWGXGYH RTGVGXIZG RUOXLYM[N RWMYN[N R[NYQWSUU RWSYTZX[Z\\Z RYVZZ RWSXTYZZ[[[\\Z RUOUY";
prog_char	gGothgbt_4C[]	PROGMEM	=	"85G]IHKFNFPGRF RLGOG RIHKGMHPHRF RNKMLLNLOJOIPIRJQLQLW RMMMU RJPMP RNKNTMVLW RK[NYRXWX[Y RMZPYWYZZ RK[OZVZY[[Y RSIRJQLQU RRKRS RSISRRTQU RSIUGWFYF[G RXGYGZH RUGWGYI[G RWGWX";
prog_char	gGothgbt_4D[]	PROGMEM	=	"07D`LJKKJMJOHOGPGRHQJQJU RKLKS RHPKP RLJLRKTJU RE[GYIXKXMYNYOX RHYKYMZ RE[GZJZL[M[NZOX RLJPFTJTWUYVY RPGSJSXRYSZTYSX RPPSP RNHOHRKROOO ROQRQRXQYS[VYWX RTJXF\\J\\W]Y^Y RXG[J[X]Z RXP[P RVHWHZKZOWO RWQZQZY\\[^Y ROHOX RWHWX";
prog_char	gGothgbt_4E[]	PROGMEM	=	"84E^GIIGKFMFOGQJVUXXYY RMGOIPKVWYZ RIGKGMHOKTVVYWZY[ RVHXIZI\\H]F RWGYH[H RVHXFZG\\G]F RKOIOHPHRIQKQ RIPKP RG[IYKXNXPY RJYMYOZ RG[JZMZN[PY RKGKX RYIY[ RRLSMUNWNYM RKTMSQSST";
prog_char	gGothgbt_4F[]	PROGMEM	=	"79E_NFLGJIIKHNHRIUJWLYNZQ[S[VZXYZW[U\\R\\N[KZIXGVFUGRIOJ RJJIMISJV RNFLHKJJMJSKVLXNZ RZV[S[MYIXH RVZXXYVZSZMYKWHUG ROJOW RPJPU RQJQTPVOW RUGUZ RUMWNXNZM RUSWRXRZS";

prog_char	gGothgbt_50[]	PROGMEM	=	"70H^KFLGMIMOKOJPJRKQMQMYJ[MZMbO` RMHNJN` RKPNP RKFMGNHOJO` ROKRIVFZJZX RVGYJYX RTHUHXKXY RRXUXXY RSYUYWZ RRZTZV[XYZX RRIR_ RRMTNVNXM RRSTRVRXS";
prog_char	gGothgbt_51[]	PROGMEM	=	"99E_NFLGJIIKHNHRIUJWLYNZP[T[VZXYZW[U\\R\\N[KZIXGVFUGRIOJ RJJIMISJV RNFLHKJJMJSKVLXNZ RZV[S[MYIXH RVZXXYVZSZMYKWHUG ROJOW RPJPU RQJQTPVOW RUGUZ RUMWNXNZM RUSWRXRZS RP[QZRZT[X`Za[a RT\\V_XaYa RRZS[VaXbZb[a";
prog_char	gGothgbt_52[]	PROGMEM	=	"08F^HHJFMFOGQF RKGNG RHHJGLHOHQF RMKLLKNKOIOHPHRIQKQKW RLMLU RIPLP RMKMTLVKW RJ[MYPXRXUY RLZNYRYTZ RJ[NZQZS[UY RRIQJPLPU RQKQS RRIRRQTPU RRIUGWFYGZIZLYNXOTQRR RWGXGYIYMXN RUGWHXJXMWOTQ RTQVRWSZX[Y\\Y RWTYX[Z RTQVSXYZ[\\Y";
prog_char	gGothgbt_53[]	PROGMEM	=	"94G^UITHRGOF RVHTG RWGSFOFLGKHJJKLLMONWNYOZPZRYU RKKLLOMXMZN[O[QZS RKHKJLKOLYL[M\\O\\QYUU[ RIOJPLQUQVRVSUU RJQLRTRUS RIOIPJRLSSSUTUU RI[LYPXSXVY RKZNYRYUZ RI[MZRZU[ RWGUISL RRNPQ ROSMUKVJVJUKV";
prog_char	gGothgbt_54[]	PROGMEM	=	"71E]JJILHOHSIVKYMZP[S[VZXYZW[U RISJVLXNYQZTZWY RJJIMIQJTLWNXQYTYWXYW[U RHIIGKFOFUGYG[F RPGTHXH RHIIHKGNGTIWIYH[F RSIRJPKPV RQKQT RRJRSQUPV RWIWX";
prog_char	gGothgbt_55[]	PROGMEM	=	"89F^HHJFLFOGQF RKGNG RHHJGMHOHQF RKJJLIOISJVKXMZP[S[VZXYZ[\\Y RJSKVNYQZTZ RKJJNJQKTLVNXQYUYXX RUIQJPLPV RQKQT RRJRSQUPV RUIWHYFZG\\HZIZW[Y\\Y RYIZHYGXHYIYX[Z RWHXIXX RUIUY RUNXN RURXR";
prog_char	gGothgbt_56[]	PROGMEM	=	"72G^JFKGLILOJOIPIRJQLQLXJY RLHMJMX RJPMP RNYQYSZ RJFLGMHNJNXRXUY RJYMYPZR[UYXXZX RRJUIWHYFZG\\HZIZX RYIZHYGXHYIYW RWHXIXX RRJRX RRMTNVNXM RRSTRVRXS";
prog_char	gGothgbt_57[]	PROGMEM	=	"95E`HFIGJIJOHOGPGRHQJQJXHY RJHKJKX RHPKP RLYNYPZ RHFJGKHLJLXOXQY RHYKYNZO[QYTXVYW[YY\\X ROHRFTHTXWXYY RRGSHSX ROHQHRIRXQY RWYXZ RWHZF\\H\\X RZG[H[X RWHYHZIZXYY ROHOX RWHWX RONRN RORRR RWNZN RWRZR";
prog_char	gGothgbt_58[]	PROGMEM	=	"65G]HIJGLFNFOGWYXZZZ RMGNHVYWZ RJGLGMHUZV[X[ZZ\\X RWFYG[G\\F RWGXHZH RVHWIYI[H\\F RH[IYKXMXNY RJYLYMZ RH[IZKZM[ RWFSO RQRM[ RLPPP RSPXP";
prog_char	gGothgbt_59[]	PROGMEM	=	"86G^JFKGLILOJOIPIRJQLQLXJY RLHMJMX RJPMP RNYQYSZ RJFLGMHNJNXRXUY RJYMYPZR[UYXX RRJUIWHYFZG\\HZIZ^Y`WbUaQ`L` RYIZHYGXHYIYY RWHXIXXZ[ RXaV`S` RY`V_P_L` RRJRX RRMTNVNXM RRSTRVRXS";
prog_char	gGothgbt_5A[]	PROGMEM	=	"57H\\XGWIROOSMWJ[ RVKNV RZFWJUNRRMXLZ RJHLFOGUGZF RKGOHSHWG RJHNIRIVHXG RLZNYRXVXZY RMZQYUYYZ RJ[OZUZX[ZY RMPQP RTPXP";
prog_char	gGothgbt_5B[]	PROGMEM	=	"12KYOBOb RPBPb ROBVB RObVb";
prog_char	gGothgbt_5C[]	PROGMEM	=	" 3KYKFY^";
prog_char	gGothgbt_5D[]	PROGMEM	=	"12KYTBTb RUBUb RNBUB RNbUb";
prog_char	gGothgbt_5E[]	PROGMEM	=	"11JZPLRITL RMORJWO RRJR[";
prog_char	gGothgbt_5F[]	PROGMEM	=	" 3JZJ]Z]";

prog_char	gGothgbt_60[]	PROGMEM	=	"14LXTFRGQIQKRMTKRIRG RRJRLSKRJ";
prog_char	gGothgbt_61[]	PROGMEM	=	"53J[PRNTMVMXNZP[RYUX RMVNXOYQZ RNTNVOXQYRY RNPPPSOUNVMXOWPWXXYYY RONNOQO RTOWOVNVYWZ RMOOMPNROUPUYW[YY RMORT";
prog_char	gGothgbt_62[]	PROGMEM	=	"44I[LHMJMXKY RNJMHNGNXQZ RLHOFOXQYRZ RKYMYOZP[RZUYWY ROPROTNUMVNXOYOWPWY RTNVOVX RROSOUPUY";
prog_char	gGothgbt_63[]	PROGMEM	=	"35JXNONXLYMYOZP[ ROOOYQZ RPOPXRYSYQZP[ RNORNTMUNWOXO RSNTOVO RPORNTPVPXO";
prog_char	gGothgbt_64[]	PROGMEM	=	"41IZRMPNMOMXKY RNONXQZ RRMOOOXQYRZ RKYMYOZP[RZUYWY RMHPFQIWOWY RPINHOGPIVOVX RMHUPUY";
prog_char	gGothgbt_65[]	PROGMEM	=	"32JXNONXLYMYOZP[ ROOOYQZ RPOPXRYSYQZP[ RNORNTMWQURPU RSNVQ RPORNUR";
prog_char	gGothgbt_66[]	PROGMEM	=	"41JWNHNXLYMYOZP[ ROHOYQZ RPHPXRYSYQZP[ RNHQGSFTGVHWH RRGSHUH RPHQGSIUIWH RKMNM RPMTM";
prog_char	gGothgbt_67[]	PROGMEM	=	"56I[MOMXKYLYNZO[PZRYUX RNPNYPZ ROOOXQYRY RMOOORNTMUNWOYOWPW\\V_TaRbQaO`M` RSNVPV\\ RSaQ`P` RRNSOUPUZV]V_ RTaS`Q_O_M`";
prog_char	gGothgbt_68[]	PROGMEM	=	"47I[LHMJMXKYLYNZO[ RNJMHNGNYPZ RLHOFOXQYO[ ROPROTNUMVNXOYOWPWYU[T] RTNVOVYU[ RROSOUPUYT]T`UbVbT`";
prog_char	gGothgbt_69[]	PROGMEM	=	"35MWRFPHRITHRF RRGQHSHRG RRMQNOOQPQYS[UY RRPSORNQORPRYSZ RRMSNUOSPSXTYUY";
prog_char	gGothgbt_6A[]	PROGMEM	=	"39MWRFPHRITHRF RRGQHSHRG RRMQNOOQPQYS[T] RRPSORNQORPRYS[ RRMSNUOSPSYT]T`RbPbPaRb";
prog_char	gGothgbt_6B[]	PROGMEM	=	"50IZLHMJMXKYLYNZO[ RNJMHNGNYPZ RLHOFOXQYO[ ROPRNTMVPSROU RSNUP RRNTQ RSRTSVXWYXY RSSTTUYVZ RRSSTTYV[XY";
prog_char	gGothgbt_6C[]	PROGMEM	=	"22MWPHQJQXOYPYRZS[ RRJQHRGRYTZ RPHSFSXUYVYTZS[";
prog_char	gGothgbt_6D[]	PROGMEM	=	"67E_GOHOIPIXGYHYJZK[ RINJOJYLZ RGOIMKOKXMYK[ RKPNOPNQMSOSXUYS[ RPNRORYTZ RNOOOQPQXPYRZS[ RSPVOXNYMZN\\O]O[P[X\\Y]Y RXNZOZY[Z RVOWOYPYY[[]Y";
prog_char	gGothgbt_6E[]	PROGMEM	=	"45I[KOLOMPMXKYLYNZO[ RMNNONYPZ RKOMMOOOXQYO[ ROPROTNUMVNXOYOWPWXXYYY RTNVOVYWZ RROSOUPUYW[YY";
prog_char	gGothgbt_6F[]	PROGMEM	=	"40I[MOMXKY RNPNXQZ ROOOXQYRZ RKYMYOZP[RZUYWY RMOOORNTMUNWOYOWPWY RSNVPVX RRNSOUPUY";

prog_char	gGothgbt_70[]	PROGMEM	=	"54I[LMMOMXKYMYMb RMNNONaO`N^ RNYOYQZ RLMNNOOOXQYRZ ROZP[RZUYWY ROZO^P`Mb ROPROTNUMVNXOYOWPWY RTNVOVX RROSOUPUY";
prog_char	gGothgbt_71[]	PROGMEM	=	"44I[MOMXKY RNPNYPZ ROOOXQYRY RKYLYNZO[PZRYUX RMOOORNTMUNWOYOWPWb RSNVPVaU`V^ RRNSOUPU^T`Wb";
prog_char	gGothgbt_72[]	PROGMEM	=	"38JXLOMONPNXLYMYOZP[ RMNOOOYQZ RLONMPOPXRYSYQZP[ RPOTMUNWOXO RSNTOVO RRNTPVPXO";
prog_char	gGothgbt_73[]	PROGMEM	=	"59JZMOMSOTUTWUWY RNONS RVUVY RPNOOOSQT RSTUUUYTZ RMOPNRMTNVNWM RQNSN RPNROTOVN RWYTZR[PZNZL[ RSZQZ RTZRYOYL[ RWMVOTROWL[";
prog_char	gGothgbt_74[]	PROGMEM	=	"28MWPHQJQXOYPYRZS[ RRJQHRGRYTZ RPHSFSXUYVYTZS[ RNMQM RSMVM";
prog_char	gGothgbt_75[]	PROGMEM	=	"47I[KOLOMPMXKY RLNNONYPZ RKOMMOOOXQYRY RKYLYNZO[PZRYUX RUMVNXOYOWPWXXYYY RTNVOVYWZ RUMSOUPUYW[YY";
prog_char	gGothgbt_76[]	PROGMEM	=	"36I[LMMOMXP[RYUXWX RMNNONXQZ RLMNNOOOWPXRY RUMVNXOYOWPWX RTNVOVW RUMSOUPUX";
prog_char	gGothgbt_77[]	PROGMEM	=	"57E_HMIOIXL[NYQX RINJOJXMZ RHMJNKOKWLXNY RQMOOQPQXT[VYYX[X RPNRORXUZ RQMRNTOSPSWTXVY RYMZN\\O]O[P[X RXNZOZW RYMWOYPYX";
prog_char	gGothgbt_78[]	PROGMEM	=	"59H[KOLONPOQSYTZV[XY RMNOOTYVZ RKOMMONPOTWUXWYXY RRSUMVNXNYM RUNVOWO RTOVPXOYM RQUN[MZKZJ[ RNZMYLY ROYMXKYJ[ RMTPT RSTVT";
prog_char	gGothgbt_79[]	PROGMEM	=	"60I[KOLOMPMXKY RLNNONYPZ RKOMMOOOXQYRY RKYLYNZO[PZRYUX RUMVNXOYOWPW\\V_TaRbQaO`M` RTNVOV\\ RSaQ`P` RUMSOUPUZV]V_ RTaS`Q_O_M`";
prog_char	gGothgbt_7A[]	PROGMEM	=	"38I[XML[ RLONPQPTOXM RMNOOSO RLONMPNTNXM RL[PYSXVXXY RQYUYWZ RL[PZTZV[XY RNTVT";
prog_char	gGothgbt_7B[]	PROGMEM	=	"40KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
prog_char	gGothgbt_7C[]	PROGMEM	=	" 3NVRBRb";
prog_char	gGothgbt_7D[]	PROGMEM	=	"40KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
prog_char	gGothgbt_7E[]	PROGMEM	=	"24F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
prog_char	gGothgbt_7F[]	PROGMEM	=	"30KYQFOGNINKOMQNSNUMVKVIUGSFQF RQFNIOMSNVKUGQF RSFOGNKQNUMVISF";

PGM_P gHershyGothgbtFontTable[]	PROGMEM =
{

	gGothgbt_00,
	gGothgbt_20,
	gGothgbt_21,
	gGothgbt_22,
	gGothgbt_23,
	gGothgbt_24,
	gGothgbt_25,
	gGothgbt_26,
	gGothgbt_27,
	gGothgbt_28,
	gGothgbt_29,
	gGothgbt_2A,
	gGothgbt_2B,
	gGothgbt_2C,
	gGothgbt_2D,
	gGothgbt_2E,
	gGothgbt_2F,

	gGothgbt_30,
	gGothgbt_31,
	gGothgbt_32,
	gGothgbt_33,
	gGothgbt_34,
	gGothgbt_35,
	gGothgbt_36,
	gGothgbt_37,
	gGothgbt_38,
	gGothgbt_39,
	gGothgbt_3A,
	gGothgbt_3B,
	gGothgbt_3C,
	gGothgbt_3D,
	gGothgbt_3E,
	gGothgbt_3F,

	gGothgbt_40,
	gGothgbt_41,
	gGothgbt_42,
	gGothgbt_43,
	gGothgbt_44,
	gGothgbt_45,
	gGothgbt_46,
	gGothgbt_47,
	gGothgbt_48,
	gGothgbt_49,
	gGothgbt_4A,
	gGothgbt_4B,
	gGothgbt_4C,
	gGothgbt_4D,
	gGothgbt_4E,
	gGothgbt_4F,

	gGothgbt_50,
	gGothgbt_51,
	gGothgbt_52,
	gGothgbt_53,
	gGothgbt_54,
	gGothgbt_55,
	gGothgbt_56,
	gGothgbt_57,
	gGothgbt_58,
	gGothgbt_59,
	gGothgbt_5A,
	gGothgbt_5B,
	gGothgbt_5C,
	gGothgbt_5D,
	gGothgbt_5E,
	gGothgbt_5F,

	gGothgbt_60,
	gGothgbt_61,
	gGothgbt_62,
	gGothgbt_63,
	gGothgbt_64,
	gGothgbt_65,
	gGothgbt_66,
	gGothgbt_67,
	gGothgbt_68,
	gGothgbt_69,
	gGothgbt_6A,
	gGothgbt_6B,
	gGothgbt_6C,
	gGothgbt_6D,
	gGothgbt_6E,
	gGothgbt_6F,

	gGothgbt_70,
	gGothgbt_71,
	gGothgbt_72,
	gGothgbt_73,
	gGothgbt_74,
	gGothgbt_75,
	gGothgbt_76,
	gGothgbt_77,
	gGothgbt_78,
	gGothgbt_79,
	gGothgbt_7A,
	gGothgbt_7B,
	gGothgbt_7C,
	gGothgbt_7D,
	gGothgbt_7E,
	gGothgbt_7F

};
