//*******************************************************************************
//*	futuram.jhf		Futuram
//*	formated for use with Arduino Processing 
//*	by Mark Sproul
//*******************************************************************************
//*	Jan 11,	2010	<MLS>	Formated Hershey Futuram for Arduino
//*******************************************************************************
//#include	"HersheyCursive.h"



//*	the 1st 2 bytes are decimal # of pairs
//*	the rest are offset coordinate pairs, each letter gets 'R' subtracted from it to come up with a number
//*	the firt pair is left position and right position

prog_char	gFuturam_00[]	PROGMEM	=	"Futuram";




prog_char	gFuturam_20[]	PROGMEM	=	" 1JZ";
prog_char	gFuturam_21[]	PROGMEM	=	"24MXRFRTST RRFSFST RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY";
prog_char	gFuturam_22[]	PROGMEM	=	"22I[NFMGMM RNGMM RNFOGMM RWFVGVM RWGVM RWFXGVM";
prog_char	gFuturam_23[]	PROGMEM	=	"12H]SBLb RYBRb RLOZO RKUYU";
prog_char	gFuturam_24[]	PROGMEM	=	"51I\\RBR_S_ RRBSBS_ RWIYIWGTFQFNGLILKMMNNVRWSXUXWWYTZQZOYNX RWIVHTGQGNHMIMKNMVQXSYUYWXYWZT[Q[NZLXNX RXXUZ";
prog_char	gFuturam_25[]	PROGMEM	=	"32F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT";
prog_char	gFuturam_26[]	PROGMEM	=	"49F_[NZO[P\\O\\N[MZMYNXPVUTXRZP[M[JZIXIUJSPORMSKSIRGPFNGMIMKNNPQUXWZZ[[[\\Z\\Y RM[KZJXJUKSMQ RMKNMVXXZZ[";
prog_char	gFuturam_27[]	PROGMEM	=	"11NWSFRGRM RSGRM RSFTGRM";
prog_char	gFuturam_28[]	PROGMEM	=	"20KYVBTDRGPKOPOTPYR]T`Vb RTDRHQKPPPTQYR\\T`";
prog_char	gFuturam_29[]	PROGMEM	=	"20KYNBPDRGTKUPUTTYR]P`Nb RPDRHSKTPTTSYR\\P`";
prog_char	gFuturam_2A[]	PROGMEM	=	"39JZRFQGSQRR RRFRR RRFSGQQRR RMINIVOWO RMIWO RMIMJWNWO RWIVINOMO RWIMO RWIWJMNMO";
prog_char	gFuturam_2B[]	PROGMEM	=	"16F_RIRZSZ RRISISZ RJQ[Q[R RJQJR[R";
prog_char	gFuturam_2C[]	PROGMEM	=	"24MXTZS[R[QZQYRXSXTYT\\S^Q_ RRYRZSZSYRY RS[T\\ RTZS^";
prog_char	gFuturam_2D[]	PROGMEM	=	" 3E_IR[R";
prog_char	gFuturam_2E[]	PROGMEM	=	"16MXRXQYQZR[S[TZTYSXRX RRYRZSZSYRY";
prog_char	gFuturam_2F[]	PROGMEM	=	" 8G^[BIbJb R[B\\BJb";

prog_char	gFuturam_30[]	PROGMEM	=	"42H\\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF ROGMJLOLRMWOZ RNYQZSZVY RUZWWXRXOWJUG RVHSGQGNH";
prog_char	gFuturam_31[]	PROGMEM	=	"12H\\NJPISFS[ RNJNKPJRHR[S[";
prog_char	gFuturam_32[]	PROGMEM	=	"34H\\LKLJMHNGPFTFVGWHXJXLWNUQL[ RLKMKMJNHPGTGVHWJWLVNTQK[ RLZYZY[ RK[Y[";
prog_char	gFuturam_33[]	PROGMEM	=	"48H\\MFXFQO RMFMGWG RWFPO RQNSNVOXQYTYUXXVZS[P[MZLYKWLW RPOSOVPXS RTOWQXTXUWXTZ RXVVYSZPZMYLW ROZLX";
prog_char	gFuturam_34[]	PROGMEM	=	"18H\\UIU[V[ RVFV[ RVFKVZV RUILV RLUZUZV";
prog_char	gFuturam_35[]	PROGMEM	=	"53H\\MFLO RNGMN RMFWFWG RNGWG RMNPMSMVNXPYSYUXXVZS[P[MZLYKWLW RLOMOONSNVOXR RTNWPXSXUWXTZ RXVVYSZPZMYLW ROZLX";
prog_char	gFuturam_36[]	PROGMEM	=	"62H\\VGWIXIWGTFRFOGMJLOLTMXOZR[S[VZXXYUYTXQVOSNRNOOMQ RWHTGRGOH RPGNJMOMTNXQZ RMVOYRZSZVYXV RTZWXXUXTWQTO RXSVPSOROOPMS RQONQMT";
prog_char	gFuturam_37[]	PROGMEM	=	"12H\\KFYFO[ RKFKGXG RXFN[O[";
prog_char	gFuturam_38[]	PROGMEM	=	"68H\\PFMGLILKMMNNPOTPVQWRXTXWWYTZPZMYLWLTMRNQPPTOVNWMXKXIWGTFPF RNGMIMKNMPNTOVPXRYTYWXYWZT[P[MZLYKWKTLRNPPOTNVMWKWIVG RWHTGPGMH RLXOZ RUZXX";
prog_char	gFuturam_39[]	PROGMEM	=	"62H\\WPURRSQSNRLPKMKLLINGQFRFUGWIXMXRWWUZR[P[MZLXMXNZ RWMVPSR RWNUQRRQRNQLN RPRMPLMLLMIPG RLKNHQGRGUHWK RSGVIWMWRVWTZ RUYRZPZMY";
prog_char	gFuturam_3A[]	PROGMEM	=	"32MXRMQNQORPSPTOTNSMRM RRNROSOSNRN RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY";
prog_char	gFuturam_3B[]	PROGMEM	=	"40MXRMQNQORPSPTOTNSMRM RRNROSOSNRN RTZS[R[QZQYRXSXTYT\\S^Q_ RRYRZSZSYRY RS[T\\ RTZS^";
prog_char	gFuturam_3C[]	PROGMEM	=	" 4F^ZIJRZ[";
prog_char	gFuturam_3D[]	PROGMEM	=	"16F_JM[M[N RJMJN[N RJU[U[V RJUJV[V";
prog_char	gFuturam_3E[]	PROGMEM	=	" 4F^JIZRJ[";
prog_char	gFuturam_3F[]	PROGMEM	=	"58I\\LKLJMHNGQFTFWGXHYJYLXNWOUPRQ RLKMKMJNHQGTGWHXJXLWNUORP RMIPG RUGXI RXMTP RRPRTSTSP RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY";

prog_char	gFuturam_40[]	PROGMEM	=	"56E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
prog_char	gFuturam_41[]	PROGMEM	=	"20H\\RFJ[ RRIK[J[ RRIY[Z[ RRFZ[ RMUWU RLVXV";
prog_char	gFuturam_42[]	PROGMEM	=	"44H\\LFL[ RMGMZ RLFTFWGXHYJYMXOWPTQ RMGTGWHXJXMWOTP RMPTPWQXRYTYWXYWZT[L[ RMQTQWRXTXWWYTZMZ";
prog_char	gFuturam_43[]	PROGMEM	=	"38H]ZKYIWGUFQFOGMILKKNKSLVMXOZQ[U[WZYXZV RZKYKXIWHUGQGOHMKLNLSMVOYQZUZWYXXYVZV";
prog_char	gFuturam_44[]	PROGMEM	=	"32H]LFL[ RMGMZ RLFSFVGXIYKZNZSYVXXVZS[L[ RMGSGVHWIXKYNYSXVWXVYSZMZ";
prog_char	gFuturam_45[]	PROGMEM	=	"27I\\MFM[ RNGNZ RMFYF RNGYGYF RNPTPTQ RNQTQ RNZYZY[ RM[Y[";
prog_char	gFuturam_46[]	PROGMEM	=	"21I[MFM[ RNGN[M[ RMFYF RNGYGYF RNPTPTQ RNQTQ";
prog_char	gFuturam_47[]	PROGMEM	=	"44H]ZKYIWGUFQFOGMILKKNKSLVMXOZQ[U[WZYXZVZRUR RZKYKXIWHUGQGOHNIMKLNLSMVNXOYQZUZWYXXYVYSUSUR";
prog_char	gFuturam_48[]	PROGMEM	=	"22G]KFK[ RKFLFL[K[ RYFXFX[Y[ RYFY[ RLPXP RLQXQ";
prog_char	gFuturam_49[]	PROGMEM	=	" 8NWRFR[S[ RRFSFS[";
prog_char	gFuturam_4A[]	PROGMEM	=	"20J[VFVVUYSZQZOYNVMV RVFWFWVVYUZS[Q[OZNYMV";
prog_char	gFuturam_4B[]	PROGMEM	=	"22H]LFL[M[ RLFMFM[ RZFYFMR RZFMS RPOY[Z[ RQOZ[";
prog_char	gFuturam_4C[]	PROGMEM	=	"14IZMFM[ RMFNFNZ RNZYZY[ RM[Y[";
prog_char	gFuturam_4D[]	PROGMEM	=	"26F^JFJ[ RKKK[J[ RKKR[ RJFRX RZFRX RYKR[ RYKY[Z[ RZFZ[";
prog_char	gFuturam_4E[]	PROGMEM	=	"20G]KFK[ RLIL[K[ RLIY[ RKFXX RXFXX RXFYFY[";
prog_char	gFuturam_4F[]	PROGMEM	=	"40G]PFNGLIKKJNJSKVLXNZP[T[VZXXYVZSZNYKXIVGTFPF RQGNHLKKNKSLVNYQZSZVYXVYSYNXKVHSGQG";

prog_char	gFuturam_50[]	PROGMEM	=	"27H\\LFL[ RMGM[L[ RLFUFWGXHYJYMXOWPUQMQ RMGUGWHXJXMWOUPMP";
prog_char	gFuturam_51[]	PROGMEM	=	"48G]PFNGLIKKJNJSKVLXNZP[T[VZXXYVZSZNYKXIVGTFPF RQGNHLKKNKSLVNYQZSZVYXVYSYNXKVHSGQG RSXX]Y] RSXTXY]";
prog_char	gFuturam_52[]	PROGMEM	=	"34H\\LFL[ RMGM[L[ RLFTFWGXHYJYMXOWPTQMQ RMGTGWHXJXMWOTPMP RRQX[Y[ RSQY[";
prog_char	gFuturam_53[]	PROGMEM	=	"43H\\YIWGTFPFMGKIKKLMMNOOTQVRWSXUXXWYTZPZNYMXKX RYIWIVHTGPGMHLILKMMONTPVQXSYUYXWZT[P[MZKX";
prog_char	gFuturam_54[]	PROGMEM	=	"15J[RGR[ RSGS[R[ RLFYFYG RLFLGYG";
prog_char	gFuturam_55[]	PROGMEM	=	"24G]KFKULXNZQ[S[VZXXYUYF RKFLFLUMXNYQZSZVYWXXUXFYF";
prog_char	gFuturam_56[]	PROGMEM	=	"14H\\JFR[ RJFKFRX RZFYFRX RZFR[";
prog_char	gFuturam_57[]	PROGMEM	=	"26E_GFM[ RGFHFMX RRFMX RRIM[ RRIW[ RRFWX R]F\\FWX R]FW[";
prog_char	gFuturam_58[]	PROGMEM	=	"16H\\KFX[Y[ RKFLFY[ RYFXFK[ RYFL[K[";
prog_char	gFuturam_59[]	PROGMEM	=	"17I\\KFRPR[S[ RKFLFSP RZFYFRP RZFSPS[";
prog_char	gFuturam_5A[]	PROGMEM	=	"20H\\XFK[ RYFL[ RKFYF RKFKGXG RLZYZY[ RK[Y[";
prog_char	gFuturam_5B[]	PROGMEM	=	"12KYOBOb RPBPb ROBVB RObVb";
prog_char	gFuturam_5C[]	PROGMEM	=	" 3KYKFY^";
prog_char	gFuturam_5D[]	PROGMEM	=	"12KYTBTb RUBUb RNBUB RNbUb";
prog_char	gFuturam_5E[]	PROGMEM	=	" 8G]JTROZT RJTRPZT";
prog_char	gFuturam_5F[]	PROGMEM	=	" 3H\\Hb\\b";

prog_char	gFuturam_60[]	PROGMEM	=	" 7LXPFUL RPFOGUL";
prog_char	gFuturam_61[]	PROGMEM	=	"36H\\WMW[X[ RWMXMX[ RWPUNSMPMNNLPKSKULXNZP[S[UZWX RWPSNPNNOMPLSLUMXNYPZSZWX";
prog_char	gFuturam_62[]	PROGMEM	=	"36H\\LFL[M[ RLFMFM[ RMPONQMTMVNXPYSYUXXVZT[Q[OZMX RMPQNTNVOWPXSXUWXVYTZQZMX";
prog_char	gFuturam_63[]	PROGMEM	=	"32I[XPVNTMQMONMPLSLUMXOZQ[T[VZXX RXPWQVOTNQNOONPMSMUNXOYQZTZVYWWXX";
prog_char	gFuturam_64[]	PROGMEM	=	"36H\\WFW[X[ RWFXFX[ RWPUNSMPMNNLPKSKULXNZP[S[UZWX RWPSNPNNOMPLSLUMXNYPZSZWX";
prog_char	gFuturam_65[]	PROGMEM	=	"36I[MTXTXQWOVNTMQMONMPLSLUMXOZQ[T[VZXX RMSWSWQVOTNQNOONPMSMUNXOYQZTZVYWWXX";
prog_char	gFuturam_66[]	PROGMEM	=	"24LZWFUFSGRJR[S[ RWFWGUGSH RTGSJS[ ROMVMVN ROMONVN";
prog_char	gFuturam_67[]	PROGMEM	=	"48H\\XMWMW\\V_U`SaQaO`N_L_ RXMX\\W_UaSbPbNaL_ RWPUNSMPMNNLPKSKULXNZP[S[UZWX RWPSNPNNOMPLSLUMXNYPZSZWX";
prog_char	gFuturam_68[]	PROGMEM	=	"25H\\LFL[M[ RLFMFM[ RMQPNRMUMWNXQX[ RMQPORNTNVOWQW[X[";
prog_char	gFuturam_69[]	PROGMEM	=	"24NWRFQGQHRISITHTGSFRF RRGRHSHSGRG RRMR[S[ RRMSMS[";
prog_char	gFuturam_6A[]	PROGMEM	=	"24NWRFQGQHRISITHTGSFRF RRGRHSHSGRG RRMRbSb RRMSMSb";
prog_char	gFuturam_6B[]	PROGMEM	=	"22H[LFL[M[ RLFMFM[ RXMWMMW RXMMX RPTV[X[ RQSX[";
prog_char	gFuturam_6C[]	PROGMEM	=	" 8NWRFR[S[ RRFSFS[";
prog_char	gFuturam_6D[]	PROGMEM	=	"42CbGMG[H[ RGMHMH[ RHQKNMMPMRNSQS[ RHQKOMNONQORQR[S[ RSQVNXM[M]N^Q^[ RSQVOXNZN\\O]Q][^[";
prog_char	gFuturam_6E[]	PROGMEM	=	"25H\\LML[M[ RLMMMM[ RMQPNRMUMWNXQX[ RMQPORNTNVOWQW[X[";
prog_char	gFuturam_6F[]	PROGMEM	=	"36I\\QMONMPLSLUMXOZQ[T[VZXXYUYSXPVNTMQM RQNOONPMSMUNXOYQZTZVYWXXUXSWPVOTNQN";

prog_char	gFuturam_70[]	PROGMEM	=	"36H\\LMLbMb RLMMMMb RMPONQMTMVNXPYSYUXXVZT[Q[OZMX RMPQNTNVOWPXSXUWXVYTZQZMX";
prog_char	gFuturam_71[]	PROGMEM	=	"36H\\WMWbXb RWMXMXb RWPUNSMPMNNLPKSKULXNZP[S[UZWX RWPSNPNNOMPLSLUMXNYPZSZWX";
prog_char	gFuturam_72[]	PROGMEM	=	"21KYOMO[P[ ROMPMP[ RPSQPSNUMXM RPSQQSOUNXNXM";
prog_char	gFuturam_73[]	PROGMEM	=	"50J[XPWNTMQMNNMPNRPSUUWV RVUWWWXVZ RWYTZQZNY ROZNXMX RXPWPVN RWOTNQNNO RONNPOR RNQPRUTWUXWXXWZT[Q[NZMX";
prog_char	gFuturam_74[]	PROGMEM	=	"16MXRFR[S[ RRFSFS[ ROMVMVN ROMONVN";
prog_char	gFuturam_75[]	PROGMEM	=	"25H\\LMLWMZO[R[TZWW RLMMMMWNYPZRZTYWW RWMW[X[ RWMXMX[";
prog_char	gFuturam_76[]	PROGMEM	=	"14JZLMR[ RLMMMRY RXMWMRY RXMR[";
prog_char	gFuturam_77[]	PROGMEM	=	"26F^IMN[ RIMJMNX RRMNX RRPN[ RRPV[ RRMVX R[MZMVX R[MV[";
prog_char	gFuturam_78[]	PROGMEM	=	"16I[LMW[X[ RLMMMX[ RXMWML[ RXMM[L[";
prog_char	gFuturam_79[]	PROGMEM	=	"17JZLMR[ RLMMMRY RXMWMRYNb RXMR[ObNb";
prog_char	gFuturam_7A[]	PROGMEM	=	"20I[VNL[ RXMNZ RLMXM RLMLNVN RNZXZX[ RL[X[";
prog_char	gFuturam_7B[]	PROGMEM	=	" 4KYUBNRUb";
prog_char	gFuturam_7C[]	PROGMEM	=	" 3NVRBRb";
prog_char	gFuturam_7D[]	PROGMEM	=	" 4KYOBVROb";
prog_char	gFuturam_7E[]	PROGMEM	=	"24F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
prog_char	gFuturam_7F[]	PROGMEM	=	"35JZJFJ[K[KFLFL[M[MFNFN[O[OFPFP[Q[QFRFR[S[SFTFT[U[UFVFV[W[WFXFX[Y[YFZFZ[";


PGM_P gHershyFuturamFontTable[]	PROGMEM =
{

	gFuturam_00,
	gFuturam_20,
	gFuturam_21,
	gFuturam_22,
	gFuturam_23,
	gFuturam_24,
	gFuturam_25,
	gFuturam_26,
	gFuturam_27,
	gFuturam_28,
	gFuturam_29,
	gFuturam_2A,
	gFuturam_2B,
	gFuturam_2C,
	gFuturam_2D,
	gFuturam_2E,
	gFuturam_2F,

	gFuturam_30,
	gFuturam_31,
	gFuturam_32,
	gFuturam_33,
	gFuturam_34,
	gFuturam_35,
	gFuturam_36,
	gFuturam_37,
	gFuturam_38,
	gFuturam_39,
	gFuturam_3A,
	gFuturam_3B,
	gFuturam_3C,
	gFuturam_3D,
	gFuturam_3E,
	gFuturam_3F,

	gFuturam_40,
	gFuturam_41,
	gFuturam_42,
	gFuturam_43,
	gFuturam_44,
	gFuturam_45,
	gFuturam_46,
	gFuturam_47,
	gFuturam_48,
	gFuturam_49,
	gFuturam_4A,
	gFuturam_4B,
	gFuturam_4C,
	gFuturam_4D,
	gFuturam_4E,
	gFuturam_4F,

	gFuturam_50,
	gFuturam_51,
	gFuturam_52,
	gFuturam_53,
	gFuturam_54,
	gFuturam_55,
	gFuturam_56,
	gFuturam_57,
	gFuturam_58,
	gFuturam_59,
	gFuturam_5A,
	gFuturam_5B,
	gFuturam_5C,
	gFuturam_5D,
	gFuturam_5E,
	gFuturam_5F,

	gFuturam_60,
	gFuturam_61,
	gFuturam_62,
	gFuturam_63,
	gFuturam_64,
	gFuturam_65,
	gFuturam_66,
	gFuturam_67,
	gFuturam_68,
	gFuturam_69,
	gFuturam_6A,
	gFuturam_6B,
	gFuturam_6C,
	gFuturam_6D,
	gFuturam_6E,
	gFuturam_6F,

	gFuturam_70,
	gFuturam_71,
	gFuturam_72,
	gFuturam_73,
	gFuturam_74,
	gFuturam_75,
	gFuturam_76,
	gFuturam_77,
	gFuturam_78,
	gFuturam_79,
	gFuturam_7A,
	gFuturam_7B,
	gFuturam_7C,
	gFuturam_7D,
	gFuturam_7E,
	gFuturam_7F

};
