//*******************************************************************************
//*	timesi.jhf		Times Italic
//*	formated for use with Arduino Processing 
//*	by Mark Sproul
//*******************************************************************************
//*	Jan 23,	2009	<MLS>	Formated Hershey Times Italic for Arduino
//*******************************************************************************
//#include	"HersheyTimesItalic.h"

prog_char	gTimesItalic_00[]	PROGMEM	=	"Times Italic";

prog_char	gTimesItalic_20[]	PROGMEM	=	" 1JZ";
prog_char	gTimesItalic_21[]	PROGMEM	=	"17MXUFTGRS RUGRS RUFVGRS RPYOZP[QZPY";
prog_char	gTimesItalic_22[]	PROGMEM	=	"12I[PFNM RQFNM RYFWM RZFWM";
prog_char	gTimesItalic_23[]	PROGMEM	=	"12H]SBLb RYBRb RLOZO RKUYU";
prog_char	gTimesItalic_24[]	PROGMEM	=	"41H]TBL_ RYBQ_ RZJYKZL[K[JZHYGVFRFOGMIMKNMONVRXT RMKOMVQWRXTXWWYVZS[O[LZKYJWJVKULVKW";
prog_char	gTimesItalic_25[]	PROGMEM	=	"32F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT";
prog_char	gTimesItalic_26[]	PROGMEM	=	"49F_[NZO[P\\O\\N[MZMYNXPVUTXRZP[M[JZIXIUJSPORMSKSIRGPFNGMIMKNNPQUXWZZ[[[\\Z\\Y RM[KZJXJUKSMQ RMKNMVXXZZ[";
prog_char	gTimesItalic_27[]	PROGMEM	=	" 6NWUFSM RVFSM";
prog_char	gTimesItalic_28[]	PROGMEM	=	"20KZZBVESHQKOONTNXO]P`Qb RVESIQMPPOUOZP_Qb";
prog_char	gTimesItalic_29[]	PROGMEM	=	"20JYSBTDUGVLVPUUSYQ\\N_Jb RSBTEUJUOTTSWQ[N_";
prog_char	gTimesItalic_2A[]	PROGMEM	=	" 9JZRLRX RMOWU RWOMU";
prog_char	gTimesItalic_2B[]	PROGMEM	=	" 6E_RIR[ RIR[R";
prog_char	gTimesItalic_2C[]	PROGMEM	=	" 8MXP[OZPYQZQ[P]N_";
prog_char	gTimesItalic_2D[]	PROGMEM	=	" 3E_IR[R";
prog_char	gTimesItalic_2E[]	PROGMEM	=	" 6MXPYOZP[QZPY";
prog_char	gTimesItalic_2F[]	PROGMEM	=	" 3G][BIb";

prog_char	gTimesItalic_30[]	PROGMEM	=	"42H]TFQGOIMLLOKSKVLYMZO[Q[TZVXXUYRZNZKYHXGVFTF RTFRGPINLMOLSLVMYO[ RQ[SZUXWUXRYNYKXHVF";
prog_char	gTimesItalic_31[]	PROGMEM	=	"15H]TJO[ RVFP[ RVFSIPKNL RUIQKNL";
prog_char	gTimesItalic_32[]	PROGMEM	=	"42H]OJPKOLNKNJOHPGSFVFYGZIZKYMWOTQPSMUKWI[ RVFXGYIYKXMVOPS RJYKXMXRZUZWYXW RMXR[U[WZXW";
prog_char	gTimesItalic_33[]	PROGMEM	=	"50H]OJPKOLNKNJOHPGSFVFYGZIZKYMVOSP RVFXGYIYKXMVO RQPSPVQWRXTXWWYVZS[O[LZKYJWJVKULVKW RSPUQVRWTWWVYUZS[";
prog_char	gTimesItalic_34[]	PROGMEM	=	"10H]XGR[ RYFS[ RYFJUZU";
prog_char	gTimesItalic_35[]	PROGMEM	=	"39H]QFLP RQF[F RQGVG[F RLPMOPNSNVOWPXRXUWXUZR[O[LZKYJWJVKULVKW RSNUOVPWRWUVXTZR[";
prog_char	gTimesItalic_36[]	PROGMEM	=	"46H]YIXJYKZJZIYGWFTFQGOIMLLOKSKWLYMZO[R[UZWXXVXSWQVPTOQOOPMRLT RTFRGPINLMOLSLXMZ RR[TZVXWVWRVP";
prog_char	gTimesItalic_37[]	PROGMEM	=	"30H]NFLL R[FZIXLSRQUPWO[ RXLRRPUOWN[ RMIPFRFWI RNHPGRGWIYIZH[F";
prog_char	gTimesItalic_38[]	PROGMEM	=	"63H]SFPGOHNJNMOOQPTPXOYNZLZIYGVFSF RSFQGPHOJOMPOQP RTPWOXNYLYIXGVF RQPMQKSJUJXKZN[R[VZWYXWXTWRVQTP RQPNQLSKUKXLZN[ RR[UZVYWWWSVQ";
prog_char	gTimesItalic_39[]	PROGMEM	=	"46H]YMXOVQTRQROQNPMNMKNIPGSFVFXGYHZJZNYRXUVXTZQ[N[LZKXKWLVMWLX ROQNONKOIQGSF RXGYIYNXRWUUXSZQ[";
prog_char	gTimesItalic_3A[]	PROGMEM	=	"11MXSMRNSOTNSM RPYOZP[QZ";
prog_char	gTimesItalic_3B[]	PROGMEM	=	"14MXSMRNSOTNSM RP[OZPYQZQ[P]N_";
prog_char	gTimesItalic_3C[]	PROGMEM	=	" 4F^ZIJRZ[";
prog_char	gTimesItalic_3D[]	PROGMEM	=	" 6E_IO[O RIU[U";
prog_char	gTimesItalic_3E[]	PROGMEM	=	" 4F^JIZRJ[";
prog_char	gTimesItalic_3F[]	PROGMEM	=	"34H]OJPKOLNKNJOHPGSFWFZG[I[KZMYNSPQQQSRTTT RWFYGZIZKYMXNVO RPYOZP[QZPY";

prog_char	gTimesItalic_40[]	PROGMEM	=	"56E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
prog_char	gTimesItalic_41[]	PROGMEM	=	"18H\\UFH[ RUFV[ RTHU[ RLUUU RF[L[ RR[X[";
prog_char	gTimesItalic_42[]	PROGMEM	=	"41F^OFI[ RPFJ[ RLFWFZG[I[KZNYOVP RWFYGZIZKYNXOVP RMPVPXQYSYUXXVZR[F[ RVPWQXSXUWXUZR[";
prog_char	gTimesItalic_43[]	PROGMEM	=	"34H]ZH[H\\F[L[JZHYGWFTFQGOIMLLOKSKVLYMZP[S[UZWXXV RTFRGPINLMOLSLVMYNZP[";
prog_char	gTimesItalic_44[]	PROGMEM	=	"30F]OFI[ RPFJ[ RLFUFXGYHZKZOYSWWUYSZO[F[ RUFWGXHYKYOXSVWTYRZO[";
prog_char	gTimesItalic_45[]	PROGMEM	=	"22F]OFI[ RPFJ[ RTLRT RLF[FZLZF RMPSP RF[U[WVT[";
prog_char	gTimesItalic_46[]	PROGMEM	=	"20F\\OFI[ RPFJ[ RTLRT RLF[FZLZF RMPSP RF[M[";
prog_char	gTimesItalic_47[]	PROGMEM	=	"42H^ZH[H\\F[L[JZHYGWFTFQGOIMLLOKSKVLYMZP[R[UZWXYT RTFRGPINLMOLSLVMYNZP[ RR[TZVXXT RUT\\T";
prog_char	gTimesItalic_48[]	PROGMEM	=	"27E_NFH[ ROFI[ R[FU[ R\\FV[ RKFRF RXF_F RLPXP RE[L[ RR[Y[";
prog_char	gTimesItalic_49[]	PROGMEM	=	"12LYUFO[ RVFP[ RRFYF RL[S[";
prog_char	gTimesItalic_4A[]	PROGMEM	=	"21I[XFSWRYQZO[M[KZJXJVKULVKW RWFRWQYO[ RTF[F";
prog_char	gTimesItalic_4B[]	PROGMEM	=	"27F]OFI[ RPFJ[ R]FLS RSOW[ RROV[ RLFSF RYF_F RF[M[ RS[Y[";
prog_char	gTimesItalic_4C[]	PROGMEM	=	"14H\\QFK[ RRFL[ RNFUF RH[W[YUV[";
prog_char	gTimesItalic_4D[]	PROGMEM	=	"30E`NFH[ RNFO[ ROFPY R\\FO[ R\\FV[ R]FW[ RKFOF R\\F`F RE[K[ RS[Z[";
prog_char	gTimesItalic_4E[]	PROGMEM	=	"21F_OFI[ ROFVX ROIV[ R\\FV[ RLFOF RYF_F RF[L[";
prog_char	gTimesItalic_4F[]	PROGMEM	=	"42G]SFPGNILLKOJSJVKYLZN[Q[TZVXXUYRZNZKYHXGVFSF RSFQGOIMLLOKSKVLYN[ RQ[SZUXWUXRYNYKXHVF";

prog_char	gTimesItalic_50[]	PROGMEM	=	"27F]OFI[ RPFJ[ RLFXF[G\\I\\K[NYPUQMQ RXFZG[I[KZNXPUQ RF[M[";
prog_char	gTimesItalic_51[]	PROGMEM	=	"61G]SFPGNILLKOJSJVKYLZN[Q[TZVXXUYRZNZKYHXGVFSF RSFQGOIMLLOKSKVLYN[ RQ[SZUXWUXRYNYKXHVF RLYLXMVOUPURVSXS_T`V`W^W] RSXT^U_V_W^";
prog_char	gTimesItalic_52[]	PROGMEM	=	"42F^OFI[ RPFJ[ RLFWFZG[I[KZNYOVPMP RWFYGZIZKYNXOVP RRPTQURVZW[Y[ZYZX RURWYXZYZZY RF[M[";
prog_char	gTimesItalic_53[]	PROGMEM	=	"35G^ZH[H\\F[L[JZHYGVFRFOGMIMKNMONVRXT RMKOMVQWRXTXWWYVZS[O[LZKYJWJUI[JYKY";
prog_char	gTimesItalic_54[]	PROGMEM	=	"16H]UFO[ RVFP[ ROFLLNF]F\\L\\F RL[S[";
prog_char	gTimesItalic_55[]	PROGMEM	=	"25F_NFKQJUJXKZN[R[UZWXXU\\F ROFLQKUKXLZN[ RKFRF RYF_F";
prog_char	gTimesItalic_56[]	PROGMEM	=	"15H\\NFO[ ROFPY R\\FO[ RLFRF RXF^F";
prog_char	gTimesItalic_57[]	PROGMEM	=	"24E_MFK[ RNFLY RUFK[ RUFS[ RVFTY R]FS[ RJFQF RZF`F";
prog_char	gTimesItalic_58[]	PROGMEM	=	"21G]NFU[ ROFV[ R\\FH[ RLFRF RXF^F RF[L[ RR[X[";
prog_char	gTimesItalic_59[]	PROGMEM	=	"20H]NFRPO[ ROFSPP[ R]FSP RLFRF RYF_F RL[S[";
prog_char	gTimesItalic_5A[]	PROGMEM	=	"16G][FH[ R\\FI[ ROFLLNF\\F RH[V[XUU[";
prog_char	gTimesItalic_5B[]	PROGMEM	=	"12KYOBOb RPBPb ROBVB RObVb";
prog_char	gTimesItalic_5C[]	PROGMEM	=	" 3KYKFY^";
prog_char	gTimesItalic_5D[]	PROGMEM	=	"12KYTBTb RUBUb RNBUB RNbUb";
prog_char	gTimesItalic_5E[]	PROGMEM	=	" 8G]JTROZT RJTRPZT";
prog_char	gTimesItalic_5F[]	PROGMEM	=	" 3H\\Hb\\b";

prog_char	gTimesItalic_60[]	PROGMEM	=	" 7LXPFUL RPFOGUL";
prog_char	gTimesItalic_61[]	PROGMEM	=	"39H]XMVTUXUZV[Y[[Y\\W RYMWTVXVZW[ RVTVQUNSMQMNNLQKTKWLYMZO[Q[SZUWVT RQMONMQLTLXMZ";
prog_char	gTimesItalic_62[]	PROGMEM	=	"36H[PFLSLVMYNZ RQFMS RMSNPPNRMTMVNWOXQXTWWUZR[P[NZMWMS RVNWPWTVWTZR[ RMFQF";
prog_char	gTimesItalic_63[]	PROGMEM	=	"25I[WPWQXQXPWNUMRMONMQLTLWMYNZP[R[UZWW RRMPNNQMTMXNZ";
prog_char	gTimesItalic_64[]	PROGMEM	=	"42H]ZFVTUXUZV[Y[[Y\\W R[FWTVXVZW[ RVTVQUNSMQMNNLQKTKWLYMZO[Q[SZUWVT RQMONMQLTLXMZ RWF[F";
prog_char	gTimesItalic_65[]	PROGMEM	=	"26I[MVQUTTWRXPWNUMRMONMQLTLWMYNZP[R[UZWX RRMPNNQMTMXNZ";
prog_char	gTimesItalic_66[]	PROGMEM	=	"35KZZGYHZI[H[GZFXFVGUHTJSMP[O_Na RXFVHUJTNRWQ[P^O`NaLbJbIaI`J_K`Ja ROMYM";
prog_char	gTimesItalic_67[]	PROGMEM	=	"43H\\YMU[T^RaObLbJaI`I_J^K_J` RXMT[S^QaOb RVTVQUNSMQMNNLQKTKWLYMZO[Q[SZUWVT RQMONMQLTLXMZ";
prog_char	gTimesItalic_68[]	PROGMEM	=	"31H]PFJ[ RQFK[ RMTOPQNSMUMWNXOXQVWVZW[ RUMWOWQUWUZV[Y[[Y\\W RMFQF";
prog_char	gTimesItalic_69[]	PROGMEM	=	"26LYUFTGUHVGUF RMQNOPMSMTNTQRWRZS[ RRMSNSQQWQZR[U[WYXW";
prog_char	gTimesItalic_6A[]	PROGMEM	=	"32LYVFUGVHWGVF RNQOOQMTMUNUQR[Q^P`OaMbKbJaJ`K_L`Ka RSMTNTQQ[P^O`Mb";
prog_char	gTimesItalic_6B[]	PROGMEM	=	"34H\\PFJ[ RQFK[ RXNWOXPYOYNXMWMUNQROSMS ROSQTSZT[ ROSPTRZS[U[WZYW RMFQF";
prog_char	gTimesItalic_6C[]	PROGMEM	=	"18MYUFQTPXPZQ[T[VYWW RVFRTQXQZR[ RRFVF";
prog_char	gTimesItalic_6D[]	PROGMEM	=	"52AbBQCOEMHMINIPHTF[ RGMHNHPGTE[ RHTJPLNNMPMRNSOSQP[ RPMRORQO[ RRTTPVNXMZM\\N]O]Q[W[Z\\[ RZM\\O\\QZWZZ[[^[`YaW";
prog_char	gTimesItalic_6E[]	PROGMEM	=	"37F]GQHOJMMMNNNPMTK[ RLMMNMPLTJ[ RMTOPQNSMUMWNXOXQVWVZW[ RUMWOWQUWUZV[Y[[Y\\W";
prog_char	gTimesItalic_6F[]	PROGMEM	=	"32I[RMONMQLTLWMYNZP[R[UZWWXTXQWOVNTMRM RRMPNNQMTMXNZ RR[TZVWWTWPVN";

prog_char	gTimesItalic_70[]	PROGMEM	=	"42G\\HQIOKMNMONOPNTJb RMMNNNPMTIb RNTOQQNSMUMWNXOYQYTXWVZS[Q[OZNWNT RWNXPXTWWUZS[ RFbMb";
prog_char	gTimesItalic_71[]	PROGMEM	=	"33H\\XMRb RYMSb RVTVQUNSMQMNNLQKTKWLYMZO[Q[SZUWVT RQMONMQLTLXMZ RObVb";
prog_char	gTimesItalic_72[]	PROGMEM	=	"26IZJQKOMMPMQNQPPTN[ ROMPNPPOTM[ RPTRPTNVMXMYNYOXPWOXN";
prog_char	gTimesItalic_73[]	PROGMEM	=	"28J[XOXPYPYOXNUMRMONNONQORVVWW RNPOQVUWVWYVZS[P[MZLYLXMXMY";
prog_char	gTimesItalic_74[]	PROGMEM	=	"18KYTFPTOXOZP[S[UYVW RUFQTPXPZQ[ RNMWM";
prog_char	gTimesItalic_75[]	PROGMEM	=	"37F]GQHOJMMMNNNQLWLYN[ RLMMNMQKWKYLZN[P[RZTXVT RXMVTUXUZV[Y[[Y\\W RYMWTVXVZW[";
prog_char	gTimesItalic_76[]	PROGMEM	=	"26H\\IQJOLMOMPNPQNWNYP[ RNMONOQMWMYNZP[Q[TZVXXUYQYMXMYO";
prog_char	gTimesItalic_77[]	PROGMEM	=	"41C`DQEOGMJMKNKQIWIYK[ RIMJNJQHWHYIZK[M[OZQXRV RTMRVRYSZU[W[YZ[X\\V]R]M\\M]O RUMSVSYU[";
prog_char	gTimesItalic_78[]	PROGMEM	=	"42H\\KQMNOMRMSOSR RQMRORRQVPXNZL[K[JZJYKXLYKZ RQVQYR[U[WZYW RYNXOYPZOZNYMXMVNTPSRRVRYS[";
prog_char	gTimesItalic_79[]	PROGMEM	=	"41G\\HQIOKMNMONOQMWMYO[ RMMNNNQLWLYMZO[Q[SZUXWT RZMV[U^SaPbMbKaJ`J_K^L_K` RYMU[T^RaPb";
prog_char	gTimesItalic_7A[]	PROGMEM	=	"31H\\YMXOVQNWLYK[ RLQMOOMRMVO RMOONRNVOXO RLYNYRZUZWY RNYR[U[WYXW";
prog_char	gTimesItalic_7B[]	PROGMEM	=	"40KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
prog_char	gTimesItalic_7C[]	PROGMEM	=	" 3NVRBRb";
prog_char	gTimesItalic_7D[]	PROGMEM	=	"40KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
prog_char	gTimesItalic_7E[]	PROGMEM	=	"24F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
prog_char	gTimesItalic_7F[]	PROGMEM	=	"35JZJFJ[K[KFLFL[M[MFNFN[O[OFPFP[Q[QFRFR[S[SFTFT[U[UFVFV[W[WFXFX[Y[YFZFZ[";


PGM_P gHershyTimesItalicFontTable[]	PROGMEM =
{

	gTimesItalic_00,
	gTimesItalic_20,
	gTimesItalic_21,
	gTimesItalic_22,
	gTimesItalic_23,
	gTimesItalic_24,
	gTimesItalic_25,
	gTimesItalic_26,
	gTimesItalic_27,
	gTimesItalic_28,
	gTimesItalic_29,
	gTimesItalic_2A,
	gTimesItalic_2B,
	gTimesItalic_2C,
	gTimesItalic_2D,
	gTimesItalic_2E,
	gTimesItalic_2F,

	gTimesItalic_30,
	gTimesItalic_31,
	gTimesItalic_32,
	gTimesItalic_33,
	gTimesItalic_34,
	gTimesItalic_35,
	gTimesItalic_36,
	gTimesItalic_37,
	gTimesItalic_38,
	gTimesItalic_39,
	gTimesItalic_3A,
	gTimesItalic_3B,
	gTimesItalic_3C,
	gTimesItalic_3D,
	gTimesItalic_3E,
	gTimesItalic_3F,

	gTimesItalic_40,
	gTimesItalic_41,
	gTimesItalic_42,
	gTimesItalic_43,
	gTimesItalic_44,
	gTimesItalic_45,
	gTimesItalic_46,
	gTimesItalic_47,
	gTimesItalic_48,
	gTimesItalic_49,
	gTimesItalic_4A,
	gTimesItalic_4B,
	gTimesItalic_4C,
	gTimesItalic_4D,
	gTimesItalic_4E,
	gTimesItalic_4F,

	gTimesItalic_50,
	gTimesItalic_51,
	gTimesItalic_52,
	gTimesItalic_53,
	gTimesItalic_54,
	gTimesItalic_55,
	gTimesItalic_56,
	gTimesItalic_57,
	gTimesItalic_58,
	gTimesItalic_59,
	gTimesItalic_5A,
	gTimesItalic_5B,
	gTimesItalic_5C,
	gTimesItalic_5D,
	gTimesItalic_5E,
	gTimesItalic_5F,

	gTimesItalic_60,
	gTimesItalic_61,
	gTimesItalic_62,
	gTimesItalic_63,
	gTimesItalic_64,
	gTimesItalic_65,
	gTimesItalic_66,
	gTimesItalic_67,
	gTimesItalic_68,
	gTimesItalic_69,
	gTimesItalic_6A,
	gTimesItalic_6B,
	gTimesItalic_6C,
	gTimesItalic_6D,
	gTimesItalic_6E,
	gTimesItalic_6F,

	gTimesItalic_70,
	gTimesItalic_71,
	gTimesItalic_72,
	gTimesItalic_73,
	gTimesItalic_74,
	gTimesItalic_75,
	gTimesItalic_76,
	gTimesItalic_77,
	gTimesItalic_78,
	gTimesItalic_79,
	gTimesItalic_7A,
	gTimesItalic_7B,
	gTimesItalic_7C,
	gTimesItalic_7D,
	gTimesItalic_7E,
	gTimesItalic_7F

};
