//*******************************************************************************
//*	Gothic English Font
//*	formated for use with Arduino Processing 
//*	by Mark Sproul
//*******************************************************************************
//*	Jan 21,	2009	<MLS> Formated Hershey Gothic English for Arduino
//*******************************************************************************
//#include	"HersheyGothicEnglish.h"

prog_char	gGothicEng_00[]	PROGMEM	=	"Gothic English";
prog_char	gGothicEng_20[]	PROGMEM	=	" 1JZ";
prog_char	gGothicEng_21[]	PROGMEM	=	"30LXRFQGOHQIRT RRISHRGQHRIRT RRFSGUHSIRT RRXPZR[TZRX RRYQZSZRY";
prog_char	gGothicEng_22[]	PROGMEM	=	"22I[NFMGMM RNGMM RNFOGMM RWFVGVM RWGVM RWFXGVM";
prog_char	gGothicEng_23[]	PROGMEM	=	"12H]SBLb RYBRb RLOZO RKUYU";
prog_char	gGothicEng_24[]	PROGMEM	=	"60H\\PBP_ RTBT_ RTFVGWIWKYJXHWGTFPFMGKIKLLNOPURWSXUXXWZ RXJWH RLLMNOOUQWRXT RMYLW RMGLILKMMONUPXRYTYWXYWZT[P[MZLYKWMVMXNZP[";
prog_char	gGothicEng_25[]	PROGMEM	=	"32F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT";
prog_char	gGothicEng_26[]	PROGMEM	=	"62E_YNZO[O\\N RXOYP[P RXPYQZQ[P\\N RYNST RRUL[HVNP ROOSKOFJLPRTXVZX[Z[[Z\\X RLZIV RRKOG RKLPQTWVYXZ[Z RMZIU RRLNG RKKQQUWVXXY[Y\\X";
prog_char	gGothicEng_27[]	PROGMEM	=	"11NWSFRGRM RSGRM RSFTGRM";
prog_char	gGothicEng_28[]	PROGMEM	=	"27KYUBSDQGOKNPNTOYQ]S`Ub RQHPKOOOUPYQ\\ RSDRFQIPOPUQ[R^S`";
prog_char	gGothicEng_29[]	PROGMEM	=	"27KYOBQDSGUKVPVTUYS]Q`Ob RSHTKUOUUTYS\\ RQDRFSITOTUS[R^Q`";
prog_char	gGothicEng_2A[]	PROGMEM	=	"39JZRFQGSQRR RRFRR RRFSGQQRR RMINIVOWO RMIWO RMIMJWNWO RWIVINOMO RWIMO RWIWJMNMO";
prog_char	gGothicEng_2B[]	PROGMEM	=	"16F_RIRZSZ RRISISZ RJQ[Q[R RJQJR[R";
prog_char	gGothicEng_2C[]	PROGMEM	=	"14LXR^R\\PZRXSZS\\R^P_ RRYQZR[RY";
prog_char	gGothicEng_2D[]	PROGMEM	=	" 3E_IR[R";
prog_char	gGothicEng_2E[]	PROGMEM	=	"11LXRXPZR[TZRX RRYQZSZRY";
prog_char	gGothicEng_2F[]	PROGMEM	=	" 8G^[BIbJb R[B\\BJb";

prog_char	gGothicEng_30[]	PROGMEM	=	"42H\\LHLXJY RMIMXPZ RNHNXPYQZ RLHNHSGUF RSGTHVIVY RTGWIWX RUFVGXHZHXIXY RJYLYNZO[QZVYXY";
prog_char	gGothicEng_31[]	PROGMEM	=	"27H\\OHPIQKQXOY RQIPHQGRIRYTZ ROHRFSHSXUYVY ROYPYRZS[TZVY";
prog_char	gGothicEng_32[]	PROGMEM	=	"48H\\LHNHPGQFSGVHXH RPHRG RLHNIPIRHSG RVHVP RWIWO RXHXPQPNQLSKVK[ RK[OYSXVXZY RNZQYVYYZ RK[PZUZX[ZY";
prog_char	gGothicEng_33[]	PROGMEM	=	"57H\\LHMHOGPFRGVHXH ROHQG RLHNIPIRG RVHVO RWIWN RXHXOVOSPQQ RQPSQVRXRXY RWSWX RVRVY RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY";
prog_char	gGothicEng_34[]	PROGMEM	=	"41H\\UFKPKUTU RVUZU[V[TZU RLPLT RMNMU RTGTXRY RUJVHUGUYWZ RUFWHVJVXXYYY RRYSYUZV[WZYY";
prog_char	gGothicEng_35[]	PROGMEM	=	"53H\\LFLO RLFXF RMGVG RLHUHWGXF RVLUMSNOOLO RSNTNVOVY RUMWNWX RVLWMYNZNXOXY RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY";
prog_char	gGothicEng_36[]	PROGMEM	=	"59H\\LHLXJY RMIMXPZ RNHNXPYQZ RLHNHRGTFUGWHXH RSGUH RRGTIVIXH RNPOPSOUNVM RSOTOVPVY RUNWPWX RVMWNYOZOXPXY RJYLYNZO[QZVYXY";
prog_char	gGothicEng_37[]	PROGMEM	=	"38H\\KHMFPGUGZF RLGOHTHWG RKHOIRIVHZF RZFYHWKSOQRPUPXQ[ RRQQTQWRZ RUMSPRSRVSYQ[";
prog_char	gGothicEng_38[]	PROGMEM	=	"71H\\LILO RMJMN RNINO RLINISHUGVF RSHTHVIVO RUGWHWN RVFWGYHZHXIXO RLONOVRXR RXOVONRLR RLRLXJY RMSMXPZ RNRNXPYQZ RVRVY RWSWX RXRXY RJYLYNZO[QZVYXY";
prog_char	gGothicEng_39[]	PROGMEM	=	"60H\\LHLQJR RMIMROS RNHNQPRQR RLHNHSGUF RSGTHVIVY RTGWIWX RUFVGXHZHXIXY RJRKRMSNTOSQRUQVQ RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY";
prog_char	gGothicEng_3A[]	PROGMEM	=	"22LXRMPORPTORM RRNQOSORN RRXPZR[TZRX RRYQZSZRY";
prog_char	gGothicEng_3B[]	PROGMEM	=	"25LXRMPORPTORM RRNQOSORN RR^R\\PZRXSZS\\R^P_ RRYQZR[RY";
prog_char	gGothicEng_3C[]	PROGMEM	=	" 4F^ZIJRZ[";
prog_char	gGothicEng_3D[]	PROGMEM	=	"16F_JM[M[N RJMJN[N RJU[U[V RJUJV[V";
prog_char	gGothicEng_3E[]	PROGMEM	=	" 4F^JIZRJ[";
prog_char	gGothicEng_3F[]	PROGMEM	=	"51I[LJMHNGQFSFVGWHXJXLWNUPSQ RMJNH RVHWIWMVN RLJNKNIOGQF RSFUGVIVMUOSQ RRQRTSQQQRT RRXPZR[TZRX RRYQZSZRY";
//										 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 
prog_char	gGothicEng_40[]	PROGMEM	=	"56E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
prog_char	gGothicEng_41[]	PROGMEM	=	"60G]LINGPFRFSGZW[X]X RQGRHYXZZ[YYX RNGPGQHXXYZZ[[[]X RLMMLOKPKQL RPLPM RMLOLPN RG[IYKXNXPY RJYNYOZ RG[JZMZN[PY RRJLX RNSVS";
prog_char	gGothicEng_42[]	PROGMEM	=	"10F^HHJFMFOGQF RKGNG RHHJGLHOHQF RMKLLKNKOIOHPHRIQKQKW RLMLU RIPLP RMKMTLVKW RRIQJPLPU RQKQS RRIRRQTPU RRIXFZG[I[KYMUO RXGZIZK RVGXHYIYLWN RWNZP[R[X RYPZRZW RWNXOYQYX RJ[MYPXTXWY RLZOYTYVZ RJ[NZSZU[WYYX[X RUOUX RURYR RUUYU";
prog_char	gGothicEng_43[]	PROGMEM	=	"69E]NGLHJJILHOHSIVJXMZP[S[VZXYZW[U RJKINISKWNYQZTZWY RNGLIKKJNJRKUNXQYTYWXYW[U RPJPV RQJQT RRIRSQUPV RPJRIUFWGYGZF RTGVHXH RSHUIWIYHZF RWIWX";
prog_char	gGothicEng_44[]	PROGMEM	=	"72G^IFWFYGZIZX RKGWGYIYW RIFJGLHWHXIXX ROKNLMNMOKOJPJRKQMQMV RNMNT RKPNP ROKOSNUMV RI[LYOXSXVY RKZNYSYUZ RI[MZRZT[VYXXZX RRHRX RRMTNVNXM RRSTRVRXS";
prog_char	gGothicEng_45[]	PROGMEM	=	"94G]IHKFMFOGQF RLGNG RIHKGMHOHQF RNKMLLNLOJOIPIRJQLQLW RMMMU RJPMP RNKNTMVLW RQMRJSHTGVFXF[G RTHVGXGZH RRJSIUHWHYI[G RQURRSPTOVOXP RTPVPWQ RRRSQUQVRXP RK[NYRXWX[Y RMZPYWYZZ RK[OZVZY[[Y RQMQX";
prog_char	gGothicEng_46[]	PROGMEM	=	"91F]JHLFOFQGSF RMGPG RJHLGNHQHSF RPKOLNNNOLOKPKRLQNQNV ROMOT RLPOP RPKPSOUNV RSJSYRZQZMXKXIYG[ RTJTX RTPXP RPZOZMYJY RUIUOXO RXQUQUWTYP[N[LZJZG[ RSJUIXFZG\\G]F RWGYH[H RVHXIZI\\H]F RXIXW";
prog_char	gGothicEng_47[]	PROGMEM	=	"87E^NGLHJJILHOHRIUJWLYNZQ[U[XZZX[V[SZQYPWOUO RJKINISJV RNGLIKKJNJSKVLXNZ RYXZWZSYQ RU[WZXYYWYSXQWPUO RPJPW RQJQU RRIRTQVPW RPJRIUFWGYGZF RTGVHXH RSHUIWIYHZF RYHUOU[ RUSYS RUVYV";
prog_char	gGothicEng_48[]	PROGMEM	=	"12F^HHJFMFOGQF RKGNG RHHJGLHOHQF RMKLLKNKOIOHPHRIQKQKW RLMLU RIPLP RMKMTLVKW RJ[MYPXSXUY RLZOYRYTZ RJ[NZQZS[UY RRIQJPLPU RQKQS RRIRRQTPU RRITGVFXFZG RWGXGYH RTGVGXIZG RUOWNYLZM[P[TZXX[ RXMYNZPZUYX RWNXNYPYUX[ RUOUY RURYR RUUYU";
prog_char	gGothicEng_49[]	PROGMEM	=	"67I\\LHNFQFTGVF ROGSG RLHNGQHTHVF RSKRLQNQOOONPNROQQQQV RRMRT ROPRP RSKSSRUQV RYHWJVMVXUZSZOXMXKYI[ RWKWW RRZQZOYLY RYHXJXVWXUZS[P[NZKZI[";
prog_char	gGothicEng_4A[]	PROGMEM	=	"65H\\LHNFQFTGVF ROGSG RLHNGQHTHVF RSKRLQNQOOONPNROQQQQV RRMRT ROPRP RSKSSRUQV RYHWJVMVXUZ RWKWW RYHXJXVWXUZR[O[LZJXJVKULUMVLWKW RJVMV";
prog_char	gGothicEng_4B[]	PROGMEM	=	"15F^HHJFMFOGQF RKGNG RHHJGLHOHQF RMKLLKNKOIOHPHRIQKQKW RLMLU RIPLP RMKMTLVKW RJ[MYPXSXUY RLZNYRYTZ RJ[NZQZS[UY RRIQJPLPU RQKQS RRIRRQTPU RRITGVFXFZG RWGXGYH RTGVGXIZG RUOXLYM[N RWMYN[N R[NYQWSUU RWSYTZX[Z\\Z RYVZZ RWSXTYZZ[[[\\Z RUOUY";
prog_char	gGothicEng_4C[]	PROGMEM	=	"85G]IHKFNFPGRF RLGOG RIHKGMHPHRF RNKMLLNLOJOIPIRJQLQLW RMMMU RJPMP RNKNTMVLW RK[NYRXWX[Y RMZPYWYZZ RK[OZVZY[[Y RSIRJQLQU RRKRS RSISRRTQU RSIUGWFYF[G RXGYGZH RUGWGYI[G RWGWX";
prog_char	gGothicEng_4D[]	PROGMEM	=	"07D`LJKKJMJOHOGPGRHQJQJU RKLKS RHPKP RLJLRKTJU RE[GYIXKXMYNYOX RHYKYMZ RE[GZJZL[M[NZOX RLJPFTJTWUYVY RPGSJSXRYSZTYSX RPPSP RNHOHRKROOO ROQRQRXQYS[VYWX RTJXF\\J\\W]Y^Y RXG[J[X]Z RXP[P RVHWHZKZOWO RWQZQZY\\[^Y ROHOX RWHWX";
prog_char	gGothicEng_4E[]	PROGMEM	=	"84E^GIIGKFMFOGQJVUXXYY RMGOIPKVWYZ RIGKGMHOKTVVYWZY[ RVHXIZI\\H]F RWGYH[H RVHXFZG\\G]F RKOIOHPHRIQKQ RIPKP RG[IYKXNXPY RJYMYOZ RG[JZMZN[PY RKGKX RYIY[ RRLSMUNWNYM RKTMSQSST";
prog_char	gGothicEng_4F[]	PROGMEM	=	"79E_NFLGJIIKHNHRIUJWLYNZQ[S[VZXYZW[U\\R\\N[KZIXGVFUGRIOJ RJJIMISJV RNFLHKJJMJSKVLXNZ RZV[S[MYIXH RVZXXYVZSZMYKWHUG ROJOW RPJPU RQJQTPVOW RUGUZ RUMWNXNZM RUSWRXRZS";

prog_char	gGothicEng_50[]	PROGMEM	=	"70H^KFLGMIMOKOJPJRKQMQMYJ[MZMbO` RMHNJN` RKPNP RKFMGNHOJO` ROKRIVFZJZX RVGYJYX RTHUHXKXY RRXUXXY RSYUYWZ RRZTZV[XYZX RRIR_ RRMTNVNXM RRSTRVRXS";
prog_char	gGothicEng_51[]	PROGMEM	=	"99E_NFLGJIIKHNHRIUJWLYNZP[T[VZXYZW[U\\R\\N[KZIXGVFUGRIOJ RJJIMISJV RNFLHKJJMJSKVLXNZ RZV[S[MYIXH RVZXXYVZSZMYKWHUG ROJOW RPJPU RQJQTPVOW RUGUZ RUMWNXNZM RUSWRXRZS RP[QZRZT[X`Za[a RT\\V_XaYa RRZS[VaXbZb[a";
prog_char	gGothicEng_52[]	PROGMEM	=	"08F^HHJFMFOGQF RKGNG RHHJGLHOHQF RMKLLKNKOIOHPHRIQKQKW RLMLU RIPLP RMKMTLVKW RJ[MYPXRXUY RLZNYRYTZ RJ[NZQZS[UY RRIQJPLPU RQKQS RRIRRQTPU RRIUGWFYGZIZLYNXOTQRR RWGXGYIYMXN RUGWHXJXMWOTQ RTQVRWSZX[Y\\Y RWTYX[Z RTQVSXYZ[\\Y";
prog_char	gGothicEng_53[]	PROGMEM	=	"94G^UITHRGOF RVHTG RWGSFOFLGKHJJKLLMONWNYOZPZRYU RKKLLOMXMZN[O[QZS RKHKJLKOLYL[M\\O\\QYUU[ RIOJPLQUQVRVSUU RJQLRTRUS RIOIPJRLSSSUTUU RI[LYPXSXVY RKZNYRYUZ RI[MZRZU[ RWGUISL RRNPQ ROSMUKVJVJUKV";
prog_char	gGothicEng_54[]	PROGMEM	=	"71E]JJILHOHSIVKYMZP[S[VZXYZW[U RISJVLXNYQZTZWY RJJIMIQJTLWNXQYTYWXYW[U RHIIGKFOFUGYG[F RPGTHXH RHIIHKGNGTIWIYH[F RSIRJPKPV RQKQT RRJRSQUPV RWIWX";
prog_char	gGothicEng_55[]	PROGMEM	=	"89F^HHJFLFOGQF RKGNG RHHJGMHOHQF RKJJLIOISJVKXMZP[S[VZXYZ[\\Y RJSKVNYQZTZ RKJJNJQKTLVNXQYUYXX RUIQJPLPV RQKQT RRJRSQUPV RUIWHYFZG\\HZIZW[Y\\Y RYIZHYGXHYIYX[Z RWHXIXX RUIUY RUNXN RURXR";
prog_char	gGothicEng_56[]	PROGMEM	=	"72G^JFKGLILOJOIPIRJQLQLXJY RLHMJMX RJPMP RNYQYSZ RJFLGMHNJNXRXUY RJYMYPZR[UYXXZX RRJUIWHYFZG\\HZIZX RYIZHYGXHYIYW RWHXIXX RRJRX RRMTNVNXM RRSTRVRXS";
prog_char	gGothicEng_57[]	PROGMEM	=	"95E`HFIGJIJOHOGPGRHQJQJXHY RJHKJKX RHPKP RLYNYPZ RHFJGKHLJLXOXQY RHYKYNZO[QYTXVYW[YY\\X ROHRFTHTXWXYY RRGSHSX ROHQHRIRXQY RWYXZ RWHZF\\H\\X RZG[H[X RWHYHZIZXYY ROHOX RWHWX RONRN RORRR RWNZN RWRZR";
prog_char	gGothicEng_58[]	PROGMEM	=	"65G]HIJGLFNFOGWYXZZZ RMGNHVYWZ RJGLGMHUZV[X[ZZ\\X RWFYG[G\\F RWGXHZH RVHWIYI[H\\F RH[IYKXMXNY RJYLYMZ RH[IZKZM[ RWFSO RQRM[ RLPPP RSPXP";
prog_char	gGothicEng_59[]	PROGMEM	=	"86G^JFKGLILOJOIPIRJQLQLXJY RLHMJMX RJPMP RNYQYSZ RJFLGMHNJNXRXUY RJYMYPZR[UYXX RRJUIWHYFZG\\HZIZ^Y`WbUaQ`L` RYIZHYGXHYIYY RWHXIXXZ[ RXaV`S` RY`V_P_L` RRJRX RRMTNVNXM RRSTRVRXS";
prog_char	gGothicEng_5A[]	PROGMEM	=	"57H\\XGWIROOSMWJ[ RVKNV RZFWJUNRRMXLZ RJHLFOGUGZF RKGOHSHWG RJHNIRIVHXG RLZNYRXVXZY RMZQYUYYZ RJ[OZUZX[ZY RMPQP RTPXP";
prog_char	gGothicEng_5B[]	PROGMEM	=	"12KYOBOb RPBPb ROBVB RObVb";
prog_char	gGothicEng_5C[]	PROGMEM	=	" 3KYKFY^";
prog_char	gGothicEng_5D[]	PROGMEM	=	"12KYTBTb RUBUb RNBUB RNbUb";
prog_char	gGothicEng_5E[]	PROGMEM	=	" 8G]JTROZT RJTRPZT";
prog_char	gGothicEng_5F[]	PROGMEM	=	" 3G]Gb]b";

prog_char	gGothicEng_60[]	PROGMEM	=	" 7LXPFUL RPFOGUL";
prog_char	gGothicEng_61[]	PROGMEM	=	"53J[PRNTMVMXNZP[RYUX RMVNXOYQZ RNTNVOXQYRY RNPPPSOUNVMXOWPWXXYYY RONNOQO RTOWOVNVYWZ RMOOMPNROUPUYW[YY RMORT";
prog_char	gGothicEng_62[]	PROGMEM	=	"44I[LHMJMXKY RNJMHNGNXQZ RLHOFOXQYRZ RKYMYOZP[RZUYWY ROPROTNUMVNXOYOWPWY RTNVOVX RROSOUPUY";
prog_char	gGothicEng_63[]	PROGMEM	=	"35JXNONXLYMYOZP[ ROOOYQZ RPOPXRYSYQZP[ RNORNTMUNWOXO RSNTOVO RPORNTPVPXO";
prog_char	gGothicEng_64[]	PROGMEM	=	"41IZRMPNMOMXKY RNONXQZ RRMOOOXQYRZ RKYMYOZP[RZUYWY RMHPFQIWOWY RPINHOGPIVOVX RMHUPUY";
prog_char	gGothicEng_65[]	PROGMEM	=	"32JXNONXLYMYOZP[ ROOOYQZ RPOPXRYSYQZP[ RNORNTMWQURPU RSNVQ RPORNUR";
prog_char	gGothicEng_66[]	PROGMEM	=	"41JWNHNXLYMYOZP[ ROHOYQZ RPHPXRYSYQZP[ RNHQGSFTGVHWH RRGSHUH RPHQGSIUIWH RKMNM RPMTM";
prog_char	gGothicEng_67[]	PROGMEM	=	"56I[MOMXKYLYNZO[PZRYUX RNPNYPZ ROOOXQYRY RMOOORNTMUNWOYOWPW\\V_TaRbQaO`M` RSNVPV\\ RSaQ`P` RRNSOUPUZV]V_ RTaS`Q_O_M`";
prog_char	gGothicEng_68[]	PROGMEM	=	"47I[LHMJMXKYLYNZO[ RNJMHNGNYPZ RLHOFOXQYO[ ROPROTNUMVNXOYOWPWYU[T] RTNVOVYU[ RROSOUPUYT]T`UbVbT`";
prog_char	gGothicEng_69[]	PROGMEM	=	"35MWRFPHRITHRF RRGQHSHRG RRMQNOOQPQYS[UY RRPSORNQORPRYSZ RRMSNUOSPSXTYUY";
prog_char	gGothicEng_6A[]	PROGMEM	=	"39MWRFPHRITHRF RRGQHSHRG RRMQNOOQPQYS[T] RRPSORNQORPRYS[ RRMSNUOSPSYT]T`RbPbPaRb";
prog_char	gGothicEng_6B[]	PROGMEM	=	"50IZLHMJMXKYLYNZO[ RNJMHNGNYPZ RLHOFOXQYO[ ROPRNTMVPSROU RSNUP RRNTQ RSRTSVXWYXY RSSTTUYVZ RRSSTTYV[XY";
prog_char	gGothicEng_6C[]	PROGMEM	=	"22MWPHQJQXOYPYRZS[ RRJQHRGRYTZ RPHSFSXUYVYTZS[";
prog_char	gGothicEng_6D[]	PROGMEM	=	"67E_GOHOIPIXGYHYJZK[ RINJOJYLZ RGOIMKOKXMYK[ RKPNOPNQMSOSXUYS[ RPNRORYTZ RNOOOQPQXPYRZS[ RSPVOXNYMZN\\O]O[P[X\\Y]Y RXNZOZY[Z RVOWOYPYY[[]Y";
prog_char	gGothicEng_6E[]	PROGMEM	=	"45I[KOLOMPMXKYLYNZO[ RMNNONYPZ RKOMMOOOXQYO[ ROPROTNUMVNXOYOWPWXXYYY RTNVOVYWZ RROSOUPUYW[YY";
prog_char	gGothicEng_6F[]	PROGMEM	=	"40I[MOMXKY RNPNXQZ ROOOXQYRZ RKYMYOZP[RZUYWY RMOOORNTMUNWOYOWPWY RSNVPVX RRNSOUPUY";

prog_char	gGothicEng_70[]	PROGMEM	=	"54I[LMMOMXKYMYMb RMNNONaO`N^ RNYOYQZ RLMNNOOOXQYRZ ROZP[RZUYWY ROZO^P`Mb ROPROTNUMVNXOYOWPWY RTNVOVX RROSOUPUY";
prog_char	gGothicEng_71[]	PROGMEM	=	"44I[MOMXKY RNPNYPZ ROOOXQYRY RKYLYNZO[PZRYUX RMOOORNTMUNWOYOWPWb RSNVPVaU`V^ RRNSOUPU^T`Wb";
prog_char	gGothicEng_72[]	PROGMEM	=	"38JXLOMONPNXLYMYOZP[ RMNOOOYQZ RLONMPOPXRYSYQZP[ RPOTMUNWOXO RSNTOVO RRNTPVPXO";
prog_char	gGothicEng_73[]	PROGMEM	=	"59JZMOMSOTUTWUWY RNONS RVUVY RPNOOOSQT RSTUUUYTZ RMOPNRMTNVNWM RQNSN RPNROTOVN RWYTZR[PZNZL[ RSZQZ RTZRYOYL[ RWMVOTROWL[";
prog_char	gGothicEng_74[]	PROGMEM	=	"28MWPHQJQXOYPYRZS[ RRJQHRGRYTZ RPHSFSXUYVYTZS[ RNMQM RSMVM";
prog_char	gGothicEng_75[]	PROGMEM	=	"47I[KOLOMPMXKY RLNNONYPZ RKOMMOOOXQYRY RKYLYNZO[PZRYUX RUMVNXOYOWPWXXYYY RTNVOVYWZ RUMSOUPUYW[YY";
prog_char	gGothicEng_76[]	PROGMEM	=	"36I[LMMOMXP[RYUXWX RMNNONXQZ RLMNNOOOWPXRY RUMVNXOYOWPWX RTNVOVW RUMSOUPUX";
prog_char	gGothicEng_77[]	PROGMEM	=	"57E_HMIOIXL[NYQX RINJOJXMZ RHMJNKOKWLXNY RQMOOQPQXT[VYYX[X RPNRORXUZ RQMRNTOSPSWTXVY RYMZN\\O]O[P[X RXNZOZW RYMWOYPYX";
prog_char	gGothicEng_78[]	PROGMEM	=	"59H[KOLONPOQSYTZV[XY RMNOOTYVZ RKOMMONPOTWUXWYXY RRSUMVNXNYM RUNVOWO RTOVPXOYM RQUN[MZKZJ[ RNZMYLY ROYMXKYJ[ RMTPT RSTVT";
prog_char	gGothicEng_79[]	PROGMEM	=	"60I[KOLOMPMXKY RLNNONYPZ RKOMMOOOXQYRY RKYLYNZO[PZRYUX RUMVNXOYOWPW\\V_TaRbQaO`M` RTNVOV\\ RSaQ`P` RUMSOUPUZV]V_ RTaS`Q_O_M`";
prog_char	gGothicEng_7A[]	PROGMEM	=	"38I[XML[ RLONPQPTOXM RMNOOSO RLONMPNTNXM RL[PYSXVXXY RQYUYWZ RL[PZTZV[XY RNTVT";
prog_char	gGothicEng_7B[]	PROGMEM	=	"40KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
prog_char	gGothicEng_7C[]	PROGMEM	=	" 3NVRBRb";
prog_char	gGothicEng_7D[]	PROGMEM	=	"40KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
prog_char	gGothicEng_7E[]	PROGMEM	=	"24F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
prog_char	gGothicEng_7F[]	PROGMEM	=	"35JZJFJ[K[KFLFL[M[MFNFN[O[OFPFP[Q[QFRFR[S[SFTFT[U[UFVFV[W[WFXFX[Y[YFZFZ[";


PGM_P gHershyGothicEngFontTable[]	PROGMEM =	   // change "string_table" name to suit
{

	gGothicEng_00,
	gGothicEng_20,
	gGothicEng_21,
	gGothicEng_22,
	gGothicEng_23,
	gGothicEng_24,
	gGothicEng_25,
	gGothicEng_26,
	gGothicEng_27,
	gGothicEng_28,
	gGothicEng_29,
	gGothicEng_2A,
	gGothicEng_2B,
	gGothicEng_2C,
	gGothicEng_2D,
	gGothicEng_2E,
	gGothicEng_2F,

	gGothicEng_30,
	gGothicEng_31,
	gGothicEng_32,
	gGothicEng_33,
	gGothicEng_34,
	gGothicEng_35,
	gGothicEng_36,
	gGothicEng_37,
	gGothicEng_38,
	gGothicEng_39,
	gGothicEng_3A,
	gGothicEng_3B,
	gGothicEng_3C,
	gGothicEng_3D,
	gGothicEng_3E,
	gGothicEng_3F,

	gGothicEng_40,
	gGothicEng_41,
	gGothicEng_42,
	gGothicEng_43,
	gGothicEng_44,
	gGothicEng_45,
	gGothicEng_46,
	gGothicEng_47,
	gGothicEng_48,
	gGothicEng_49,
	gGothicEng_4A,
	gGothicEng_4B,
	gGothicEng_4C,
	gGothicEng_4D,
	gGothicEng_4E,
	gGothicEng_4F,

	gGothicEng_50,
	gGothicEng_51,
	gGothicEng_52,
	gGothicEng_53,
	gGothicEng_54,
	gGothicEng_55,
	gGothicEng_56,
	gGothicEng_57,
	gGothicEng_58,
	gGothicEng_59,
	gGothicEng_5A,
	gGothicEng_5B,
	gGothicEng_5C,
	gGothicEng_5D,
	gGothicEng_5E,
	gGothicEng_5F,

	gGothicEng_60,
	gGothicEng_61,
	gGothicEng_62,
	gGothicEng_63,
	gGothicEng_64,
	gGothicEng_65,
	gGothicEng_66,
	gGothicEng_67,
	gGothicEng_68,
	gGothicEng_69,
	gGothicEng_6A,
	gGothicEng_6B,
	gGothicEng_6C,
	gGothicEng_6D,
	gGothicEng_6E,
	gGothicEng_6F,

	gGothicEng_70,
	gGothicEng_71,
	gGothicEng_72,
	gGothicEng_73,
	gGothicEng_74,
	gGothicEng_75,
	gGothicEng_76,
	gGothicEng_77,
	gGothicEng_78,
	gGothicEng_79,
	gGothicEng_7A,
	gGothicEng_7B,
	gGothicEng_7C,
	gGothicEng_7D,
	gGothicEng_7E,
	gGothicEng_7F

};
