//*******************************************************************************
//*	greek.jhf		Greek
//*	formated for use with Arduino Processing 
//*	by Mark Sproul
//*******************************************************************************
//*	Jan 11,	2010	<MLS>	Formated Hershey gothitt for Arduino
//*******************************************************************************
//#include	"HersheyGothitt.h"


prog_char	gGothitt_00[]	PROGMEM	=	"Gothitt";


prog_char	gGothitt_20[]	PROGMEM	=	" 1JZ";
prog_char	gGothitt_21[]	PROGMEM	=	"30LXRFQGOHQIRT RRISHRGQHRIRT RRFSGUHSIRT RRXPZR[TZRX RRYQZSZRY";
prog_char	gGothitt_22[]	PROGMEM	=	"22I[NFMGMM RNGMM RNFOGMM RWFVGVM RWGVM RWFXGVM";
prog_char	gGothitt_23[]	PROGMEM	=	"12H]SFLb RYFRb RLQZQ RKWYW";
prog_char	gGothitt_24[]	PROGMEM	=	"60H\\PBP_ RTBT_ RTFVGWIWKYJXHWGTFPFMGKIKLLNOPURWSXUXXWZ RXJWH RLLMNOOUQWRXT RMYLW RMGLILKMMONUPXRYTYWXYWZT[P[MZLYKWMVMXNZP[";
prog_char	gGothitt_25[]	PROGMEM	=	"32F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT";
prog_char	gGothitt_26[]	PROGMEM	=	"62E_YNZO[O\\N RXOYP[P RXPYQZQ[P\\N RYNST RRUL[HVNP ROOSKOFJLPRTXVZX[Z[[Z\\X RLZIV RRKOG RKLPQTWVYXZ[Z RMZIU RRLNG RKKQQUWVXXY[Y\\X";
prog_char	gGothitt_27[]	PROGMEM	=	"14LXRLRJPHRFSHSJRLPM RRGQHRIRG";
prog_char	gGothitt_28[]	PROGMEM	=	"27KYUBSDQGOKNPNTOYQ]S`Ub RQHPKOOOUPYQ\\ RSDRFQIPOPUQ[R^S`";
prog_char	gGothitt_29[]	PROGMEM	=	"27KYOBQDSGUKVPVTUYS]Q`Ob RSHTKUOUUTYS\\ RQDRFSITOTUS[R^Q`";
prog_char	gGothitt_2A[]	PROGMEM	=	"39JZRFQGSQRR RRFRR RRFSGQQRR RMINIVOWO RMIWO RMIMJWNWO RWIVINOMO RWIMO RWIWJMNMO";
prog_char	gGothitt_2B[]	PROGMEM	=	"16F_RIRZSZ RRISISZ RJQ[Q[R RJQJR[R";
prog_char	gGothitt_2C[]	PROGMEM	=	"14LXR^R\\PZRXSZS\\R^P_ RRYQZR[RY";
prog_char	gGothitt_2D[]	PROGMEM	=	" 8F_JQ[Q[R RJQJR[R";
prog_char	gGothitt_2E[]	PROGMEM	=	"11LXRXPZR[TZRX RRYQZSZRY";
prog_char	gGothitt_2F[]	PROGMEM	=	" 8G^[BIbJb R[B\\BJb";

prog_char	gGothitt_30[]	PROGMEM	=	"42H\\LHLXJY RMIMXPZ RNHNXPYQZ RLHNHSGUF RSGTHVIVY RTGWIWX RUFVGXHZHXIXY RJYLYNZO[QZVYXY";
prog_char	gGothitt_31[]	PROGMEM	=	"27H\\OHPIQKQXOY RQIPHQGRIRYTZ ROHRFSHSXUYVY ROYPYRZS[TZVY";
prog_char	gGothitt_32[]	PROGMEM	=	"48H\\LHNHPGQFSGVHXH RPHRG RLHNIPIRHSG RVHVP RWIWO RXHXPQPNQLSKVK[ RK[OYSXVXZY RNZQYVYYZ RK[PZUZX[ZY";
prog_char	gGothitt_33[]	PROGMEM	=	"57H\\LHMHOGPFRGVHXH ROHQG RLHNIPIRG RVHVO RWIWN RXHXOVOSPQQ RQPSQVRXRXY RWSWX RVRVY RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY";
prog_char	gGothitt_34[]	PROGMEM	=	"41H\\UFKPKUTU RVUZU[V[TZU RLPLT RMNMU RTGTXRY RUJVHUGUYWZ RUFWHVJVXXYYY RRYSYUZV[WZYY";
prog_char	gGothitt_35[]	PROGMEM	=	"53H\\LFLO RLFXF RMGVG RLHUHWGXF RVLUMSNOOLO RSNTNVOVY RUMWNWX RVLWMYNZNXOXY RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY";
prog_char	gGothitt_36[]	PROGMEM	=	"59H\\LHLXJY RMIMXPZ RNHNXPYQZ RLHNHRGTFUGWHXH RSGUH RRGTIVIXH RNPOPSOUNVM RSOTOVPVY RUNWPWX RVMWNYOZOXPXY RJYLYNZO[QZVYXY";
prog_char	gGothitt_37[]	PROGMEM	=	"38H\\KHMFPGUGZF RLGOHTHWG RKHOIRIVHZF RZFYHWKSOQRPUPXQ[ RRQQTQWRZ RUMSPRSRVSYQ[";
prog_char	gGothitt_38[]	PROGMEM	=	"71H\\LILO RMJMN RNINO RLINISHUGVF RSHTHVIVO RUGWHWN RVFWGYHZHXIXO RLONOVRXR RXOVONRLR RLRLXJY RMSMXPZ RNRNXPYQZ RVRVY RWSWX RXRXY RJYLYNZO[QZVYXY";
prog_char	gGothitt_39[]	PROGMEM	=	"60H\\LHLQJR RMIMROS RNHNQPRQR RLHNHSGUF RSGTHVIVY RTGWIWX RUFVGXHZHXIXY RJRKRMSNTOSQRUQVQ RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY";
prog_char	gGothitt_3A[]	PROGMEM	=	"22LXRMPORPTORM RRNQOSORN RRXPZR[TZRX RRYQZSZRY";
prog_char	gGothitt_3B[]	PROGMEM	=	"25LXRMPORPTORM RRNQOSORN RR^R\\PZRXSZS\\R^P_ RRYQZR[RY";
prog_char	gGothitt_3C[]	PROGMEM	=	" 4F^ZIJRZ[";
prog_char	gGothitt_3D[]	PROGMEM	=	"16F_JM[M[N RJMJN[N RJU[U[V RJUJV[V";
prog_char	gGothitt_3E[]	PROGMEM	=	" 4F^JIZRJ[";
prog_char	gGothitt_3F[]	PROGMEM	=	"51I[LJMHNGQFSFVGWHXJXLWNUPSQ RMJNH RVHWIWMVN RLJNKNIOGQF RSFUGVIVMUOSQ RRQRTSQQQRT RRXPZR[TZRX RRYQZSZRY";

prog_char	gGothitt_40[]	PROGMEM	=	"56E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
prog_char	gGothitt_41[]	PROGMEM	=	"52E_NHLIJKIMHPHSIUKV RJLIOISJU RNHLJKLJOJRKVKXJZH[ RVHXHXYVY RYHYY RZGZZ RHFKGQHVHZG\\F RJPXP RH[KZQYVYZZ\\[";
prog_char	gGothitt_42[]	PROGMEM	=	"65E_LGLZ RMGMZ RPFNGNZP[ RHJJHLGPFUFXGZIZKYM RXHYIYKXM RUFWGXIXKWL RQUOTNRNPONPMSLVLYM[O\\Q\\T[WYYWZT[P[LZJYHW RZO[Q[UZW RVLYNZQZUYXWZ";
prog_char	gGothitt_43[]	PROGMEM	=	"60E_\\F[HZJXHVGSFQFNGLHJJILHOHRIUJWLYNZQ[S[VZXYZW[Y\\[ R[HZMZT[Y RZKYJ RZNYKXIVG RJKINISJV RNGLIKKJNJSKVLXNZ RYWZV RVZXXYVZS";
prog_char	gGothitt_44[]	PROGMEM	=	"46E_KGKZ RLGLZ RNFMGMZN[ RHKIIKGNFSFVGXHZJ[L\\O\\R[UZWXYVZS[N[KZIXHV RZK[N[SZV RVGXIYKZNZSYVXXVZ";
prog_char	gGothitt_45[]	PROGMEM	=	"86E_\\F[HZJXHVGSFQFNGLHJJILHOHRIUJWLYNZQ[S[VZXYZW[Y\\[ R[HZMZT[Y RZKYJ RZMXIVG RJKINISJV RNGLIKKJNJSKVLXNZ RYWZV RVZXXYVZS RJPKONOUQXQZP RPPRQURWRYQ RMORRUSWSYRZP RZMYLXLWMXNYM";
prog_char	gGothitt_46[]	PROGMEM	=	"69E_JHJZ RMGKHKY ROFMGLILYNY RHJJHLGOFSFVGXHYI\\F R\\F[HZLZO[S\\U RZIYK RVGXIYLZO RLPMOOOTPWPYO RQPTQVQXP RNOTRVRXQYOYLXKWKVLWMXL RH[JZNYSYYZ\\[";
prog_char	gGothitt_47[]	PROGMEM	=	"90E_\\F[HZJXHVGSFQFNGLHJJILHOHRIUJWLYNZQ[T[VZXYYXZV[Y\\[ R[HZMZT[Y RZKYJ RZNYKXIVG RJKINISJV RNGLIKKJNJSKVLXNZ RXXYVYR RVZWYXVXQ RKSLRMSLTKTJS RJPKNMMOMRNUPWQ RKOMNONROTP RJPLOOOUQYQZP";
prog_char	gGothitt_48[]	PROGMEM	=	"50E_JGJZH[ RKHKZ RNHLHLZ RHFJGNHSHYG\\F RLPMNOLRKVKYL[N\\Q\\T[UYV RZN[P[SZU RVKXLYMZOZSYVYXZZ\\[ RH[LZPZU[";
prog_char	gGothitt_49[]	PROGMEM	=	"23E_QIQY RRJRX RSISY RHFLHPITIXH\\F RH[KZOYUYYZ\\[";
prog_char	gGothitt_4A[]	PROGMEM	=	"42E_TIVIVXUZS[ RWIWXVY RXHXY RHFLHPITIXH\\F RIOHQHUIXKZN[S[VZXYZW\\T RIUJXKY RHSJUKXLZN[";
prog_char	gGothitt_4B[]	PROGMEM	=	"70E_JGJZH[ RKHKZ RNHLHLZ RHFJGNHSHYG\\F RLPMNOLRKUKXLYMYOXPSRQSPTPUQVRUQT RWLXMXOWP RUKWMWOVPSR RSRVRYSZUZWYX RWSYUYW RSRVSXUYXZZ[[\\[ RH[LZPZU[";
prog_char	gGothitt_4C[]	PROGMEM	=	"45E_JGJZ RKHKY RNHLHLYNY R\\KZNYPXSXUYW[X RZOYRYUZW R\\K[MZQZT[X\\[ RHFJGNHSHYG\\F RH[JZNYSYYZ\\[";
prog_char	gGothitt_4D[]	PROGMEM	=	"68E_QIQY RRJRX RSISY RNYLWJVIUHRHMIJKHMGPFTFWGYH[J\\M\\R[UZVXWVY RJUIRIMJJ RLWKUJRJLKIMG RZJ[M[RZU RWGYIZLZRYUXW RHFLHPITIXH\\F RH[KZOYUYYZ\\[";
prog_char	gGothitt_4E[]	PROGMEM	=	"48E_JHJZH[ RLHKIKZ ROFMGLILZ RHJJHLGOFSFVGXHZJ[L\\O\\S[UYV RZK[N[RZU RVGXIYKZNZRYVYXZZ[[\\[ RH[LZPZU[";
prog_char	gGothitt_4F[]	PROGMEM	=	"54E_QFNGLHJJILHOHRIUJWLYNZQ[S[VZXYZW[U\\R\\O[LZJXHVGSFQF RJKINISJV RNGLIKKJNJSKVLXNZ RZV[S[NZK RVZXXYVZSZNYKXIVG";

prog_char	gGothitt_50[]	PROGMEM	=	"51E_JIJZ RMHKJKY RQFOGMILKLYNY RHKJINGQFTFWGYH[J\\M\\O[RYTVURUOTMRLO RZJ[L[PZR RWGYIZLZPYSVU RH[JZNYSYYZ\\[";
prog_char	gGothitt_51[]	PROGMEM	=	"74E_QFNGLHJJILHOHRIUJWLYNZQ[S[VZXYZW[U\\R\\O[LZJXHVGSFQF RJKINISJV RNGLIKKJNJSKVLXNZ RZV[S[NZK RVZXXYVZSZNYKXIVG RJSKUNVTW[W\\X\\Z[[[Z\\Y RPWRW RKUNWQXSXTW";
prog_char	gGothitt_52[]	PROGMEM	=	"69E_JIJZH[ RKIKZ RLHLZ RHKJILHNGQFUFYG[I\\K\\N[PZQ RYHZI[K[NZP RUFWGYIZKZOYQ RXRUSRSPRPPROUOXPZR\\U\\W[XZX RXQYR[V[WZT RTOVPXRYTZX[Z\\[ RH[LZPZU[";
prog_char	gGothitt_53[]	PROGMEM	=	"94E_TFZG\\F[H[JYHWGTFPFMGJJIMIOJRLTOURUTTUSVQVP R[GZH[J RJPKRLSOTRTTS RKIJKJNKPMRPSRSTRVPWOXO RLQMQNPPNRMUMWNYPZRZUYXWZ RPMRLULXMZO[R[UZW RIWJYIZ RNPNOOMPLRKUKXL[O\\R\\T[WYYWZT[P[MZKYIWIYH[JZP[";
prog_char	gGothitt_54[]	PROGMEM	=	"66E_QHMHKIJJILHOHSIVJXKYMZP[S[VZXYZW[U\\R\\N[KYIWH RUHTITKULVKUJ RISJVLXNYQZTZWY RJJINIQJTLWNXQYTYWXYW[T\\R RHFKI RKHLG RIGJGKFMGQHWHZG\\F";
prog_char	gGothitt_55[]	PROGMEM	=	"51E_LHJJILHOHRIUJWLYNZQ[U[XZZY RKJJLIOISJV RKILJLKKMJPJSKVLXNZ RVHXHXXWZU[ RYHYXXY RZGZY\\[ RHFKGQHVHZG\\F";
prog_char	gGothitt_56[]	PROGMEM	=	"31E_HFR[ RIGJHQWRY RJGKHRWSX R\\FR[ RWNUS RYLUQTTTV RHFJGOHUHZG\\F";
prog_char	gGothitt_57[]	PROGMEM	=	"67E_LHJJILHOHRIUJWLYNZQ[S[VZXYZW[U\\R\\O[LZJXH RJLIOIRJUKW RJJKKKLJOJRKVLXNZ RYWZU[R[OZL RVZXXYVZRZOYLYKZJ RQIQ[ RRJRZ RSIS[ RHFLHPITIXH\\F";
prog_char	gGothitt_58[]	PROGMEM	=	"41E_HFXYYZ RIGKHZZ RLH\\[ R\\FSP RQRJZ RPSMULW RQRMTLUKWKY RHFLHPITIXH\\F RH[JZNYSYYZ\\[";
prog_char	gGothitt_59[]	PROGMEM	=	"47E_XHXZ RYHYY RZGZY RKHIJHMHPISKUMVPWSWVVXU RLUOVUV RHPIRKTNUTUVV RHFLHPITIXH\\F RHWJYLZP[T[XZ\\X";
prog_char	gGothitt_5A[]	PROGMEM	=	"73E_HFIGKHNHSFVFYGZIZKYM RXGYIYKXM RVFWGXIXL RXNTOROPNPLRKTKXL RTKVLWMVNTO RYM[O\\R\\T[WYYWZT[P[MZKYIWHTHRIOJNLMNMPNPPOQNPOO RXMZO[Q[UZW RXNYOZQZUYXWZ";
prog_char	gGothitt_5B[]	PROGMEM	=	"12KYOBOb RPBPb ROBVB RObVb";
prog_char	gGothitt_5C[]	PROGMEM	=	" 3KYKFY^";
prog_char	gGothitt_5D[]	PROGMEM	=	"12KYTBTb RUBUb RNBUB RNbUb";
prog_char	gGothitt_5E[]	PROGMEM	=	"11JZPLRITL RMORJWO RRJR[";
prog_char	gGothitt_5F[]	PROGMEM	=	" 3JZJ]Z]";

prog_char	gGothitt_60[]	PROGMEM	=	"14LXTFRGQIQKRMTKRIRG RRJRLSKRJ";
prog_char	gGothitt_61[]	PROGMEM	=	"42J[PQMTMXP[TY RNTNXPZ ROROWRZ RRSMNNMONNO RONSNUMWOWXXY RUNVOVXUYVZWYVX RSNUPUXTYV[XY";
prog_char	gGothitt_62[]	PROGMEM	=	"31IZNHLFMJMXP[UYWX RNHNXPZ RNHPFOJOWRZ ROOTMWPWX RTNVPVX RRNUQUY";
prog_char	gGothitt_63[]	PROGMEM	=	"23KWNPNYP[RY ROPOYPZ RPOPXQYRY RNPTMVOTPRN RSNUO";
prog_char	gGothitt_64[]	PROGMEM	=	"32JZRMMPMXP[RZUYWY RNPNXPZ ROOOWRZ RPIPFQIWPWY RPIVPVX RPIMIPJUPUY";
prog_char	gGothitt_65[]	PROGMEM	=	"25KXNPNYP[RY ROPOYPZ RPOPXQYRY RNPTMWQPU RSNVQ RRNUR";
prog_char	gGothitt_66[]	PROGMEM	=	"32KWOIOXNYP[ RPIPXOYPZQYPX RQHQXRYP[ ROIUFWHUISG RTGVH RLMOM RQMUM";
prog_char	gGothitt_67[]	PROGMEM	=	"41J[MPMXP[UY RNPNXPZ ROOOWRZ RMPOOTMWPW]V_U`SaQaO`MaObQa RTNVPV]U_ RPaNa RRNUQU^T`Sa";
prog_char	gGothitt_68[]	PROGMEM	=	"42I[NHLFMJMXLYN[ RNHNXMYNZOYNX RNHPFOJOXPYN[ ROORNTMWPWYT]T`UbVbT` RTNVPVYU[ RRNUQUZT]";
prog_char	gGothitt_69[]	PROGMEM	=	"37MWRFPHRJTHRF RRGQHRISHRG RRMPOQPQXPYR[ RRPSORNQORPRXQYRZSYRX RRMTOSPSXTYR[";
prog_char	gGothitt_6A[]	PROGMEM	=	"37MWRFPHRJTHRF RRGQHRISHRG RRMPOQPQYT] RRPSORNQORPRYS[ RRMTOSPSZT]T`RbPaPbRb";
prog_char	gGothitt_6B[]	PROGMEM	=	"51IZNHLFMJMXLYN[ RNHNXMYNZOYNX RNHPFOJOXPYN[ ROPRNTMVPSROU RSNUP RRNTQ RRSSTTYV[XY RSSTUUYVZ RSRTSVXWYXY";
prog_char	gGothitt_6C[]	PROGMEM	=	"21MWRHPFQJQXPYR[ RRHRXQYRZSYRX RRHTFSJSXTYR[";
prog_char	gGothitt_6D[]	PROGMEM	=	"66E_GOHOIPIXHYJ[ RINJOJXIYJZKYJX RGOIMKOKXLYJ[ RKONNPMSOSXTYR[ RPNRORXQYRZSYRX RNNQPQXPYR[ RSOVNXM[O[X\\YZ[ RXNZOZXYYZZ[YZX RVNYPYXXYZ[";
prog_char	gGothitt_6E[]	PROGMEM	=	"44I[KOLOMPMXLYN[ RMNNONXMYNZOYNX RKOMMOOOXPYN[ ROORNTMWOWXXYV[ RTNVOVXUYVZWYVX RRNUPUXTYV[";
prog_char	gGothitt_6F[]	PROGMEM	=	"28JZMPMXP[UYWX RNPNXPZ ROOOWRZ RMPOOTMWPWX RTNVPVX RRNUQUY";

prog_char	gGothitt_70[]	PROGMEM	=	"47IZLMMOMXKYMYM_LbN` RNON` RLMNNOOOXQYRZ RNYOYQZ ROZP[UYWX ROZO_PbN` ROORNTMWPWX RTNVPVX RRNUQUY";
prog_char	gGothitt_71[]	PROGMEM	=	"31J[MPMXP[UY RNPNXPZ ROOOWRZ RMPOOTMWPW_XbV` RTNVPV` RRNUQU_TbV`";
prog_char	gGothitt_72[]	PROGMEM	=	"31KXMONOOPOXNYP[ RONPOPXOYPZQYPX RMOOMQOQXRYP[ RQOUMWOUPSN RTNVO";
prog_char	gGothitt_73[]	PROGMEM	=	"41JZMPMSOUURWTWX RNPNSOT ROOOSPT RUSVTVX RTSUTUY RMPSMVNTOQN RRNUN RWXQ[MYOXSZ ROYQZ";
prog_char	gGothitt_74[]	PROGMEM	=	"27MWRHPFQJQXPYR[ RRHRXQYRZSYRX RRHTFSJSXTYR[ RNMQM RSMVM";
prog_char	gGothitt_75[]	PROGMEM	=	"40I[KOLOMPMYP[UY RMNNONYPZ RKOMMOOOXRZ RVMXOWPWXXYYY RVPWOVNUOVPVYWZ RVMTOUPUYW[YY";
prog_char	gGothitt_76[]	PROGMEM	=	"36I[LMMOMXQ[SYWW RMNNONXQZ RLMNNOOOWRYSY RVMXOWPWW RVPWOVNUOVPVW RVMTOUPUX";
prog_char	gGothitt_77[]	PROGMEM	=	"59E_HMIOIXM[OYQX RINJOJXMZ RHMJNKOKWNYOY RRMPOQPQXU[WY[W RRPSORNQORPRXUZ RRMTOSPSWVYWY RZM\\O[P[W RZP[OZNYOZPZW RZMXOYPYX";
prog_char	gGothitt_78[]	PROGMEM	=	"39I[LONPUZV[XY RMNOOUYWZ RLONMONVXXY RXMVMVOXOXMVOSS RQUNYL[N[NYLYL[ RNTQT RSTVT";
prog_char	gGothitt_79[]	PROGMEM	=	"49I[KOLOMPMYP[UY RMNNONYPZ RKOMMOOOXRZ RVMXOWPW]V_U`SaQaO`MaObQa RVPWOVNUOVPV^U_ RPaNa RVMTOUPU^T`Sa";
prog_char	gGothitt_7A[]	PROGMEM	=	"43L[RNOPOORNTMWOWSRU RTNVOVS RRNUPUSTT RRUWWW]V_U`SaQaO`MaObQa RVWV^U_ RPaNa RTVUWU^T`Sa";
prog_char	gGothitt_7B[]	PROGMEM	=	"40KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
prog_char	gGothitt_7C[]	PROGMEM	=	" 3NVRBRb";
prog_char	gGothitt_7D[]	PROGMEM	=	"40KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
prog_char	gGothitt_7E[]	PROGMEM	=	"24F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
prog_char	gGothitt_7F[]	PROGMEM	=	"30KYQFOGNINKOMQNSNUMVKVIUGSFQF RQFNIOMSNVKUGQF RSFOGNKQNUMVISF";



PGM_P gHershyGothittFontTable[]	PROGMEM =	   // change "string_table" name to suit
{

	gGothitt_00,
	gGothitt_20,
	gGothitt_21,
	gGothitt_22,
	gGothitt_23,
	gGothitt_24,
	gGothitt_25,
	gGothitt_26,
	gGothitt_27,
	gGothitt_28,
	gGothitt_29,
	gGothitt_2A,
	gGothitt_2B,
	gGothitt_2C,
	gGothitt_2D,
	gGothitt_2E,
	gGothitt_2F,

	gGothitt_30,
	gGothitt_31,
	gGothitt_32,
	gGothitt_33,
	gGothitt_34,
	gGothitt_35,
	gGothitt_36,
	gGothitt_37,
	gGothitt_38,
	gGothitt_39,
	gGothitt_3A,
	gGothitt_3B,
	gGothitt_3C,
	gGothitt_3D,
	gGothitt_3E,
	gGothitt_3F,

	gGothitt_40,
	gGothitt_41,
	gGothitt_42,
	gGothitt_43,
	gGothitt_44,
	gGothitt_45,
	gGothitt_46,
	gGothitt_47,
	gGothitt_48,
	gGothitt_49,
	gGothitt_4A,
	gGothitt_4B,
	gGothitt_4C,
	gGothitt_4D,
	gGothitt_4E,
	gGothitt_4F,

	gGothitt_50,
	gGothitt_51,
	gGothitt_52,
	gGothitt_53,
	gGothitt_54,
	gGothitt_55,
	gGothitt_56,
	gGothitt_57,
	gGothitt_58,
	gGothitt_59,
	gGothitt_5A,
	gGothitt_5B,
	gGothitt_5C,
	gGothitt_5D,
	gGothitt_5E,
	gGothitt_5F,

	gGothitt_60,
	gGothitt_61,
	gGothitt_62,
	gGothitt_63,
	gGothitt_64,
	gGothitt_65,
	gGothitt_66,
	gGothitt_67,
	gGothitt_68,
	gGothitt_69,
	gGothitt_6A,
	gGothitt_6B,
	gGothitt_6C,
	gGothitt_6D,
	gGothitt_6E,
	gGothitt_6F,

	gGothitt_70,
	gGothitt_71,
	gGothitt_72,
	gGothitt_73,
	gGothitt_74,
	gGothitt_75,
	gGothitt_76,
	gGothitt_77,
	gGothitt_78,
	gGothitt_79,
	gGothitt_7A,
	gGothitt_7B,
	gGothitt_7C,
	gGothitt_7D,
	gGothitt_7E,
	gGothitt_7F

};
