//*******************************************************************************
//*	Gothic German Font
//*	formated for use with Arduino Processing 
//*	by Mark Sproul
//*******************************************************************************
//*	Jan 21,	2009	<MLS> Formated Hershey Gothic German for Arduino
//*******************************************************************************
//#include	"HersheyGothicGermanh.h"

prog_char	gGothicGerman_00[]	PROGMEM	=	"Gothic German";

prog_char	gGothicGerman_20[]	PROGMEM	=	" 1JZ";
prog_char	gGothicGerman_21[]	PROGMEM	=	"30LXRFQGOHQIRT RRISHRGQHRIRT RRFSGUHSIRT RRXPZR[TZRX RRYQZSZRY";
prog_char	gGothicGerman_22[]	PROGMEM	=	"22I[NFMGMM RNGMM RNFOGMM RWFVGVM RWGVM RWFXGVM";
prog_char	gGothicGerman_23[]	PROGMEM	=	"12H]SBLb RYBRb RLOZO RKUYU";
prog_char	gGothicGerman_24[]	PROGMEM	=	"60H\\PBP_ RTBT_ RTFVGWIWKYJXHWGTFPFMGKIKLLNOPURWSXUXXWZ RXJWH RLLMNOOUQWRXT RMYLW RMGLILKMMONUPXRYTYWXYWZT[P[MZLYKWMVMXNZP[";
prog_char	gGothicGerman_25[]	PROGMEM	=	"32F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT";
prog_char	gGothicGerman_26[]	PROGMEM	=	"62E_YNZO[O\\N RXOYP[P RXPYQZQ[P\\N RYNST RRUL[HVNP ROOSKOFJLPRTXVZX[Z[[Z\\X RLZIV RRKOG RKLPQTWVYXZ[Z RMZIU RRLNG RKKQQUWVXXY[Y\\X";
prog_char	gGothicGerman_27[]	PROGMEM	=	"11NWSFRGRM RSGRM RSFTGRM";
prog_char	gGothicGerman_28[]	PROGMEM	=	"27KYUBSDQGOKNPNTOYQ]S`Ub RQHPKOOOUPYQ\\ RSDRFQIPOPUQ[R^S`";
prog_char	gGothicGerman_29[]	PROGMEM	=	"27KYOBQDSGUKVPVTUYS]Q`Ob RSHTKUOUUTYS\\ RQDRFSITOTUS[R^Q`";
prog_char	gGothicGerman_2A[]	PROGMEM	=	"39JZRFQGSQRR RRFRR RRFSGQQRR RMINIVOWO RMIWO RMIMJWNWO RWIVINOMO RWIMO RWIWJMNMO";
prog_char	gGothicGerman_2B[]	PROGMEM	=	"16F_RIRZSZ RRISISZ RJQ[Q[R RJQJR[R";
prog_char	gGothicGerman_2C[]	PROGMEM	=	"14LXR^R\\PZRXSZS\\R^P_ RRYQZR[RY";
prog_char	gGothicGerman_2D[]	PROGMEM	=	" 3E_IR[R";
prog_char	gGothicGerman_2E[]	PROGMEM	=	"11LXRXPZR[TZRX RRYQZSZRY";
prog_char	gGothicGerman_2F[]	PROGMEM	=	" 8G^[BIbJb R[B\\BJb";

prog_char	gGothicGerman_30[]	PROGMEM	=	"42H\\LHLXJY RMIMXPZ RNHNXPYQZ RLHNHSGUF RSGTHVIVY RTGWIWX RUFVGXHZHXIXY RJYLYNZO[QZVYXY";
prog_char	gGothicGerman_31[]	PROGMEM	=	"27H\\OHPIQKQXOY RQIPHQGRIRYTZ ROHRFSHSXUYVY ROYPYRZS[TZVY";
prog_char	gGothicGerman_32[]	PROGMEM	=	"48H\\LHNHPGQFSGVHXH RPHRG RLHNIPIRHSG RVHVP RWIWO RXHXPQPNQLSKVK[ RK[OYSXVXZY RNZQYVYYZ RK[PZUZX[ZY";
prog_char	gGothicGerman_33[]	PROGMEM	=	"57H\\LHMHOGPFRGVHXH ROHQG RLHNIPIRG RVHVO RWIWN RXHXOVOSPQQ RQPSQVRXRXY RWSWX RVRVY RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY";
prog_char	gGothicGerman_34[]	PROGMEM	=	"41H\\UFKPKUTU RVUZU[V[TZU RLPLT RMNMU RTGTXRY RUJVHUGUYWZ RUFWHVJVXXYYY RRYSYUZV[WZYY";
prog_char	gGothicGerman_35[]	PROGMEM	=	"53H\\LFLO RLFXF RMGVG RLHUHWGXF RVLUMSNOOLO RSNTNVOVY RUMWNWX RVLWMYNZNXOXY RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY";
prog_char	gGothicGerman_36[]	PROGMEM	=	"59H\\LHLXJY RMIMXPZ RNHNXPYQZ RLHNHRGTFUGWHXH RSGUH RRGTIVIXH RNPOPSOUNVM RSOTOVPVY RUNWPWX RVMWNYOZOXPXY RJYLYNZO[QZVYXY";
prog_char	gGothicGerman_37[]	PROGMEM	=	"38H\\KHMFPGUGZF RLGOHTHWG RKHOIRIVHZF RZFYHWKSOQRPUPXQ[ RRQQTQWRZ RUMSPRSRVSYQ[";
prog_char	gGothicGerman_38[]	PROGMEM	=	"71H\\LILO RMJMN RNINO RLINISHUGVF RSHTHVIVO RUGWHWN RVFWGYHZHXIXO RLONOVRXR RXOVONRLR RLRLXJY RMSMXPZ RNRNXPYQZ RVRVY RWSWX RXRXY RJYLYNZO[QZVYXY";
prog_char	gGothicGerman_39[]	PROGMEM	=	"60H\\LHLQJR RMIMROS RNHNQPRQR RLHNHSGUF RSGTHVIVY RTGWIWX RUFVGXHZHXIXY RJRKRMSNTOSQRUQVQ RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY";
prog_char	gGothicGerman_3A[]	PROGMEM	=	"22LXRMPORPTORM RRNQOSORN RRXPZR[TZRX RRYQZSZRY";
prog_char	gGothicGerman_3B[]	PROGMEM	=	"25LXRMPORPTORM RRNQOSORN RR^R\\PZRXSZS\\R^P_ RRYQZR[RY";
prog_char	gGothicGerman_3C[]	PROGMEM	=	" 4F^ZIJRZ[";
prog_char	gGothicGerman_3D[]	PROGMEM	=	"16F_JM[M[N RJMJN[N RJU[U[V RJUJV[V";
prog_char	gGothicGerman_3E[]	PROGMEM	=	" 4F^JIZRJ[";
prog_char	gGothicGerman_3F[]	PROGMEM	=	"51I[LJMHNGQFSFVGWHXJXLWNUPSQ RMJNH RVHWIWMVN RLJNKNIOGQF RSFUGVIVMUOSQ RRQRTSQQQRT RRXPZR[TZRX RRYQZSZRY";

prog_char	gGothicGerman_40[]	PROGMEM	=	"56E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
prog_char	gGothicGerman_41[]	PROGMEM	=	"62F^IHJIIJHIIGKFMFOGPHQKQOPRNTLUIV ROHPKPPOR RMFNGOJOPNSLU RLVOY RKVOZ RIVN[UV R\\G[H\\H\\G[FYFWGVHUJUYW[[W RWHVJVXXZ RYFXGWJWWYY";
prog_char	gGothicGerman_42[]	PROGMEM	=	"01E_GQGRHSJSLRLOKMIJIHKF RKOIK RJSKRKPIMHKHIIGKFNFPGQHRJRRQUOW RPHQJQT RNFOGPJPUOW RRISGUFWFYGZH[J\\K RYHZJ RWFXGYJZK\\K R\\KRP RYM[O\\R\\U[XYZV[S[PZJWIWHX RXNYN[P RVNYO[Q\\S RTZRZLWKW RZYXZUZRYNWKVIVHXHZI[JZIY";
prog_char	gGothicGerman_43[]	PROGMEM	=	"79F^RHPFNFLGJJINIRJVLYNZQ[T[WZYY[W RLHKJJMJRKVMYPZ RNFMGLIKMKQLUMWOYRZUZXY[W RUFRHQIPKPLQNTPURUT RQKQLUPUQ RQIQJRLUNVPVRUTSURUPTOR RUFVGXHZH RUGVHWH RTGVIXIZH[G";
prog_char	gGothicGerman_44[]	PROGMEM	=	"79E_HLHKIIKGNFRFUGWHYJ[M\\Q\\U[XYZV[S[PZJWIWHX RKHMGRGUHWIYK[N RTZRZLWKW RHKJIMHRHUIWJYL[O\\R RZYXZUZRYNWKVIVHXHZI[JZIY RPHMKLMLONSNU RMNMONQNR RMKMMOQOSNUMVKVJUJT";
prog_char	gGothicGerman_45[]	PROGMEM	=	"95F^RHPFNFLGJJINIRJVLYNZQ[T[WZYY[W RLHKJJMJRKVMYPZ RNFMGLIKMKQLUMWOYRZUZXY[W RUFRHQIPKPLQNTPURUT RQKQLUPUQ RQIQJRLUNVPVRUTSURUPTOR RUFVGXHZH RUGVHWH RTGVIXIZH[G RUNYK RYKZL\\L RXLYMZM RWMXNZN\\L";
prog_char	gGothicGerman_46[]	PROGMEM	=	"94F^MNKMJKJIKGNFQFTGXI RKHMGRGUH RJKKIMHRHXIZI[H[GZFYF RSHRIQKQMROVSWVWYV\\U]S^ RTPWSXVXYW[ RQMSOVQXSYVYYX[V]S^O^L]K\\JZJWLTLRKQ RL\\K[KWLU RO^M]L[LWMTMRLQJQIRIS RUPYL RYLZM\\M RXMYNZN RWNXOZO\\M";
prog_char	gGothicGerman_47[]	PROGMEM	=	"99E_UJTHSGQFNFKGIJHNHRIUJWLYNZQ[T[WZYY[W\\T\\Q[NYL RKHJJIMIRJUKW RZW[U[QZNYM RNFLGKIJMJRKVLXNZ RWZYXZUZQYOWM RUFRHPJOLOMPOSQTSTU RPLPMTQTR RPJPKQMTOUQUSTURVQVOUNS RTOYLZJ R\\FZJ RYG]I R\\F[GYGZHZJ[I]I\\H\\F";
prog_char	gGothicGerman_48[]	PROGMEM	=	"92F_RFPGNIMKMMNOPQQSQU RNLNMQQQR RNINKOMQORQRSQUPVNWLWJVIUHSHQIPJQIR RRFTHVHXG RQGSH RPGQHSIUIXG RRPYK RYK[N\\Q\\T[WYYVZR[ RXLZN[Q[UZW RVMWMYOZRZVYXXYVZ RVZTZRYPYNZM\\N^P_R_T^ RSZQZ RR[PZNZ";
prog_char	gGothicGerman_49[]	PROGMEM	=	"83F_PPNPLOKNJLJJKHLGOFQFTGWJYK RLHNGRGTHUI RJJKIMHQHTIVJYK[K\\J\\H[GYG RJXKYJZIYIWJVLVNWPYR\\T^ RNXOYQ\\R] RLVMWNYP\\Q]S^V^X]Y\\ZZZWYUWRVPVO RYXYWVRVQ RX]Y[YYXWVTURUPWNYNZOZP";
prog_char	gGothicGerman_4A[]	PROGMEM	=	"83F_PPNPLOKNJLJJKHLGOFQFTGWJYK RLHNGRGTHUI RJJKIMHQHTIVJYK[K\\J\\H[GYG RJXKYJZIYIWJVLVNWPYR\\T^ RNXOYQ\\R] RLVMWNYP\\Q]S^V^X]Y\\ZZZWYUWRVPVO RYXYWVRVQ RX]Y[YYXWVTURUPWNYNZOZP";
prog_char	gGothicGerman_4B[]	PROGMEM	=	"81E_[KZIXGUFRFOGMILKLNMQPWPYN[ RMNMOPUPV RNHMJMMNOPSQVQXPZN[L[JZ RHVJZ RGYKW RHVHXGYIYJZJXKWIWHV RNONMOKQJTJVKXMYM RUKWM RRJTKULVN RYMPQ RUOYXZY[Y RTPXXZZ RSPWYY[\\X";
prog_char	gGothicGerman_4C[]	PROGMEM	=	"73G^ZSYTVTUSUQVOXLYJYH RVQVPYLYK RWTVSVRWPYNZLZJYHXGUFPFMGLHKJKLLNNQOSOTNV RLKLLOQOR RLHLJMLOOPQPSOUMWJY RMWOWRYUZXZZY RNXOXSZTZ RJYLXMXQZT[V[YZZY[W";
//										 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789  123456789 123456789 123456789
prog_char	gGothicGerman_4D[]	PROGMEM	=	"28BbEQERFSHSJRJOIMGJGHIF RIOGK RHSIRIPGMFKFIGGIFKFMGOIPLPROUNWLYI[HZGZ RNIOLORNUMW RJZIYHY RKFMHNKNRMVLXKYJXIXF[ RNGPFRFTGVIWLWRVUUWSYQ[PZOZ RUIVLVRUV RRZQYPY RRFTHUKUSTWSYRXQXN[ RUHVGXFZF\\G]H^J_K R\\H]J RZF[G\\J]K_K R_K\\M[NZQZT[X][`X R\\N[P[T\\W^Z R_K]M\\O\\S]W_Y";
prog_char	gGothicGerman_4E[]	PROGMEM	=	"96D`GQGRHSJSLRLOKMIJIHKF RKOIK RJSKRKPIMHKHIIGKFNFPGRISLSRRUQWOYL[KZIZG[ RQIRKRRQUPWOX RMZKYIY RNFPHQKQRPVNYLXJXG[ RRHSGUFWFYGZH[J\\K RYHZJ RWFXGYJZK\\K R\\KYMXNWQWTXXZ[]X RYNXPXTYW[Z R\\KZMYOYSZW\\Y";
prog_char	gGothicGerman_4F[]	PROGMEM	=	"72D`PFNGLIKKKMMQMS RLLLMMOMP RLILKNONQMSLTJTISIR RPFQGWIZK[M\\P\\S[VZXXZU[R[OZIWHWGX RPGQHWJYKZL RPFPHQIWKYL[N\\P RSZQZKWJW RYYWZTZQYMWJVHVGXGZH[IZHY";

prog_char	gGothicGerman_50[]	PROGMEM	=	"00E`HQHRISKSMRMOLMJJJHLF RLOJK RKSLRLPJMIKIIJGLFOFQGRHSJSU RSWS\\R^P_M_L^L\\M[N\\M] RQHRJR\\Q^ ROFPGQJQU RQWQ\\P^O_ RSJXF RXFZI[K\\O\\R[UYXV[ RWGZK[N[O RVHXJZM[P[SZVYX RWYUVSU RQUOVMX RWZUWSVPV RV[TXSW RQWOWMX";
prog_char	gGothicGerman_51[]	PROGMEM	=	"88D`PFNGLIKKKMMQMS RLLLMMOMP RLILKNONQMSLTJTISIR RPFQGWIZK[M\\P\\S[VZX RXZU[R[OZIWHWGX RPGQHWJYKZL RPFPHQIWKYL[N\\P RSZQZKWJW RXZTZQYMWJVHVGXGZH[IZHY RTXVVXV\\Z]Z RWWXW[Z RUWVWZ[\\[^Y";
prog_char	gGothicGerman_52[]	PROGMEM	=	"96D`GQGRHSJSLRLOKMIJIHKF RKOIK RJSKRKPIMHKHIIGKFNFPGQHRJRVQXOZM[K[IZ RPHQJQVPX RNFOGPJPVOYM[ RGVIZ RFYJW RGVGXFYHYIZIXJWHWGV RRISGUFWFYGZH[J\\K RYHZJ RWFXGYJZK\\K R\\KRP RTOXYZ[]X RUOYX[Z RVNZX[Y\\Y";
prog_char	gGothicGerman_53[]	PROGMEM	=	"83E`\\H[G\\F]G]I\\KZKVISHOHKIIK RYJVHSGOGLH R]I\\JZJVGSFOFLGJIIKHNHRIUJWLYNZQ[U[XZZY\\W]T]Q\\OZNWNUOSRQSOS RLXNYQZUZYY RIUKWMXPYUYYX[W\\V]T RXOWOSSRS R]Q[OYOWPUSSTQTOSNQNOOMQL";
prog_char	gGothicGerman_54[]	PROGMEM	=	"81F_LNJMIKIIJGMFRFUGYJ[J\\I RJHLGRGUHXJ RIKJILHRHUIYK[K\\I\\G[FZG[H RUIRLQNQPSTSV RRORPSRSS RRLRNTRTTSVRWPWOVOT RJYKZJ[IZIXJVLVOWSYVZYZ[Y RLWMWSZUZ RIXJWKWMXQZT[W[ZZ\\X";
prog_char	gGothicGerman_55[]	PROGMEM	=	"45G]JHKHLILWJX RKGMHMXPZ RIILFNHNWPYRY RJXKXMYO[RYVV RTHUHVIVYX[[X RUGWHWYYZ RSIVFYHXIXXYYZY";
prog_char	gGothicGerman_56[]	PROGMEM	=	"00D`GQGRHSJSLRLOKMIJIHKF RKOIK RJSKRKPIMHKHIIGKFNFPGQHRJRRQUOW RPHQJQT RNFOGPJPUOW RRISGUFWFYG[J\\K RYHZJ RWFXGYJZK\\K RZKXKWLWNXP[R\\T RXO[Q RWMXN[P\\R\\V[XYZW[S[PZJWIWHX RTZRZLWKW RZYXZUZRYNWKVIVHXHZI[JZIY";
prog_char	gGothicGerman_57[]	PROGMEM	=	"43BcEQERFSHSJRJOIMGJGHIF RIOGK RHSIRIPGMFKFIGGIFLFNGOHPJPNOQMTKV RNHOJOONR RLFMGNJNOMSKV RNGPFSFUG RWFTGSISMTPVSWUWWVY RTMTNWSWT RWFUGTITLUNWQXTXVWXUZS[O[MZKXIWGWFX RNZKWJW RQ[OZLWJVGVFXFZG[HZGY RWFZF\\G^J_K R\\H]J RZF[G\\J]K_K R]K[KZLZN[P^R_T R[O^Q RZM[N^P_R_W^Y]Z[[X[UZ RYZXZVY R^Y\\ZZZXYWX";
prog_char	gGothicGerman_58[]	PROGMEM	=	"86F^KHMHOIPJQMQO RQQQUPXM[KZI[ RNZLYKY ROYNYLXI[ RMGPHQIRLRUSWUYWZ RIINFPGRISLSO RSQSTTWUXWYYY RQURXTZV[[X RSLTIWFYG[F RVGXHYH RUHVHXI[F RKSMOQO RSOWOYM RMPWP RKSMQQQ RSQWQYM";
prog_char	gGothicGerman_59[]	PROGMEM	=	"74E_HQHRISKSMRMOLMJJJHLF RLOJK RKSLRLPJMIKIIJGLFOFQGRHSJSORRQTQUSWTW RQHRJRPQSPUSX ROFPGQJQPPTOVRYUV RSJ[F RYGYZX] RZGZXY[ R[F[VZZY\\W^T_P_M^K\\JZKYLZK[";
prog_char	gGothicGerman_5A[]	PROGMEM	=	"74F^NIOGQFTFVGWHXJXMWOVPTQ RQQOPNN RVHWIWNVO RTFUGVIVNUPTQ RMUNSORQQTQWRYTZVZZY\\W^T_P_N^KZJY RXTYVYZX\\ RTQWSXUX[W]V^T_ RO^N]LZKY RR_P^O]MZLYIYHZH\\I]J]";
prog_char	gGothicGerman_5B[]	PROGMEM	=	"12KYOBOb RPBPb ROBVB RObVb";
prog_char	gGothicGerman_5C[]	PROGMEM	=	" 3KYKFY^";
prog_char	gGothicGerman_5D[]	PROGMEM	=	"12KYTBTb RUBUb RNBUB RNbUb";
prog_char	gGothicGerman_5E[]	PROGMEM	=	" 8G]JTROZT RJTRPZT";
prog_char	gGothicGerman_5F[]	PROGMEM	=	" 3F^Fb^b";

prog_char	gGothicGerman_60[]	PROGMEM	=	" 7LXPFUL RPFOGUL";
prog_char	gGothicGerman_61[]	PROGMEM	=	"46J[TMQNOONPMSMVNYO[UX RNVOYPZ RQNOPNSNUOXQZ RRNSOUPUYW[ZX RSNVPVXXZ RTMUNWOXO RWPXO RWPWXXYYY";
prog_char	gGothicGerman_62[]	PROGMEM	=	"50J[LHMINK RTFQGOINKNXMY RPIOKOXRZ RTFRGQHPKPXRYSZ RMYNYPZQ[TZ RPPVMWOXRXUWXVYTZ RUNVOWQ RTNVPWSWUVXTZ";
prog_char	gGothicGerman_63[]	PROGMEM	=	"27KXRNTPVOTMRNOPNRNWOYQ[UY RSNUO RPPOROWPYQZ RQOPQPVQXSZ";
prog_char	gGothicGerman_64[]	PROGMEM	=	"47J[QFNINKOLSNVPWRWUVXTZ ROJOKSMVOWP ROHOIPJUMWOXRXUWXTZQ[ RRNNPNXMY ROPOXRZ RPOPXRYSZ RMYNYPZQ[";
prog_char	gGothicGerman_65[]	PROGMEM	=	"27KXPUVQSMOPNRNWOYQ[UY RUQRN RPPOROWPYQZ RTRROQOPQPVQXSZ";
prog_char	gGothicGerman_66[]	PROGMEM	=	"49LYXFWGUGSFQFPHPMOONP RVHTHRGQG RXFWHVITIRHQHPI RPKQMRNTOVOVP RNPPP RRPVP RPPPTQ` RSOPOQNQ[ RRPRTQ`";
prog_char	gGothicGerman_67[]	PROGMEM	=	"53J[TMQNOONPMSMVNYO[UX RNWOYPZ RQNOPNSNUOXQZ RRNSOUPUXV[V]U_ RSNVPVZ RTMUNWOXO RWPXO RWPW\\V^U_S`P`N_M^M]N]N^";
prog_char	gGothicGerman_68[]	PROGMEM	=	"50J[LHMINK RTFQGOINKNXMY RPIOKOYPZ RTFRGQHPKPXQYRY RMYOZP[SX RPPVMWOXSXWWZV\\T^Q` RUNVOWR RTNVQWTWWV[T^";
prog_char	gGothicGerman_69[]	PROGMEM	=	"39MWRFQGQHRISHSGRF RQGSH RQHSG ROOPOQPQYS[VX RPNRORXTZ RNPQMRNTO RSPTO RSPSXTYUY";
prog_char	gGothicGerman_6A[]	PROGMEM	=	"45MWRFQGQHRISHSGRF RQGSH RQHSG ROOPOQPQ[P^O_M` RPNROR[Q] RNPQMRNTO RSPTO RSPS[R]P_M` RS[T]U^";
prog_char	gGothicGerman_6B[]	PROGMEM	=	"63KYNHOIPK RUFSGQIPKPMOONP RPPPXOY RRIQKQM RQOPOQMQXSZ RUFSHRKRO RRPRXSYTY ROYQZR[UX RRLVIWJWLUNSO RUJVKVLUN RROWOWP RNPPP RRPWP";
prog_char	gGothicGerman_6C[]	PROGMEM	=	"29MWOHPIQK RWFTGRIQKQXPY RSIRKRYTZ RWFUGTHSKSXTYUY RPYRZS[VX";
prog_char	gGothicGerman_6D[]	PROGMEM	=	"74E_GOHOIPIXHYJ[ RHNJPJXIYJZKYJX RFPIMKOKXLYJ[ RNNPOQQQXPYR[ RPNQORQRXQYRZSYRX RKPNNPMRNSPSXTYR[ RVNWOYPYY[[^X RWNZPZX\\Z RSPVNXMYN[O\\O R[P\\O R[P[X\\Y]Y";
prog_char	gGothicGerman_6E[]	PROGMEM	=	"49I[KOLOMPMXLYN[ RLNNPNXMYNZOYNX RJPMMOOOXPYN[ RRNSOUPUYW[ZX RSNVPVXXZ ROPRNTMUNWOXO RWPXO RWPWXXYYY";
prog_char	gGothicGerman_6F[]	PROGMEM	=	"41J[NPNXMY ROPOXRZ RQOPPPXRYSZ RMYNYPZQ[TZ RNPQOVMWOXRXUWXVYTZ RUNVOWQ RTNVPWSWUVXTZ";

prog_char	gGothicGerman_70[]	PROGMEM	=	"57J[OJMLMNNQNXLZ RNYO` RNMNNOQO[ RNKNLONPQPXQXSYTZ RPYO` RSZQY RTZR[PY RNYLZ RPPVMWOXRXUWXVYTZ RUNVOWQ RTNVPWSWUVXTZ";
prog_char	gGothicGerman_71[]	PROGMEM	=	"43J[TMQNOONPMSMVNYO[UX RNWOYPZ RQNOPNSNUOXQZ RRNSOUPUXV` RSNVPV[ RTMUNWOXO RWPXO RWPWXV`";
prog_char	gGothicGerman_72[]	PROGMEM	=	"32KYNOOOPPPXOY RONQPQYSZ RMPPMRORXSYTY ROYQZR[UX RTNUPWOVMRO RUNVO";
prog_char	gGothicGerman_73[]	PROGMEM	=	"42LWXFWGUGSFQFPHPMOONP RVHTHRGQG RXFWHVITIRHQHPI RPKRP RPPPTQ` RQOPOQNQ[ RRPRTQ` RNPPP";
prog_char	gGothicGerman_74[]	PROGMEM	=	"37LXSIRLQNPONP RSISOVOVP RNPQP RSPVP RQPQXPY RROQORMRXTZ RSPSXTYUY RPYRZS[VX";
prog_char	gGothicGerman_75[]	PROGMEM	=	"47I[KOLOMPMXLY RLNNPNXPZ RJPMMOOOXQYRZ RLYMYOZP[RZUX RVMTOUPUYW[ZX RVPWOVNUOVPVXXZ RVMXOWPWXXYYY";
prog_char	gGothicGerman_76[]	PROGMEM	=	"47J[OKMMMONRNXMY RNNNOOROXRZ RNLNMOOPRPXRYSZ RMYNYPZQ[TZ RPPVMWOXRXUWXVYTZ RUNVOWQ RTNVPWSWUVXTZ";
prog_char	gGothicGerman_77[]	PROGMEM	=	"72F_KKIMIOJRJXIYK[ RJNJOKRKXJYKZLYKX RJLJMKOLRLXMYK[ RONQORQRXQY RQNROSQSXVZ RLPONQMSNTPTXVYWZ RQYRYTZU[XZ RTPZM[O\\R\\T[XZYXZ RYNZO[Q RXNZP[S[UZXXZ";
prog_char	gGothicGerman_78[]	PROGMEM	=	"44KZOOPOQPQXPXNYM[M]N_P`S`V_V^U^U_ RPNRPRXUZ RNPQMSOSXUYVZ RXYT[SZQYOYM[ RUNVPXOWMSO RVNWO";
prog_char	gGothicGerman_79[]	PROGMEM	=	"47J[OKMMMONRNXMY RNNNOOROYQZ RNLNMOOPRPXQYRY RMYOZP[SX RPPVMWOXSXWWZV\\T^Q` RUNVOWR RTNVQWTWWV[T^";
prog_char	gGothicGerman_7A[]	PROGMEM	=	"43KYNPSMUNVPVRUTQV RSNUO RRNTOUQURTTSU RSUUWVYV]U_S`Q`O_N]N[OYQXWV RRVTWUY RQVTXUZU]T_S`";
prog_char	gGothicGerman_7B[]	PROGMEM	=	"40KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
prog_char	gGothicGerman_7C[]	PROGMEM	=	" 3NVRBRb";
prog_char	gGothicGerman_7D[]	PROGMEM	=	"40KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
prog_char	gGothicGerman_7E[]	PROGMEM	=	"24F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
prog_char	gGothicGerman_7F[]	PROGMEM	=	"35JZJFJ[K[KFLFL[M[MFNFN[O[OFPFP[Q[QFRFR[S[SFTFT[U[UFVFV[W[WFXFX[Y[YFZFZ[";

PGM_P gHershyGothicGermanFontTable[]	PROGMEM =	   // change "string_table" name to suit
{

	gGothicGerman_00,
	gGothicGerman_20,
	gGothicGerman_21,
	gGothicGerman_22,
	gGothicGerman_23,
	gGothicGerman_24,
	gGothicGerman_25,
	gGothicGerman_26,
	gGothicGerman_27,
	gGothicGerman_28,
	gGothicGerman_29,
	gGothicGerman_2A,
	gGothicGerman_2B,
	gGothicGerman_2C,
	gGothicGerman_2D,
	gGothicGerman_2E,
	gGothicGerman_2F,

	gGothicGerman_30,
	gGothicGerman_31,
	gGothicGerman_32,
	gGothicGerman_33,
	gGothicGerman_34,
	gGothicGerman_35,
	gGothicGerman_36,
	gGothicGerman_37,
	gGothicGerman_38,
	gGothicGerman_39,
	gGothicGerman_3A,
	gGothicGerman_3B,
	gGothicGerman_3C,
	gGothicGerman_3D,
	gGothicGerman_3E,
	gGothicGerman_3F,

	gGothicGerman_40,
	gGothicGerman_41,
	gGothicGerman_42,
	gGothicGerman_43,
	gGothicGerman_44,
	gGothicGerman_45,
	gGothicGerman_46,
	gGothicGerman_47,
	gGothicGerman_48,
	gGothicGerman_49,
	gGothicGerman_4A,
	gGothicGerman_4B,
	gGothicGerman_4C,
	gGothicGerman_4D,
	gGothicGerman_4E,
	gGothicGerman_4F,

	gGothicGerman_50,
	gGothicGerman_51,
	gGothicGerman_52,
	gGothicGerman_53,
	gGothicGerman_54,
	gGothicGerman_55,
	gGothicGerman_56,
	gGothicGerman_57,
	gGothicGerman_58,
	gGothicGerman_59,
	gGothicGerman_5A,
	gGothicGerman_5B,
	gGothicGerman_5C,
	gGothicGerman_5D,
	gGothicGerman_5E,
	gGothicGerman_5F,

	gGothicGerman_60,
	gGothicGerman_61,
	gGothicGerman_62,
	gGothicGerman_63,
	gGothicGerman_64,
	gGothicGerman_65,
	gGothicGerman_66,
	gGothicGerman_67,
	gGothicGerman_68,
	gGothicGerman_69,
	gGothicGerman_6A,
	gGothicGerman_6B,
	gGothicGerman_6C,
	gGothicGerman_6D,
	gGothicGerman_6E,
	gGothicGerman_6F,

	gGothicGerman_70,
	gGothicGerman_71,
	gGothicGerman_72,
	gGothicGerman_73,
	gGothicGerman_74,
	gGothicGerman_75,
	gGothicGerman_76,
	gGothicGerman_77,
	gGothicGerman_78,
	gGothicGerman_79,
	gGothicGerman_7A,
	gGothicGerman_7B,
	gGothicGerman_7C,
	gGothicGerman_7D,
	gGothicGerman_7E,
	gGothicGerman_7F

};
