//*******************************************************************************
//*	rowmand.jhf		Rowmand
//*	formated for use with Arduino Processing 
//*	by Mark Sproul
//*******************************************************************************
//*	Jan 24,	2009	<MLS>	Formated Hershey rowmand for Arduino
//*******************************************************************************
//#include	"HersheyRowmand.h"



prog_char	gRowmand_00[]	PROGMEM	=	"Rowmand";


prog_char	gRowmand_20[]	PROGMEM	=	" 1JZ";
prog_char	gRowmand_21[]	PROGMEM	=	"24MXRFRTST RRFSFST RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY";
prog_char	gRowmand_22[]	PROGMEM	=	"22I[NFMGMM RNGMM RNFOGMM RWFVGVM RWGVM RWFXGVM";
prog_char	gRowmand_23[]	PROGMEM	=	"12H]SFLb RYFRb RLQZQ RKWYW";
prog_char	gRowmand_24[]	PROGMEM	=	"51I\\RBR_S_ RRBSBS_ RWIYIWGTFQFNGLILKMMNNVRWSXUXWWYTZQZOYNX RWIVHTGQGNHMIMKNMVQXSYUYWXYWZT[Q[NZLXNX RXXUZ";
prog_char	gRowmand_25[]	PROGMEM	=	"32F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT";
prog_char	gRowmand_26[]	PROGMEM	=	"71F_\\MZMXNWPUVTXSYQZMZKYJWJUKSLRQOSMTKTISGQFPFNGMIMKNNPQUWXZZ[\\[ R\\M\\NZNXO RYNXPVVUXSZQ[M[KZJYIWIUJSLQQNRMSKSIRG RSHQGPGNH ROGNINKONQQVWXYZZ\\Z\\[";
prog_char	gRowmand_27[]	PROGMEM	=	"24MXTHSIRIQHQGRFSFTGTJSLQM RRGRHSHSGRG RSITJ RTHSL";
prog_char	gRowmand_28[]	PROGMEM	=	"24KYUBSDQGOKNPNTOYQ]S`UbVb RUBVBTDRGPKOPOTPYR]T`Vb";
prog_char	gRowmand_29[]	PROGMEM	=	"24KYNBPDRGTKUPUTTYR]P`NbOb RNBOBQDSGUKVPVTUYS]Q`Ob";
prog_char	gRowmand_2A[]	PROGMEM	=	"39JZRFQGSQRR RRFRR RRFSGQQRR RMINIVOWO RMIWO RMIMJWNWO RWIVINOMO RWIMO RWIWJMNMO";
prog_char	gRowmand_2B[]	PROGMEM	=	"16F_RIRZSZ RRISISZ RJQ[Q[R RJQJR[R";
prog_char	gRowmand_2C[]	PROGMEM	=	"24MXTZS[R[QZQYRXSXTYT\\S^Q_ RRYRZSZSYRY RS[T\\ RTZS^";
prog_char	gRowmand_2D[]	PROGMEM	=	" 8F_JQ[Q[R RJQJR[R";
prog_char	gRowmand_2E[]	PROGMEM	=	"16MXRXQYQZR[S[TZTYSXRX RRYRZSZSYRY";
prog_char	gRowmand_2F[]	PROGMEM	=	" 8G^[BIbJb R[B\\BJb";

prog_char	gRowmand_30[]	PROGMEM	=	"42H\\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF ROGMJLOLRMWOZ RNYQZSZVY RUZWWXRXOWJUG RVHSGQGNH";
prog_char	gRowmand_31[]	PROGMEM	=	"12H\\NJPISFS[ RNJNKPJRHR[S[";
prog_char	gRowmand_32[]	PROGMEM	=	"34H\\LKLJMHNGPFTFVGWHXJXLWNUQL[ RLKMKMJNHPGTGVHWJWLVNTQK[ RLZYZY[ RK[Y[";
prog_char	gRowmand_33[]	PROGMEM	=	"48H\\MFXFQO RMFMGWG RWFPO RQNSNVOXQYTYUXXVZS[P[MZLYKWLW RPOSOVPXS RTOWQXTXUWXTZ RXVVYSZPZMYLW ROZLX";
prog_char	gRowmand_34[]	PROGMEM	=	"18H\\UIU[V[ RVFV[ RVFKVZV RUILV RLUZUZV";
prog_char	gRowmand_35[]	PROGMEM	=	"53H\\MFLO RNGMN RMFWFWG RNGWG RMNPMSMVNXPYSYUXXVZS[P[MZLYKWLW RLOMOONSNVOXR RTNWPXSXUWXTZ RXVVYSZPZMYLW ROZLX";
prog_char	gRowmand_36[]	PROGMEM	=	"62H\\VGWIXIWGTFRFOGMJLOLTMXOZR[S[VZXXYUYTXQVOSNRNOOMQ RWHTGRGOH RPGNJMOMTNXQZ RMVOYRZSZVYXV RTZWXXUXTWQTO RXSVPSOROOPMS RQONQMT";
prog_char	gRowmand_37[]	PROGMEM	=	"12H\\KFYFO[ RKFKGXG RXFN[O[";
prog_char	gRowmand_38[]	PROGMEM	=	"68H\\PFMGLILKMMNNPOTPVQWRXTXWWYTZPZMYLWLTMRNQPPTOVNWMXKXIWGTFPF RNGMIMKNMPNTOVPXRYTYWXYWZT[P[MZLYKWKTLRNPPOTNVMWKWIVG RWHTGPGMH RLXOZ RUZXX";
prog_char	gRowmand_39[]	PROGMEM	=	"62H\\WPURRSQSNRLPKMKLLINGQFRFUGWIXMXRWWUZR[P[MZLXMXNZ RWMVPSR RWNUQRRQRNQLN RPRMPLMLLMIPG RLKNHQGRGUHWK RSGVIWMWRVWTZ RUYRZPZMY";
prog_char	gRowmand_3A[]	PROGMEM	=	"32MXRMQNQORPSPTOTNSMRM RRNROSOSNRN RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY";
prog_char	gRowmand_3B[]	PROGMEM	=	"40MXRMQNQORPSPTOTNSMRM RRNROSOSNRN RTZS[R[QZQYRXSXTYT\\S^Q_ RRYRZSZSYRY RS[T\\ RTZS^";
prog_char	gRowmand_3C[]	PROGMEM	=	" 4F^ZIJRZ[";
prog_char	gRowmand_3D[]	PROGMEM	=	"16F_JM[M[N RJMJN[N RJU[U[V RJUJV[V";
prog_char	gRowmand_3E[]	PROGMEM	=	" 4F^JIZRJ[";
prog_char	gRowmand_3F[]	PROGMEM	=	"58I\\LKLJMHNGQFTFWGXHYJYLXNWOUPRQ RLKMKMJNHQGTGWHXJXLWNUORP RMIPG RUGXI RXMTP RRPRTSTSP RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY";

prog_char	gRowmand_40[]	PROGMEM	=	"56E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
prog_char	gRowmand_41[]	PROGMEM	=	"20H\\RFJ[ RRIK[J[ RRIY[Z[ RRFZ[ RMUWU RLVXV";
prog_char	gRowmand_42[]	PROGMEM	=	"44H\\LFL[ RMGMZ RLFTFWGXHYJYMXOWPTQ RMGTGWHXJXMWOTP RMPTPWQXRYTYWXYWZT[L[ RMQTQWRXTXWWYTZMZ";
prog_char	gRowmand_43[]	PROGMEM	=	"38H]ZKYIWGUFQFOGMILKKNKSLVMXOZQ[U[WZYXZV RZKYKXIWHUGQGOHMKLNLSMVOYQZUZWYXXYVZV";
prog_char	gRowmand_44[]	PROGMEM	=	"32H]LFL[ RMGMZ RLFSFVGXIYKZNZSYVXXVZS[L[ RMGSGVHWIXKYNYSXVWXVYSZMZ";
prog_char	gRowmand_45[]	PROGMEM	=	"27I\\MFM[ RNGNZ RMFYF RNGYGYF RNPTPTQ RNQTQ RNZYZY[ RM[Y[";
prog_char	gRowmand_46[]	PROGMEM	=	"21I[MFM[ RNGN[M[ RMFYF RNGYGYF RNPTPTQ RNQTQ";
prog_char	gRowmand_47[]	PROGMEM	=	"44H]ZKYIWGUFQFOGMILKKNKSLVMXOZQ[U[WZYXZVZRUR RZKYKXIWHUGQGOHNIMKLNLSMVNXOYQZUZWYXXYVYSUSUR";
prog_char	gRowmand_48[]	PROGMEM	=	"22G]KFK[ RKFLFL[K[ RYFXFX[Y[ RYFY[ RLPXP RLQXQ";
prog_char	gRowmand_49[]	PROGMEM	=	" 8NWRFR[S[ RRFSFS[";
prog_char	gRowmand_4A[]	PROGMEM	=	"20J[VFVVUYSZQZOYNVMV RVFWFWVVYUZS[Q[OZNYMV";
prog_char	gRowmand_4B[]	PROGMEM	=	"22H]LFL[M[ RLFMFM[ RZFYFMR RZFMS RPOY[Z[ RQOZ[";
prog_char	gRowmand_4C[]	PROGMEM	=	"14IZMFM[ RMFNFNZ RNZYZY[ RM[Y[";
prog_char	gRowmand_4D[]	PROGMEM	=	"26F^JFJ[ RKKK[J[ RKKR[ RJFRX RZFRX RYKR[ RYKY[Z[ RZFZ[";
prog_char	gRowmand_4E[]	PROGMEM	=	"20G]KFK[ RLIL[K[ RLIY[ RKFXX RXFXX RXFYFY[";
prog_char	gRowmand_4F[]	PROGMEM	=	"40G]PFNGLIKKJNJSKVLXNZP[T[VZXXYVZSZNYKXIVGTFPF RQGNHLKKNKSLVNYQZSZVYXVYSYNXKVHSGQG";

prog_char	gRowmand_50[]	PROGMEM	=	"27H\\LFL[ RMGM[L[ RLFUFWGXHYJYMXOWPUQMQ RMGUGWHXJXMWOUPMP";
prog_char	gRowmand_51[]	PROGMEM	=	"48G]PFNGLIKKJNJSKVLXNZP[T[VZXXYVZSZNYKXIVGTFPF RQGNHLKKNKSLVNYQZSZVYXVYSYNXKVHSGQG RSXX]Y] RSXTXY]";
prog_char	gRowmand_52[]	PROGMEM	=	"34H\\LFL[ RMGM[L[ RLFTFWGXHYJYMXOWPTQMQ RMGTGWHXJXMWOTPMP RRQX[Y[ RSQY[";
prog_char	gRowmand_53[]	PROGMEM	=	"43H\\YIWGTFPFMGKIKKLMMNOOTQVRWSXUXXWYTZPZNYMXKX RYIWIVHTGPGMHLILKMMONTPVQXSYUYXWZT[P[MZKX";
prog_char	gRowmand_54[]	PROGMEM	=	"15J[RGR[ RSGS[R[ RLFYFYG RLFLGYG";
prog_char	gRowmand_55[]	PROGMEM	=	"24G]KFKULXNZQ[S[VZXXYUYF RKFLFLUMXNYQZSZVYWXXUXFYF";
prog_char	gRowmand_56[]	PROGMEM	=	"14H\\JFR[ RJFKFRX RZFYFRX RZFR[";
prog_char	gRowmand_57[]	PROGMEM	=	"26E_GFM[ RGFHFMX RRFMX RRIM[ RRIW[ RRFWX R]F\\FWX R]FW[";
prog_char	gRowmand_58[]	PROGMEM	=	"16H\\KFX[Y[ RKFLFY[ RYFXFK[ RYFL[K[";
prog_char	gRowmand_59[]	PROGMEM	=	"17I\\KFRPR[S[ RKFLFSP RZFYFRP RZFSPS[";
prog_char	gRowmand_5A[]	PROGMEM	=	"20H\\XFK[ RYFL[ RKFYF RKFKGXG RLZYZY[ RK[Y[";
prog_char	gRowmand_5B[]	PROGMEM	=	"12KYOBOb RPBPb ROBVB RObVb";
prog_char	gRowmand_5C[]	PROGMEM	=	" 3KYKFY^";
prog_char	gRowmand_5D[]	PROGMEM	=	"12KYTBTb RUBUb RNBUB RNbUb";
prog_char	gRowmand_5E[]	PROGMEM	=	"11JZPLRITL RMORJWO RRJR[";
prog_char	gRowmand_5F[]	PROGMEM	=	" 3JZJ]Z]";

prog_char	gRowmand_60[]	PROGMEM	=	"24MXTFRGQIQLRMSMTLTKSJRJQK RRKRLSLSKRK RRGQK RQIRJ";
prog_char	gRowmand_61[]	PROGMEM	=	"36H\\WMW[X[ RWMXMX[ RWPUNSMPMNNLPKSKULXNZP[S[UZWX RWPSNPNNOMPLSLUMXNYPZSZWX";
prog_char	gRowmand_62[]	PROGMEM	=	"36H\\LFL[M[ RLFMFM[ RMPONQMTMVNXPYSYUXXVZT[Q[OZMX RMPQNTNVOWPXSXUWXVYTZQZMX";
prog_char	gRowmand_63[]	PROGMEM	=	"32I[XPVNTMQMONMPLSLUMXOZQ[T[VZXX RXPWQVOTNQNOONPMSMUNXOYQZTZVYWWXX";
prog_char	gRowmand_64[]	PROGMEM	=	"36H\\WFW[X[ RWFXFX[ RWPUNSMPMNNLPKSKULXNZP[S[UZWX RWPSNPNNOMPLSLUMXNYPZSZWX";
prog_char	gRowmand_65[]	PROGMEM	=	"36I[MTXTXQWOVNTMQMONMPLSLUMXOZQ[T[VZXX RMSWSWQVOTNQNOONPMSMUNXOYQZTZVYWWXX";
prog_char	gRowmand_66[]	PROGMEM	=	"24LZWFUFSGRJR[S[ RWFWGUGSH RTGSJS[ ROMVMVN ROMONVN";
prog_char	gRowmand_67[]	PROGMEM	=	"48H\\XMWMW\\V_U`SaQaO`N_L_ RXMX\\W_UaSbPbNaL_ RWPUNSMPMNNLPKSKULXNZP[S[UZWX RWPSNPNNOMPLSLUMXNYPZSZWX";
prog_char	gRowmand_68[]	PROGMEM	=	"25H\\LFL[M[ RLFMFM[ RMQPNRMUMWNXQX[ RMQPORNTNVOWQW[X[";
prog_char	gRowmand_69[]	PROGMEM	=	"24NWRFQGQHRISITHTGSFRF RRGRHSHSGRG RRMR[S[ RRMSMS[";
prog_char	gRowmand_6A[]	PROGMEM	=	"24NWRFQGQHRISITHTGSFRF RRGRHSHSGRG RRMRbSb RRMSMSb";
prog_char	gRowmand_6B[]	PROGMEM	=	"22H[LFL[M[ RLFMFM[ RXMWMMW RXMMX RPTV[X[ RQSX[";
prog_char	gRowmand_6C[]	PROGMEM	=	" 8NWRFR[S[ RRFSFS[";
prog_char	gRowmand_6D[]	PROGMEM	=	"42CbGMG[H[ RGMHMH[ RHQKNMMPMRNSQS[ RHQKOMNONQORQR[S[ RSQVNXM[M]N^Q^[ RSQVOXNZN\\O]Q][^[";
prog_char	gRowmand_6E[]	PROGMEM	=	"25H\\LML[M[ RLMMMM[ RMQPNRMUMWNXQX[ RMQPORNTNVOWQW[X[";
prog_char	gRowmand_6F[]	PROGMEM	=	"36I\\QMONMPLSLUMXOZQ[T[VZXXYUYSXPVNTMQM RQNOONPMSMUNXOYQZTZVYWXXUXSWPVOTNQN";

prog_char	gRowmand_70[]	PROGMEM	=	"36H\\LMLbMb RLMMMMb RMPONQMTMVNXPYSYUXXVZT[Q[OZMX RMPQNTNVOWPXSXUWXVYTZQZMX";
prog_char	gRowmand_71[]	PROGMEM	=	"36H\\WMWbXb RWMXMXb RWPUNSMPMNNLPKSKULXNZP[S[UZWX RWPSNPNNOMPLSLUMXNYPZSZWX";
prog_char	gRowmand_72[]	PROGMEM	=	"21KYOMO[P[ ROMPMP[ RPSQPSNUMXM RPSQQSOUNXNXM";
prog_char	gRowmand_73[]	PROGMEM	=	"50J[XPWNTMQMNNMPNRPSUUWV RVUWWWXVZ RWYTZQZNY ROZNXMX RXPWPVN RWOTNQNNO RONNPOR RNQPRUTWUXWXXWZT[Q[NZMX";
prog_char	gRowmand_74[]	PROGMEM	=	"16MXRFR[S[ RRFSFS[ ROMVMVN ROMONVN";
prog_char	gRowmand_75[]	PROGMEM	=	"25H\\LMLWMZO[R[TZWW RLMMMMWNYPZRZTYWW RWMW[X[ RWMXMX[";
prog_char	gRowmand_76[]	PROGMEM	=	"14JZLMR[ RLMMMRY RXMWMRY RXMR[";
prog_char	gRowmand_77[]	PROGMEM	=	"26F^IMN[ RIMJMNX RRMNX RRPN[ RRPV[ RRMVX R[MZMVX R[MV[";
prog_char	gRowmand_78[]	PROGMEM	=	"16I[LMW[X[ RLMMMX[ RXMWML[ RXMM[L[";
prog_char	gRowmand_79[]	PROGMEM	=	"17JZLMR[ RLMMMRY RXMWMRYNb RXMR[ObNb";
prog_char	gRowmand_7A[]	PROGMEM	=	"20I[VNL[ RXMNZ RLMXM RLMLNVN RNZXZX[ RL[X[";
prog_char	gRowmand_7B[]	PROGMEM	=	"40KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
prog_char	gRowmand_7C[]	PROGMEM	=	" 3NVRBRb";
prog_char	gRowmand_7D[]	PROGMEM	=	"40KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
prog_char	gRowmand_7E[]	PROGMEM	=	"24F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
prog_char	gRowmand_7F[]	PROGMEM	=	"30KYQFOGNINKOMQNSNUMVKVIUGSFQF RQFNIOMSNVKUGQF RSFOGNKQNUMVISF";


PGM_P gHershyRowmandFontTable[]	PROGMEM =	   // change "string_table" name to suit
{

	gRowmand_00,
	gRowmand_20,
	gRowmand_21,
	gRowmand_22,
	gRowmand_23,
	gRowmand_24,
	gRowmand_25,
	gRowmand_26,
	gRowmand_27,
	gRowmand_28,
	gRowmand_29,
	gRowmand_2A,
	gRowmand_2B,
	gRowmand_2C,
	gRowmand_2D,
	gRowmand_2E,
	gRowmand_2F,

	gRowmand_30,
	gRowmand_31,
	gRowmand_32,
	gRowmand_33,
	gRowmand_34,
	gRowmand_35,
	gRowmand_36,
	gRowmand_37,
	gRowmand_38,
	gRowmand_39,
	gRowmand_3A,
	gRowmand_3B,
	gRowmand_3C,
	gRowmand_3D,
	gRowmand_3E,
	gRowmand_3F,

	gRowmand_40,
	gRowmand_41,
	gRowmand_42,
	gRowmand_43,
	gRowmand_44,
	gRowmand_45,
	gRowmand_46,
	gRowmand_47,
	gRowmand_48,
	gRowmand_49,
	gRowmand_4A,
	gRowmand_4B,
	gRowmand_4C,
	gRowmand_4D,
	gRowmand_4E,
	gRowmand_4F,

	gRowmand_50,
	gRowmand_51,
	gRowmand_52,
	gRowmand_53,
	gRowmand_54,
	gRowmand_55,
	gRowmand_56,
	gRowmand_57,
	gRowmand_58,
	gRowmand_59,
	gRowmand_5A,
	gRowmand_5B,
	gRowmand_5C,
	gRowmand_5D,
	gRowmand_5E,
	gRowmand_5F,

	gRowmand_60,
	gRowmand_61,
	gRowmand_62,
	gRowmand_63,
	gRowmand_64,
	gRowmand_65,
	gRowmand_66,
	gRowmand_67,
	gRowmand_68,
	gRowmand_69,
	gRowmand_6A,
	gRowmand_6B,
	gRowmand_6C,
	gRowmand_6D,
	gRowmand_6E,
	gRowmand_6F,

	gRowmand_70,
	gRowmand_71,
	gRowmand_72,
	gRowmand_73,
	gRowmand_74,
	gRowmand_75,
	gRowmand_76,
	gRowmand_77,
	gRowmand_78,
	gRowmand_79,
	gRowmand_7A,
	gRowmand_7B,
	gRowmand_7C,
	gRowmand_7D,
	gRowmand_7E,
	gRowmand_7F

};
