//*******************************************************************************
//*	Japanese
//*	formated for use with Arduino Processing 
//*	by Mark Sproul
//*******************************************************************************
//*	Jan 21,	2009	<MLS>	Formated Hershey Japanese for Arduino
//*******************************************************************************
//#include	"HersheyJapanese.h"


prog_char	gJapanese_00[]	PROGMEM	=	"Japanese";
prog_char	gJapanese_20[]	PROGMEM	=	" 6D_HYGZH[IZHY";
prog_char	gJapanese_21[]	PROGMEM	=	" 8D_H[GZHYIZI\\H^G_";
prog_char	gJapanese_22[]	PROGMEM	=	" 8D_HOJQZP\\Q RIP\\Q";
prog_char	gJapanese_23[]	PROGMEM	=	"27D_MHKGK\\ RLHL\\ RLZXZ RLHXH RWHXGZHYJ RXHX\\ RYHY\\ RLQXQ";
prog_char	gJapanese_24[]	PROGMEM	=	"40D_KGIFI[ RJGJ[ RJGYG RXGYF[GZI RYGYWXYWZ RYXYYXZ RZGZYY[X[WZUY RQGQP RRGRP RJPYP";
prog_char	gJapanese_25[]	PROGMEM	=	"47D_LFJKGQ RLFMGLIINGQ RLI\\IZGXI RXI[H RRIR\\ RSIS\\ RNOLNLU RMOMU RMO[OYMWO RWOZN RGU]U[SYU RYU\\T";
prog_char	gJapanese_26[]	PROGMEM	=	"46D_QFQLPQNULXJZG\\ RRGRK RQFSGRNQROVLYI[G\\ RGM]M[KYM RYM\\L RSMTQUTVVXY[\\][ RYY[[ RSMTPVTXWZY][";
prog_char	gJapanese_27[]	PROGMEM	=	"51D_JGHFH\\ RIGI\\ RIG[G RZG[F]G\\I R[G[\\ R\\G\\\\ RKKYKXJWK RQKQW RRKRW RLQXQWPVQ RKWYWXVWW RTSUUVUVTTS RI[[[";
prog_char	gJapanese_28[]	PROGMEM	=	"39D_QFQLPQNULXJZG\\ RRGRK RQFSGRNQROVLYI[G\\ RSGSKTQUTVVXY[\\][ RYY[[ RSKTPVTXWZY][";
prog_char	gJapanese_29[]	PROGMEM	=	"61D_RGSFQFQ\\ RRGR\\ RGH]H[GZH RLLJKJU RKLKU RKLXL RWLXKZLYN RXLXU RYLYU RKPXP RKTXT RQTNWKYG[ RQVNXLYG[ RRTUXXZ[[]Z RRTUWYY]Z";
prog_char	gJapanese_2A[]	PROGMEM	=	"32D_RHSGQFQ] RRGR] RJLHKHV RILIV RILZL RYLZK\\L[N RZLZV R[L[V RIUZU";
prog_char	gJapanese_2B[]	PROGMEM	=	"48D_RHSGQFQ\\ RRGR\\ RGL]L[JYL RYL\\K RPLMRJVGY RQMOQMTKVGY RSMTPURXV[Y]X RYV[X RSMTOWSZV]X RMWVWUVTW";
prog_char	gJapanese_2C[]	PROGMEM	=	"69D_RGRFSEQEQG RGG]G[EYG RYG\\F RLKJJJR RKKKR RKKXK RWKXJZKYM RXKXR RYKYR RKQXQ RQQQXPZO[ RQYQZP[ RRQRZQ\\P\\O[MZ RLTGY RLTMUGY RVTXVZY[Y[XZWVT";
prog_char	gJapanese_2D[]	PROGMEM	=	"41D_QFQ[ RQFRFR[ RJHJP RJHKHKP RKOXO RXHXP RXHYHYP RHSH\\ RHSISI\\ RI[Z[ RZSZ\\ RZS[S[\\";
prog_char	gJapanese_2E[]	PROGMEM	=	"65D_HFHW RHFIGIW RIGMG RMGMV RLGMFNGNV RINMN RIUMU RUGVFTFTN RUGUN RPJ[JYIXJ RNN]N[MZN RWNWZV[ RXNXZW\\V[TZ RNR]R[QZR RQTRUSWTWTVSUQT";
prog_char	gJapanese_2F[]	PROGMEM	=	"24D_RHSGQFQ[ RRGR[ RRP[PYNWP RWPZO RG[][[YY[ RY[\\Z";

prog_char	gJapanese_30[]	PROGMEM	=	"59D_QGRFPFPM RQGQM RIIUITHSI RGM]M[LZM RXGUKRNNQIT RXGYHTMPPMRITGU ROQMPM\\ RNQN\\ RNQXQ RWQXPZQYS RXQX\\ RYQY\\ RNVXV RN[X[";
prog_char	gJapanese_31[]	PROGMEM	=	"16D_RHSGQFQ\\ RRGR\\ RGO]O[MYO RYO\\N";
prog_char	gJapanese_32[]	PROGMEM	=	" 8D_GQ]QZOXQ RXQ[P";
prog_char	gJapanese_33[]	PROGMEM	=	"16D_JJZJXHVJ RVJYI RGX]X[VYX RYX\\W";
prog_char	gJapanese_34[]	PROGMEM	=	"24D_II[IYGWI RWIZH RKQYQWOUQ RUQXP RGZ]Z[XYZ RYZ\\Y";
prog_char	gJapanese_35[]	PROGMEM	=	"49D_JIHHHZ RIIIZ RII[I RZI[H]I\\K R[I[Z R\\I\\Z ROIONNRMT RPIPNOQMTKV RSISSTTXTYSXR RTITRUSWSXRXP RIY[Y";
prog_char	gJapanese_36[]	PROGMEM	=	"37D_IHZHXFVH RVHYG RQHNZ RRHOZ RIPVP RUPVOXPWR RVPUZ RWPWRVZ RGZ]Z[XYZ RYZ\\Y";
prog_char	gJapanese_37[]	PROGMEM	=	"43D_RISHQGQM RRHRM RGM]M[KYM RYM\\L RMQLTJXH[ RNRMT RMQORMUJYH[ RTQVSYWZY[Z\\Y[WXTTQ RYV[Y";
prog_char	gJapanese_38[]	PROGMEM	=	"30D_MINHLGLZM[Y[ZZYX RXZYZYY RMHMYNZWZYXZU RHQNPSO[MXLWN RWNYM";
prog_char	gJapanese_39[]	PROGMEM	=	"43D_RLQOOTMWJZG\\ RRLSMRPPTNWLYI[G\\ RLGUG RRGSFUGSI RSGSLTQUTVVXY[\\][ RYY[[ RSLTPVTXWZY][";
prog_char	gJapanese_3A[]	PROGMEM	=	"40D_NIOHMGMRLVJYG\\ RNHNRMVKYG\\ RGNTM RSMTLVMUO RTMTZU[\\[]Z\\X R[Z\\Z\\Y RUMUYVZZZ\\X]U";
prog_char	gJapanese_3B[]	PROGMEM	=	" 6D_HYGZH[IZHY";
prog_char	gJapanese_3C[]	PROGMEM	=	" 6D_HYGZH[IZHY";
prog_char	gJapanese_3D[]	PROGMEM	=	" 6D_HYGZH[IZHY";
prog_char	gJapanese_3E[]	PROGMEM	=	" 6D_HYGZH[IZHY";
prog_char	gJapanese_3F[]	PROGMEM	=	" 6D_HYGZH[IZHY";

prog_char	gJapanese_40[]	PROGMEM	=	" 6D_HYGZH[IZHY";
prog_char	gJapanese_41[]	PROGMEM	=	"59D_OFQGQIPL RPGPRQV RKKMLRLUKXJ RUKVJXJ RSSTOUPSSPWNYLZJZIYIVJTLRNQQPVPYQ[S\\U\\W[YY[V\\T\\ RKZJYJVKTMRQP RVPXQZS[U[WZYX[V\\";
prog_char	gJapanese_42[]	PROGMEM	=	"34D_HHJIJKIMHP RIIIKHPHSIVJWLXMXMVNSOQ RJWLWMV RWLYM[P\\S\\UZTWU R[P[SZT";
prog_char	gJapanese_43[]	PROGMEM	=	"39D_NEOFQGUG ROFTFUGQI RKMKNLOMOPMRL RKNLNOMRLTLWMXOXRWUUXRZN\\ RTLVMWOWRVUUWSYP[";
prog_char	gJapanese_44[]	PROGMEM	=	"45D_NEOFQGUG ROFTFUGQI RJMJNKOMORMULVM RJNMNRM RVMRPLVHZ RULRP RHZHYLVNURUSVTZU[\\[ RW[ZZ[Z\\[";
prog_char	gJapanese_45[]	PROGMEM	=	"62D_MFOGOINM RNGN[ RNTOZN[MYKXHW RHMJNNNQMSL RNNPMQLSL RHXLUQRTQVQYRZTZVYXWYUYSXRV RHXHWLU RVQXRYTYVXXWY RWKYK[L\\MZMYN RYKZLZM";
prog_char	gJapanese_46[]	PROGMEM	=	"54D_NFPGPIOLMQH[ ROGOIMOKTH[ RHMHNIOJOMMOLRLTMUOURTVRZQ[P[PZOYMX RHNJNMM RRLTNTRSVRXPZ RWMYN[P\\R\\T[SYT RZO[Q[S";
prog_char	gJapanese_47[]	PROGMEM	=	"46D_NFQGRKSNURXVWW RPGRK RURWW RLKNLQLTK RIOJPMQRQWPZO RWPYNZO RWWUVRUNULVKWKYLZN[Q\\W\\ RN[V[W\\";
prog_char	gJapanese_48[]	PROGMEM	=	"18D_TFVGVHNP RUGTINPNQSVUYV[ RNQVXWZV[";
prog_char	gJapanese_49[]	PROGMEM	=	"45D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQNOONQMZM\\L RIUJWKX RVMZL[K\\L RVFXGXUWXUZR\\ RWGXJ RXRWVUYR\\";
prog_char	gJapanese_4A[]	PROGMEM	=	"23D_MHOIRJTJWI ROITIVHWIQL RKSKULWNXRYYY RNXXXYY";
prog_char	gJapanese_4B[]	PROGMEM	=	"49D_JKKLNMRMVLXKYJ RVLXJYJ RPFQIRKUOWRXT RPFQFQHRK RUOXRYTYU RYUXTVSRRNRKSJUJWKYMZQ[U[ RJWKXMYQZVZU[";
prog_char	gJapanese_4C[]	PROGMEM	=	"17D_LFNGMSMXNZ RMGLSLWMYNZP[S[VZYX[V";
prog_char	gJapanese_4D[]	PROGMEM	=	"36D_RFTGTSSUQVOUNSNROPQOSPTRTVSZQ\\ RSGTL RTVSYQ\\ RHJJLMLVKZJ\\K RIKML RVK\\K";
prog_char	gJapanese_4E[]	PROGMEM	=	"45D_LJNKNVOXPYRZZZ RMKNN RUZXYYYZZ RUGWHWTVVUURS RVHWK RWQVTUU RHNJPLPPOUNYM[M\\N RIOPO RUN\\N";
prog_char	gJapanese_4F[]	PROGMEM	=	"47D_NGPIVG ROHQHVGWH RWHTKNOJQ RVGUISKNO RIPKROP RJQOPUOZN[O RUO[O RUOSPQRPTPVQXRYUZYZ RQXTYXYYZ";

prog_char	gJapanese_50[]	PROGMEM	=	"48D_NFPGPINOMRKWI[ ROGOJNO RMRKVIYI[ RHMJNMNPMRLTK RRLSJTK RUNXN[OYOWP RXNYO RRVSXTYVZ[Z RSXUY\\Y[Z";
prog_char	gJapanese_51[]	PROGMEM	=	"44D_MFOGOIMNLRLTMU RNGNK RMNMU RHJKKOKSJUI RSJTHUI RMUOSRQUPXPZQ[S[VZXWZS[O[ RXPYQZSZVYXWZ";
prog_char	gJapanese_52[]	PROGMEM	=	"26D_HLJNOLSKWKZL[M\\O\\R[TZUXVUWPX RIMOL RWKYLZM[O[RZTXV";
prog_char	gJapanese_53[]	PROGMEM	=	"35D_HIJKLKPJUIYH[H\\I RIJPJ RUI\\I RYIVJSLQOPRPUQXRYTZX[[[ RPUQWRXTYXZZZ[[";
prog_char	gJapanese_54[]	PROGMEM	=	"29D_OFQGQQ RPGPMQQ RWNYPQQ RXOTPQQNRLSKUKWLYMZO[Z[ RLYNZYZZ[";
prog_char	gJapanese_55[]	PROGMEM	=	"63D_MFOGOIMOLRJWH[ RNGNJMO RLRJVHYH[ RHMJNLNOMQLSK RQLRJSK RVJXJZK\\MZLXM RXJZL RVOVQWTXVXXWZU[R[PZOXPVRUUUWV[Z RVQWVWYU[ RYXZZ[Z";
prog_char	gJapanese_56[]	PROGMEM	=	"42D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RSJVIYI[JYJWK RWIYJ RQSQURWUX\\X RQURVUWZW\\X";
prog_char	gJapanese_57[]	PROGMEM	=	"69D_JILJLO RKJLOMRNTOVPW RNTPVPW RRGTHTJROOVMYKZIZHXHVISJQLOOMSLVLYM[O\\R\\U[XZYXZVZTYSXSWTVVUXUZV\\Y RSHSJRO RJZIXIUJRLO RVLXMZO[R[VZY RZV\\X\\Y";
prog_char	gJapanese_58[]	PROGMEM	=	"60D_MFOGOIM[ RNGN[M[LXKWIV RHLINKNOLOM RIMLMNLMP ROMMPKSHWHVKSOOSLVKXKZL[N[UZXYYWZUZSYRXRWSVUUWUYVZW\\Z RXKYLZNZVYY RZW\\Y\\Z";
prog_char	gJapanese_59[]	PROGMEM	=	"42D_QHRJRMQPPRNULWJWIVHTHQINKKNIQHTHWIYJ[L\\O\\R[UYWWXTYQY RNULVJVITIQJMKK RWIZL[O[RZUWX";
prog_char	gJapanese_5A[]	PROGMEM	=	"51D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RUGWHWWVYTZRZPYOWPURTTTVU[Y RVHWL RVU[X[Y RPMRNUNYM[L RYMZK[L";
prog_char	gJapanese_5B[]	PROGMEM	=	"52D_IGJHLIPI RJHOHPI RPIMKKMIPHSHVIXJYLZOZRYTWUUVQVMUIVI RHUIWJXLYOYRXTVUTVQ RVIXLYN[Q\\SZSYT RUIXL RYNZQZS";
prog_char	gJapanese_5C[]	PROGMEM	=	"53D_PFQISJ RQHSITITJ RTJQKOLNMNOOPQQSRTSUUUWTYRZPZMYKW RQQSSTUTWSYRZ RIYLVOTRS RVSYT[V\\XYX RIYIXLV RVSXTZV[X";
prog_char	gJapanese_5D[]	PROGMEM	=	"17D_HPJRMM RIQNLPLUQYT[U\\VZVXW RUQZV";
prog_char	gJapanese_5E[]	PROGMEM	=	"61D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RQGSHUHYG RUHWGXFYG RPOSPVPYO[N RYOZM[N RUHWIWWVYTZRZPYOWPURTTTVU[Y RVIWM RVU[X[Y";
prog_char	gJapanese_5F[]	PROGMEM	=	"45D_RFTGTXSZQ[O[MZLXMVOUQUTVWXZ[ RSGTK RWXZZZ[ RHIJKSKZJ RIJNK RSKWJYIZJ RMPOQSQWPYO RWPXNYO";

prog_char	gJapanese_60[]	PROGMEM	=	"44D_JGKIMIPHSFTG RKHPH RTGPMMSKVJWIWHVHTIRKQPQTRWS\\U RSFPM RTR\\T\\U RVMXNXTWWUYSZP[ RWNWUVX";
prog_char	gJapanese_61[]	PROGMEM	=	"57D_MFOGOINMMQLTKVJWIWHVHTIRJQKQLRLWMZO[U[XZYYXXWVVRVNWMYM[N\\P\\Q[QYR RNGNM RLWMYOZUZWYXX RYM[O[Q RHKKLNLQKSJ RQKRISJ";
prog_char	gJapanese_62[]	PROGMEM	=	"61D_JILJLO RKJLOMRNTOVPW RNTPVPW RSGUHUJTMRRQTOWMYKZIZHYHWITJRLPONRMVMYN[P\\S\\V[XZYXZU[R[ RTHTJRR RJZIYIVJSLP RVMXNZP[S[VZXXZ";
prog_char	gJapanese_63[]	PROGMEM	=	"42D_OFQGQIPM RPGPTQXRZT[X[ZZ[X[VZTXRUP RW[YZZXZUYS RLJMKPLSL RMKRKSL RSLPMNNLPKRLTNUSU";
prog_char	gJapanese_64[]	PROGMEM	=	"48D_PFRGSHTJSKPJMJLKLMOTQ[ RRGSISK ROTRZQ[ RHNIPKPNNRLVKYK[L\\N\\P[RZSWTTTQS RIOKONN RYKZL[N[PZRYSWT";
prog_char	gJapanese_65[]	PROGMEM	=	"34D_HHJIJKIMHP RIIIKHPHSIVJWLXMXMVNSOQ RJWLWMV RWLYM[P\\S\\UZTWU R[P[SZT";
prog_char	gJapanese_66[]	PROGMEM	=	"52D_HJJKJMIP RIKITJWKXKVLSMQONRKUJXJZK[L\\N\\Q[SYUWVTVRUPSOPOMPIQGSFUFVHVSUWTYQ[ RITJVKV RZK[N[QZT RVSUVTXQ[";
prog_char	gJapanese_67[]	PROGMEM	=	"45D_NEOFQGUG ROFTFUGQI RJMJNKOMORMULVM RJNMNRM RVMRPLVHZ RULRP RHZHYLVNURUSVTZU[\\[ RW[ZZ[Z\\[";
prog_char	gJapanese_68[]	PROGMEM	=	"34D_PFSGSIRN RRGRXQZO[L[JZIYIWJVLUOURVVX[[ RRVWX[Z[[ RRNUNYM RUNWMXLYM";
prog_char	gJapanese_69[]	PROGMEM	=	"42D_OFQFSGTHRHPI RQFRGRH RLLKNJRJTKUORQQTPWPYQZSZUYWWYUZQ[O[ RJRKTLT RWPXQYSYUXWVYTZQ[";
prog_char	gJapanese_6A[]	PROGMEM	=	"37D_LFNGNILM RMGMILMLPMSNTNROOQLSJUIWIXJYMYRXVVYS[O\\ RLPMRNR RVIWJXMXRWVUYS[";
prog_char	gJapanese_6B[]	PROGMEM	=	"50D_MGNIPIUG RNHPHUGVH RVHRKNPKU RUGRK RNPKSKU RKUMSPQSPVPXQYRZTZWYYXZV[S[QZPYPXQWSWUXWZ RVPXRYTYWXYV[";
prog_char	gJapanese_6C[]	PROGMEM	=	"49D_MFOGOIM[ RNGN[M[LXKWIV RHLINKNOLOM RIMLMOLMP ROMMPKSHWHVKSOOSLVKWKYLZNYXYZZ[ RWKXLYNXXXZY[Z[[Z\\X";
prog_char	gJapanese_6D[]	PROGMEM	=	"42D_MGNIPIUG RNHPHUGVH RVHRKNPKU RUGRK RNPKSKU RKUMSPQSPVPXQYRZTZWYYW[T\\R\\ RVPXRYTYWXZ";
prog_char	gJapanese_6E[]	PROGMEM	=	"49D_MFOGOIM[ RNGN[M[LXKWIV RHLINKNOLOM RIMLMOLMP ROMMPKSHWHVKSNPQNTMWMYNZO[Q[TZWXYVZS[ RWMYOZQZTYWVZ";
prog_char	gJapanese_6F[]	PROGMEM	=	"52D_MGNIPITG RNHPHTGUH RUHQNMVLXKYIYHWHUISKQNORNVNYO[Q\\S\\V[XYZW[T[RZQYQXRWTWVXXZ RTGQN RJYIWIUJR RZP[S[VZY";

prog_char	gJapanese_70[]	PROGMEM	=	"39D_NEOFQGUG ROFTFUGQI RKMKNLOMOPMRL RKNLNOMRLTLWMXOXRWUUXRZN\\ RTLVMWOWRVUUWSYP[";
prog_char	gJapanese_71[]	PROGMEM	=	"69D_LGMIOIQHTF RMHOHRGTFUG RUGQJMNJR RTFQJ RJRJPMNOMRLULWMXOXQWSUTPTOSOQPPRPSQSSRTNUKWHZH[I[KW RJYLXNXPZQZSXVWYW[X\\Y\\[[ZYZ RNXPYQYSX RYW[Y[Z";
prog_char	gJapanese_72[]	PROGMEM	=	"57D_PFRGRHPLNOKRHU RQGQHPL RKRHTHU RMPOOQOSPTRTV RQORPSRSWTV RIJLKOKSJWI RSJVHWI R[O\\QTRQSOTNVNXOZQ[Y[ R[PTR RT[XZY[";
prog_char	gJapanese_73[]	PROGMEM	=	"30D_QFSHPMLTH[ RRGPM RH[HYLTNRPQRQTRTWUYVZ RRQSRSWTYVZXZZY[W\\T";
prog_char	gJapanese_74[]	PROGMEM	=	" 6D_HYGZH[IZHY";
prog_char	gJapanese_75[]	PROGMEM	=	" 6D_HYGZH[IZHY";
prog_char	gJapanese_76[]	PROGMEM	=	" 6D_HYGZH[IZHY";
prog_char	gJapanese_77[]	PROGMEM	=	" 6D_HYGZH[IZHY";
prog_char	gJapanese_78[]	PROGMEM	=	"60D_NFPGPIOLMQH[ ROGOIMOKTH[ RHMHNIOJOMMOLRLTMUOURTVRZQ[P[PZOYMX RHNJNMM RRLTNTRSVRXPZ RWMYN[P\\R\\T[SYT RZO[Q[S RWHYJ RYF[H";
prog_char	gJapanese_79[]	PROGMEM	=	"52D_NFQGRKSNURXVWW RPGRK RURWW RLKNLQLTK RIOJPMQRQWPZO RWPYNZO RWWUVRUNULVKWKYLZN[Q\\W\\ RN[V[W\\ RWHYJ RYF[H";
prog_char	gJapanese_7A[]	PROGMEM	=	"24D_TFVGVHNP RUGTINPNQSVUYV[ RNQVXWZV[ RYH[J R[F]H";
prog_char	gJapanese_7B[]	PROGMEM	=	"51D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQNOONQMZM\\L RIUJWKX RVMZL[K\\L RVFXGXUWXUZR\\ RWGXJ RXRWVUYR\\ R[G]I R]E_G";
prog_char	gJapanese_7C[]	PROGMEM	=	"29D_MHOIRJTJWI ROITIVHWIQL RKSKULWNXRYYY RNXXXYY RYG[I R[E]G";
prog_char	gJapanese_7D[]	PROGMEM	=	"55D_JKKLNMRMVLXKYJ RVLXJYJ RPFQIRKUOWRXT RPFQFQHRK RUOXRYTYU RYUXTVSRRNRKSJUJWKYMZQ[U[ RJWKXMYQZVZU[ RZG\\I R\\E^G";
prog_char	gJapanese_7E[]	PROGMEM	=	"23D_LFNGMSMXNZ RMGLSLWMYNZP[S[VZYX[V RSHUJ RUFWH";
prog_char	gJapanese_7F[]	PROGMEM	=	"42D_RFTGTSSUQVOUNSNROPQOSPTRTVSZQ\\ RSGTL RTVSYQ\\ RHJJLMLVKZJ\\K RIKML RVK\\K RXFZH R[E]G";

#if 0
prog_char	gJapanese_20[]	PROGMEM	=	"51D_LJNKNVOXPYRZZZ RMKNN RUZXYYYZZ RUGWHWTVVUURS RVHWK RWQVTUU RHNJPLPPOUNYM[M\\N RIOPO RUN\\N RZH\\J R\\F^H";
prog_char	gJapanese_20[]	PROGMEM	=	"53D_NGPIVG ROHQHVGWH RWHTKNOJQ RVGUISKNO RIPKROP RJQOPUOZN[O RUO[O RUOSPQRPTPVQXRYUZYZ RQXTYXYYZ RZH\\J R\\F^H";
prog_char	gJapanese_20[]	PROGMEM	=	"54D_NFPGPINOMRKWI[ ROGOJNO RMRKVIYI[ RHMJNMNPMRLTK RRLSJTK RUNXN[OYOWP RXNYO RRVSXTYVZ[Z RSXUY\\Y[Z RXHZJ RZF\\H";
prog_char	gJapanese_20[]	PROGMEM	=	"50D_MFOGOIMNLRLTMU RNGNK RMNMU RHJKKOKSJUI RSJTHUI RMUOSRQUPXPZQ[S[VZXWZS[O[ RXPYQZSZVYXWZ RXIZK RZG\\I";
prog_char	gJapanese_20[]	PROGMEM	=	"32D_HLJNOLSKWKZL[M\\O\\R[TZUXVUWPX RIMOL RWKYLZM[O[RZTXV RZH\\J R\\F^H";
prog_char	gJapanese_20[]	PROGMEM	=	"41D_HIJKLKPJUIYH[H\\I RIJPJ RUI\\I RYIVJSLQOPRPUQXRYTZX[[[ RPUQWRXTYXZZZ[[ RZM\\O R\\K^M";
prog_char	gJapanese_20[]	PROGMEM	=	"35D_OFQGQQ RPGPMQQ RWNYPQQ RXOTPQQNRLSKUKWLYMZO[Z[ RLYNZYZZ[ RXIZK RZG\\I";
prog_char	gJapanese_20[]	PROGMEM	=	"57D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RUGWHWWVYTZRZPYOWPURTTTVU[Y RVHWL RVU[X[Y RPMRNUNYM[L RYMZK[L RZG\\I R\\E^G";
prog_char	gJapanese_20[]	PROGMEM	=	"58D_IGJHLIPI RJHOHPI RPIMKKMIPHSHVIXJYLZOZRYTWUUVQVMUIVI RHUIWJXLYOYRXTVUTVQ RVIXLYN[Q\\SZSYT RUIXL RYNZQZS RYH[J R[F]H";
prog_char	gJapanese_20[]	PROGMEM	=	"59D_PFQISJ RQHSITITJ RTJQKOLNMNOOPQQSRTSUUUWTYRZPZMYKW RQQSSTUTWSYRZ RIYLVOTRS RVSYT[V\\XYX RIYIXLV RVSXTZV[X RWIYK RYG[I";
prog_char	gJapanese_20[]	PROGMEM	=	"23D_HPJRMM RIQNLPLUQYT[U\\VZVXW RUQZV RUJWL RWHYJ";
prog_char	gJapanese_20[]	PROGMEM	=	"67D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RQGSHUHYG RUHWGXFYG RPOSPVPYO[N RYOZM[N RUHWIWWVYTZRZPYOWPURTTTVU[Y RVIWM RVU[X[Y R[I]K R]G_I";
prog_char	gJapanese_20[]	PROGMEM	=	"61D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RUGWHWWVYTZRZPYOWPURTTTVU[Y RVHWL RVU[X[Y RPMRNUNYM[L RYMZK[L R[EZFZH[I]I^H^F]E[E";
prog_char	gJapanese_20[]	PROGMEM	=	"62D_IGJHLIPI RJHOHPI RPIMKKMIPHSHVIXJYLZOZRYTWUUVQVMUIVI RHUIWJXLYOYRXTVUTVQ RVIXLYN[Q\\SZSYT RUIXL RYNZQZS RZFYGYIZJ\\J]I]G\\FZF";
prog_char	gJapanese_20[]	PROGMEM	=	"63D_PFQISJ RQHSITITJ RTJQKOLNMNOOPQQSRTSUUUWTYRZPZMYKW RQQSSTUTWSYRZ RIYLVOTRS RVSYT[V\\XYX RIYIXLV RVSXTZV[X RXGWHWJXKZK[J[HZGXG";
prog_char	gJapanese_20[]	PROGMEM	=	"27D_HPJRMM RIQNLPLUQYT[U\\VZVXW RUQZV RVHUIUKVLXLYKYIXHVH";
prog_char	gJapanese_20[]	PROGMEM	=	"71D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RQGSHUHYG RUHWGXFYG RPOSPVPYO[N RYOZM[N RUHWIWWVYTZRZPYOWPURTTTVU[Y RVIWM RVU[X[Y R\\G[H[J\\K^K_J_H^G\\G";
prog_char	gJapanese_20[]	PROGMEM	=	"36D_HGJIOHUGZF\\H RIHOH RUG[G R\\HZJVMTN R[GYJWLTN RRMTNTQSUQXN[ RRMSNSQRUPY";
prog_char	gJapanese_20[]	PROGMEM	=	"22D_VFXHULRONRKT RWGVISMOQKT RSNUOU\\ RSNTOT[U\\";
prog_char	gJapanese_20[]	PROGMEM	=	"42D_PFSGSIRK RPFRGRK RJIKKKPLQ RLKLQ RLKYK RJIKJOK RUKXJZL RZLWRUURXOZM[ RYKXNVRSVPYM[";
prog_char	gJapanese_20[]	PROGMEM	=	"23D_QKSLSW RRLRW RJJLLXJZK RKKZK RHVJXZV\\W RIW\\W";
prog_char	gJapanese_20[]	PROGMEM	=	"35D_RFUGUYT[SYPW RTGTXSY RHLJNOMULZK\\L RIMOM RUL\\L RSMPQLUHX RTMRPOSKVHX";
prog_char	gJapanese_20[]	PROGMEM	=	"41D_QFSHRKPPNTLWI[ RRGQJOPMUI[ RILKNOMTLXKZM RJMOM RTLYL RZMYSXWWYU[TZRY RYLXSWWVYTZ";
prog_char	gJapanese_20[]	PROGMEM	=	"34D_OFRGT[ RQGS\\T[ RJLLNPMTLXKZL RKMPM RTLZL RHRJTOSURZQ\\R RISOS RUR\\R";
prog_char	gJapanese_20[]	PROGMEM	=	"34D_PFRHPLNOLQJS RQGPJNNLQ RQJSKXK RUKWJYL RYLVRSVPYM[K\\ RXKWNURRVOYK\\";
prog_char	gJapanese_20[]	PROGMEM	=	"32D_NFPHNLLOJQHS ROGNJLNJQ RLOTNYM\\N RTN\\N RROTQRUPXNZL\\ RSPRSPWNZ";
prog_char	gJapanese_20[]	PROGMEM	=	"24D_JJLLXJZL RKKYK RZLYOXV RYKXPXV RJVLXXVYW RKWYW";
prog_char	gJapanese_20[]	PROGMEM	=	"36D_LINJNOMS RMJMS RTFWGWLVQUTTVRYP[ RVGVLUQTURY RHMJOONUMZL\\M RINON RUM\\M";
prog_char	gJapanese_20[]	PROGMEM	=	"28D_MGOHPIPJOJNHMG RHNJOKPKQJQIOHN RIXKZOXSUWQ[L RJYOWST[L";
prog_char	gJapanese_20[]	PROGMEM	=	"30D_JILKWIYK RKJXJ RYKWNTQQSOTJV RXJWLUOSQPSJV RUSXUZWZXYXXVUS";
prog_char	gJapanese_20[]	PROGMEM	=	"35D_OGRHRJQS RQHQVRXTY[Y RVYZX[Y RHNJPOOUNZM\\O RIOOO RUN[N R\\OYQVT R[NVT";
prog_char	gJapanese_20[]	PROGMEM	=	"23D_IIKJLKLLKLJJII RXHZJWPTTQWNYLZ RYIXLVPSTPWLZ";
prog_char	gJapanese_20[]	PROGMEM	=	"44D_PFRHPLNOLQJS RQGPJNNLQ RQJSKXK RUKWJYL RYLVRSVPYM[K\\ RXKWNURRVOYK\\ RNPQQSRVTWUWVVVUTSR";
prog_char	gJapanese_20[]	PROGMEM	=	"36D_LJOJTIXG ROJRITHWFXG RPJSKSQRUPXM[ RRKRQQUOY RHNJPOOUNZM\\N RIOOO RUN\\N";
prog_char	gJapanese_20[]	PROGMEM	=	"31D_IIKJLKLLKLJJII ROHQIRJRKQKPIOH RXHZJWPTTQWNYLZ RYIXLVPSTPWLZ";
prog_char	gJapanese_20[]	PROGMEM	=	"32D_LFNHWFXG RMGXG RHNJPOOUNZM\\N RIOOO RUN\\N RSOSQRUPXM[ RRORQQUOY";
prog_char	gJapanese_20[]	PROGMEM	=	"17D_MFPGP\\ ROGO[P\\ RPOROUPVQVRURTPRO";
prog_char	gJapanese_20[]	PROGMEM	=	"28D_QFTGTLSQRTQVOYM[ RSGSLRQQUOY RHNJPOOUNZM\\N RIOOO RUN\\N";
prog_char	gJapanese_20[]	PROGMEM	=	"16D_LJNLWJXK RMKXK RHVJXZV\\W RIW\\W";
prog_char	gJapanese_20[]	PROGMEM	=	"32D_JILKWIYK RKJXJ RYKWNTQQSOTJV RXJWLUOSQPSJV RMOPPTRWTYVYWXWVTTR";
prog_char	gJapanese_20[]	PROGMEM	=	"44D_PFRGSHSIRIQGPF RJLLNVLXN RKMWM RXNTRQTOUJW RWMUPSRPTJW RRSSTS\\ RRSR[S\\ RXUZV[W[XZXYVXU";
prog_char	gJapanese_20[]	PROGMEM	=	"15D_WHYJVPSTPWMYKZ RXIWLTQQUNXKZ";
prog_char	gJapanese_20[]	PROGMEM	=	"20D_LLNNMQLSJUHV RMMLQJU RVLXNZQ\\U\\V[VZRXN";
prog_char	gJapanese_20[]	PROGMEM	=	"25D_IGLHLJKS RKHKVLXNYYY RQYUXWXYY RKROQRPXN RRPVNXN";
prog_char	gJapanese_20[]	PROGMEM	=	"25D_JGLIYI RKHOI RUIXHZJ RZJWPUSRVOXMY RYIXLVPSTPWMY";
prog_char	gJapanese_20[]	PROGMEM	=	"15D_GQISPLQL[V RHRJQNN RUPZT\\U[V";
prog_char	gJapanese_20[]	PROGMEM	=	"40D_PFSGSYR[QYOX RRGRXQY RHLJNOMULZK\\L RIMOM RUL\\L RLSJVIWHWHVJULS RXS[U\\V\\W[WZUXS";
prog_char	gJapanese_20[]	PROGMEM	=	"31D_HLJNOMULZK\\M RIMOM RUL[L R\\MZOVRTS R[LYOWQTS RQRTTVVVWUWTUQR";
prog_char	gJapanese_20[]	PROGMEM	=	"28D_PFSGUHVIVJUJSHPF RMMPNROSPSQRQPOMM RNVSXUYVZV[U[SYPWNV";
prog_char	gJapanese_20[]	PROGMEM	=	"22D_RITKMW RSJMW RHWJYYV RIXYV RVSXUZX[X[WYUVS";
prog_char	gJapanese_20[]	PROGMEM	=	"25D_WHYJVPSTPWMYKZ RXIWLUPRTOWKZ RONSPVRXTXUWUVSTQQO";
prog_char	gJapanese_20[]	PROGMEM	=	"35D_LINKWIXJ RMJXJ RQKQVRXTY[Y RRKRMQS RVYZX[Y RHQJSORUQZP\\Q RIROR RUQ\\Q";
prog_char	gJapanese_20[]	PROGMEM	=	"31D_OFRGT[ RQGS\\T[ RHLJNOMULZK\\M RIMOM RUL[L R\\MYPVRTS R[LZNWQTS";
prog_char	gJapanese_20[]	PROGMEM	=	"22D_VFXHULRONRKT RWGVISMOQKT RSNUOU\\ RSNTOT[U\\";
prog_char	gJapanese_20[]	PROGMEM	=	"24D_IJKLUJWL RJKVK RWLVOUV RVKUPUV RHVJXZV\\W RIW\\W";
prog_char	gJapanese_20[]	PROGMEM	=	"23D_QKSLSW RRLRW RJJLLXJZK RKKZK RHVJXZV\\W RIW\\W";
prog_char	gJapanese_20[]	PROGMEM	=	"30D_JJLLXJZL RKKYK RJPLRXP RKQXQ RJVLXXV RKWXW RZLYOYY RYKXPXY";
prog_char	gJapanese_20[]	PROGMEM	=	"30D_LFNHWFXG RMGXG RJMLOWMYO RKNXN RYOWRTUQWOXLY RXNWPUSSUPWLY";
prog_char	gJapanese_20[]	PROGMEM	=	"21D_LINJNOMS RMJMS RTFWGWQVUTXQ[ RVGVQUUTWQ[";
prog_char	gJapanese_20[]	PROGMEM	=	"31D_LJNKNNMRKUHX RMKMNLRKTHX RQISJSMRS RRJRVSXUXWWYU\\Q RRVSWVWXV";
prog_char	gJapanese_20[]	PROGMEM	=	"21D_HIKJKMJS RJJJVKXNXQWTUXR[O RJVKWNWQVUTXR";
prog_char	gJapanese_20[]	PROGMEM	=	"30D_JJLLXJZL RKKYK RKKKZ RLLLXKZ RZLYOXV RYKXPXV RLXXVYW RLWYW";
prog_char	gJapanese_20[]	PROGMEM	=	"33D_JGKIKNLO RLILO RLIYI RJGKHOI RUIXHZJ RZJWPUSRVOXMY RYIXLVPSTPWMY";
prog_char	gJapanese_20[]	PROGMEM	=	"31D_QFTGT[ RSGS\\T[ RJJLLXJZK RKKZK RLLNMNR RMMMR RHQJSZQ\\R RIR\\R";
prog_char	gJapanese_20[]	PROGMEM	=	"42D_PFSGSIRK RPFRGRK RJIKKKPLQ RLKLQ RLKYK RJIKJOK RUKXJZL RZLWRUURXOZM[ RYKXNVRSVPYM[";
prog_char	gJapanese_20[]	PROGMEM	=	"30D_JJLLXJZL RKKYK RZLWNSQ RYKSQ RQPSQSW RRQRW RHVJXZV\\W RIW\\W";
prog_char	gJapanese_20[]	PROGMEM	=	"32D_JGLIYI RKHOI RUIXHZJ RLNNPVO RMOVO RZJWPUSRVOXMY RYIXLVPSTPWMY";
prog_char	gJapanese_20[]	PROGMEM	=	"20D_JHLIMJMKLKKIJH RIWKYOWSTWP[K RJXOVSS[K";
prog_char	gJapanese_20[]	PROGMEM	=	" 6D_HYGZH[IZHY";
prog_char	gJapanese_20[]	PROGMEM	=	" 6D_HYGZH[IZHY";
prog_char	gJapanese_20[]	PROGMEM	=	" 6D_HYGZH[IZHY";
prog_char	gJapanese_20[]	PROGMEM	=	" 6D_HYGZH[IZHY";
prog_char	gJapanese_20[]	PROGMEM	=	"47D_QFSHRKPPNTLWI[ RRGQJOPMUI[ RILKNOMTLXKZM RJMOM RTLYL RZMYSXWWYU[TZRY RYLXSWWVYTZ RZH\\J R\\F^H";
prog_char	gJapanese_20[]	PROGMEM	=	"40D_OFRGT[ RQGS\\T[ RJLLNPMTLXKZL RKMPM RTLZL RHRJTOSURZQ\\R RISOS RUR\\R RZH\\J R\\F^H";
prog_char	gJapanese_20[]	PROGMEM	=	"40D_PFRHPLNOLQJS RQGPJNNLQ RQJSKXK RUKWJYL RYLVRSVPYM[K\\ RXKWNURRVOYK\\ RYH[J R[F]H";
prog_char	gJapanese_20[]	PROGMEM	=	"38D_NFPHNLLOJQHS ROGNJLNJQ RLOTNYM\\N RTN\\N RROTQRUPXNZL\\ RSPRSPWNZ RYH[J R[F]H";
prog_char	gJapanese_20[]	PROGMEM	=	"30D_JJLLXJZL RKKYK RZLYOXV RYKXPXV RJVLXXVYW RKWYW RZH\\J R\\F^H";
prog_char	gJapanese_20[]	PROGMEM	=	"42D_LINJNOMS RMJMS RTFWGWLVQUTTVRYP[ RVGVLUQTURY RHMJOONUMZL\\M RINON RUM\\M RZH\\J R\\F^H";
prog_char	gJapanese_20[]	PROGMEM	=	"34D_MGOHPIPJOJNHMG RHNJOKPKQJQIOHN RIXKZOXSUWQ[L RJYOWST[L RVHXJ RXFZH";
prog_char	gJapanese_20[]	PROGMEM	=	"36D_JILKWIYK RKJXJ RYKWNTQQSOTJV RXJWLUOSQPSJV RUSXUZWZXYXXVUS RZH\\J R\\F^H";
prog_char	gJapanese_20[]	PROGMEM	=	"41D_OGRHRJQS RQHQVRXTY[Y RVYZX[Y RHNJPOOUNZM\\O RIOOO RUN[N R\\OYQVT R[NVT RYH[J R[F]H";
prog_char	gJapanese_20[]	PROGMEM	=	"29D_IIKJLKLLKLJJII RXHZJWPTTQWNYLZ RYIXLVPSTPWLZ R[G]I R]E_G";
prog_char	gJapanese_20[]	PROGMEM	=	"50D_PFRHPLNOLQJS RQGPJNNLQ RQJSKXK RUKWJYL RYLVRSVPYM[K\\ RXKWNURRVOYK\\ RNPQQSRVTWUWVVVUTSR RYH[J R[F]H";
prog_char	gJapanese_20[]	PROGMEM	=	"42D_LJOJTIXG ROJRITHWFXG RPJSKSQRUPXM[ RRKRQQUOY RHNJPOOUNZM\\N RIOOO RUN\\N RZH\\J R\\F^H";
prog_char	gJapanese_20[]	PROGMEM	=	"37D_IIKJLKLLKLJJII ROHQIRJRKQKPIOH RXHZJWPTTQWNYLZ RYIXLVPSTPWLZ R[G]I R]E_G";
prog_char	gJapanese_20[]	PROGMEM	=	"38D_LFNHWFXG RMGXG RHNJPOOUNZM\\N RIOOO RUN\\N RSOSQRUPXM[ RRORQQUOY RZH\\J R\\F^H";
prog_char	gJapanese_20[]	PROGMEM	=	"23D_MFPGP\\ ROGO[P\\ RPOROUPVQVRURTPRO RTHVJ RVFXH";
prog_char	gJapanese_20[]	PROGMEM	=	"26D_LLNNMQLSJUHV RMMLQJU RVLXNZQ\\U\\V[VZRXN RYI[K R[G]I";
prog_char	gJapanese_20[]	PROGMEM	=	"31D_IGLHLJKS RKHKVLXNYYY RQYUXWXYY RKROQRPXN RRPVNXN RYI[K R[G]I";
prog_char	gJapanese_20[]	PROGMEM	=	"31D_JGLIYI RKHOI RUIXHZJ RZJWPUSRVOXMY RYIXLVPSTPWMY R[G]I R]E_G";
prog_char	gJapanese_20[]	PROGMEM	=	"21D_GQISPLQL[V RHRJQNN RUPZT\\U[V RVJXL RXHZJ";
prog_char	gJapanese_20[]	PROGMEM	=	"46D_PFSGSYR[QYOX RRGRXQY RHLJNOMULZK\\L RIMOM RUL\\L RLSJVIWHWHVJULS RXS[U\\V\\W[WZUXS RZG\\I R\\E^G";
prog_char	gJapanese_20[]	PROGMEM	=	"30D_LLNNMQLSJUHV RMMLQJU RVLXNZQ\\U\\V[VZRXN RZGYHYJZK\\K]J]H\\GZG";
prog_char	gJapanese_20[]	PROGMEM	=	"35D_IGLHLJKS RKHKVLXNYYY RQYUXWXYY RKROQRPXN RRPVNXN RZGYHYJZK\\K]J]H\\GZG";
prog_char	gJapanese_20[]	PROGMEM	=	"35D_JGLIYI RKHOI RUIXHZJ RZJWPUSRVOXMY RYIXLVPSTPWMY R\\E[F[H\\I^I_H_F^E\\E";
prog_char	gJapanese_20[]	PROGMEM	=	"25D_GQISPLQL[V RHRJQNN RUPZT\\U[V RWHVIVKWLYLZKZIYHWH";
prog_char	gJapanese_20[]	PROGMEM	=	"50D_PFSGSYR[QYOX RRGRXQY RHLJNOMULZK\\L RIMOM RUL\\L RLSJVIWHWHVJULS RXS[U\\V\\W[WZUXS R[EZFZH[I]I^H^F]E[E";

#endif

PGM_P gHershyJapaneseFontTable[]	PROGMEM =	   // change "string_table" name to suit
{

	gJapanese_00,
	gJapanese_20,
	gJapanese_21,
	gJapanese_22,
	gJapanese_23,
	gJapanese_24,
	gJapanese_25,
	gJapanese_26,
	gJapanese_27,
	gJapanese_28,
	gJapanese_29,
	gJapanese_2A,
	gJapanese_2B,
	gJapanese_2C,
	gJapanese_2D,
	gJapanese_2E,
	gJapanese_2F,

	gJapanese_30,
	gJapanese_31,
	gJapanese_32,
	gJapanese_33,
	gJapanese_34,
	gJapanese_35,
	gJapanese_36,
	gJapanese_37,
	gJapanese_38,
	gJapanese_39,
	gJapanese_3A,
	gJapanese_3B,
	gJapanese_3C,
	gJapanese_3D,
	gJapanese_3E,
	gJapanese_3F,

	gJapanese_40,
	gJapanese_41,
	gJapanese_42,
	gJapanese_43,
	gJapanese_44,
	gJapanese_45,
	gJapanese_46,
	gJapanese_47,
	gJapanese_48,
	gJapanese_49,
	gJapanese_4A,
	gJapanese_4B,
	gJapanese_4C,
	gJapanese_4D,
	gJapanese_4E,
	gJapanese_4F,

	gJapanese_50,
	gJapanese_51,
	gJapanese_52,
	gJapanese_53,
	gJapanese_54,
	gJapanese_55,
	gJapanese_56,
	gJapanese_57,
	gJapanese_58,
	gJapanese_59,
	gJapanese_5A,
	gJapanese_5B,
	gJapanese_5C,
	gJapanese_5D,
	gJapanese_5E,
	gJapanese_5F,

	gJapanese_60,
	gJapanese_61,
	gJapanese_62,
	gJapanese_63,
	gJapanese_64,
	gJapanese_65,
	gJapanese_66,
	gJapanese_67,
	gJapanese_68,
	gJapanese_69,
	gJapanese_6A,
	gJapanese_6B,
	gJapanese_6C,
	gJapanese_6D,
	gJapanese_6E,
	gJapanese_6F,

	gJapanese_70,
	gJapanese_71,
	gJapanese_72,
	gJapanese_73,
	gJapanese_74,
	gJapanese_75,
	gJapanese_76,
	gJapanese_77,
	gJapanese_78,
	gJapanese_79,
	gJapanese_7A,
	gJapanese_7B,
	gJapanese_7C,
	gJapanese_7D,
	gJapanese_7E,
	gJapanese_7F

};
