//*******************************************************************************
//*	timesg.jhf		Times Greek
//*	formated for use with Arduino Processing 
//*	by Mark Sproul
//*******************************************************************************
//*	Jan 22,	2009	<MLS>	Formated Hershey Times Greek for Arduino
//*******************************************************************************
//#include	"HersheyTimesGreek.h"

prog_char	gTimesGreek_00[]	PROGMEM	=	"Times Greek";
prog_char	gTimesGreek_20[]	PROGMEM	=	" 1JZ";
prog_char	gTimesGreek_21[]	PROGMEM	=	"15MWRFQHRTSHRF RRHRN RRYQZR[SZRY";
prog_char	gTimesGreek_22[]	PROGMEM	=	"12JZNFMM ROFMM RVFUM RWFUM";
prog_char	gTimesGreek_23[]	PROGMEM	=	"12H]SBLb RYBRb RLOZO RKUYU";
prog_char	gTimesGreek_24[]	PROGMEM	=	"42H\\PBP_ RTBT_ RXIWJXKYJYIWGTFPFMGKIKKLMMNOOUQWRYT RKKMMONUPWQXRYTYXWZT[P[MZKXKWLVMWLX";
prog_char	gTimesGreek_25[]	PROGMEM	=	"32F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT";
prog_char	gTimesGreek_26[]	PROGMEM	=	"49F_[NZO[P\\O\\N[MZMYNXPVUTXRZP[M[JZIXIUJSPORMSKSIRGPFNGMIMKNNPQUXWZZ[[[\\Z\\Y RM[KZJXJUKSMQ RMKNMVXXZZ[";
prog_char	gTimesGreek_27[]	PROGMEM	=	" 6NVRFQM RSFQM";
prog_char	gTimesGreek_28[]	PROGMEM	=	"24KYUBSDQGOKNPNTOYQ]S`UbVb RUBVBTDRGPKOPOTPYR]T`Vb";
prog_char	gTimesGreek_29[]	PROGMEM	=	"24KYNBPDRGTKUPUTTYR]P`NbOb RNBOBQDSGUKVPVTUYS]Q`Ob";
prog_char	gTimesGreek_2A[]	PROGMEM	=	" 9JZRLRX RMOWU RWOMU";
prog_char	gTimesGreek_2B[]	PROGMEM	=	" 6E_RIR[ RIR[R";
prog_char	gTimesGreek_2C[]	PROGMEM	=	" 8NVSWRXQWRVSWSYQ[";
prog_char	gTimesGreek_2D[]	PROGMEM	=	" 3E_IR[R";
prog_char	gTimesGreek_2E[]	PROGMEM	=	" 6NVRVQWRXSWRV";
prog_char	gTimesGreek_2F[]	PROGMEM	=	" 3G][BIb";

prog_char	gTimesGreek_30[]	PROGMEM	=	"40H\\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF RQFOGNHMJLOLRMWNYOZQ[ RS[UZVYWWXRXOWJVHUGSF";
prog_char	gTimesGreek_31[]	PROGMEM	=	"11H\\NJPISFS[ RRGR[ RN[W[";
prog_char	gTimesGreek_32[]	PROGMEM	=	"45H\\LJMKLLKKKJLHMGPFTFWGXHYJYLXNUPPRNSLUKXK[ RTFVGWHXJXLWNTPPR RKYLXNXSZVZXYYX RNXS[W[XZYXYV";
prog_char	gTimesGreek_33[]	PROGMEM	=	"47H\\LJMKLLKKKJLHMGPFTFWGXIXLWNTOQO RTFVGWIWLVNTO RTOVPXRYTYWXYWZT[P[MZLYKWKVLUMVLW RWQXTXWWYVZT[";
prog_char	gTimesGreek_34[]	PROGMEM	=	"13H\\THT[ RUFU[ RUFJUZU RQ[X[";
prog_char	gTimesGreek_35[]	PROGMEM	=	"39H\\MFKP RKPMNPMSMVNXPYSYUXXVZS[P[MZLYKWKVLUMVLW RSMUNWPXSXUWXUZS[ RMFWF RMGRGWF";
prog_char	gTimesGreek_36[]	PROGMEM	=	"48H\\WIVJWKXJXIWGUFRFOGMILKKOKULXNZQ[S[VZXXYUYTXQVOSNRNOOMQLT RRFPGNIMKLOLUMXOZQ[ RS[UZWXXUXTWQUOSN";
prog_char	gTimesGreek_37[]	PROGMEM	=	"31H\\KFKL RKJLHNFPFUIWIXHYF RLHNGPGUI RYFYIXLTQSSRVR[ RXLSQRSQVQ[";
prog_char	gTimesGreek_38[]	PROGMEM	=	"63H\\PFMGLILLMNPOTOWNXLXIWGTFPF RPFNGMIMLNNPO RTOVNWLWIVGTF RPOMPLQKSKWLYMZP[T[WZXYYWYSXQWPTO RPONPMQLSLWMYNZP[ RT[VZWYXWXSWQVPTO";
prog_char	gTimesGreek_39[]	PROGMEM	=	"48H\\XMWPURRSQSNRLPKMKLLINGQFSFVGXIYLYRXVWXUZR[O[MZLXLWMVNWMX RQSORMPLMLLMIOGQF RSFUGWIXLXRWVVXTZR[";
prog_char	gTimesGreek_3A[]	PROGMEM	=	"12NVROQPRQSPRO RRVQWRXSWRV";
prog_char	gTimesGreek_3B[]	PROGMEM	=	"14NVROQPRQSPRO RSWRXQWRVSWSYQ[";
prog_char	gTimesGreek_3C[]	PROGMEM	=	" 4F^ZIJRZ[";
prog_char	gTimesGreek_3D[]	PROGMEM	=	" 6E_IO[O RIU[U";
prog_char	gTimesGreek_3E[]	PROGMEM	=	" 4F^JIZRJ[";
prog_char	gTimesGreek_3F[]	PROGMEM	=	"32I[MJNKMLLKLJMHNGPFSFVGWHXJXLWNVORQRT RSFUGVHWJWLVNTP RRYQZR[SZRY";

prog_char	gTimesGreek_40[]	PROGMEM	=	"56E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
prog_char	gTimesGreek_41[]	PROGMEM	=	"18H\\RFK[ RRFY[ RRIX[ RMUVU RI[O[ RU[[[";
prog_char	gTimesGreek_42[]	PROGMEM	=	"45G]LFL[ RMFM[ RIFUFXGYHZJZLYNXOUP RUFWGXHYJYLXNWOUP RMPUPXQYRZTZWYYXZU[I[ RUPWQXRYTYWXYWZU[";
prog_char	gTimesGreek_43[]	PROGMEM	=	"21H\\KFX[ RLFY[ RYFK[ RIFOF RUF[F RI[O[ RU[[[";
prog_char	gTimesGreek_44[]	PROGMEM	=	"15H\\RFJ[ RRFZ[ RRIY[ RKZYZ RJ[Z[";
prog_char	gTimesGreek_45[]	PROGMEM	=	"22G\\LFL[ RMFM[ RSLST RIFYFYLXF RMPSP RI[Y[YUX[";
prog_char	gTimesGreek_46[]	PROGMEM	=	"48H]RFR[ RSFS[ RPKMLLMKOKRLTMUPVUVXUYTZRZOYMXLUKPK RPKNLMMLOLRMTNUPV RUVWUXTYRYOXMWLUK ROFVF RO[V[";
prog_char	gTimesGreek_47[]	PROGMEM	=	"14I[NFN[ ROFO[ RKFZFZLYF RK[R[";
prog_char	gTimesGreek_48[]	PROGMEM	=	"27F^KFK[ RLFL[ RXFX[ RYFY[ RHFOF RUF\\F RLPXP RH[O[ RU[\\[";
prog_char	gTimesGreek_49[]	PROGMEM	=	"12MXRFR[ RSFS[ ROFVF RO[V[";
prog_char	gTimesGreek_4A[]	PROGMEM	=	" 6PURQRRSRSQRQ";
prog_char	gTimesGreek_4B[]	PROGMEM	=	"27F\\KFK[ RLFL[ RYFLS RQOY[ RPOX[ RHFOF RUF[F RH[O[ RU[[[";
prog_char	gTimesGreek_4C[]	PROGMEM	=	"15H\\RFK[ RRFY[ RRIX[ RI[O[ RU[[[";
prog_char	gTimesGreek_4D[]	PROGMEM	=	"30F_KFK[ RLFRX RKFR[ RYFR[ RYFY[ RZFZ[ RHFLF RYF]F RH[N[ RV[][";
prog_char	gTimesGreek_4E[]	PROGMEM	=	"21G^LFL[ RMFYY RMHY[ RYFY[ RIFMF RVF\\F RI[O[";
prog_char	gTimesGreek_4F[]	PROGMEM	=	"44G]QFNGLIKKJOJRKVLXNZQ[S[VZXXYVZRZOYKXIVGSFQF RQFOGMILKKOKRLVMXOZQ[ RS[UZWXXVYRYOXKWIUGSF";

prog_char	gTimesGreek_50[]	PROGMEM	=	"21F^KFK[ RLFL[ RXFX[ RYFY[ RHF\\F RH[O[ RU[\\[";
prog_char	gTimesGreek_51[]	PROGMEM	=	"56G]QFNGLIKKJOJRKVLXNZQ[S[VZXXYVZRZOYKXIVGSFQF RQFOGMILKKOKRLVMXOZQ[ RS[UZWXXVYRYOXKWIUGSF ROMOT RUMUT ROPUP ROQUQ";
prog_char	gTimesGreek_52[]	PROGMEM	=	"29G]LFL[ RMFM[ RIFUFXGYHZJZMYOXPUQMQ RUFWGXHYJYMXOWPUQ RI[P[";
prog_char	gTimesGreek_53[]	PROGMEM	=	"20H]KFRPJ[ RJFQP RJFYFZLXF RKZXZ RJ[Y[ZUX[";
prog_char	gTimesGreek_54[]	PROGMEM	=	"16I\\RFR[ RSFS[ RLFKLKFZFZLYF RO[V[";
prog_char	gTimesGreek_55[]	PROGMEM	=	"33I\\KKKILGMFOFPGQIRMR[ RKIMGOGQI RZKZIYGXFVFUGTISMS[ RZIXGVGTI RO[V[";
prog_char	gTimesGreek_56[]	PROGMEM	=	"14KYQFOGNINKOMQNSNUMVKVIUGSFQF";
prog_char	gTimesGreek_57[]	PROGMEM	=	"43G]JXK[O[MWKSJPJLKIMGPFTFWGYIZLZPYSWWU[Y[ZX RMWLTKPKLLINGPF RTFVGXIYLYPXTWW RKZNZ RVZYZ";
prog_char	gTimesGreek_58[]	PROGMEM	=	"36G]KEJJ RZEYJ RONNS RVNUS RKWJ\\ RZWY\\ RKGYG RKHYH ROPUP ROQUQ RKYYY RKZYZ";
prog_char	gTimesGreek_59[]	PROGMEM	=	"41G^RFR[ RSFS[ RIMJLLMMQNSOTQU RJLKMLQMSNTQUTUWTXSYQZM[L RTUVTWSXQYM[L\\M ROFVF RO[V[";
prog_char	gTimesGreek_5A[]	PROGMEM	=	"16H\\XFK[ RYFL[ RLFKLKFYF RK[Y[YUX[";
prog_char	gTimesGreek_5B[]	PROGMEM	=	"12KYOBOb RPBPb ROBVB RObVb";
prog_char	gTimesGreek_5C[]	PROGMEM	=	" 3KYKFY^";
prog_char	gTimesGreek_5D[]	PROGMEM	=	"12KYTBTb RUBUb RNBUB RNbUb";
prog_char	gTimesGreek_5E[]	PROGMEM	=	" 8G]JTROZT RJTRPZT";
prog_char	gTimesGreek_5F[]	PROGMEM	=	" 3H\\Hb\\b";

prog_char	gTimesGreek_60[]	PROGMEM	=	" 7LXPFUL RPFOGUL";
prog_char	gTimesGreek_61[]	PROGMEM	=	"40G^QMNNLPKRJUJXKZN[P[RZUWWTYPZM RQMONMPLRKUKXLZN[ RQMSMUNVPXXYZZ[ RSMTNUPWXXZZ[[[";
prog_char	gTimesGreek_62[]	PROGMEM	=	"57G\\TFQGOIMMLPKTJZIb RTFRGPINMMPLTKZJb RTFVFXGYHYKXMWNTOPO RVFXHXKWMVNTO RPOTPVRWTWWVYUZR[P[NZMYLV RPOSPURVTVWUYTZR[";
prog_char	gTimesGreek_63[]	PROGMEM	=	"23I[KMMMONPPU_VaWb RMMNNOPT_UaWbYb RZMYOWRM]K`Jb";
prog_char	gTimesGreek_64[]	PROGMEM	=	"44I\\VNTMRMONMQLTLWMYNZP[R[UZWWXTXQWOSJRHRFSEUEWFYH RRMPNNQMTMXNZ RR[TZVWWTWPVNTKSISGTFVFYH";
prog_char	gTimesGreek_65[]	PROGMEM	=	"32I[XPVNTMPMNNNPPRSS RPMONOPQRSS RSSNTLVLXMZP[S[UZWX RSSOTMVMXNZP[";
prog_char	gTimesGreek_66[]	PROGMEM	=	"37G]ONMOKQJTJWKYLZN[Q[TZWXYUZRZOXMVMTORSPXMb RJWLYNZQZTYWWYU RZOXNVNTPRSPYNb";
prog_char	gTimesGreek_67[]	PROGMEM	=	"28H\\IPKNMMOMQNROSRSVRZOb RJOLNPNRO RZMYPXRSYP^Nb RYMXPWRSY";
prog_char	gTimesGreek_68[]	PROGMEM	=	"32G]HQIOKMNMONOPNTL[ RMMNNNPMTK[ RNTPPRNTMVMXNYOYRXWUb RVMXOXRWWTb";
prog_char	gTimesGreek_69[]	PROGMEM	=	"15LXRMPTOXOZP[S[UYVW RSMQTPXPZQ[";
prog_char	gTimesGreek_6A[]	PROGMEM	=	" 6G]KKYY RYKKY";
prog_char	gTimesGreek_6B[]	PROGMEM	=	"29H\\NMJ[ ROMK[ RXMYNZNYMWMUNQROSMS ROSQTSZT[ ROSPTRZS[U[WZYW";
prog_char	gTimesGreek_6C[]	PROGMEM	=	"23H\\KFMFOGPHQJWXXZY[ RMFOHPJVXWZY[Z[ RRMJ[ RRMK[";
prog_char	gTimesGreek_6D[]	PROGMEM	=	"28F]MMGb RNMHb RMPLVLYN[P[RZTXVU RXMUXUZV[Y[[Y\\W RYMVXVZW[";
prog_char	gTimesGreek_6E[]	PROGMEM	=	"24H\\NML[ ROMNSMXL[ RYMXQVU RZMYPXRVUTWQYOZL[ RKMOM";
prog_char	gTimesGreek_6F[]	PROGMEM	=	"32I[RMONMQLTLWMYNZP[R[UZWWXTXQWOVNTMRM RRMPNNQMTMXNZ RR[TZVWWTWPVN";

prog_char	gTimesGreek_70[]	PROGMEM	=	"22G]PNL[ RPNM[ RVNV[ RVNW[ RIPKNNM[M RIPKONN[N";
prog_char	gTimesGreek_71[]	PROGMEM	=	"44F]GQHOJMMMNNNPMUMXNZO[ RLMMNMPLULXMZO[Q[SZUXWUXRYMYIXGVFTFRHRJSMUPWRZT RSZUWVUWRXMXIWGVF";
prog_char	gTimesGreek_72[]	PROGMEM	=	"31H[LVMYNZP[R[UZWWXTXQWOVNTMRMONMQLTHb RR[TZVWWTWPVN RRMPNNQMTIb";
prog_char	gTimesGreek_73[]	PROGMEM	=	"35H][MQMNNLQKTKWLYMZO[Q[TZVWWTWQVOUNSM RQMONMQLTLXMZ RQ[SZUWVTVPUN RUN[N";
prog_char	gTimesGreek_74[]	PROGMEM	=	"16H\\SNP[ RSNQ[ RJPLNOMZM RJPLOONZN";
prog_char	gTimesGreek_75[]	PROGMEM	=	"31H\\IQJOLMOMPNPPNVNYP[ RNMONOPMVMYNZP[Q[TZVXXUYRYOXMWNXOYR RXUYO";
prog_char	gTimesGreek_76[]	PROGMEM	=	"15E_RIQJRKSJRI RIR[R RRYQZR[SZRY";
prog_char	gTimesGreek_77[]	PROGMEM	=	"44F]JQLOONNMLNJQITIWJZK[M[OZQWRT RIWJYKZMZOYQW RQTQWRZS[U[WZYWZTZQYNXMWNYOZQ RQWRYSZUZWYYW";
prog_char	gTimesGreek_78[]	PROGMEM	=	"45IZTFRGQHQIRJUKXK RUKQLOMNONQPSSTVT RUKRLPMOOOQQSST RSTOUMVLXLZN\\S^T_TaRbPb RSTPUNVMXMZO\\S^";
prog_char	gTimesGreek_79[]	PROGMEM	=	"34F]UFOb RVFNb RGQHOJMMMNNNPMUMXOZRZTYWVYS RLMMNMPLULXMZO[R[TZVXXUYS[M";
prog_char	gTimesGreek_7A[]	PROGMEM	=	"31I[TFRGQHQIRJUKZKZJWKSMPOMRLULWMYP[S]T_TaSbQbPa RULQONRMUMWNYP[";
prog_char	gTimesGreek_7B[]	PROGMEM	=	"40KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
prog_char	gTimesGreek_7C[]	PROGMEM	=	" 3NVRBRb";
prog_char	gTimesGreek_7D[]	PROGMEM	=	"40KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
prog_char	gTimesGreek_7E[]	PROGMEM	=	"24F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
prog_char	gTimesGreek_7F[]	PROGMEM	=	"35JZJFJ[K[KFLFL[M[MFNFN[O[OFPFP[Q[QFRFR[S[SFTFT[U[UFVFV[W[WFXFX[Y[YFZFZ[";


PGM_P gHershyTimesGreekFontTable[]	PROGMEM =	   // change "string_table" name to suit
{

	gTimesGreek_00,
	gTimesGreek_20,
	gTimesGreek_21,
	gTimesGreek_22,
	gTimesGreek_23,
	gTimesGreek_24,
	gTimesGreek_25,
	gTimesGreek_26,
	gTimesGreek_27,
	gTimesGreek_28,
	gTimesGreek_29,
	gTimesGreek_2A,
	gTimesGreek_2B,
	gTimesGreek_2C,
	gTimesGreek_2D,
	gTimesGreek_2E,
	gTimesGreek_2F,

	gTimesGreek_30,
	gTimesGreek_31,
	gTimesGreek_32,
	gTimesGreek_33,
	gTimesGreek_34,
	gTimesGreek_35,
	gTimesGreek_36,
	gTimesGreek_37,
	gTimesGreek_38,
	gTimesGreek_39,
	gTimesGreek_3A,
	gTimesGreek_3B,
	gTimesGreek_3C,
	gTimesGreek_3D,
	gTimesGreek_3E,
	gTimesGreek_3F,

	gTimesGreek_40,
	gTimesGreek_41,
	gTimesGreek_42,
	gTimesGreek_43,
	gTimesGreek_44,
	gTimesGreek_45,
	gTimesGreek_46,
	gTimesGreek_47,
	gTimesGreek_48,
	gTimesGreek_49,
	gTimesGreek_4A,
	gTimesGreek_4B,
	gTimesGreek_4C,
	gTimesGreek_4D,
	gTimesGreek_4E,
	gTimesGreek_4F,

	gTimesGreek_50,
	gTimesGreek_51,
	gTimesGreek_52,
	gTimesGreek_53,
	gTimesGreek_54,
	gTimesGreek_55,
	gTimesGreek_56,
	gTimesGreek_57,
	gTimesGreek_58,
	gTimesGreek_59,
	gTimesGreek_5A,
	gTimesGreek_5B,
	gTimesGreek_5C,
	gTimesGreek_5D,
	gTimesGreek_5E,
	gTimesGreek_5F,

	gTimesGreek_60,
	gTimesGreek_61,
	gTimesGreek_62,
	gTimesGreek_63,
	gTimesGreek_64,
	gTimesGreek_65,
	gTimesGreek_66,
	gTimesGreek_67,
	gTimesGreek_68,
	gTimesGreek_69,
	gTimesGreek_6A,
	gTimesGreek_6B,
	gTimesGreek_6C,
	gTimesGreek_6D,
	gTimesGreek_6E,
	gTimesGreek_6F,

	gTimesGreek_70,
	gTimesGreek_71,
	gTimesGreek_72,
	gTimesGreek_73,
	gTimesGreek_74,
	gTimesGreek_75,
	gTimesGreek_76,
	gTimesGreek_77,
	gTimesGreek_78,
	gTimesGreek_79,
	gTimesGreek_7A,
	gTimesGreek_7B,
	gTimesGreek_7C,
	gTimesGreek_7D,
	gTimesGreek_7E,
	gTimesGreek_7F

};
